/* kernel/cm/license.h - GENERATED by tools/gen_license.py from
 * third_party/wine/loader/wine.inf's [LicenseInformation] section — the
 * payload that writes HKLM\Software\Wine\LicenseInformation into the
 * pinned oracle's prefix, and so the payload NtQueryLicenseValue answers
 * out of on that leg (dlls/ntdll/unix/registry.c names the key literally).
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_license.py
 *
 * proskrnl has no prefix, so CmInitialize (kernel/cm/registry.c) seeds this
 * table into the same key — which is what makes the two legs of ntdll:reg
 * and of tests/ntapi/sem_reg/license_value.c read the SAME data rather than
 * each inventing a plausible one.
 *
 * kernel/cm/registry.c is the ONE includer, which is what makes `static
 * const` right here (the kernel/lib/upcase.h precedent): a second includer
 * would get its own silent copy, and there is one seed site, not two.
 */
#ifndef PROSKRNL_KERNEL_CM_LICENSE_H
#define PROSKRNL_KERNEL_CM_LICENSE_H

#include "abi/ntdef.h"
#include "abi/ntregapi.h"
#include "kernel/lib/rtl.h"

/* One row of the INF section. REG_SZ rows carry `string` and REG_DWORD rows
 * carry `dword`; the unused member is zero, and `type` is what says which. */
typedef struct CMP_LICENSE_VALUE
{
    PCWSTR name;
    ULONG type;
    PCWSTR string;
    ULONG dword;
} CMP_LICENSE_VALUE;

#define CMP_LICENSE_VALUE_COUNT 11

static const CMP_LICENSE_VALUE CmpLicenseValues[CMP_LICENSE_VALUE_COUNT] = {
    {WSTR("Kernel-MUI-Language-Allowed"), REG_SZ, WSTR("EMPTY"), 0},
    {WSTR("Kernel-MUI-Language-Disallowed"), REG_SZ, WSTR("EMPTY"), 0},
    {WSTR("Kernel-MUI-Number-Allowed"), REG_DWORD, 0, 1000},
    {WSTR("Shell-InBoxGames-FreeCell-EnableGame"), REG_DWORD, 0, 1},
    {WSTR("Shell-InBoxGames-Hearts-EnableGame"), REG_DWORD, 0, 1},
    {WSTR("Shell-InBoxGames-Minesweeper-EnableGame"), REG_DWORD, 0, 1},
    {WSTR("Shell-InBoxGames-PurblePlace-EnableGame"), REG_DWORD, 0, 1},
    {WSTR("Shell-InBoxGames-Shanghai-EnableGame"), REG_DWORD, 0, 1},
    {WSTR("Shell-InBoxGames-Solitaire-EnableGame"), REG_DWORD, 0, 1},
    {WSTR("Shell-InBoxGames-SpiderSolitaire-EnableGame"), REG_DWORD, 0, 1},
    {WSTR("Shell-PremiumInBoxGames-Chess-EnableGame"), REG_DWORD, 0, 1},
};

#endif /* PROSKRNL_KERNEL_CM_LICENSE_H */
