#!/usr/bin/env bash
#
# run.sh — the ntapi runner. ONE binary per test, two runners (docs/08,
# docs/14): every test is a single mingw-built, CRT-less PE .exe linked
# against the pinned Wine import libraries.
#
#   run.sh oracle     Run every test .exe under the pinned Wine. This is the
#                     SPEC gate: it must be all-green before you may implement
#                     the corresponding kernel code.
#
#   run.sh proskrnl   Bake the SAME .exes (plus the Wine PE userland) into a
#                     disk image under C:\ntapi and boot it: the kernel's
#                     ntapi runner (kernel/init/main.c) sweeps the directory
#                     and runs each test. This is the REGRESSION gate: it must
#                     stay all-green as the boundary is implemented.
#
#   run.sh winetest   The M10 stretch gate: run the curated manifest of
#                     Wine's-own-test-suite pairs (tests/winetest/) under the
#                     oracle AND on proskrnl. Same one-binary discipline.
#
# Verdict protocol: each test emits one machine-greppable line
#     [KTEST] <name> PASS
#     [KTEST] <name> FAIL failures=<n> todo_unexpected=<n>
# We grep those; nothing parses free-text. Exit non-zero iff any test FAILs.
#
# Needs a Windows-targeting toolchain (x86_64-w64-mingw32-gcc) and the pinned
# third_party/wine build (tools/setup_linux.sh) for the import libraries, the
# oracle runtime, and the DLLs/NLS files the proskrnl image bakes.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
NTAPI="$ROOT/tests/ntapi"
BUILD="$ROOT/build/tests"
MODE="${1:-}"

: "${CC_ORACLE:=x86_64-w64-mingw32-gcc}"   # override for a different mingw

# The oracle wine: PREFER the pinned third_party/wine build (built in-tree by
# tools/setup_linux.sh) so the oracle can never diverge from the Wine version
# the abi/ contract is generated from; $WINE overrides, host wine is the
# fallback. The pinned tree is the PATCHED proskrnl-target fork by design
# (docs/06 "One tree, three roles"): every seam commit is dormant when a
# unixlib is present, so running the oracle on it both enforces that dormancy
# and exercises the identical PE ntdll.dll bytes the Makefile's WINFILES bake
# onto proskrnl's boot volume.
#
# The pinned wine is wrapped so its font backend resolves to the PINNED
# FreeType: win32u.so does not link that backend, it dlopen()s
# SONAME_LIBFREETYPE ("libfreetype.so.6", recorded by configure) with no
# rpath of its own, and when the open fails it does not fail — it proceeds
# with no fonts at all, which is exactly the silent divergence the
# font-metrics oracle was rebuilt to remove (GUI-3; docs/03 "the font
# oracle"). The path goes in a WRAPPER rather than this script's environment
# because it must reach wine and nothing else: our FreeType is built for
# win32u's needs, not as a system library, and QEMU's GTK stack loads the
# distro fontconfig, which wants symbols this build does not export
# (FT_Get_BDF_Property) — an exported LD_LIBRARY_PATH stops QEMU from
# starting at all. A caller-supplied $WINE is left alone: it pairs with
# whatever FreeType that wine was built against.
find_wine() {
    local w
    for w in "$ROOT/third_party/wine/wine64" "$ROOT/third_party/wine/wine"; do
        [[ -x "$w" ]] || continue
        local wrapper="$BUILD/wine-fonts"
        mkdir -p "$BUILD"
        cat >"$wrapper" <<EOF
#!/bin/sh
# GENERATED by tests/run/run.sh — hands the pinned wine the pinned FreeType.
LD_LIBRARY_PATH="$ROOT/third_party/freetype/x86_64-linux\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH
exec "$w" "\$@"
EOF
        chmod +x "$wrapper"
        echo "$wrapper"
        return 0
    done
    echo "wine"
}
: "${WINE:=$(find_wine)}"                  # runner for the .exe when not on Windows

# Oracle runs get a scratch prefix under build/ (created by wine on first
# use): the M8 sem_reg tests write real registry keys, and they must land in
# a disposable registry, never the developer's ~/.wine. $WINEPREFIX overrides.
: "${WINEPREFIX:=$BUILD/wineprefix}"
export WINEPREFIX

# Keep mscoree/mshtml unloadable in every oracle prefix: wine.inf's
# RegisterDllsSection registers both, and their DllRegisterServer is the
# Wine Mono / Gecko INSTALLER (dlls/mscoree/mscoree_main.c
# install_wine_mono, via appwiz.cpl) — a multi-minute download on every
# fresh-prefix init, and addon state the proskrnl side never has. The
# override makes setupapi's registration warn-and-continue instead.
: "${WINEDLLOVERRIDES:=mscoree,mshtml=}"
export WINEDLLOVERRIDES
CFLAGS_COMMON="-std=c11 -O1 -g -Wall -Wextra -I$ROOT -I$NTAPI"

# The pinned Wine import libraries the test .exes link against (built by
# tools/setup_linux.sh). Import libs bind by DLL name, so the same .exe
# resolves against Wine's ntdll under the oracle and against the baked
# C:\windows\system32 DLLs on proskrnl.
WINE_PE="$ROOT/third_party/wine/dlls"
WINE_LIBS=("$WINE_PE/kernel32/x86_64-windows/libkernel32.a"
           "$WINE_PE/kernelbase/x86_64-windows/libkernelbase.a"
           "$WINE_PE/ntdll/x86_64-windows/libntdll.a")

# Every test = a .c under tests/ntapi/<bucket>/ (excludes the harness itself
# and the helper-DLL sources under dll/).
all_tests() { find "$NTAPI" -name '*.c' ! -name 'ntapi.c' ! -path '*/dll/*' | sort; }

# The search-order probe DLL (sem_ps/dll_load.c): built beside the test
# .exes so a bare-name LoadLibrary resolves it from the application
# directory. CRT-less like everything else here.
build_helper_dll() {   # echoes the .dll path
    local dll="$BUILD/ntapi/prshelper.dll"
    if [[ ! -f "$dll" || "$NTAPI/dll/prshelper.c" -nt "$dll" ]]; then
        "$CC_ORACLE" $CFLAGS_COMMON -ffreestanding -fno-builtin -nostdlib -nostartfiles \
            -shared -Wl,--entry=DllMainCRTStartup "$NTAPI/dll/prshelper.c" \
            "${WINE_LIBS[@]}" -lgcc -o "$dll" >&2
    fi
    echo "$dll"
}

# Build one test into build/tests/ntapi/<name>.exe: no CRT (-nostdlib, entry
# ntapi_start in ntapi.c), the pinned Wine import libs, -lgcc for the mingw
# helpers the compiler may emit (___chkstk_ms). Skips work when up to date.
build_test() {   # $1 = .c path; echoes the .exe path
    local src="$1" name exe
    name="$(basename "${src%.c}")"
    exe="$BUILD/ntapi/$name.exe"
    if [[ ! -f "$exe" || "$src" -nt "$exe" || "$NTAPI/ntapi.c" -nt "$exe" || \
          "$NTAPI/ntapi.h" -nt "$exe" ]]; then
        "$CC_ORACLE" $CFLAGS_COMMON -ffreestanding -fno-builtin -nostdlib -nostartfiles \
            -Wl,--entry=ntapi_start "$src" "$NTAPI/ntapi.c" \
            "${WINE_LIBS[@]}" -lgcc -o "$exe" >&2
    fi
    echo "$exe"
}

oracle() {
    mkdir -p "$BUILD/ntapi"
    build_helper_dll >/dev/null
    local fails=0
    while read -r src; do
        local name exe out
        name="$(basename "${src%.c}")"
        exe="$(build_test "$src")"
        out="$("$WINE" "$exe" 2>&1 || true)"
        echo "$out"
        # tr -d '\r': tolerate CRLF if a console handle translates.
        echo "$out" | tr -d '\r' | grep -qE "^\[KTEST\] $name PASS$" || fails=$((fails+1))
    done < <(all_tests)

    # M10: the standalone cmd.exe (Wine's cmd objects + user/cmd glue) is
    # spec-checked off-target here — the same binary the console image bakes
    # must behave under the oracle (docs/06 one-tree discipline).
    make -C "$ROOT" build/modules/cmd.exe >/dev/null
    local cmdexe="$ROOT/build/modules/cmd.exe" cmdout
    cmdout="$(cd "$BUILD" && "$WINE" "$cmdexe" /c \
        "echo smoke-echo & echo smoke-data > cmdsmoke.txt & type cmdsmoke.txt & del cmdsmoke.txt" \
        2>/dev/null | tr -d '\r')"
    if echo "$cmdout" | grep -q "smoke-echo" && echo "$cmdout" | grep -q "smoke-data"; then
        echo "[KTEST] cmd-standalone PASS"
    else
        echo "[KTEST] cmd-standalone FAIL"
        fails=$((fails+1))
    fi

    # GUI-3: the oracle is also the font-metrics oracle, and its font backend
    # is dlopen'd -- when the open fails win32u proceeds with NO fonts rather
    # than failing, so nothing above would notice. Ask it for a face and check
    # it answers (tests/gdi/fontsmoke.c). Oracle-only: it links gdi32, which
    # the proskrnl ntapi image does not carry.
    local fontexe fontout
    fontexe="$BUILD/ntapi/fontsmoke.exe"
    if [[ ! -f "$fontexe" || "$ROOT/tests/gdi/fontsmoke.c" -nt "$fontexe" || \
          "$NTAPI/ntapi.c" -nt "$fontexe" ]]; then
        "$CC_ORACLE" $CFLAGS_COMMON -ffreestanding -fno-builtin -nostdlib -nostartfiles \
            -Wl,--entry=ntapi_start "$ROOT/tests/gdi/fontsmoke.c" "$NTAPI/ntapi.c" \
            "${WINE_LIBS[@]}" "$WINE_PE/gdi32/x86_64-windows/libgdi32.a" -lgcc -o "$fontexe" >&2
    fi
    fontout="$("$WINE" "$fontexe" 2>&1 || true)"
    echo "$fontout"
    if echo "$fontout" | tr -d '\r' | grep -qE '^\[KTEST\] fontsmoke PASS$'; then
        :
    else
        fails=$((fails+1))
    fi

    # GUI-5: the metric differential itself (tests/gdi/fontdiff.c — the half
    # docs/03 "the font oracle" deferred here). The same binary the gui5 leg
    # bakes prints a fixed metric table; the oracle's table is pinned as
    # tests/gdi/fontdiff.golden and re-diffed HERE on every run, so the
    # golden can never go silently stale. The gui5 leg diffs the guest's
    # table against the same file — exact integers, no epsilon (same pinned
    # FreeType, same font bytes, 96 dpi on both sides). Regenerate with
    # FONTDIFF_REFRESH=1 and commit the diff: a pin bump that moves a metric
    # is a reviewed change, never a silent one.
    local fdexe fdout fdlines fdgold="$ROOT/tests/gdi/fontdiff.golden"
    fdexe="$BUILD/ntapi/fontdiff.exe"
    if [[ ! -f "$fdexe" || "$ROOT/tests/gdi/fontdiff.c" -nt "$fdexe" || \
          "$NTAPI/ntapi.c" -nt "$fdexe" ]]; then
        "$CC_ORACLE" $CFLAGS_COMMON -ffreestanding -fno-builtin -nostdlib -nostartfiles \
            -Wl,--entry=ntapi_start "$ROOT/tests/gdi/fontdiff.c" "$NTAPI/ntapi.c" \
            "${WINE_LIBS[@]}" "$WINE_PE/gdi32/x86_64-windows/libgdi32.a" -lgcc -o "$fdexe" >&2
    fi
    fdout="$("$WINE" "$fdexe" 2>&1 || true)"
    echo "$fdout"
    fdlines="$(echo "$fdout" | tr -d '\r' | grep -E '^\[KTEST\] fontdiff (dpi=|face=|done )')"
    if ! echo "$fdout" | tr -d '\r' | grep -qE '^\[KTEST\] fontdiff PASS$'; then
        fails=$((fails+1))
    elif [[ "${FONTDIFF_REFRESH:-0}" == "1" ]]; then
        echo "$fdlines" > "$fdgold"
        echo "== fontdiff: golden refreshed ($fdgold) — review and commit the diff =="
    elif ! diff -u "$fdgold" <(echo "$fdlines") >&2; then
        echo "[KTEST] fontdiff-golden FAIL (oracle metrics differ from tests/gdi/fontdiff.golden)"
        fails=$((fails+1))
    else
        echo "[KTEST] fontdiff-golden PASS"
    fi

    echo "== oracle: $fails failing =="
    return $(( fails > 0 ? 1 : 0 ))
}

# Bake the SAME .exes into a disk image under C:\ntapi beside the Wine PE
# userland (ntdll/kernel32/kernelbase + the NLS tables), boot it, and read
# each test's own [KTEST] <name> PASS line off the serial log. The kernel's
# ntapi runner (kernel/init/main.c) sweeps C:\ntapi, runs every .exe as a
# console-less Wine process, and prints '[KTEST] ntapi done' when the sweep
# finishes — the boot's stop condition here.
proskrnl() {
    local kernel img
    kernel="$ROOT/build/proskrnl"
    img="$ROOT/build/tests/proskrnl.hdd"
    mkdir -p "$BUILD/ntapi"

    # The kernel image must exist (make builds it); build it if missing.
    if [[ ! -f "$kernel" ]]; then
        make -C "$ROOT" >/dev/null
    fi

    # The M5 RAM-disk seed files (built by make with the kernel): kmt's
    # image/file section tests read them; they are data, never run.
    local specs=() names=()
    for seed in "$ROOT/build/modules/pe_smoke.exe" "$ROOT/build/modules/sample.dat"; do
        [[ -f "$seed" ]] && specs+=("$seed=initrd")
    done
    # The Wine PE userland the tests run on (the same files Makefile WINFILES
    # bakes for `make test`): the debug-STRIPPED staging copies — with no COW
    # and no eviction, the -g mingw builds' DWARF triples every mapped image
    # copy (see Makefile winestrip).
    make -C "$ROOT" winestrip >/dev/null
    for dll in ntdll kernel32 kernelbase msvcrt ucrtbase advapi32 sechost rpcrt4 version \
               cryptbase; do
        specs+=("win:$ROOT/build/winestrip/$dll.dll=windows/system32/$dll.dll")
    done
    specs+=("win:$(build_helper_dll)=ntapi/prshelper.dll")
    for nls in locale l_intl c_1252 c_437 c_20127 sortdefault normnfc normnfd normnfkc normnfkd \
               normidna; do
        [[ -f "$ROOT/third_party/wine/nls/$nls.nls" ]] && \
            specs+=("win:$ROOT/third_party/wine/nls/$nls.nls=windows/system32/$nls.nls")
    done
    while read -r src; do
        local name exe
        name="$(basename "${src%.c}")"
        exe="$(build_test "$src")"
        specs+=("win:$exe=ntapi/$name.exe")
        names+=("$name")
    done < <(all_tests)

    "$ROOT/tools/mkimage.sh" "$kernel" "$img" "${specs[@]}" >/dev/null

    local log="$ROOT/build/tests/proskrnl-serial.log"
    LOG="$log" PASS_RE="\[KTEST\] ntapi done" TIMEOUT="${TIMEOUT:-900}" \
        "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 || true

    # Symbolized sidecar for a human/LLM reading a failure (Art. 9); the
    # verdict greps below stay on the raw log.
    "$ROOT/tools/symbolize.py" --kernel "$kernel" \
        --moduledir "$ROOT/build/modules" < "$log" \
        > "$ROOT/build/tests/proskrnl-serial.sym.log" 2>/dev/null || true

    local fails=0
    for name in "${names[@]}"; do
        if grep -qE "^\[KTEST\] $name PASS$" "$log" 2>/dev/null; then
            echo "[KTEST] $name PASS"
        else
            echo "[KTEST] $name FAIL"
            fails=$((fails + 1))
        fi
    done
    # The external FAT oracle on the mutated image (docs/08): the kernel's
    # writes must parse under implementations that have never met fs/fat32/.
    "$ROOT/tests/run/fatcheck.sh" verify proskrnl "$img" || fails=$((fails + 1))
    echo "== proskrnl: $fails failing =="
    return $((fails > 0 ? 1 : 0))
}

# The M10 stretch gate (docs/02 "Ideal regression: the CUI subset of Wine's
# own test suite"): the curated manifest of <test_exe>:<subtest> pairs
# (tests/winetest/manifest.txt) must exit 0 under the pinned oracle AND on
# proskrnl. The binaries are the pinned tree's own test objects linked
# standalone (Makefile `wtests`) — ONE binary, two runners, like everything
# else here. On proskrnl the kernel sweep (kernel/init/main.c
# KiRunWineTests) reads the baked manifest, runs each pair on the console
# (winetest prints through msvcrt stdout -> conhost -> serial), and the exit
# code — winetest's failure count — is the verdict.
winetest() {
    local manifest="$ROOT/tests/winetest/manifest.txt"
    make -C "$ROOT" wtests >/dev/null
    mkdir -p "$BUILD/wtests"

    local pairs=()
    while IFS= read -r line; do
        line="${line%$'\r'}"
        [[ -z "$line" || "$line" == \#* ]] && continue
        pairs+=("$line")
    done < "$manifest"
    if [[ ${#pairs[@]} -eq 0 ]]; then
        echo "== winetest: manifest empty ==" >&2
        return 2
    fi

    # --- oracle leg (the SPEC gate: green here before the kernel side) ---
    local fails=0
    for pair in "${pairs[@]}"; do
        local exe="${pair%%:*}" sub="${pair#*:}"
        local olog="$BUILD/wtests/${exe}.${sub}.oracle.log"
        # scratch cwd: the cmd tests write test.cmd/test.out where they run
        if (cd "$BUILD/wtests" && "$WINE" "$ROOT/build/wtests/$exe" "$sub") >"$olog" 2>&1; then
            echo "[KTEST] wtest-oracle $pair PASS"
        else
            echo "[KTEST] wtest-oracle $pair FAIL (see $olog)"
            fails=$((fails+1))
        fi
    done

    # --- proskrnl leg (the REGRESSION gate) ---
    local kernel img
    kernel="$ROOT/build/proskrnl"
    img="$ROOT/build/tests/wtest.hdd"
    if [[ ! -f "$kernel" ]]; then
        make -C "$ROOT" >/dev/null
    fi
    make -C "$ROOT" build/modules/cmd.exe build/modules/conhost.exe >/dev/null

    # The Wine PE userland (the run.sh proskrnl set) + conhost (winetest
    # processes run on the console) + cmd.exe (%COMSPEC%, the cmd tests'
    # subject) + the test binaries and the manifest under C:\wtests. The M5
    # seed modules keep the in-kernel M6 suite green on this image too, and
    # the FULL nls set goes in — the CRT/codepage subtests exercise every
    # codepage the oracle has (a missing c_932.nls reads as a divergence).
    local specs=()
    for seed in "$ROOT/build/modules/pe_smoke.exe" "$ROOT/build/modules/sample.dat"; do
        [[ -f "$seed" ]] && specs+=("$seed=initrd")
    done
    make -C "$ROOT" winestrip >/dev/null
    for dll in ntdll kernel32 kernelbase msvcrt ucrtbase advapi32 sechost rpcrt4 version \
               cryptbase; do
        specs+=("win:$ROOT/build/winestrip/$dll.dll=windows/system32/$dll.dll")
    done
    local nlsfile
    for nlsfile in "$ROOT"/third_party/wine/nls/*.nls; do
        specs+=("win:$nlsfile=windows/system32/$(basename "$nlsfile")")
    done
    specs+=("win:$ROOT/build/modules/conhost.exe=windows/system32/conhost.exe")
    specs+=("win:$ROOT/build/modules/cmd.exe=windows/system32/cmd.exe")
    for exe in ntdll_test.exe kernel32_test.exe msvcrt_test.exe ucrtbase_test.exe \
               cmd.exe_test.exe; do
        specs+=("win:$ROOT/build/wtests/$exe=wtests/$exe")
    done
    specs+=("win:$manifest=wtests/manifest.txt")

    # MB-scale test binaries: a bigger volume than the 64 MB default. And
    # 1 GiB of guest RAM: no eviction (Art. 3) means the page cache holds
    # every test binary's pages for the whole sweep — memory is provisioned,
    # not managed.
    SIZE_MB=256 "$ROOT/tools/mkimage.sh" "$kernel" "$img" "${specs[@]}" >/dev/null

    local log="$ROOT/build/tests/wtest-serial.log"
    LOG="$log" MEM=1024M PASS_RE="\[KTEST\] wtest done" TIMEOUT="${TIMEOUT:-1800}" \
        "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 || true

    "$ROOT/tools/symbolize.py" --kernel "$kernel" \
        --moduledir "$ROOT/build/modules" < "$log" \
        > "$ROOT/build/tests/wtest-serial.sym.log" 2>/dev/null || true

    # No ^ anchor: conhost cursor escapes may share the verdict's line (the
    # run.sh console precedent).
    for pair in "${pairs[@]}"; do
        if grep -qF "[KTEST] wtest $pair PASS" "$log" 2>/dev/null; then
            echo "[KTEST] wtest $pair PASS"
        else
            echo "[KTEST] wtest $pair FAIL"
            fails=$((fails + 1))
        fi
    done
    echo "== winetest: $fails failing =="
    return $((fails > 0 ? 1 : 0))
}

# The FAT interop battery (docs/08 "The FAT on-disk format has its own
# oracles"): bake an adversarial corpus with mtools + host-side FAT surgery
# (tests/run/fatgen.py), boot, and let the in-kernel suite
# (tests/kmt/fat_interop.c) enumerate/read/checksum it all; then extract the
# battery the kernel wrote and verify it on the host. Both directions of
# dir.c's 8.3/LFN logic meet an implementation they have never met. No Wine
# userland needed: the suite runs in-kernel, gated by the baked manifest.
fatinterop() {
    local kernel="$ROOT/build/proskrnl" img="$BUILD/fatinterop.hdd"
    local work="$BUILD/fatinterop" off=2097152    # mkimage.sh ESP_OFF
    if [[ ! -f "$kernel" ]]; then
        make -C "$ROOT" build/proskrnl >/dev/null
    fi
    rm -rf "$work"
    mkdir -p "$work"

    # Base image: kernel + the M5 seed modules only (keeps M5/M6 green).
    local specs=()
    make -C "$ROOT" build/modules/pe_smoke.exe build/modules/sample.dat >/dev/null 2>&1 || true
    for seed in "$ROOT/build/modules/pe_smoke.exe" "$ROOT/build/modules/sample.dat"; do
        [[ -f "$seed" ]] && specs+=("$seed=initrd")
    done
    "$ROOT/tools/mkimage.sh" "$kernel" "$img" ${specs[@]+"${specs[@]}"} >/dev/null

    # Cluster size from the real volume (mformat decided it): bytes/sector *
    # sectors/cluster out of the BPB, via fatsweep's parser.
    local cbytes
    cbytes=$(python3 - "$img" <<'PYEOF'
import struct, sys
with open(sys.argv[1], "rb") as f:
    f.seek(2097152)
    boot = f.read(64)
print(struct.unpack_from("<H", boot, 11)[0] * boot[13])
PYEOF
)
    python3 "$ROOT/tests/run/fatgen.py" emit --outdir "$work" --cluster-bytes "$cbytes"

    # Bake the corpus with raw mtools at the ESP offset (the firstboot mcopy
    # precedent). The manifest goes LAST: it is the kernel-side gate, so a
    # partially baked image never runs the suite.
    mmd -i "$img@@$off" ::/fatcorpus
    local fails=0
    while IFS=$'\t' read -r op a b; do
        case "$op" in
            mkdir) mmd  -i "$img@@$off" "::$a" || fails=$((fails+1)) ;;
            copy)  mcopy -i "$img@@$off" "$work/hostfiles/$a" "::$b" || fails=$((fails+1)) ;;
            del)   mdel -i "$img@@$off" "::$a" || fails=$((fails+1)) ;;
        esac
    done < "$work/bake.txt"
    if [[ $fails -ne 0 ]]; then
        echo "== fatinterop: FAIL ($fails bake ops failed) =="
        return 1
    fi
    # Deterministic fragmentation (host-side FAT surgery), then prove it.
    python3 "$ROOT/tests/run/fatgen.py" fragment --image "$img" --path fatcorpus/frag.bin
    python3 "$ROOT/tests/run/fatgen.py" fragment --image "$img" --path fatcorpus/frag2.bin
    python3 "$ROOT/tests/run/fatgen.py" fragcheck --image "$img" --path fatcorpus/frag.bin \
        --min-extents 2 || { echo "== fatinterop: FAIL (fragmentation) =="; return 1; }
    mcopy -i "$img@@$off" "$work/manifest.txt" ::/fatcorpus/manifest.txt

    local log="$BUILD/fatinterop-serial.log"
    LOG="$log" PASS_RE="\[KTEST\] FATINTEROP PASS" TIMEOUT="${TIMEOUT:-900}" \
        "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 || true
    "$ROOT/tools/symbolize.py" --kernel "$kernel" --moduledir "$ROOT/build/modules" \
        < "$log" > "$BUILD/fatinterop-serial.sym.log" 2>/dev/null || true

    fails=0
    if grep -qE '\[KTEST\] FATINTEROP PASS' "$log" 2>/dev/null; then
        echo "[KTEST] fatinterop-boot PASS"
    else
        echo "[KTEST] fatinterop-boot FAIL (see $log)"
        fails=$((fails+1))
    fi

    # Kernel->host: extract AFTER qemu exits (the image lock), verify against
    # the manifest, and run the structural oracles on the mutated image.
    rm -rf "$work/extracted"
    mkdir -p "$work/extracted"
    mcopy -s -p -i "$img@@$off" ::/fatout/. "$work/extracted" 2>/dev/null || true
    if python3 "$ROOT/tests/run/fatgen.py" verify --extracted "$work/extracted/fatout" \
           --manifest "$work/manifest.txt"; then
        echo "[KTEST] fatinterop-extract PASS"
    else
        echo "[KTEST] fatinterop-extract FAIL"
        fails=$((fails+1))
    fi
    "$ROOT/tests/run/fatcheck.sh" verify fatinterop "$img" || fails=$((fails+1))
    echo "== fatinterop: $fails failing =="
    return $((fails > 0 ? 1 : 0))
}

# The FS churn stress (docs/08): fixed-seed random churn against an
# in-kernel shadow model (tests/kmt/fat_churn.c), across THREE mkfs
# geometries — boundary bugs are geometry-specific. Non-diskfull legs boot
# TWICE (the m8_persist pattern): boot 1 seeds wet, boot 2 replays the
# model dry from the seed alone and verifies through a COLD cache. Then the
# host convicts independently: dump-vs-dump determinism diff, mcopy
# extraction + crc diff (churn_verify.py), fsck.fat + the sweeper.
fatstress() {
    local kernel="$ROOT/build/proskrnl"
    if [[ ! -f "$kernel" ]]; then
        make -C "$ROOT" build/proskrnl >/dev/null
    fi
    make -C "$ROOT" build/modules/pe_smoke.exe build/modules/sample.dat >/dev/null 2>&1 || true
    mkdir -p "$BUILD"

    # name:SIZE_MB:CLUSTER_SECTORS:ops:expect_diskfull:boots
    #   default   the standard geometry (512 B clusters on 64 MiB)
    #   c8        4 KiB clusters (page-size, the untested shape)
    #   nearfull  a small volume + ballast so allocation hits DISK_FULL
    local legs=("default:64::400:0:2" "c8:320:8:400:0:2" "nearfull:36:1:300:1:1")
    local fails=0
    for leg in "${legs[@]}"; do
        local lname lsize lcs lops ldf lboots
        IFS=: read -r lname lsize lcs lops ldf lboots <<< "$leg"
        local img="$BUILD/fatstress-$lname.hdd" cfg="$BUILD/churn-$lname.cfg"
        # The near-full leg gets a huge budget: the point is to press the
        # allocator against a really-full volume (ballast below).
        local budget=6291456
        [[ "$ldf" == 1 ]] && budget=33554432
        printf 'seed=0x1965A11D ops=%s maxfiles=48 maxsize=16384 budget=%s expect_diskfull=%s\n' \
            "$lops" "$budget" "$ldf" > "$cfg"

        local specs=()
        for seed in "$ROOT/build/modules/pe_smoke.exe" "$ROOT/build/modules/sample.dat"; do
            [[ -f "$seed" ]] && specs+=("$seed=initrd")
        done
        specs+=("win:$cfg=churn.cfg")
        SIZE_MB="$lsize" CLUSTER_SECTORS="$lcs" \
            "$ROOT/tools/mkimage.sh" "$kernel" "$img" "${specs[@]}" >/dev/null
        if [[ "$ldf" == 1 ]]; then
            # Fill the baked volume down to ~150 KiB free — well inside the
            # churn's working set, so allocation really hits DISK_FULL. The
            # ballast is sized from the image's MEASURED free space, not a
            # fixed count: the kernel binary's size swings by hundreds of
            # KiB across toolchains (debug info), and a fixed 31 MiB once
            # left a container's build ~300 KiB free — above the churn's
            # peak, so DISK_FULL never fired and the leg failed for no
            # kernel fault of its own.
            local off=2097152   # mkimage.sh ESP_OFF
            local freeBytes keepBytes=153600
            # mtools space-groups thousands ("311 296 bytes free"); strip
            # everything but digits from that one line.
            freeBytes=$(mdir -i "$img@@$off" :: | grep 'bytes free' | tr -dc '0-9')
            if [[ -z "$freeBytes" || "$freeBytes" -le "$keepBytes" ]]; then
                echo "[KTEST] fatstress-$lname-seed FAIL (cannot size ballast: free='$freeBytes')"
                fails=$((fails+1))
                continue
            fi
            dd if=/dev/zero of="$BUILD/ballast.bin" bs=1024 \
                count=$(( (freeBytes - keepBytes) / 1024 )) 2>/dev/null
            mcopy -i "$img@@$off" "$BUILD/ballast.bin" ::/ballast.bin
        fi

        local log1="$BUILD/fatstress-$lname-1.log" log2="$BUILD/fatstress-$lname-2.log"
        LOG="$log1" PASS_RE="\[KTEST\] churn-seed PASS" TIMEOUT="${TIMEOUT:-900}" \
            "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 || true
        if ! grep -q '\[KTEST\] churn-seed PASS' "$log1"; then
            echo "[KTEST] fatstress-$lname-seed FAIL (see $log1)"
            fails=$((fails+1))
            continue
        fi
        echo "[KTEST] fatstress-$lname-seed PASS"

        local finalLog="$log1"
        if [[ "$lboots" == 2 ]]; then
            LOG="$log2" PASS_RE="\[KTEST\] churn-verify PASS" TIMEOUT="${TIMEOUT:-900}" \
                "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 || true
            if grep -q '\[KTEST\] churn-verify PASS' "$log2"; then
                echo "[KTEST] fatstress-$lname-verify PASS"
            else
                echo "[KTEST] fatstress-$lname-verify FAIL (see $log2)"
                fails=$((fails+1))
            fi
            # Dry-replay determinism: the two dumps must be identical.
            if diff <(grep '^\[CHURN\] ' "$log1" | tr -d '\r' | sort) \
                    <(grep '^\[CHURN\] ' "$log2" | tr -d '\r' | sort) >/dev/null; then
                echo "[KTEST] fatstress-$lname-replay PASS"
            else
                echo "[KTEST] fatstress-$lname-replay FAIL (dumps differ)"
                fails=$((fails+1))
            fi
            finalLog="$log2"
        fi

        # Host conviction: extraction + crc, then the structural oracles.
        local extract="$BUILD/fatstress-$lname-extract"
        rm -rf "$extract"
        mkdir -p "$extract"
        mcopy -s -p -i "$img@@2097152" ::/churn "$extract" 2>/dev/null || true
        if python3 "$ROOT/tests/run/churn_verify.py" --log "$finalLog" \
               --extracted "$extract/churn"; then
            echo "[KTEST] fatstress-$lname-extract PASS"
        else
            echo "[KTEST] fatstress-$lname-extract FAIL"
            fails=$((fails+1))
        fi
        "$ROOT/tests/run/fatcheck.sh" verify churn "$img" || fails=$((fails+1))
    done
    echo "== fatstress: $fails failing =="
    return $((fails > 0 ? 1 : 0))
}

# Exhaustive torn-write testing (docs/08): boot a minimal image whose
# workload module (user/init-tests/torn_workload.c) exercises every
# disk-write shape while QEMU's blklogwrites driver logs each block write
# (tools/qemu.sh WRITE_LOG); then tests/run/tornreplay.py applies every
# prefix of the log to a pristine copy of the partition — each prefix is a
# reachable power-loss state — and checks structural invariants plus the
# hive's torn-write-falls-back-to-empty guarantee on all of them.
tornwrite() {
    make -C "$ROOT" build/proskrnl build/modules/torn_workload.bin \
        build/modules/pe_smoke.exe build/modules/sample.dat >/dev/null
    local kernel="$ROOT/build/proskrnl" img="$BUILD/tornwrite.hdd"
    local logbin="$BUILD/tornwrite-writes.bin" serial="$BUILD/tornwrite-serial.log"
    mkdir -p "$BUILD"

    local specs=("$ROOT/build/modules/pe_smoke.exe=initrd"
                 "$ROOT/build/modules/sample.dat=initrd"
                 "$ROOT/build/modules/torn_workload.bin=expect=0")
    "$ROOT/tools/mkimage.sh" "$kernel" "$img" "${specs[@]}" >/dev/null
    cp "$img" "$BUILD/tornwrite-pristine.hdd"

    rm -f "$logbin"
    truncate -s 64M "$logbin"
    WRITE_LOG="$logbin" LOG="$serial" PASS_RE="\[KTEST\] module /torn_workload.bin PASS" \
        TIMEOUT="${TIMEOUT:-900}" "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 || true
    if ! grep -q '\[KTEST\] module /torn_workload.bin PASS' "$serial"; then
        echo "== tornwrite: FAIL (the workload run itself went red; see $serial) =="
        return 1
    fi

    local fails=0
    if python3 "$ROOT/tests/run/tornreplay.py" --pristine "$BUILD/tornwrite-pristine.hdd" \
           --final "$img" --log "$logbin"; then
        :
    else
        fails=$((fails+1))
    fi
    "$ROOT/tests/run/fatcheck.sh" verify tornwrite "$img" || fails=$((fails+1))
    echo "== tornwrite: $fails failing =="
    return $((fails > 0 ? 1 : 0))
}

# The differential fuzzer (docs/08, tests/fuzz/): random Nt* sequences run on
# both the oracle and proskrnl, divergence == bug. Delegates to fuzz.py, which
# reuses the exact build recipes above. All args after `fuzz` are forwarded.
fuzz() { exec "$ROOT/tests/fuzz/fuzz.py" "$@"; }

# The M8 persistence acceptance (docs/02 "a value written by a user program
# survives reboot"): boot the SAME disk image twice. The m8_persist boot
# module seeds registry values on boot 1 (hive absent) and byte-verifies them
# — and the volatile key's absence — on boot 2, when the kernel has reloaded
# the hive the first boot wrote.
persist() {
    # A VIRGIN image: build/proskrnl.hdd may already carry a seeded hive from
    # an earlier `make test` (m8_persist runs on every boot), which would make
    # boot 1 verify instead of seed. Rebuilding the image resets the disk.
    rm -f "$ROOT/build/proskrnl.hdd"
    make -C "$ROOT" >/dev/null
    local img="$ROOT/build/tests/persist.hdd"
    mkdir -p "$ROOT/build/tests"
    cp "$ROOT/build/proskrnl.hdd" "$img"

    local log1="$ROOT/build/tests/persist1.log" log2="$ROOT/build/tests/persist2.log"
    # Boot 1 of a virgin image runs the whole CUI-1 firstboot INF pass
    # (minutes under TCG); boot 2 skips it via wineboot's timestamp check.
    LOG="$log1" TIMEOUT="${TIMEOUT:-900}" "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 || true
    if ! grep -q 'm8_persist: seeded' "$log1" || \
       ! grep -qE '^\[KTEST\] module /m8_persist.bin PASS' "$log1"; then
        echo "== persist: FAIL (boot 1 did not seed; see $log1) =="
        return 1
    fi
    LOG="$log2" TIMEOUT="${TIMEOUT:-900}" "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 || true
    if ! grep -q 'm8_persist: verified' "$log2" || \
       ! grep -qE '^\[KTEST\] module /m8_persist.bin PASS' "$log2" || \
       ! grep -qE '^\[KTEST\] M8 PASS' "$log2"; then
        echo "== persist: FAIL (boot 2 did not verify; see $log2) =="
        return 1
    fi
    # The external FAT oracle after boot 2 (the hive write path's image).
    if ! "$ROOT/tests/run/fatcheck.sh" verify persist "$img"; then
        echo "== persist: FAIL (fatcheck) =="
        return 1
    fi
    echo "== persist: PASS (seeded on boot 1, verified after reboot) =="
    return 0
}

# The CUI-1 acceptance (docs/02 "a registry differential vs. the oracle's
# prefix is green" — Art. 6, the diff convicts): boot a VIRGIN standard
# image once (firstboot runs wineboot --init through rundll32/setupapi),
# pull the SYSTEM hive off the FAT volume, and diff it against the registry
# the SAME payload produces in a fresh prefix under the pinned oracle wine.
# regdump.py canonicalizes both sides; regdiff.py carries the documented
# exclusion list (docs/03 "CUI-1 firstboot notes").
firstboot() {
    mkdir -p "$BUILD"

    # --- proskrnl leg: virgin image (the persist() pattern), one boot ---
    rm -f "$ROOT/build/proskrnl.hdd"
    make -C "$ROOT" >/dev/null
    local img="$BUILD/firstboot.hdd"
    cp "$ROOT/build/proskrnl.hdd" "$img"
    local log="$BUILD/firstboot.log"
    LOG="$log" PASS_RE="\[KTEST\] firstboot PASS" TIMEOUT="${TIMEOUT:-900}" \
        "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 || true
    if ! grep -q "\[KTEST\] firstboot PASS" "$log"; then
        echo "[KTEST] firstboot-diff FAIL (boot did not reach firstboot PASS; see $log)"
        return 1
    fi
    # The external FAT oracle BEFORE the hive extraction below: a FAT-corrupt
    # image should fail loudly here, not feed a torn hive to regdiff.
    if ! "$ROOT/tests/run/fatcheck.sh" verify firstboot "$img"; then
        echo "[KTEST] firstboot-diff FAIL (fatcheck on the booted image)"
        return 1
    fi
    # The hive sits on the image's ESP FAT32 partition (mkimage.sh: p2 at
    # sector 4096, the same byte offset mkimage's own mcopy uses).
    local hive="$BUILD/firstboot-SYSTEM"
    rm -f "$hive"
    mcopy -i "$img@@2097152" ::/windows/system32/config/SYSTEM "$hive"

    # --- oracle leg: wineboot --init in a fresh prefix under the pinned wine ---
    # BOTH sides apply the IDENTICAL filtered INF, so the differential
    # isolates the kernel's Cm/setupapi boundary from the directive families
    # tools/filter_inf.py documents as out of scope (their registry effect —
    # RegisterDlls self-registration — is neither applied on proskrnl nor
    # comparable). The filtered INF is staged as input data over the pinned
    # tree's loader/wine.inf for the duration of this one prefix init (the
    # loader's WINEBUILDDIR always wins over the environment, so the file is
    # the only staging point); the byte-identical original is restored even
    # on failure, keeping the pinned tree — the hack meter — clean.
    local prefix="$BUILD/firstboot-prefix"
    local inf="$ROOT/third_party/wine/loader/wine.inf"
    rm -rf "$prefix"
    cp "$inf" "$BUILD/wine.inf.pristine"
    trap 'cp "'"$BUILD"'/wine.inf.pristine" "'"$inf"'"' EXIT
    # --keep WineFakeDlls: fake dlls write no registry, but a prefix without
    # them cannot launch any non-bootstrap process (see tools/filter_inf.py);
    # on the host the sources exist, so the oracle keeps them. The compared
    # AddReg/DelReg/Services payload is byte-identical to the baked INF's.
    python3 "$ROOT/tools/filter_inf.py" --keep WineFakeDlls \
        "$BUILD/wine.inf.pristine" "$BUILD/wine-oracle.inf" 2>/dev/null
    cp "$BUILD/wine-oracle.inf" "$inf"
    # Prefix creation itself applies the payload: ntdll's prefix bootstrap
    # (unix/env.c run_wineboot) runs wineboot --init --update synchronously
    # before the requested command ever loads. The requested command must be
    # a REAL on-disk .exe by unix path — a filtered-INF prefix has no fake
    # dlls, so a builtin app (bare "wineboot", or even an explicit
    # system32 path: load_main_exe hard-fails an explicit path with no file
    # behind it) can never be the initial process. The repo's own standalone
    # cmd.exe doubles as the it-really-booted signal; the registry verdict
    # itself belongs to regdiff, not this exit code.
    local oracle_out
    oracle_out="$(WINEPREFIX="$prefix" "$WINE" "$ROOT/build/modules/cmd.exe" /c \
        "echo firstboot-oracle-ok" 2>"$BUILD/firstboot-oracle.log" | tr -d '\r')"
    if ! echo "$oracle_out" | grep -q "firstboot-oracle-ok"; then
        echo "[KTEST] firstboot-diff FAIL (oracle prefix init failed; see $BUILD/firstboot-oracle.log)"
        cp "$BUILD/wine.inf.pristine" "$inf"
        trap - EXIT
        return 1
    fi
    # wineserver persists system.reg on exit; -w waits for that shutdown.
    WINEPREFIX="$prefix" "$ROOT/third_party/wine/server/wineserver" -w
    cp "$BUILD/wine.inf.pristine" "$inf"
    trap - EXIT

    # --- the differential ---
    if python3 "$ROOT/tests/run/regdiff.py" "$hive" "$prefix/system.reg" \
        "$ROOT/build/wine-proskrnl.inf"; then
        echo "[KTEST] firstboot-diff PASS"
        echo "== firstboot: PASS =="
        return 0
    fi
    echo "[KTEST] firstboot-diff FAIL"
    echo "== firstboot: FAIL (regdiff divergences above) =="
    return 1
}

# The M9 interactive-console acceptance (docs/02 "input typed into the
# serial console echoes through conhost"): boot the console-mode image with
# the serial wire on a unix socket, let console_expect.py type "ping" and
# assert conhost's echo, the cooked line, and the M9 verdict. The loop keeps
# the docs/08 shape — the expect script tees the wire into the log the
# verdict grep reads.
console() {
    make -C "$ROOT" console-img >/dev/null
    local img="$ROOT/build/proskrnl-console.hdd"
    local sock="$ROOT/build/tests/console.sock" log="$ROOT/build/tests/console.log"
    mkdir -p "$ROOT/build/tests"

    # CUI-3: a resident SCM under no-eviction/no-COW needs the winetest
    # leg's provisioning.
    SERIAL_SOCK="$sock" LOG="$log" MEM=1024M TIMEOUT="${TIMEOUT:-900}" \
        "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 &
    local qemu_wrapper=$!
    if EXPECT_DEADLINE="${EXPECT_DEADLINE:-600}" \
        python3 "$ROOT/tests/run/console_expect.py" "$sock" "$log"; then
        wait "$qemu_wrapper" 2>/dev/null || true
        # No ^ anchor: conhost cursor escapes may share the verdict's line.
        if grep -qE '\[KTEST\] module m9_echo.exe PASS' "$log" &&
           grep -qE '\[KTEST\] module cmd.exe PASS' "$log"; then
            echo "== console: PASS (conhost echo + interactive cmd.exe session) =="
            return 0
        fi
    fi
    wait "$qemu_wrapper" 2>/dev/null || true
    echo "== console: FAIL (see $log) =="
    return 1
}

# The CUI-3 acceptance (docs/02 "an sc-style query round-trips; a real
# service installs, starts, and survives reboot, all driven from ring 3"):
# boot ONE console-image disk twice. Boot 1 drives the round-trip from
# cmd.exe — sc query RpcSs over \pipe\svcctl, sc start RpcSs (a real
# service process), sc create + start SvcDemo (tests/cui/svcdemo.c), the
# proof line in C:\svcdemo.log (console_expect.py EXPECT_SCM=1). Boot 2
# asserts the SCM AUTO-started SvcDemo from the persisted registry before
# cmd ever prompted, and the proof file grew (EXPECT_SCM=2).
scm() {
    # A VIRGIN console image (the persist() pattern): a hive seeded by an
    # earlier console run could already carry SvcDemo and break the create.
    rm -f "$ROOT/build/proskrnl-console.hdd"
    make -C "$ROOT" console-img >/dev/null
    local img="$ROOT/build/tests/scm.hdd"
    mkdir -p "$ROOT/build/tests"
    cp "$ROOT/build/proskrnl-console.hdd" "$img"

    local boot sock log qemu_wrapper
    for boot in 1 2; do
        sock="$ROOT/build/tests/scm$boot.sock"
        log="$ROOT/build/tests/scm$boot.log"
        SERIAL_SOCK="$sock" LOG="$log" MEM=1024M TIMEOUT="${TIMEOUT:-900}" \
            "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 &
        qemu_wrapper=$!
        if ! EXPECT_DEADLINE="${EXPECT_DEADLINE:-600}" EXPECT_SCM="$boot" \
            python3 "$ROOT/tests/run/console_expect.py" "$sock" "$log"; then
            wait "$qemu_wrapper" 2>/dev/null || true
            echo "== scm: FAIL (boot $boot; see $log) =="
            return 1
        fi
        wait "$qemu_wrapper" 2>/dev/null || true
        if ! grep -qE '\[KTEST\] module cmd.exe PASS' "$log"; then
            echo "== scm: FAIL (boot $boot cmd verdict; see $log) =="
            return 1
        fi
    done
    echo "== scm: PASS (sc round-trip + reboot-survival autostart) =="
    return 0
}

# CUI-4 acceptance (docs/02 "a tasklist/taskkill pair works against live
# processes; Ctrl+C interrupts a loop under cmd.exe; a job-object-using build
# tool completes"). One interactive boot over the console image: the
# EXPECT_PROCS block in console_expect.py types the session and asserts the
# markers, ^C included (the serial socket is bidirectional — docs/08).
procs() {
    # A VIRGIN console image (the scm() pattern): a booted image is REWRITTEN
    # by the guest, so its mtime outruns the modules and make would skip the
    # rebuild — the acceptance would then run against an image missing the
    # very programs it types.
    rm -f "$ROOT/build/proskrnl-console.hdd"
    make -C "$ROOT" console-img >/dev/null
    local img="$ROOT/build/tests/procs.hdd"
    mkdir -p "$ROOT/build/tests"
    cp "$ROOT/build/proskrnl-console.hdd" "$img"

    local sock="$ROOT/build/tests/procs.sock" log="$ROOT/build/tests/procs.log"
    SERIAL_SOCK="$sock" LOG="$log" MEM=1024M TIMEOUT="${TIMEOUT:-900}" \
        "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 &
    local qemu_wrapper=$!
    if EXPECT_DEADLINE="${EXPECT_DEADLINE:-600}" EXPECT_PROCS=1 \
        python3 "$ROOT/tests/run/console_expect.py" "$sock" "$log"; then
        wait "$qemu_wrapper" 2>/dev/null || true
        if grep -qE '\[KTEST\] module cmd.exe PASS' "$log"; then
            echo "== procs: PASS (Ctrl+C interrupt + tasklist/taskkill + job tool) =="
            return 0
        fi
    fi
    wait "$qemu_wrapper" 2>/dev/null || true
    echo "== procs: FAIL (see $log) =="
    return 1
}

# The GUI-1 acceptance (docs/02 "a user program maps the framebuffer and
# draws a rectangle visible in a screendump; key input is readable"): boot
# the gui image with a QMP socket and a virtio keyboard, wait for the guest
# to report what it painted, screendump the scanout and check the pixels
# against that report, then press a key and watch it come back out of
# \Device\Input0.
#
# There is no oracle leg here and cannot be one: \Device\Fb0 and
# \Device\Input0 are HACK devices (docs/10 HACK-001/002) that NT does not
# have, so no tests/ntapi case can pin them on Wine (the G5 adaptation is
# written out in docs/03 "GUI-1 notes"). What stands in for the oracle is
# QEMU: the pixels are rendered by its device model and the key is injected
# by its input layer, neither of which the kernel controls (Art. 6).
gui() {
    make -C "$ROOT" gui-img >/dev/null
    local img="$ROOT/build/proskrnl-gui.hdd"
    local dir="$ROOT/build/tests"
    local sock="$dir/gui.sock" log="$dir/gui.log" ppm="$dir/gui.ppm"
    mkdir -p "$dir"
    # The log too: qemu.sh truncates it, but not before this function starts
    # polling it, and a previous run's markers would satisfy every await
    # instantly -- screendumping a framebuffer the guest has not painted yet.
    rm -f "$sock" "$ppm" "$log"

    # The guest never powers itself off (it must hold the painted frame for
    # the screendump), so this leg always ends the guest itself.
    QMP_SOCK="$sock" LOG="$log" EXTRA_DEVICES="virtio-keyboard-pci" \
        TIMEOUT="${TIMEOUT:-300}" PASS_RE='\[KTEST\] gui input PASS' \
        "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 &
    local qemu_wrapper=$!

    # Wait for a marker to appear in the serial log, or give up.
    await() {
        local pattern="$1" deadline=$((SECONDS + ${GUI_DEADLINE:-180}))
        while ((SECONDS < deadline)); do
            grep -qE "$pattern" "$log" 2>/dev/null && return 0
            kill -0 "$qemu_wrapper" 2>/dev/null || return 1  # QEMU died first
            sleep 1
        done
        return 1
    }
    gui_fail() {
        python3 "$ROOT/tests/gui/qmpctl.py" "$sock" quit >/dev/null 2>&1 || true
        wait "$qemu_wrapper" 2>/dev/null || true
        echo "== gui: FAIL ($1; see $log) =="
        return 1
    }

    if ! await '\[KTEST\] gui fb drawn '; then
        gui_fail "the guest never reported a painted framebuffer"; return 1
    fi
    if ! python3 "$ROOT/tests/gui/qmpctl.py" "$sock" screendump "$ppm"; then
        gui_fail "screendump failed"; return 1
    fi

    if ! await '\[KTEST\] gui input READY'; then
        gui_fail "the guest never opened \\Device\\Input0"; return 1
    fi
    if ! python3 "$ROOT/tests/gui/qmpctl.py" "$sock" sendkey a; then
        gui_fail "send-key failed"; return 1
    fi
    if ! await '\[KTEST\] gui input (PASS|FAIL)'; then
        gui_fail "no input verdict after send-key"; return 1
    fi

    python3 "$ROOT/tests/gui/qmpctl.py" "$sock" quit >/dev/null 2>&1 || true
    wait "$qemu_wrapper" 2>/dev/null || true

    # Both halves must be green, and the picture must agree with the guest.
    if ! grep -qE '\[KTEST\] gui fb PASS' "$log"; then
        echo "== gui: FAIL (framebuffer half; see $log) =="; return 1
    fi
    if ! grep -qE '\[KTEST\] gui input PASS' "$log"; then
        echo "== gui: FAIL (input half; see $log) =="; return 1
    fi
    if ! python3 "$ROOT/tests/gui/check_rect.py" --log "$log" --ppm "$ppm"; then
        echo "== gui: FAIL (screendump does not match what the guest painted) =="; return 1
    fi
    echo "== gui: PASS (framebuffer rectangle in a screendump + key input) =="
    return 0
}

# GUI-2 (docs/02 "winemine.exe appears on screen"). Same shape as gui()
# above: boot the gui2 image with a QMP socket and a virtio keyboard, wait
# for winefb.drv to report the scanout and then a painted window,
# screendump, and check the picture against what the guest said.
#
# No oracle leg, for the same reason gui() has none -- \Device\Fb0 is a
# HACK device NT does not have (docs/03 "GUI-1 notes", the G5 adaptation).
# What stands in for it is QEMU's own device model rendering the pixels
# back (Art. 6), plus the fact that everything ABOVE the driver is
# unmodified Wine: user32, gdi32, comctl32 and winemine are the pinned
# tree's own binaries, and win32u is its own sources compiled as PE.
gui2() {
    make -C "$ROOT" gui2-img >/dev/null
    local img="$ROOT/build/proskrnl-gui2.hdd"
    local dir="$ROOT/build/tests"
    local sock="$dir/gui2.sock" log="$dir/gui2.log" ppm="$dir/gui2.ppm"
    mkdir -p "$dir"
    rm -f "$sock" "$ppm" "$log"

    # 1024M like the console leg: no COW means every process copies the
    # DLLs it maps, and this image's userland is the whole GUI stack.
    #
    # PASS_RE deliberately never matches: qemu.sh's verdict-killer reaps
    # QEMU GRACE seconds after the regex appears, and this leg still needs
    # the live QMP socket for the screendump AFTER the window marker. QEMU's
    # lifetime is owned here (qmpctl quit below), with qemu.sh's TIMEOUT as
    # the wedged-run backstop.
    QMP_SOCK="$sock" LOG="$log" EXTRA_DEVICES="virtio-keyboard-pci" MEM="${MEM:-1024M}" \
        TIMEOUT="${TIMEOUT:-900}" PASS_RE='PRSK-GUI2-NEVER' \
        "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 &
    local qemu_wrapper=$!

    await() {
        local pattern="$1" deadline=$((SECONDS + ${GUI_DEADLINE:-600}))
        while ((SECONDS < deadline)); do
            grep -qE "$pattern" "$log" 2>/dev/null && return 0
            kill -0 "$qemu_wrapper" 2>/dev/null || return 1  # QEMU died first
            sleep 1
        done
        return 1
    }
    gui2_fail() {
        python3 "$ROOT/tests/gui/qmpctl.py" "$sock" quit >/dev/null 2>&1 || true
        wait "$qemu_wrapper" 2>/dev/null || true
        echo "== gui2: FAIL ($1; see $log) =="
        return 1
    }

    if ! await '\[KTEST\] gui2 mode '; then
        gui2_fail "winefb.drv never mapped the scanout"; return 1
    fi
    if ! await '\[KTEST\] gui2 window '; then
        gui2_fail "no window ever reached the scanout"; return 1
    fi
    # The first flush is the whole first paint (dibdrv composes the full
    # window before winefb flushes it); winemine then IDLES — no repaint
    # without input, so no later flush to wait for. The sleep lets the
    # scanout and QEMU's device model settle before the dump.
    sleep 3

    if ! python3 "$ROOT/tests/gui/qmpctl.py" "$sock" screendump "$ppm"; then
        gui2_fail "screendump failed"; return 1
    fi

    python3 "$ROOT/tests/gui/qmpctl.py" "$sock" quit >/dev/null 2>&1 || true
    wait "$qemu_wrapper" 2>/dev/null || true

    if ! python3 "$ROOT/tests/gui/check_window.py" --log "$log" --ppm "$ppm"; then
        echo "== gui2: FAIL (the screendump does not show what the guest painted) =="
        return 1
    fi
    echo "== gui2: PASS (winemine.exe on screen) =="
    return 0
}

# GUI-3 (docs/02 "two GUI processes run at once; Z-order, focus, cross-thread
# SendMessage, FindWindow all behave"): wineserver-lite as a PROCESS with two
# GUI clients above it. Same shape as gui2 -- this function owns QEMU's
# lifetime so the screendump can be taken while the windows are still up --
# but the verdict has two halves: what the guests REPORTED about each
# behaviour, and the pixels proving both windows really reached the scanout
# (tests/gui/check_gui3.py).
gui3() {
    make -C "$ROOT" gui3-img >/dev/null
    local img="$ROOT/build/proskrnl-gui3.hdd"
    local dir="$ROOT/build/tests"
    local sock="$dir/gui3.sock" log="$dir/gui3.log" ppm="$dir/gui3.ppm"
    mkdir -p "$dir"
    rm -f "$sock" "$ppm" "$log"

    # More memory than gui2: no COW, and this image runs THREE Wine processes
    # (the server plus two clients), each copying the images it maps.
    QMP_SOCK="$sock" LOG="$log" EXTRA_DEVICES="virtio-keyboard-pci" MEM="${MEM:-1536M}" \
        TIMEOUT="${TIMEOUT:-1200}" PASS_RE='PRSK-GUI3-NEVER' \
        "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 &
    local qemu_wrapper=$!

    await() {
        local pattern="$1" deadline=$((SECONDS + ${GUI_DEADLINE:-900}))
        while ((SECONDS < deadline)); do
            grep -qE "$pattern" "$log" 2>/dev/null && return 0
            kill -0 "$qemu_wrapper" 2>/dev/null || return 1  # QEMU died first
            sleep 1
        done
        return 1
    }
    gui3_fail() {
        python3 "$ROOT/tests/gui/qmpctl.py" "$sock" quit >/dev/null 2>&1 || true
        wait "$qemu_wrapper" 2>/dev/null || true
        echo "== gui3: FAIL ($1; see $log) =="
        return 1
    }

    if ! await '\[KTEST\] gui3 server READY'; then
        gui3_fail "wineserver-lite never published its transport"; return 1
    fi
    if ! await '\[KTEST\] gui3 verdict (PASS|FAIL)'; then
        gui3_fail "the second GUI process never reached a verdict"; return 1
    fi
    # Both clients park with their windows up; let the last paint settle on
    # the scanout before dumping (the gui2 reasoning).
    sleep 3

    if ! python3 "$ROOT/tests/gui/qmpctl.py" "$sock" screendump "$ppm"; then
        gui3_fail "screendump failed"; return 1
    fi

    python3 "$ROOT/tests/gui/qmpctl.py" "$sock" quit >/dev/null 2>&1 || true
    wait "$qemu_wrapper" 2>/dev/null || true

    if ! python3 "$ROOT/tests/gui/check_gui3.py" --log "$log" --ppm "$ppm"; then
        echo "== gui3: FAIL (behaviour or pixels; see $log) =="
        return 1
    fi
    echo "== gui3: PASS (two GUI processes over wineserver-lite) =="
    return 0
}

# GUI-4 (docs/02 "windows can be grabbed and moved; clicks reach the right
# window"): two overlapping windows over wineserver-lite, driven from here
# through QEMU's tablet and keyboard (qmpctl absmove/button/sendkey). Every
# injection is awaited before the next -- the guests print on receipt -- so
# the choreography is sequenced, not timed. Two screendumps: before the
# drag (compositing: the upper window's colour wins the overlap; the cursor
# parked on background) and after it (the window moved; what it uncovered
# was repaired). tests/gui/check_gui4.py grades both halves.
gui4() {
    make -C "$ROOT" gui4-img >/dev/null
    local img="$ROOT/build/proskrnl-gui4.hdd"
    local dir="$ROOT/build/tests"
    local sock="$dir/gui4.sock" log="$dir/gui4.log"
    local ppm1="$dir/gui4-before.ppm" ppm2="$dir/gui4-after.ppm"
    mkdir -p "$dir"
    rm -f "$sock" "$ppm1" "$ppm2" "$log"

    QMP_SOCK="$sock" LOG="$log" EXTRA_DEVICES="virtio-keyboard-pci virtio-tablet-pci" \
        MEM="${MEM:-1536M}" TIMEOUT="${TIMEOUT:-1200}" PASS_RE='PRSK-GUI4-NEVER' \
        "$ROOT/tools/qemu.sh" "$img" >/dev/null 2>&1 &
    local qemu_wrapper=$!

    await() {
        local pattern="$1" deadline=$((SECONDS + ${GUI_DEADLINE:-900}))
        while ((SECONDS < deadline)); do
            grep -qE "$pattern" "$log" 2>/dev/null && return 0
            kill -0 "$qemu_wrapper" 2>/dev/null || return 1  # QEMU died first
            sleep 1
        done
        return 1
    }
    gui4_fail() {
        python3 "$ROOT/tests/gui/qmpctl.py" "$sock" quit >/dev/null 2>&1 || true
        wait "$qemu_wrapper" 2>/dev/null || true
        echo "== gui4: FAIL ($1; see $log) =="
        return 1
    }
    qmp() { python3 "$ROOT/tests/gui/qmpctl.py" "$sock" "$@"; }

    await '\[KTEST\] gui4 A ready rect=' || { gui4_fail "A never came up"; return 1; }
    await '\[KTEST\] gui4 B ready wrect=.* ztop=PASS' || { gui4_fail "B never came up above A"; return 1; }
    await '\[KTEST\] gui4 mouse READY' || { gui4_fail "no pointer reader"; return 1; }

    # Geometry, all guest-reported: the scanout mode, the tablet's own abs
    # range, and the windows' rectangles. Nothing here assumes a size.
    local w h maxx maxy
    w=$(grep -oE '\[KTEST\] gui2 mode w=[0-9]+' "$log" | tail -1 | grep -oE '[0-9]+$')
    h=$(grep -oE '\[KTEST\] gui2 mode w=[0-9]+ h=[0-9]+' "$log" | tail -1 | grep -oE '[0-9]+$')
    maxx=$(grep -oE 'mouse READY abs=[0-9]+\.\.[0-9]+' "$log" | tail -1 | grep -oE '[0-9]+$')
    maxy=$(grep -oE 'mouse READY abs=[0-9]+\.\.[0-9]+,[0-9]+\.\.[0-9]+' "$log" | tail -1 | grep -oE '[0-9]+$')
    local a_line b_line
    a_line=$(grep -oE '\[KTEST\] gui4 A ready rect=[-0-9]+,[-0-9]+,[0-9]+x[0-9]+' "$log" | tail -1)
    b_line=$(grep -oE '\[KTEST\] gui4 B ready wrect=[-0-9]+,[-0-9]+,[0-9]+x[0-9]+ crect=[-0-9]+,[-0-9]+,[0-9]+x[0-9]+ caption=[-0-9]+,[-0-9]+' "$log" | tail -1)
    local ax ay aw ah bx by bw bh cx cy capx capy
    ax=$(sed -E 's/.*rect=(-?[0-9]+),.*/\1/' <<<"$a_line")
    ay=$(sed -E 's/.*rect=-?[0-9]+,(-?[0-9]+),.*/\1/' <<<"$a_line")
    aw=$(sed -E 's/.*,([0-9]+)x[0-9]+$/\1/' <<<"$a_line")
    ah=$(sed -E 's/.*x([0-9]+)$/\1/' <<<"$a_line")
    bx=$(sed -E 's/.*wrect=(-?[0-9]+),.*/\1/' <<<"$b_line")
    by=$(sed -E 's/.*wrect=-?[0-9]+,(-?[0-9]+),.*/\1/' <<<"$b_line")
    bw=$(sed -E 's/.*wrect=-?[0-9]+,-?[0-9]+,([0-9]+)x.*/\1/' <<<"$b_line")
    bh=$(sed -E 's/.*wrect=-?[0-9]+,-?[0-9]+,[0-9]+x([0-9]+).*/\1/' <<<"$b_line")
    cx=$(sed -E 's/.*crect=(-?[0-9]+),.*/\1/' <<<"$b_line")
    cy=$(sed -E 's/.*crect=-?[0-9]+,(-?[0-9]+),.*/\1/' <<<"$b_line")
    local cw ch
    cw=$(sed -E 's/.*crect=-?[0-9]+,-?[0-9]+,([0-9]+)x.*/\1/' <<<"$b_line")
    ch=$(sed -E 's/.*crect=-?[0-9]+,-?[0-9]+,[0-9]+x([0-9]+).*/\1/' <<<"$b_line")
    capx=$(sed -E 's/.*caption=(-?[0-9]+),.*/\1/' <<<"$b_line")
    capy=$(sed -E 's/.*caption=-?[0-9]+,(-?[0-9]+).*/\1/' <<<"$b_line")
    if [ -z "$w" ] || [ -z "$maxx" ] || [ -z "$capy" ]; then
        gui4_fail "could not parse guest geometry"; return 1
    fi

    # Pixel -> tablet value, exact by construction: v = ceil(px*max/(w-1))
    # makes the guest's floor(v*(w-1)/max) reproduce px (qmpctl.py notes the
    # verbatim QMP->guest path this relies on), so `await` can gate on the
    # guest echoing the exact position back.
    move_px() {
        local vx=$(( ($1 * maxx + w - 2) / (w - 1) ))
        local vy=$(( ($2 * maxy + h - 2) / (h - 1) ))
        qmp absmove "$vx" "$vy" || return 1
        await "\[KTEST\] gui4 ptr x=$1 y=$2 btn=" || return 1
    }

    # Park the cursor over bare desktop and take the before-drag dump.
    local park1x=40 park1y=$((h - 100)) park2x=60 park2y=$((h - 40))
    move_px "$park1x" "$park1y" || { gui4_fail "pointer motion never arrived"; return 1; }
    sleep 2   # let the last flush settle (the gui2 reasoning)
    qmp screendump "$ppm1" || { gui4_fail "screendump 1 failed"; return 1; }

    # Click the centre of the overlap of A with B's CLIENT area (a frame
    # click would be a non-client message): it must reach B (above), never A.
    local ox=$(( ( (ax > cx ? ax : cx) + ( (ax + aw) < (cx + cw) ? (ax + aw) : (cx + cw) ) ) / 2 ))
    local oy=$(( ( (ay > cy ? ay : cy) + ( (ay + ah) < (cy + ch) ? (ay + ah) : (cy + ch) ) ) / 2 ))
    move_px "$ox" "$oy" || { gui4_fail "pointer motion lost"; return 1; }
    qmp button left down && qmp button left up
    await '\[KTEST\] gui4 B click ' || { gui4_fail "the overlap click never reached B"; return 1; }
    qmp sendkey b
    await '\[KTEST\] gui4 B char=62' || { gui4_fail "keyboard input never reached B"; return 1; }

    # Click A's exposed part: focus follows the click across processes.
    move_px $((ax + 50)) $((ay + 50)) || { gui4_fail "pointer motion lost"; return 1; }
    qmp button left down && qmp button left up
    await '\[KTEST\] gui4 A click ' || { gui4_fail "the exposed click never reached A"; return 1; }
    await '\[KTEST\] gui4 A active' || { gui4_fail "the click did not activate A"; return 1; }
    qmp sendkey a
    await '\[KTEST\] gui4 A char=61' || { gui4_fail "focus did not follow the click"; return 1; }

    # Grab B by its own advertised caption point and drag it +150,+120 in
    # ten awaited steps (DefWindowProc's modal loop moves the window per
    # WM_MOUSEMOVE under server-side capture; none of the drag is our code).
    local dragx=$capx dragy=$capy step
    move_px "$dragx" "$dragy" || { gui4_fail "pointer motion lost"; return 1; }
    qmp button left down
    for step in $(seq 1 10); do
        dragx=$((dragx + 15)); dragy=$((dragy + 12))
        move_px "$dragx" "$dragy" || { gui4_fail "drag motion lost at step $step"; return 1; }
    done
    qmp button left up
    await "\[KTEST\] gui4 B moved rect=$((bx + 150)),$((by + 120)),${bw}x${bh}" \
        || { gui4_fail "B never reported the dragged-to rectangle"; return 1; }

    # Park again (a different spot, so the await cannot match the first
    # park), then ask B -- still focused from the drag -- for one more
    # repaint now that the cursor has left it (the save-under restore can
    # deposit a stale patch over the caption; cursor.c documents it), and
    # take the after-drag dump.
    move_px "$park2x" "$park2y" || { gui4_fail "pointer motion lost"; return 1; }
    qmp sendkey r
    await '\[KTEST\] gui4 B char=72' || { gui4_fail "the repaint request never reached B"; return 1; }
    sleep 2
    qmp screendump "$ppm2" || { gui4_fail "screendump 2 failed"; return 1; }

    python3 "$ROOT/tests/gui/qmpctl.py" "$sock" quit >/dev/null 2>&1 || true
    wait "$qemu_wrapper" 2>/dev/null || true

    if ! python3 "$ROOT/tests/gui/check_gui4.py" --log "$log" --ppm1 "$ppm1" --ppm2 "$ppm2" \
            --park1 "$park1x,$park1y" --park2 "$park2x,$park2y"; then
        echo "== gui4: FAIL (behaviour or pixels; see $log) =="
        return 1
    fi
    echo "== gui4: PASS (grabbed, moved, clicked -- the compositor holds) =="
    return 0
}

case "$MODE" in
    oracle)   oracle ;;
    proskrnl) proskrnl ;;
    winetest) winetest ;;
    fuzz)     fuzz "${@:2}" ;;
    persist)  persist ;;
    firstboot) firstboot ;;
    console)  console ;;
    scm)      scm ;;
    procs)    procs ;;
    fatinterop) fatinterop ;;
    fatstress) fatstress ;;
    tornwrite) tornwrite ;;
    gui)      gui ;;
    gui2)     gui2 ;;
    gui3)     gui3 ;;
    gui4)     gui4 ;;
    *) echo "usage: $0 {oracle|proskrnl|winetest|fuzz [fuzz.py options]|persist|firstboot|console|scm|procs|fatinterop|fatstress|tornwrite|gui|gui2|gui3|gui4}" >&2
       exit 2 ;;
esac
