/*
 * config.h - shadows the pinned tree's, to turn win32u's font backend on.
 *
 * Found before third_party/wine/include because -Iuser/wine/include comes
 * first; the real header is pulled in unchanged through #include_next, so
 * this adds to it rather than forking it.
 *
 * This shadow exists because the proskrnl win32u build runs no configure of
 * its own -- it is a PE cross-build of the pinned tree's unix sources, so
 * nothing generates a config.h for it and the defines have to come from
 * somewhere. That is the whole reason, and it does not go away.
 *
 * What DID change: at GUI-2 the pinned Wine was configured
 * --without-freetype, so these defines described this build alone and the
 * two builds had no font backend in common. GUI-3 reconfigured the pin
 * --with-freetype --without-fontconfig against the SAME pinned FreeType
 * (tools/setup_linux.sh), making it the font-metrics oracle -- so the values
 * below now MATCH the ones the pinned tree's own config.h carries, and the
 * two builds of dlls/win32u/freetype.c compile identically. Keep them in
 * agreement: they are one contract with two generators (docs/03 "the font
 * oracle").
 *
 * The difference that remains is only how the library is reached. The oracle
 * dlopen()s a real libfreetype.so.6; here there is no dynamic loader, so the
 * same soname is answered by prsk_dlopen against the PE static library
 * linked in (user/wine/win32u/freetype_link.c).
 *
 * fontconfig is deliberately NOT enabled -- on either side. It is a
 * font-discovery service for unix desktops; with SONAME_LIBFONTCONFIG
 * undefined, freetype.c falls back to scanning the fonts directory, which is
 * where the gui images bake Wine's own font files. Enabling it in the oracle
 * would let host fonts into the spec, which is why the configure line pins it
 * off rather than leaving it to autodetection.
 *
 * The pin below is the belt to that braces. The pinned tree's config.h is
 * GENERATED by its configure on whatever host built the oracle, so every
 * optional-backend SONAME in it reflects that host's installed dev packages
 * (the QEMU GTK build drags fontconfig/EGL dev headers onto the CI runner).
 * This build enables exactly one backend -- FreeType, linked in below -- so
 * every other SONAME the compiled sources test is pinned OFF here, right
 * after the include_next hands us the host's answers. Fontconfig would
 * otherwise #include the unix <fontconfig/fontconfig.h> into a PE
 * cross-compile; EGL/Vulkan would merely dlopen names prsk_dlopen refuses,
 * but which code a binary contains must not depend on who built the oracle.
 */
#ifndef PRSK_CONFIG_H
#define PRSK_CONFIG_H

#include_next <config.h>

#undef SONAME_LIBFONTCONFIG
#undef SONAME_LIBEGL
#undef SONAME_LIBVULKAN

#ifdef PRSK_WITH_FREETYPE

#undef HAVE_FT2BUILD_H
#define HAVE_FT2BUILD_H 1

/* The name freetype.c passes to dlopen(). There is no shared object behind
 * it -- prsk_dlopen answers for exactly this string and prsk_dlsym resolves
 * against the linked-in library (user/wine/win32u/freetype_link.c) -- but it
 * still has to be the spelling both sides agree on. */
#undef SONAME_LIBFREETYPE
#define SONAME_LIBFREETYPE "libfreetype.so.6"

#endif /* PRSK_WITH_FREETYPE */

#endif /* PRSK_CONFIG_H */
