#!/usr/bin/env python3
"""gen_abi.py - generate abi/ headers from Wine's headers (Constitution Art. 4).

Every numeric value in abi/ (NTSTATUS codes, contract enums, boundary limits)
is extracted from third_party/wine/include/*.h - never typed by hand and never
recalled from model memory. Re-run after bumping the Wine submodule:

    python3 tools/gen_abi.py            # writes abi/ntstatus.h, abi/ntdef.h

The non-numeric scaffold (base typedefs, LIST_ENTRY/LARGE_INTEGER shapes) is
fixed text below; it carries static_asserts so a drift fails at compile time.
"""

import argparse
import re
import sys
from pathlib import Path

BANNER = """\
/* {name} - GENERATED by tools/gen_abi.py from {source}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
"""


def gen_ntstatus(wine: Path) -> str:
    """Extract every `#define STATUS_* ((NTSTATUS) 0x...)` from Wine's ntstatus.h."""
    src = (wine / "include/ntstatus.h").read_text()
    pattern = re.compile(
        r"^#define\s+(STATUS_\w+)\s+\(\(NTSTATUS\)\s*(0x[0-9A-Fa-f]+)\)", re.M
    )
    lines = [
        f"#define {name} ((NTSTATUS) {value})" for name, value in pattern.findall(src)
    ]
    if len(lines) < 2000:
        sys.exit(f"gen_abi: ntstatus extraction looks wrong ({len(lines)} values)")
    body = "\n".join(lines)
    return (
        BANNER.format(name="abi/ntstatus.h", source="wine/include/ntstatus.h")
        + "#ifndef PROSKRNL_ABI_NTSTATUS_H\n"
        + "#define PROSKRNL_ABI_NTSTATUS_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + body
        + "\n\n#endif /* PROSKRNL_ABI_NTSTATUS_H */\n"
    )


def extract_defines(src: str, source_name: str, names: list[str]) -> str:
    """Pull `#define NAME value` lines verbatim, in the order given (so a
    definition may reference an earlier one). Backslash-continued definitions
    (e.g. winnt.h's FILE_GENERIC_READ) are joined. Values are never retyped."""
    lines = []
    for name in names:
        match = re.search(
            r"^#define\s+" + re.escape(name) + r"\s+((?:[^\n]*\\\n)*[^\n]*?)\s*$",
            src,
            re.M,
        )
        if not match:
            sys.exit(f"gen_abi: #define {name} not found in {source_name}")
        value = re.sub(r"\s*\\\n\s*", " ", match.group(1))
        lines.append(f"#define {name} {value}")
    return "\n".join(lines)


def extract_struct(src: str, tag: str, typedef: str, keep_tag: bool = False) -> str:
    """Pull one `typedef struct _TAG { ... } NAME, *PNAME...;` body verbatim.
    The reserved `_TAG` tag is dropped by default; members are kept
    byte-for-byte. keep_tag preserves the tag so another header can carry a
    forward declaration (`typedef struct _TAG NAME;`) of the same type."""
    match = re.search(
        r"typedef struct " + tag + r"\s*\{(.*?)\}\s*([^;{}]*" + typedef + r"[^;{}]*)\s*;",
        src,
        re.S,
    )
    if not match:
        sys.exit(f"gen_abi: struct {typedef} not found")
    intro = "typedef struct " + (tag + " " if keep_tag else "") + "{"
    return intro + match.group(1) + "} " + match.group(2).strip() + ";"


def extract_plain_struct(src: str, name: str) -> str:
    """Pull one `struct NAME { ... };` body verbatim (the wine/condrv.h shape:
    plain struct tags, no typedef)."""
    match = re.search(r"struct " + re.escape(name) + r"\s*\{(.*?)\}\s*;", src, re.S)
    if not match:
        sys.exit(f"gen_abi: struct {name} not found")
    return "struct " + name + "\n{" + match.group(1) + "};"


def extract_anonymous_struct(src: str, typedef: str) -> str:
    """Pull one tagless `typedef struct { ... } NAME;` body verbatim (the
    wine/condrv.h char_info_t shape)."""
    match = re.search(
        r"typedef struct\s*\{(.*?)\}\s*(" + re.escape(typedef) + r")\s*;", src, re.S
    )
    if not match:
        sys.exit(f"gen_abi: anonymous struct {typedef} not found")
    return "typedef struct\n{" + match.group(1) + "} " + match.group(2) + ";"


def extract_plain_enum(src: str, name: str) -> str:
    """Pull one `enum NAME { ... };` body verbatim (values are positional, so
    the body must come from the Wine header, not from memory)."""
    match = re.search(r"enum " + re.escape(name) + r"\s*\{(.*?)\}\s*;", src, re.S)
    if not match:
        sys.exit(f"gen_abi: enum {name} not found")
    return "enum " + name + "\n{" + match.group(1) + "};"


def extract_prototypes(src: str, names: list[str]) -> str:
    """Pull `NTSYSAPI <ret> WINAPI Nt*(...)` prototypes verbatim from Wine's
    winternl.h, dropping the Windows linkage macros (signatures are contract;
    calling convention on x86_64 kernel builds is the platform default)."""
    lines = []
    for name in names:
        match = re.search(
            r"^NTSYSAPI\s+([\w* ]+?)\s+(?:WINAPI|NTAPI)\s+" + name + r"\s*\((.*)\);\s*$",
            src,
            re.M,
        )
        if not match:
            sys.exit(f"gen_abi: prototype {name} not found in winternl.h")
        ret, args = match.group(1).strip(), match.group(2).strip()
        lines.append(f"{ret} {name}({args});")
    return "\n".join(lines)


def resolve_ifdef(text: str, macro: str, keep: bool) -> str:
    """Resolve `#ifdef MACRO` / `#else` / `#endif` blocks in an extracted
    struct body, keeping the branch selected by `keep`. Only used for
    macros whose value is fixed by the project (e.g. __WINESRC__ selects
    the real NT field names in PROCESS_BASIC_INFORMATION); the member
    text itself stays byte-for-byte."""
    out = []
    stack = []  # each entry: (was_matching_macro, keeping_before, in_else)
    keeping = True
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#ifdef"):
            name = stripped.split()[1] if len(stripped.split()) > 1 else ""
            if name == macro:
                stack.append((True, keeping, False))
                keeping = keeping and keep
                continue
            stack.append((False, keeping, False))
        elif stripped.startswith("#else") and stack and stack[-1][0]:
            matched, before, _ = stack[-1]
            stack[-1] = (matched, before, True)
            keeping = before and not keep
            continue
        elif stripped.startswith("#endif") and stack:
            matched, before, _ = stack.pop()
            if matched:
                keeping = before
                continue
            keeping = before
        if keeping:
            out.append(line)
    return "\n".join(out)


# Offset-comment forms in Wine's headers: `/* 32bit/64bit */` (winternl.h
# PEB/TEB), `/* 0x000 */` (wdm.h KUSER_SHARED_DATA), `/* 000 */` (winnt.h
# AMD64_CONTEXT). Trailing prose after the offsets is allowed.
OFFSET_COMMENT = re.compile(
    r"/\*\s*(?:0x)?([0-9a-fA-F]*)\s*(?:(/)\s*(?:0x)?([0-9a-fA-F]*))?"
    r"(?:\s[^*]*)?\*/"
)
MEMBER_DECL = re.compile(r"([A-Za-z_]\w*)\s*(?:\[[^\]]*\])?\s*;")


def gen_offset_asserts(struct_text: str, typedef: str) -> str:
    """Turn Wine's own per-member offset comments into _Static_asserts, so
    every extracted layout is pinned against the exact source it came from
    (Art. 4: the numbers are read from the Wine header, never retyped).
    Only top-level, non-bitfield members with an x64 offset are pinned."""
    lines = []
    depth = 0
    body = struct_text[struct_text.index("{") + 1 : struct_text.rindex("}")]
    for line in body.splitlines():
        at_top = depth == 0
        depth += line.count("{") - line.count("}")
        if not at_top or depth != 0:
            continue  # inside (or entering/leaving) a nested union/struct
        comment = OFFSET_COMMENT.search(line)
        if not comment:
            continue
        offset = comment.group(3) if comment.group(2) else comment.group(1)
        if not offset:
            continue  # 32-bit-only column
        decl = line[: comment.start()]
        if ":" in decl:
            continue  # bitfield: no offsetof
        member = MEMBER_DECL.search(decl)
        if not member:
            continue
        lines.append(
            f"_Static_assert(offsetof({typedef}, {member.group(1)}) == 0x{offset.lower()}, "
            f'"{typedef} x64 layout (offset comment in the Wine header)");'
        )
    if not lines:
        sys.exit(f"gen_abi: no offset comments found for {typedef}")
    return "\n".join(lines)


def extract_enum(src: str, tag: str, typedef: str) -> str:
    """Pull one `typedef enum _TAG { ... } NAME;` block verbatim (values are
    positional, so the body must come from the Wine header, not from memory).
    The reserved `_TAG` struct tag is dropped; the body is kept byte-for-byte."""
    match = re.search(
        r"typedef enum " + tag + r"\s*\{(.*?)\}\s*([^;{}]*" + typedef + r"[^;{}]*)\s*;",
        src,
        re.S,
    )
    if not match:
        sys.exit(f"gen_abi: enum {typedef} not found")
    return "typedef enum {" + match.group(1) + "} " + match.group(2).strip() + ";"


def gen_ntdef(wine: Path) -> str:
    ntdef = (wine / "include/ntdef.h").read_text()
    winnt = (wine / "include/winnt.h").read_text()
    winternl = (wine / "include/winternl.h").read_text()
    wdm = (wine / "include/ddk/wdm.h").read_text()

    enums = "\n\n".join(
        extract_enum(ntdef, tag, typedef)
        for tag, typedef in [
            ("_EVENT_TYPE", "EVENT_TYPE"),
            ("_TIMER_TYPE", "TIMER_TYPE"),
            ("_WAIT_TYPE", "WAIT_TYPE"),
        ]
    )

    match = re.search(r"^#define MAXIMUM_WAIT_OBJECTS\s+(\d+)", winnt, re.M)
    if not match:
        sys.exit("gen_abi: MAXIMUM_WAIT_OBJECTS not found")
    max_wait = match.group(1)

    # M3 (Ob): name/handle structs verbatim from Wine, values never retyped.
    ob_structs = "\n\n".join(
        [
            extract_struct(winternl, "_UNICODE_STRING", "UNICODE_STRING"),
            extract_struct(winternl, "_OBJECT_ATTRIBUTES", "OBJECT_ATTRIBUTES"),
        ]
    )
    obj_flags = extract_defines(
        winternl,
        "winternl.h",
        [
            "OBJ_INHERIT",
            "OBJ_PERMANENT",
            "OBJ_EXCLUSIVE",
            "OBJ_CASE_INSENSITIVE",
            "OBJ_OPENIF",
            "OBJ_OPENLINK",
            "OBJ_KERNEL_HANDLE",
        ],
    ) + "\n" + extract_defines(
        winternl, "winternl.h", ["NtCurrentProcess()", "NtCurrentThread()"]
    )
    access_rights = extract_defines(
        winnt,
        "winnt.h",
        [
            "DELETE",
            "READ_CONTROL",
            "WRITE_DAC",
            "WRITE_OWNER",
            "SYNCHRONIZE",
            "STANDARD_RIGHTS_REQUIRED",
            "STANDARD_RIGHTS_READ",
            "STANDARD_RIGHTS_WRITE",
            "STANDARD_RIGHTS_EXECUTE",
            "STANDARD_RIGHTS_ALL",
            "SPECIFIC_RIGHTS_ALL",
            "GENERIC_READ",
            "GENERIC_WRITE",
            "GENERIC_EXECUTE",
            "GENERIC_ALL",
            "MAXIMUM_ALLOWED",
            "EVENT_QUERY_STATE",
            "EVENT_MODIFY_STATE",
            "EVENT_ALL_ACCESS",
            "SEMAPHORE_QUERY_STATE",
            "SEMAPHORE_MODIFY_STATE",
            "SEMAPHORE_ALL_ACCESS",
            "MUTANT_QUERY_STATE",
            "MUTANT_ALL_ACCESS",
            "TIMER_QUERY_STATE",
            "TIMER_MODIFY_STATE",
            "TIMER_ALL_ACCESS",
            "DUPLICATE_CLOSE_SOURCE",
            "DUPLICATE_SAME_ACCESS",
            "DUPLICATE_SAME_ATTRIBUTES",
        ],
    )
    directory_rights = extract_defines(
        wdm,
        "ddk/wdm.h",
        [
            "DIRECTORY_QUERY",
            "DIRECTORY_TRAVERSE",
            "DIRECTORY_CREATE_OBJECT",
            "DIRECTORY_CREATE_SUBDIRECTORY",
            "DIRECTORY_ALL_ACCESS",
            "SYMBOLIC_LINK_QUERY",
            "SYMBOLIC_LINK_ALL_ACCESS",
        ],
    )

    scaffold = """\
/* Base NT types (LLP64). The typedef shapes are fixed scaffold; the sizes are
 * pinned by the static_asserts below, so this cannot drift silently. */
typedef char CHAR;
typedef signed char CCHAR;
typedef unsigned char UCHAR;
typedef unsigned char BOOLEAN;
typedef short CSHORT;
typedef unsigned short USHORT;
typedef int LONG;
typedef unsigned int ULONG;
typedef long long LONGLONG;
typedef unsigned long long ULONGLONG;
typedef void *PVOID;
typedef ULONGLONG ULONG_PTR;
typedef ULONG_PTR *PULONG_PTR;

typedef LONG *PLONG;
typedef ULONG *PULONG;
typedef unsigned short WCHAR, *PWCHAR, *PWSTR;
typedef const WCHAR *PCWSTR;
typedef void *HANDLE;
typedef HANDLE *PHANDLE;
typedef ULONG ACCESS_MASK;

/* Win32-flavoured aliases some contract structs/prototypes are written in
 * (Wine's winnt.h MEMORY_BASIC_INFORMATION, winternl.h Nt* prototypes). */
typedef ULONG DWORD;
typedef PVOID LPVOID;
typedef const void *LPCVOID;
typedef ULONG_PTR SIZE_T, *PSIZE_T;

/* Win32 base names used verbatim inside extracted structs (winnt.h). */
typedef unsigned short WORD;
typedef unsigned char BYTE;

/* Anonymous-union/-struct spellings used verbatim inside extracted structs. */
#define DUMMYUNIONNAME
#define DUMMYUNIONNAME2
#define DUMMYUNIONNAME3
#define DUMMYSTRUCTNAME
#define DUMMYSTRUCTNAME2

/* winnt.h: `#define VOID void`, used verbatim in extracted prototypes. */
#define VOID void

typedef LONG NTSTATUS;
typedef LONG KPRIORITY;
typedef CCHAR KPROCESSOR_MODE;

#ifndef TRUE
#define TRUE 1
#define FALSE 0
#endif

#define NT_SUCCESS(status) (((NTSTATUS)(status)) >= 0)

typedef union {
    struct
    {
        ULONG LowPart;
        LONG HighPart;
    } u;
    LONGLONG QuadPart;
} LARGE_INTEGER, *PLARGE_INTEGER;

typedef union {
    struct
    {
        ULONG LowPart;
        ULONG HighPart;
    } u;
    ULONGLONG QuadPart;
} ULARGE_INTEGER, *PULARGE_INTEGER;

typedef struct LIST_ENTRY {
    struct LIST_ENTRY *Flink;
    struct LIST_ENTRY *Blink;
} LIST_ENTRY, *PLIST_ENTRY;

_Static_assert(sizeof(LONG) == 4, "LLP64: LONG is 4 bytes");
_Static_assert(sizeof(ULONGLONG) == 8, "LLP64: ULONGLONG is 8 bytes");
_Static_assert(sizeof(PVOID) == 8, "x86_64: pointers are 8 bytes");
_Static_assert(sizeof(LARGE_INTEGER) == 8, "LARGE_INTEGER is 8 bytes");
_Static_assert(sizeof(LIST_ENTRY) == 16, "LIST_ENTRY is two pointers");
_Static_assert(sizeof(BOOLEAN) == 1, "BOOLEAN is 1 byte");
_Static_assert(sizeof(WCHAR) == 2, "WCHAR is UTF-16");
_Static_assert(sizeof(HANDLE) == 8, "x86_64: HANDLE is pointer-sized");
_Static_assert(sizeof(DWORD) == 4, "LLP64: DWORD is 4 bytes");
_Static_assert(sizeof(SIZE_T) == 8, "x86_64: SIZE_T is 8 bytes");
_Static_assert(sizeof(WORD) == 2, "Win32: WORD is 2 bytes");
_Static_assert(sizeof(BYTE) == 1, "Win32: BYTE is 1 byte");
"""

    ob_asserts = """\
#include <stddef.h>
_Static_assert(sizeof(UNICODE_STRING) == 16, "UNICODE_STRING x64 layout");
_Static_assert(offsetof(UNICODE_STRING, MaximumLength) == 2, "UNICODE_STRING x64 layout");
_Static_assert(offsetof(UNICODE_STRING, Buffer) == 8, "UNICODE_STRING x64 layout");
_Static_assert(sizeof(OBJECT_ATTRIBUTES) == 48, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, RootDirectory) == 8, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, ObjectName) == 16, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, Attributes) == 24, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, SecurityDescriptor) == 32, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, SecurityQualityOfService) == 40, "OBJECT_ATTRIBUTES x64 layout");
"""

    return (
        BANNER.format(
            name="abi/ntdef.h",
            source="wine/include/{ntdef.h,winnt.h,winternl.h,ddk/wdm.h}",
        )
        + "#ifndef PROSKRNL_ABI_NTDEF_H\n"
        + "#define PROSKRNL_ABI_NTDEF_H\n\n"
        + scaffold
        + "\n/* Contract enums, extracted verbatim from wine/include/ntdef.h. */\n"
        + enums
        + "\n\n/* Extracted from wine/include/winnt.h. */\n"
        + f"#define MAXIMUM_WAIT_OBJECTS {max_wait}\n"
        + "\n/* Ob name/handle structs, extracted verbatim from wine/include/winternl.h;\n"
        + " * the static_asserts below pin the x64 layout the boundary depends on. */\n"
        + ob_structs
        + "\n\n"
        + ob_asserts
        + "\n/* Object-attribute flags, extracted from wine/include/winternl.h. */\n"
        + obj_flags
        + "\n\n/* Access rights, extracted from wine/include/winnt.h. */\n"
        + access_rights
        + "\n\n/* Directory/symlink access rights, extracted from wine/include/ddk/wdm.h. */\n"
        + directory_rights
        + "\n\n#endif /* PROSKRNL_ABI_NTDEF_H */\n"
    )


# The M3 Nt* surface (docs/02): Ob lifetime (close/duplicate), the dispatcher
# objects moved under Ob (event/mutant/semaphore), handle-based waits, and the
# namespace (directory/symbolic link). Prototypes are extracted verbatim from
# Wine's winternl.h so no signature is ever recalled from memory (Art. 4).
NTOBAPI_FUNCTIONS = [
    "NtClose",
    "NtDuplicateObject",
    "NtMakeTemporaryObject",
    "NtCreateEvent",
    "NtOpenEvent",
    "NtSetEvent",
    "NtResetEvent",
    "NtClearEvent",
    "NtPulseEvent",
    "NtQueryEvent",
    "NtCreateMutant",
    "NtOpenMutant",
    "NtReleaseMutant",
    "NtQueryMutant",
    "NtCreateSemaphore",
    "NtOpenSemaphore",
    "NtReleaseSemaphore",
    "NtQuerySemaphore",
    "NtWaitForSingleObject",
    "NtWaitForMultipleObjects",
    "NtCreateDirectoryObject",
    "NtOpenDirectoryObject",
    "NtCreateSymbolicLinkObject",
    "NtOpenSymbolicLinkObject",
    "NtQuerySymbolicLinkObject",
    # M10 waitable timers
    "NtCreateTimer",
    "NtSetTimer",
    "NtCancelTimer",
    "NtQueryTimer",
]


def gen_ntobapi(wine: Path) -> str:
    winternl = (wine / "include/winternl.h").read_text()

    enums = "\n\n".join(
        extract_enum(winternl, tag, typedef)
        for tag, typedef in [
            ("_EVENT_INFORMATION_CLASS", "EVENT_INFORMATION_CLASS"),
            ("_MUTANT_INFORMATION_CLASS", "MUTANT_INFORMATION_CLASS"),
            ("_SEMAPHORE_INFORMATION_CLASS", "SEMAPHORE_INFORMATION_CLASS"),
            ("_TIMER_INFORMATION_CLASS", "TIMER_INFORMATION_CLASS"),
        ]
    )
    structs = "\n\n".join(
        extract_struct(winternl, tag, typedef)
        for tag, typedef in [
            ("_EVENT_BASIC_INFORMATION", "EVENT_BASIC_INFORMATION"),
            ("_MUTANT_BASIC_INFORMATION", "MUTANT_BASIC_INFORMATION"),
            ("_SEMAPHORE_BASIC_INFORMATION", "SEMAPHORE_BASIC_INFORMATION"),
            ("_TIMER_BASIC_INFORMATION", "TIMER_BASIC_INFORMATION"),
        ]
    )
    timer_apc = extract_typedef_line(winternl, "winternl.h", "PTIMER_APC_ROUTINE")
    prototypes = extract_prototypes(winternl, NTOBAPI_FUNCTIONS)

    return (
        BANNER.format(name="abi/ntobapi.h", source="wine/include/winternl.h")
        + "#ifndef PROSKRNL_ABI_NTOBAPI_H\n"
        + "#define PROSKRNL_ABI_NTOBAPI_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + "/* Information classes, extracted verbatim from wine/include/winternl.h. */\n"
        + enums
        + "\n\n"
        + structs
        + "\n\n"
        + timer_apc
        + "\n\n/* The M3 Nt* surface; signatures extracted verbatim from\n"
        + " * wine/include/winternl.h (linkage macros dropped). */\n"
        + prototypes
        + "\n\n#endif /* PROSKRNL_ABI_NTOBAPI_H */\n"
    )


# The M4 Mm surface (docs/02): the reserve/commit two-step and its query.
# M5 adds the section surface: create/open/map/unmap/query (docs/02).
NTMMAPI_FUNCTIONS = [
    "NtAllocateVirtualMemory",
    "NtFreeVirtualMemory",
    "NtQueryVirtualMemory",
    "NtCreateSection",
    "NtOpenSection",
    "NtMapViewOfSection",
    "NtUnmapViewOfSection",
    "NtQuerySection",
    # M7 (ntdll startup / loader paths)
    "NtProtectVirtualMemory",
    "NtFlushInstructionCache",
]


def gen_ntmmapi(wine: Path) -> str:
    winnt = (wine / "include/winnt.h").read_text()
    winternl = (wine / "include/winternl.h").read_text()

    mem_flags = extract_defines(
        winnt,
        "winnt.h",
        [
            "PAGE_NOACCESS",
            "PAGE_READONLY",
            "PAGE_READWRITE",
            "PAGE_WRITECOPY",
            "PAGE_EXECUTE",
            "PAGE_EXECUTE_READ",
            "PAGE_EXECUTE_READWRITE",
            "PAGE_EXECUTE_WRITECOPY",
            "PAGE_GUARD",
            "PAGE_NOCACHE",
            "MEM_COMMIT",
            "MEM_RESERVE",
            "MEM_RESET",
            "MEM_TOP_DOWN",
            "MEM_DECOMMIT",
            "MEM_RELEASE",
            "MEM_FREE",
            "MEM_PRIVATE",
            "MEM_MAPPED",
            "MEM_WRITE_WATCH",
        ],
    )

    # M5 (sections): allocation attributes + section access rights (winnt.h).
    sec_flags = extract_defines(
        winnt,
        "winnt.h",
        [
            "SEC_FILE",
            "SEC_IMAGE",
            "SEC_RESERVE",
            "SEC_COMMIT",
            "SEC_NOCACHE",
            "SEC_WRITECOMBINE",
            "SEC_LARGE_PAGES",
            "MEM_IMAGE",
            "SECTION_QUERY",
            "SECTION_MAP_WRITE",
            "SECTION_MAP_READ",
            "SECTION_MAP_EXECUTE",
            "SECTION_EXTEND_SIZE",
            "SECTION_MAP_EXECUTE_EXPLICIT",
            "SECTION_ALL_ACCESS",
            "AT_ROUND_TO_PAGE",
        ],
    )

    mbi = extract_struct(winnt, "_MEMORY_BASIC_INFORMATION", "MEMORY_BASIC_INFORMATION")
    info_class = extract_enum(
        winternl, "_MEMORY_INFORMATION_CLASS", "MEMORY_INFORMATION_CLASS"
    )
    section_enums = "\n\n".join(
        extract_enum(winternl, tag, typedef)
        for tag, typedef in [
            ("_SECTION_INHERIT", "SECTION_INHERIT"),
            ("_SECTION_INFORMATION_CLASS", "SECTION_INFORMATION_CLASS"),
        ]
    )
    section_structs = "\n\n".join(
        extract_struct(winternl, tag, typedef)
        for tag, typedef in [
            ("_SECTION_BASIC_INFORMATION", "SECTION_BASIC_INFORMATION"),
            ("_SECTION_IMAGE_INFORMATION", "SECTION_IMAGE_INFORMATION"),
        ]
    )
    prototypes = extract_prototypes(winternl, NTMMAPI_FUNCTIONS)

    mbi_asserts = """\
#include <stddef.h>
_Static_assert(sizeof(MEMORY_BASIC_INFORMATION) == 48, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, AllocationBase) == 8, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, AllocationProtect) == 16, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, RegionSize) == 24, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, State) == 32, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, Protect) == 36, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, Type) == 40, "MEMORY_BASIC_INFORMATION x64 layout");
"""

    section_asserts = """\
_Static_assert(sizeof(SECTION_BASIC_INFORMATION) == 24, "SECTION_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_BASIC_INFORMATION, Attributes) == 8, "SECTION_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_BASIC_INFORMATION, Size) == 16, "SECTION_BASIC_INFORMATION x64 layout");
_Static_assert(sizeof(SECTION_IMAGE_INFORMATION) == 64, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, MaximumStackSize) == 16, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, SubSystemType) == 32, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, Machine) == 48, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, LoaderFlags) == 52, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, CheckSum) == 60, "SECTION_IMAGE_INFORMATION x64 layout");
"""

    return (
        BANNER.format(
            name="abi/ntmmapi.h", source="wine/include/{winnt.h,winternl.h}"
        )
        + "#ifndef PROSKRNL_ABI_NTMMAPI_H\n"
        + "#define PROSKRNL_ABI_NTMMAPI_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + "/* Allocation/protection flags, extracted from wine/include/winnt.h. */\n"
        + mem_flags
        + "\n\n/* Section allocation attributes + access rights (M5), extracted from\n"
        + " * wine/include/winnt.h. */\n"
        + sec_flags
        + "\n\n/* Extracted verbatim from wine/include/winnt.h; the static_asserts pin\n"
        + " * the x64 layout the boundary depends on. */\n"
        + mbi
        + "\n\n"
        + mbi_asserts
        + "\n/* Extracted verbatim from wine/include/winternl.h. */\n"
        + info_class
        + "\n\n/* Section enums/structs (M5), extracted verbatim from\n"
        + " * wine/include/winternl.h; static_asserts pin the x64 layout. */\n"
        + section_enums
        + "\n\n"
        + section_structs
        + "\n\n"
        + section_asserts
        + "\n/* The M4+M5 Mm Nt* surface; signatures extracted verbatim from\n"
        + " * wine/include/winternl.h (linkage macros dropped). */\n"
        + prototypes
        + "\n\n#endif /* PROSKRNL_ABI_NTMMAPI_H */\n"
    )


# The PE/COFF on-disk format (M5 image sections): structures and constants
# extracted verbatim from wine/include/winnt.h (the same layout Microsoft
# documents in the PE/COFF specification). x86_64 only (ADR 0006), so only
# the 64-bit optional header is carried.
def gen_ntimage(wine: Path) -> str:
    winnt = (wine / "include/winnt.h").read_text()

    signatures = extract_defines(
        winnt,
        "winnt.h",
        [
            "IMAGE_DOS_SIGNATURE",
            "IMAGE_NT_SIGNATURE",
            "IMAGE_NT_OPTIONAL_HDR64_MAGIC",
            "IMAGE_FILE_MACHINE_AMD64",
            "IMAGE_FILE_RELOCS_STRIPPED",
            "IMAGE_FILE_EXECUTABLE_IMAGE",
            "IMAGE_FILE_DLL",
            "IMAGE_NUMBEROF_DIRECTORY_ENTRIES",
            "IMAGE_SIZEOF_SHORT_NAME",
            "IMAGE_SIZEOF_SECTION_HEADER",
            "IMAGE_DIRECTORY_ENTRY_EXPORT",
            "IMAGE_DIRECTORY_ENTRY_BASERELOC",
            "IMAGE_SCN_CNT_CODE",
            "IMAGE_SCN_CNT_INITIALIZED_DATA",
            "IMAGE_SCN_CNT_UNINITIALIZED_DATA",
            "IMAGE_SCN_MEM_SHARED",
            "IMAGE_SCN_MEM_EXECUTE",
            "IMAGE_SCN_MEM_READ",
            "IMAGE_SCN_MEM_WRITE",
            "IMAGE_REL_BASED_ABSOLUTE",
            "IMAGE_REL_BASED_HIGHLOW",
            "IMAGE_REL_BASED_DIR64",
            "IMAGE_SUBSYSTEM_NATIVE",
            "IMAGE_SUBSYSTEM_WINDOWS_GUI",
            "IMAGE_SUBSYSTEM_WINDOWS_CUI",
            "IMAGE_FIRST_SECTION(ntheader)",
        ],
    )

    structs = "\n\n".join(
        extract_struct(winnt, tag, typedef)
        for tag, typedef in [
            ("_IMAGE_DOS_HEADER", "IMAGE_DOS_HEADER"),
            ("_IMAGE_FILE_HEADER", "IMAGE_FILE_HEADER"),
            ("_IMAGE_DATA_DIRECTORY", "IMAGE_DATA_DIRECTORY"),
            ("_IMAGE_OPTIONAL_HEADER64", "IMAGE_OPTIONAL_HEADER64"),
            ("_IMAGE_NT_HEADERS64", "IMAGE_NT_HEADERS64"),
            ("_IMAGE_SECTION_HEADER", "IMAGE_SECTION_HEADER"),
            ("_IMAGE_BASE_RELOCATION", "IMAGE_BASE_RELOCATION"),
            ("_IMAGE_EXPORT_DIRECTORY", "IMAGE_EXPORT_DIRECTORY"),
        ]
    )

    asserts = """\
#include <stddef.h>
_Static_assert(sizeof(IMAGE_DOS_HEADER) == 64, "IMAGE_DOS_HEADER layout");
_Static_assert(offsetof(IMAGE_DOS_HEADER, e_lfanew) == 0x3c, "IMAGE_DOS_HEADER layout");
_Static_assert(sizeof(IMAGE_FILE_HEADER) == 20, "IMAGE_FILE_HEADER layout");
_Static_assert(sizeof(IMAGE_OPTIONAL_HEADER64) == 240, "IMAGE_OPTIONAL_HEADER64 layout");
_Static_assert(offsetof(IMAGE_OPTIONAL_HEADER64, ImageBase) == 24, "IMAGE_OPTIONAL_HEADER64 layout");
_Static_assert(offsetof(IMAGE_OPTIONAL_HEADER64, SizeOfStackReserve) == 72, "IMAGE_OPTIONAL_HEADER64 layout");
_Static_assert(offsetof(IMAGE_NT_HEADERS64, OptionalHeader) == 24, "IMAGE_NT_HEADERS64 layout");
_Static_assert(sizeof(IMAGE_SECTION_HEADER) == IMAGE_SIZEOF_SECTION_HEADER, "IMAGE_SECTION_HEADER layout");
_Static_assert(sizeof(IMAGE_BASE_RELOCATION) == 8, "IMAGE_BASE_RELOCATION layout");
_Static_assert(sizeof(IMAGE_EXPORT_DIRECTORY) == 40, "IMAGE_EXPORT_DIRECTORY layout");
_Static_assert(offsetof(IMAGE_EXPORT_DIRECTORY, NumberOfNames) == 24, "IMAGE_EXPORT_DIRECTORY layout");
_Static_assert(offsetof(IMAGE_EXPORT_DIRECTORY, AddressOfFunctions) == 28, "IMAGE_EXPORT_DIRECTORY layout");
_Static_assert(offsetof(IMAGE_EXPORT_DIRECTORY, AddressOfNames) == 32, "IMAGE_EXPORT_DIRECTORY layout");
_Static_assert(offsetof(IMAGE_EXPORT_DIRECTORY, AddressOfNameOrdinals) == 36, "IMAGE_EXPORT_DIRECTORY layout");
"""

    return (
        BANNER.format(name="abi/ntimage.h", source="wine/include/winnt.h")
        + "#ifndef PROSKRNL_ABI_NTIMAGE_H\n"
        + "#define PROSKRNL_ABI_NTIMAGE_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + "/* PE/COFF signatures and flags, extracted from wine/include/winnt.h. */\n"
        + signatures
        + "\n\n/* PE/COFF structures, extracted verbatim from wine/include/winnt.h;\n"
        + " * the static_asserts pin the on-disk layout. */\n"
        + structs
        + "\n\n"
        + asserts
        + "\n#endif /* PROSKRNL_ABI_NTIMAGE_H */\n"
    )


# The M6 Io surface (docs/02): NtCreateFile/NtOpenFile, read/write with the
# async-completion protocol shapes (IOSB, APC routine), the main info
# classes, directory enumeration, flush, and byte-range locks.
NTIOAPI_FUNCTIONS = [
    "NtCreateFile",
    "NtOpenFile",
    "NtReadFile",
    "NtWriteFile",
    "NtQueryInformationFile",
    "NtSetInformationFile",
    "NtQueryDirectoryFile",
    "NtQueryAttributesFile",
    "NtFlushBuffersFile",
    "NtLockFile",
    "NtUnlockFile",
    # M7 (ntdll startup)
    "NtQueryVolumeInformationFile",
    # M9 (npfs + condrv)
    "NtDeviceIoControlFile",
    "NtFsControlFile",
    "NtCreateNamedPipeFile",
    # M10 (CUI userland)
    "NtQueryFullAttributesFile",
    "NtCreateIoCompletion",
    "NtSetIoCompletion",
    "NtRemoveIoCompletion",
    "NtRemoveIoCompletionEx",
    "NtQueryIoCompletion",
]


def extract_typedef_line(src: str, source_name: str, name: str) -> str:
    """Pull a one-line `typedef ... NAME ...;` verbatim (used for the
    PIO_APC_ROUTINE function-pointer type), dropping the WINAPI macro."""
    match = re.search(r"^typedef[^\n;]*\b" + re.escape(name) + r"\b[^\n;]*;", src, re.M)
    if not match:
        sys.exit(f"gen_abi: typedef {name} not found in {source_name}")
    return match.group(0).strip().replace("WINAPI ", "").replace("CALLBACK ", "")


def gen_ntioapi(wine: Path) -> str:
    winnt = (wine / "include/winnt.h").read_text()
    winternl = (wine / "include/winternl.h").read_text()

    access_rights = extract_defines(
        winnt,
        "winnt.h",
        [
            "ANYSIZE_ARRAY",
            "FILE_READ_DATA",
            "FILE_LIST_DIRECTORY",
            "FILE_WRITE_DATA",
            "FILE_ADD_FILE",
            "FILE_APPEND_DATA",
            "FILE_ADD_SUBDIRECTORY",
            "FILE_READ_EA",
            "FILE_WRITE_EA",
            "FILE_EXECUTE",
            "FILE_TRAVERSE",
            "FILE_DELETE_CHILD",
            "FILE_READ_ATTRIBUTES",
            "FILE_WRITE_ATTRIBUTES",
            "FILE_ALL_ACCESS",
            "FILE_GENERIC_READ",
            "FILE_GENERIC_WRITE",
            "FILE_GENERIC_EXECUTE",
            "FILE_SHARE_READ",
            "FILE_SHARE_WRITE",
            "FILE_SHARE_DELETE",
            "FILE_ATTRIBUTE_READONLY",
            "FILE_ATTRIBUTE_HIDDEN",
            "FILE_ATTRIBUTE_SYSTEM",
            "FILE_ATTRIBUTE_DIRECTORY",
            "FILE_ATTRIBUTE_ARCHIVE",
            "FILE_ATTRIBUTE_NORMAL",
        ],
    )

    create_flags = extract_defines(
        winternl,
        "winternl.h",
        [
            # NtCreateFile options
            "FILE_DIRECTORY_FILE",
            "FILE_WRITE_THROUGH",
            "FILE_SEQUENTIAL_ONLY",
            "FILE_SYNCHRONOUS_IO_ALERT",
            "FILE_SYNCHRONOUS_IO_NONALERT",
            "FILE_NON_DIRECTORY_FILE",
            "FILE_RANDOM_ACCESS",
            "FILE_DELETE_ON_CLOSE",
            "FILE_OPEN_REPARSE_POINT",
            # IO_STATUS_BLOCK.Information values for create/open
            "FILE_SUPERSEDED",
            "FILE_OPENED",
            "FILE_CREATED",
            "FILE_OVERWRITTEN",
            "FILE_EXISTS",
            "FILE_DOES_NOT_EXIST",
            # create dispositions
            "FILE_SUPERSEDE",
            "FILE_OPEN",
            "FILE_CREATE",
            "FILE_OPEN_IF",
            "FILE_OVERWRITE",
            "FILE_OVERWRITE_IF",
            "FILE_MAXIMUM_DISPOSITION",
        ],
    )

    winioctl = (wine / "include/winioctl.h").read_text()

    # M7: NtQueryVolumeInformationFile (RtlSetCurrentDirectory_U issues it
    # during ntdll startup — dlls/ntdll/env.c).
    fs_info_class = extract_enum(winternl, "_FSINFOCLASS", "FS_INFORMATION_CLASS")
    device_type_alias = extract_defines(winioctl, "winioctl.h", ["DEVICE_TYPE"])
    fs_structs = "\n\n".join(
        extract_struct(winioctl, tag, typedef)
        for tag, typedef in [
            ("_FILE_FS_VOLUME_INFORMATION", "FILE_FS_VOLUME_INFORMATION"),
            ("_FILE_FS_SIZE_INFORMATION", "FILE_FS_SIZE_INFORMATION"),
            ("_FILE_FS_DEVICE_INFORMATION", "FILE_FS_DEVICE_INFORMATION"),
            ("_FILE_FS_ATTRIBUTE_INFORMATION", "FILE_FS_ATTRIBUTE_INFORMATION"),
        ]
    )
    device_types = extract_defines(
        winioctl,
        "winioctl.h",
        [
            "FILE_DEVICE_DISK",
            "FILE_DEVICE_DISK_FILE_SYSTEM",
            "FILE_DEVICE_FILE_SYSTEM",
            "FILE_DEVICE_SERIAL_PORT",
        ],
    )

    # M9: ioctl/fsctl plumbing + the named-pipe surface. CTL_CODE and the
    # FSCTL_PIPE_* verbs come from winioctl.h; the pipe create/mode constants
    # and info structs from winternl.h ("options for NtCreateNamedPipeFile").
    ioctl_defines = extract_defines(
        winioctl,
        "winioctl.h",
        [
            "CTL_CODE( DeviceType, Function, Method, Access )",
            "METHOD_BUFFERED",
            "METHOD_IN_DIRECT",
            "METHOD_OUT_DIRECT",
            "METHOD_NEITHER",
            "FILE_ANY_ACCESS",
            "FILE_READ_ACCESS",
            "FILE_WRITE_ACCESS",
            "FILE_DEVICE_NAMED_PIPE",
            "FILE_DEVICE_CONSOLE",
            "FSCTL_PIPE_DISCONNECT",
            "FSCTL_PIPE_LISTEN",
            "FSCTL_PIPE_PEEK",
            "FSCTL_PIPE_TRANSCEIVE",
            "FSCTL_PIPE_WAIT",
        ],
    )
    # M10: completion-port surface (ntdll threadpool / CreateIoCompletionPort).
    completion_defines = extract_defines(
        winternl,
        "winternl.h",
        [
            "IO_COMPLETION_QUERY_STATE",
            "IO_COMPLETION_MODIFY_STATE",
            "IO_COMPLETION_ALL_ACCESS",
        ],
    )
    completion_enum = extract_enum(
        winternl, "_IO_COMPLETION_INFORMATION_CLASS", "IO_COMPLETION_INFORMATION_CLASS"
    )
    completion_struct = extract_struct(
        winternl, "_FILE_IO_COMPLETION_INFORMATION", "FILE_IO_COMPLETION_INFORMATION"
    )

    pipe_defines = extract_defines(
        winternl,
        "winternl.h",
        [
            "FILE_PIPE_DISCONNECTED_STATE",
            "FILE_PIPE_LISTENING_STATE",
            "FILE_PIPE_CONNECTED_STATE",
            "FILE_PIPE_CLOSING_STATE",
            "FILE_PIPE_INBOUND",
            "FILE_PIPE_OUTBOUND",
            "FILE_PIPE_FULL_DUPLEX",
            "FILE_PIPE_TYPE_MESSAGE",
            "FILE_PIPE_TYPE_BYTE",
            "FILE_PIPE_MESSAGE_MODE",
            "FILE_PIPE_BYTE_STREAM_MODE",
            "FILE_PIPE_COMPLETE_OPERATION",
            "FILE_PIPE_QUEUE_OPERATION",
            "FILE_PIPE_SERVER_END",
            "FILE_PIPE_CLIENT_END",
        ],
    )
    pipe_structs = "\n\n".join(
        [
            extract_struct(winternl, "_FILE_PIPE_INFORMATION", "FILE_PIPE_INFORMATION"),
            extract_struct(
                winternl, "_FILE_PIPE_LOCAL_INFORMATION", "FILE_PIPE_LOCAL_INFORMATION"
            ),
            extract_struct(winioctl, "_FILE_PIPE_WAIT_FOR_BUFFER", "FILE_PIPE_WAIT_FOR_BUFFER"),
            extract_struct(winioctl, "_FILE_PIPE_PEEK_BUFFER", "FILE_PIPE_PEEK_BUFFER"),
        ]
    )

    iosb = extract_struct(winternl, "_IO_STATUS_BLOCK", "IO_STATUS_BLOCK")
    apc_routine = extract_typedef_line(winternl, "winternl.h", "PIO_APC_ROUTINE")
    info_class = extract_enum(
        winternl, "_FILE_INFORMATION_CLASS", "FILE_INFORMATION_CLASS"
    )
    structs = "\n\n".join(
        extract_struct(winternl, tag, typedef)
        for tag, typedef in [
            ("_FILE_DIRECTORY_INFORMATION", "FILE_DIRECTORY_INFORMATION"),
            ("_FILE_FULL_DIRECTORY_INFORMATION", "FILE_FULL_DIRECTORY_INFORMATION"),
            ("_FILE_BOTH_DIRECTORY_INFORMATION", "FILE_BOTH_DIRECTORY_INFORMATION"),
            ("_FILE_BASIC_INFORMATION", "FILE_BASIC_INFORMATION"),
            ("_FILE_STANDARD_INFORMATION", "FILE_STANDARD_INFORMATION"),
            ("_FILE_INTERNAL_INFORMATION", "FILE_INTERNAL_INFORMATION"),
            ("_FILE_EA_INFORMATION", "FILE_EA_INFORMATION"),
            ("_FILE_ACCESS_INFORMATION", "FILE_ACCESS_INFORMATION"),
            ("_FILE_NAME_INFORMATION", "FILE_NAME_INFORMATION"),
            ("_FILE_NAMES_INFORMATION", "FILE_NAMES_INFORMATION"),
            ("_FILE_DISPOSITION_INFORMATION", "FILE_DISPOSITION_INFORMATION"),
            ("_FILE_POSITION_INFORMATION", "FILE_POSITION_INFORMATION"),
            ("_FILE_MODE_INFORMATION", "FILE_MODE_INFORMATION"),
            ("_FILE_ALIGNMENT_INFORMATION", "FILE_ALIGNMENT_INFORMATION"),
            ("_FILE_ALLOCATION_INFORMATION", "FILE_ALLOCATION_INFORMATION"),
            ("_FILE_END_OF_FILE_INFORMATION", "FILE_END_OF_FILE_INFORMATION"),
            ("_FILE_NETWORK_OPEN_INFORMATION", "FILE_NETWORK_OPEN_INFORMATION"),
            ("_FILE_ATTRIBUTE_TAG_INFORMATION", "FILE_ATTRIBUTE_TAG_INFORMATION"),
            ("_FILE_ALL_INFORMATION", "FILE_ALL_INFORMATION"),
        ]
    )
    prototypes = extract_prototypes(winternl, NTIOAPI_FUNCTIONS)

    asserts = """\
#include <stddef.h>
_Static_assert(sizeof(IO_STATUS_BLOCK) == 16, "IO_STATUS_BLOCK x64 layout");
_Static_assert(offsetof(IO_STATUS_BLOCK, Information) == 8, "IO_STATUS_BLOCK x64 layout");
_Static_assert(sizeof(FILE_BASIC_INFORMATION) == 40, "FILE_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_BASIC_INFORMATION, FileAttributes) == 32, "FILE_BASIC_INFORMATION x64 layout");
_Static_assert(sizeof(FILE_STANDARD_INFORMATION) == 24, "FILE_STANDARD_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_STANDARD_INFORMATION, DeletePending) == 20, "FILE_STANDARD_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_DIRECTORY_INFORMATION, FileName) == 64, "FILE_DIRECTORY_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_FULL_DIRECTORY_INFORMATION, FileName) == 68, "FILE_FULL_DIRECTORY_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_BOTH_DIRECTORY_INFORMATION, ShortName) == 70, "FILE_BOTH_DIRECTORY_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_BOTH_DIRECTORY_INFORMATION, FileName) == 94, "FILE_BOTH_DIRECTORY_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_NAMES_INFORMATION, FileName) == 12, "FILE_NAMES_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_ALL_INFORMATION, NameInformation) == 96, "FILE_ALL_INFORMATION x64 layout");
_Static_assert(sizeof(FILE_PIPE_INFORMATION) == 8, "FILE_PIPE_INFORMATION x64 layout");
_Static_assert(sizeof(FILE_PIPE_LOCAL_INFORMATION) == 40, "FILE_PIPE_LOCAL_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_PIPE_LOCAL_INFORMATION, NamedPipeState) == 32, "FILE_PIPE_LOCAL_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_PIPE_PEEK_BUFFER, Data) == 16, "FILE_PIPE_PEEK_BUFFER x64 layout");
_Static_assert(offsetof(FILE_PIPE_WAIT_FOR_BUFFER, Name) == 14, "FILE_PIPE_WAIT_FOR_BUFFER x64 layout");
"""

    return (
        BANNER.format(
            name="abi/ntioapi.h", source="wine/include/{winnt.h,winternl.h}"
        )
        + "#ifndef PROSKRNL_ABI_NTIOAPI_H\n"
        + "#define PROSKRNL_ABI_NTIOAPI_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + "/* File access rights, share modes, and attributes, extracted from\n"
        + " * wine/include/winnt.h. */\n"
        + access_rights
        + "\n\n/* Create options/dispositions and IOSB Information values, extracted\n"
        + " * from wine/include/winternl.h. */\n"
        + create_flags
        + "\n\n/* The async-completion protocol shapes (docs/03: IOSB timing is a kept\n"
        + " * contract), extracted verbatim from wine/include/winternl.h. */\n"
        + iosb
        + "\n\n"
        + apc_routine
        + "\n\n/* Extracted verbatim from wine/include/winternl.h. */\n"
        + info_class
        + "\n\n"
        + structs
        + "\n\n/* Volume information (M7: RtlSetCurrentDirectory_U queries it at\n"
        + " * ntdll startup); enum from wine/include/winternl.h, structs and\n"
        + " * device types from wine/include/winioctl.h. */\n"
        + fs_info_class
        + "\n\n"
        + device_type_alias
        + "\n\n"
        + fs_structs
        + "\n\n"
        + device_types
        + "\n\n/* Ioctl/fsctl encoding + the named-pipe FSCTL verbs (M9), extracted\n"
        + " * from wine/include/winioctl.h. */\n"
        + ioctl_defines
        + "\n\n/* NtCreateNamedPipeFile options + pipe info shapes (M9), extracted\n"
        + " * from wine/include/{winternl.h,winioctl.h}. */\n"
        + pipe_defines
        + "\n\n"
        + pipe_structs
        + "\n\n"
        + completion_defines
        + "\n\n"
        + completion_enum
        + "\n\n"
        + completion_struct
        + "\n\n"
        + asserts
        + "\n/* The M6+M7 Io Nt* surface; signatures extracted verbatim from\n"
        + " * wine/include/winternl.h (linkage macros dropped). */\n"
        + prototypes
        + "\n\n#endif /* PROSKRNL_ABI_NTIOAPI_H */\n"
    )


# The M9 ConDrv contract (docs/02): the IOCTL_CONDRV_* surface Wine's
# kernelbase console client issues via NtDeviceIoControlFile, and the
# structures those ioctls exchange — wine/include/wine/condrv.h is the
# authoritative source (conhost and kernelbase both compile against it, so
# it IS the observable boundary). COORD/SMALL_RECT come from wincontypes.h,
# the CONSOLE_HANDLE_* sentinels' LongToHandle from basetsd.h.
def gen_ntcondrv(wine: Path) -> str:
    condrv = (wine / "include/wine/condrv.h").read_text()
    wincontypes = (wine / "include/wincontypes.h").read_text()
    basetsd = (wine / "include/basetsd.h").read_text()

    ioctls = extract_defines(
        condrv,
        "wine/condrv.h",
        [
            "IOCTL_CONDRV_GET_MODE",
            "IOCTL_CONDRV_SET_MODE",
            "IOCTL_CONDRV_IS_UNIX",
            "IOCTL_CONDRV_READ_CONSOLE",
            "IOCTL_CONDRV_READ_FILE",
            "IOCTL_CONDRV_READ_INPUT",
            "IOCTL_CONDRV_WRITE_INPUT",
            "IOCTL_CONDRV_PEEK",
            "IOCTL_CONDRV_GET_INPUT_INFO",
            "IOCTL_CONDRV_SET_INPUT_INFO",
            "IOCTL_CONDRV_GET_TITLE",
            "IOCTL_CONDRV_SET_TITLE",
            "IOCTL_CONDRV_CTRL_EVENT",
            "IOCTL_CONDRV_BEEP",
            "IOCTL_CONDRV_FLUSH",
            "IOCTL_CONDRV_GET_WINDOW",
            "IOCTL_CONDRV_GET_PROCESS_LIST",
            "IOCTL_CONDRV_READ_CONSOLE_CONTROL",
            "IOCTL_CONDRV_GET_INPUT_COUNT",
            "IOCTL_CONDRV_WRITE_CONSOLE",
            "IOCTL_CONDRV_WRITE_FILE",
            "IOCTL_CONDRV_READ_OUTPUT",
            "IOCTL_CONDRV_WRITE_OUTPUT",
            "IOCTL_CONDRV_GET_OUTPUT_INFO",
            "IOCTL_CONDRV_SET_OUTPUT_INFO",
            "IOCTL_CONDRV_ACTIVATE",
            "IOCTL_CONDRV_FILL_OUTPUT",
            "IOCTL_CONDRV_SCROLL",
            "IOCTL_CONDRV_BIND_PID",
            "IOCTL_CONDRV_SETUP_INPUT",
            "IOCTL_CONDRV_INIT_OUTPUT",
            "IOCTL_CONDRV_CLOSE_OUTPUT",
        ],
    )
    masks = extract_defines(
        condrv,
        "wine/condrv.h",
        [
            "SET_CONSOLE_INPUT_INFO_INPUT_CODEPAGE",
            "SET_CONSOLE_INPUT_INFO_OUTPUT_CODEPAGE",
            "SET_CONSOLE_OUTPUT_INFO_CURSOR_GEOM",
            "SET_CONSOLE_OUTPUT_INFO_CURSOR_POS",
            "SET_CONSOLE_OUTPUT_INFO_SIZE",
            "SET_CONSOLE_OUTPUT_INFO_ATTR",
            "SET_CONSOLE_OUTPUT_INFO_DISPLAY_WINDOW",
            "SET_CONSOLE_OUTPUT_INFO_MAX_SIZE",
            "SET_CONSOLE_OUTPUT_INFO_POPUP_ATTR",
            "SET_CONSOLE_OUTPUT_INFO_FONT",
        ],
    )
    sentinels = extract_defines(basetsd, "basetsd.h", ["LongToHandle(l)"]) + "\n" + extract_defines(
        condrv,
        "wine/condrv.h",
        [
            "CONSOLE_HANDLE_ALLOC",
            "CONSOLE_HANDLE_ALLOC_NO_WINDOW",
            "CONSOLE_HANDLE_SHELL",
            "CONSOLE_HANDLE_SHELL_NO_WINDOW",
        ],
    )

    handle_typedef = extract_typedef_line(condrv, "wine/condrv.h", "condrv_handle_t")
    char_info = extract_anonymous_struct(condrv, "char_info_t")
    coord_structs = "\n\n".join(
        [
            extract_struct(wincontypes, "tagCOORD", "COORD"),
            extract_struct(wincontypes, "tagSMALL_RECT", "SMALL_RECT"),
        ]
    )
    structs = "\n\n".join(
        [
            extract_plain_struct(condrv, "condrv_input_info"),
            extract_plain_struct(condrv, "condrv_input_info_params"),
            extract_plain_struct(condrv, "condrv_output_params"),
            extract_plain_enum(condrv, "char_info_mode"),
            extract_plain_struct(condrv, "condrv_output_info"),
            extract_plain_struct(condrv, "condrv_output_info_params"),
            extract_plain_struct(condrv, "condrv_title_params"),
            extract_plain_struct(condrv, "condrv_fill_output_params"),
            extract_plain_struct(condrv, "condrv_scroll_params"),
            extract_plain_struct(condrv, "condrv_ctrl_event"),
        ]
    )

    scaffold = """\
/* Win32 alias scaffold for the extracted structs/macros; sizes pinned. */
typedef short SHORT;
typedef LONGLONG LONG_PTR;
_Static_assert(sizeof(SHORT) == 2, "Win32: SHORT is 2 bytes");
_Static_assert(sizeof(LONG_PTR) == 8, "x86_64: LONG_PTR is pointer-sized");
"""

    asserts = """\
#include <stddef.h>
_Static_assert(sizeof(char_info_t) == 4, "char_info_t layout");
_Static_assert(sizeof(struct condrv_input_info) == 8, "condrv_input_info layout");
_Static_assert(sizeof(struct condrv_output_info) == 100, "condrv_output_info layout");
_Static_assert(offsetof(struct condrv_output_params, width) == 12, "condrv_output_params layout");
_Static_assert(offsetof(struct condrv_ctrl_event, group_id) == 4, "condrv_ctrl_event layout");
"""

    return (
        BANNER.format(
            name="abi/ntcondrv.h",
            source="wine/include/{wine/condrv.h,wincontypes.h,basetsd.h}",
        )
        + "#ifndef PROSKRNL_ABI_NTCONDRV_H\n"
        + "#define PROSKRNL_ABI_NTCONDRV_H\n\n"
        + '#include "abi/ntdef.h"\n'
        + '#include "abi/ntioapi.h" /* CTL_CODE, FILE_DEVICE_CONSOLE */\n\n'
        + scaffold
        + "\n/* Extracted verbatim from wine/include/wincontypes.h. */\n"
        + coord_structs
        + "\n\n/* The ConDrv ioctl surface, extracted from wine/include/wine/condrv.h. */\n"
        + ioctls
        + "\n\n"
        + handle_typedef
        + "\n\n/* The ioctl parameter/result shapes, extracted verbatim from\n"
        + " * wine/include/wine/condrv.h. */\n"
        + char_info
        + "\n\n"
        + structs
        + "\n\n"
        + masks
        + "\n\n/* Console-inheritance sentinels (RTL_USER_PROCESS_PARAMETERS.ConsoleHandle);\n"
        + " * LongToHandle from wine/include/basetsd.h. */\n"
        + sentinels
        + "\n\n"
        + asserts
        + "\n#endif /* PROSKRNL_ABI_NTCONDRV_H */\n"
    )


# The M7 user-visible structures (docs/00: PEB/TEB/RTL_USER_PROCESS_PARAMETERS
# byte-for-byte — Wine's DLLs read the fields directly). Extracted verbatim
# from wine/include/winternl.h; every member with an x64 offset comment in the
# Wine header is pinned by a generated static_assert.
def gen_ntpebteb(wine: Path) -> str:
    winternl = (wine / "include/winternl.h").read_text()
    guiddef = (wine / "include/guiddef.h").read_text()

    guid = extract_struct(guiddef, "_GUID", "GUID")
    small_structs = "\n\n".join(
        [
            extract_struct(winternl, "_CURDIR", "CURDIR"),
            extract_struct(winternl, "RTL_DRIVE_LETTER_CURDIR", "RTL_DRIVE_LETTER_CURDIR"),
            extract_struct(winternl, "tagRTL_BITMAP", "RTL_BITMAP"),
            extract_struct(winternl, "_PEB_LDR_DATA", "PEB_LDR_DATA"),
            extract_struct(winternl, "_GDI_TEB_BATCH", "GDI_TEB_BATCH"),
            extract_struct(
                winternl,
                "_RTL_ACTIVATION_CONTEXT_STACK_FRAME",
                "RTL_ACTIVATION_CONTEXT_STACK_FRAME",
            ),
            extract_struct(winternl, "_ACTIVATION_CONTEXT_STACK", "ACTIVATION_CONTEXT_STACK"),
        ]
    )
    params = extract_struct(
        winternl, "_RTL_USER_PROCESS_PARAMETERS", "RTL_USER_PROCESS_PARAMETERS", keep_tag=True
    )
    peb = extract_struct(winternl, "_PEB", "PEB", keep_tag=True)
    teb = extract_struct(winternl, "_TEB", "TEB", keep_tag=True)
    callback_proc = extract_typedef_line(winternl, "winternl.h", "KERNEL_CALLBACK_PROC")

    scaffold = """\
/* x86_64 only (ADR 0006): the extracted PEB/TEB carry #ifdef _WIN64 blocks
 * verbatim; this build is always the 64-bit layout. */
#ifndef _WIN64
#define _WIN64 1
#endif

/* Win32 alias/opaque scaffold for extracted-struct member types. Only the
 * pointer identity matters for layout; the pointees are not part of the M7
 * boundary (nothing dereferences them across it). */
typedef PVOID HMODULE;
typedef ULONG_PTR KAFFINITY;
typedef struct _RTL_CRITICAL_SECTION *PRTL_CRITICAL_SECTION;
typedef struct _ACTIVATION_CONTEXT ACTIVATION_CONTEXT;
typedef struct _TEB_ACTIVE_FRAME TEB_ACTIVE_FRAME;
typedef struct _TEB_FLS_DATA TEB_FLS_DATA;
typedef struct _CHPEV2_PROCESS_INFO CHPEV2_PROCESS_INFO;
typedef struct _CHPE_V2_CPU_AREA_INFO CHPE_V2_CPU_AREA_INFO;
"""

    return (
        BANNER.format(
            name="abi/ntpebteb.h", source="wine/include/{winternl.h,guiddef.h}"
        )
        + "#ifndef PROSKRNL_ABI_NTPEBTEB_H\n"
        + "#define PROSKRNL_ABI_NTPEBTEB_H\n\n"
        + '#include "abi/ntdef.h"\n'
        + '#include "abi/ntpsapi.h" /* NT_TIB, CLIENT_ID */\n\n'
        + scaffold
        + "\n/* Extracted verbatim from wine/include/guiddef.h. */\n"
        + guid
        + "\n\n/* Extracted verbatim from wine/include/winternl.h. */\n"
        + callback_proc
        + "\n\n"
        + small_structs
        + "\n\n"
        + params
        + "\n\n"
        + peb
        + "\n\n"
        + teb
        + "\n\n#include <stddef.h>\n"
        + "/* Layout pins, generated from the offset comments in the SAME Wine\n"
        + " * header the structs were extracted from (Art. 4). */\n"
        + gen_offset_asserts(peb, "PEB")
        + "\n"
        + gen_offset_asserts(teb, "TEB")
        + "\n\n#endif /* PROSKRNL_ABI_NTPEBTEB_H */\n"
    )


# The M7 exception/context machinery (docs/02: KiUserExceptionDispatcher
# return protocol; docs/05 Ps "usermode.c"): the x64 CONTEXT and
# EXCEPTION_RECORD as Wine's winnt.h defines them.
def gen_ntcontext(wine: Path) -> str:
    winnt = (wine / "include/winnt.h").read_text()

    flags = extract_defines(
        winnt,
        "winnt.h",
        [
            "CONTEXT_AMD64",
            "CONTEXT_AMD64_CONTROL",
            "CONTEXT_AMD64_INTEGER",
            "CONTEXT_AMD64_SEGMENTS",
            "CONTEXT_AMD64_FLOATING_POINT",
            "CONTEXT_AMD64_DEBUG_REGISTERS",
            "CONTEXT_AMD64_FULL",
            "CONTEXT_AMD64_ALL",
            "EXCEPTION_MAXIMUM_PARAMETERS",
            "EXCEPTION_NONCONTINUABLE",
            "EXCEPTION_UNWINDING",
            "EXCEPTION_EXIT_UNWIND",
            "EXCEPTION_STACK_INVALID",
            "EXCEPTION_NESTED_CALL",
            "EXCEPTION_TARGET_UNWIND",
            "EXCEPTION_COLLIDED_UNWIND",
            "UNWIND_HISTORY_TABLE_SIZE",
        ],
    )

    m128a = extract_struct(winnt, r"DECLSPEC_ALIGN\(16\) _M128A", "M128A")
    xsave = extract_struct(winnt, "_XSAVE_FORMAT", "XSAVE_FORMAT")
    context = extract_struct(winnt, r"DECLSPEC_ALIGN\(16\) _AMD64_CONTEXT", "AMD64_CONTEXT")
    exception_record = extract_struct(winnt, "_EXCEPTION_RECORD", "EXCEPTION_RECORD")
    exception_pointers = extract_struct(winnt, "_EXCEPTION_POINTERS", "EXCEPTION_POINTERS")
    runtime_function = extract_struct(
        winnt, "IMAGE_AMD64_RUNTIME_FUNCTION_ENTRY", "IMAGE_AMD64_RUNTIME_FUNCTION_ENTRY"
    )

    scaffold = """\
#define DECLSPEC_ALIGN(x) __attribute__((aligned(x)))
typedef ULONGLONG DWORD64, *PDWORD64;
typedef ULONGLONG ULONG64;
typedef int BOOL;
"""

    asserts = """\
#include <stddef.h>
_Static_assert(sizeof(CONTEXT) == 0x4d0, "AMD64 CONTEXT size (last member 0x4c8 + 8, aligned 16 — Wine offset comments)");
_Static_assert(sizeof(EXCEPTION_RECORD) == 0x98, "EXCEPTION_RECORD x64 layout");
_Static_assert(offsetof(EXCEPTION_RECORD, ExceptionAddress) == 0x10, "EXCEPTION_RECORD x64 layout");
_Static_assert(offsetof(EXCEPTION_RECORD, ExceptionInformation) == 0x20, "EXCEPTION_RECORD x64 layout");
"""

    return (
        BANNER.format(name="abi/ntcontext.h", source="wine/include/winnt.h")
        + "#ifndef PROSKRNL_ABI_NTCONTEXT_H\n"
        + "#define PROSKRNL_ABI_NTCONTEXT_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + scaffold
        + "\n/* Extracted from wine/include/winnt.h. */\n"
        + flags
        + "\n\n"
        + m128a
        + "\n\n"
        + xsave
        + "\n\ntypedef XSAVE_FORMAT XMM_SAVE_AREA32, *PXMM_SAVE_AREA32;\n\n"
        + runtime_function
        + "\ntypedef IMAGE_AMD64_RUNTIME_FUNCTION_ENTRY RUNTIME_FUNCTION, *PRUNTIME_FUNCTION;\n\n"
        + context
        + "\n\n/* x86_64 only (ADR 0006): AMD64_CONTEXT IS the CONTEXT, as Wine's\n"
        + " * winnt.h typedefs under __x86_64__. */\n"
        + "typedef AMD64_CONTEXT CONTEXT, *PCONTEXT;\n"
        + "#define CONTEXT_CONTROL CONTEXT_AMD64_CONTROL\n"
        + "#define CONTEXT_INTEGER CONTEXT_AMD64_INTEGER\n"
        + "#define CONTEXT_SEGMENTS CONTEXT_AMD64_SEGMENTS\n"
        + "#define CONTEXT_FLOATING_POINT CONTEXT_AMD64_FLOATING_POINT\n"
        + "#define CONTEXT_DEBUG_REGISTERS CONTEXT_AMD64_DEBUG_REGISTERS\n"
        + "#define CONTEXT_FULL CONTEXT_AMD64_FULL\n"
        + "#define CONTEXT_ALL CONTEXT_AMD64_ALL\n\n"
        + exception_record
        + "\n\n"
        + exception_pointers
        + "\n\n"
        + asserts
        + "\n/* Layout pins, generated from the offset comments in the SAME Wine\n"
        + " * header the struct was extracted from (Art. 4). */\n"
        + gen_offset_asserts(context, "CONTEXT")
        + "\n\n#endif /* PROSKRNL_ABI_NTCONTEXT_H */\n"
    )


# KUSER_SHARED_DATA (docs/00: byte-for-byte — read directly by Wine's PE
# DLLs and by the ntdll syscall thunks at fixed user address 0x7ffe0000).
def gen_ntkeapi(wine: Path) -> str:
    wdm = (wine / "include/ddk/wdm.h").read_text()
    winnt = (wine / "include/winnt.h").read_text()

    defines = extract_defines(wdm, "ddk/wdm.h", ["PROCESSOR_FEATURE_MAX"]) + "\n" + extract_defines(
        winnt, "winnt.h", ["MAXIMUM_XSTATE_FEATURES"]
    )
    enums = "\n\n".join(
        [
            extract_enum(wdm, "_NT_PRODUCT_TYPE", "NT_PRODUCT_TYPE"),
            extract_enum(wdm, "_ALTERNATIVE_ARCHITECTURE_TYPE", "ALTERNATIVE_ARCHITECTURE_TYPE"),
        ]
    )
    ksystem_time = extract_struct(wdm, "_KSYSTEM_TIME", "KSYSTEM_TIME")
    xstate_feature = extract_struct(winnt, "_XSTATE_FEATURE", "XSTATE_FEATURE")
    xstate_config = extract_struct(winnt, "_XSTATE_CONFIGURATION", "XSTATE_CONFIGURATION")
    kusd = extract_struct(wdm, "_KUSER_SHARED_DATA", "KUSER_SHARED_DATA")

    scaffold = """\
typedef ULONGLONG ULONG64;
typedef ULONGLONG DWORD64;
"""

    asserts = """\
#include <stddef.h>
_Static_assert(sizeof(KUSER_SHARED_DATA) == 0x738, "KUSER_SHARED_DATA size (C_ASSERT in wine/include/ddk/wdm.h)");
"""

    return (
        BANNER.format(
            name="abi/ntkeapi.h", source="wine/include/{ddk/wdm.h,winnt.h}"
        )
        + "#ifndef PROSKRNL_ABI_NTKEAPI_H\n"
        + "#define PROSKRNL_ABI_NTKEAPI_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + scaffold
        + "\n/* Extracted from wine/include/ddk/wdm.h. */\n"
        + defines
        + "\n\n"
        + enums
        + "\n\n"
        + ksystem_time
        + "\n\n/* Extracted verbatim from wine/include/winnt.h (embedded in\n"
        + " * KUSER_SHARED_DATA.XState). */\n"
        + xstate_feature
        + "\n\n"
        + xstate_config
        + "\n\n"
        + kusd
        + "\n\n"
        + asserts
        + "\n/* Layout pins, generated from the offset comments in the SAME Wine\n"
        + " * header the struct was extracted from (Art. 4). */\n"
        + gen_offset_asserts(kusd, "KUSER_SHARED_DATA")
        + "\n\n#endif /* PROSKRNL_ABI_NTKEAPI_H */\n"
    )


# The M4 Ps surface (process termination, NtDisplayString) + the M7 surface:
# thread/process creation, the user dispatcher return protocol, queries.
NTPSAPI_FUNCTIONS = [
    "NtTerminateProcess",
    "NtDisplayString",
    "NtCreateUserProcess",
    "NtCreateThreadEx",
    "NtOpenThread",
    "NtResumeThread",
    "NtSuspendThread",
    "NtTerminateThread",
    "NtAlertThread",
    "NtTestAlert",
    "NtYieldExecution",
    "NtDelayExecution",
    "NtQueueApcThread",
    "NtContinue",
    "NtRaiseException",
    "NtQueryInformationProcess",
    "NtSetInformationProcess",
    "NtQueryInformationThread",
    "NtSetInformationThread",
    "NtQueryPerformanceCounter",
    "NtQueryTimerResolution",
    "NtSetTimerResolution",
    "NtConvertBetweenAuxiliaryCounterAndPerformanceCounter",
    "NtQuerySystemInformation",
    "NtQueryDefaultLocale",
    "NtGetContextThread",
    "NtSetContextThread",
    "NtContinueEx",
    "NtCallbackReturn",
    "NtWaitForAlertByThreadId",
    "NtAlertThreadByThreadId",
    "NtInitializeNlsFiles",
    "NtGetNlsSectionPtr",
    "NtQuerySystemTime",
]


def gen_ntpsapi(wine: Path) -> str:
    winnt = (wine / "include/winnt.h").read_text()
    winternl = (wine / "include/winternl.h").read_text()

    process_rights = extract_defines(
        winnt,
        "winnt.h",
        [
            "PROCESS_TERMINATE",
            "PROCESS_CREATE_THREAD",
            "PROCESS_VM_OPERATION",
            "PROCESS_VM_READ",
            "PROCESS_VM_WRITE",
            "PROCESS_QUERY_INFORMATION",
            "PROCESS_SET_INFORMATION",
            "PROCESS_SUSPEND_RESUME",
            "PROCESS_QUERY_LIMITED_INFORMATION",
            "PROCESS_ALL_ACCESS",
            # M7: thread access rights (winnt.h)
            "THREAD_TERMINATE",
            "THREAD_SUSPEND_RESUME",
            "THREAD_GET_CONTEXT",
            "THREAD_SET_CONTEXT",
            "THREAD_SET_INFORMATION",
            "THREAD_QUERY_INFORMATION",
            "THREAD_SET_THREAD_TOKEN",
            "THREAD_IMPERSONATE",
            "THREAD_DIRECT_IMPERSONATION",
            "THREAD_SET_LIMITED_INFORMATION",
            "THREAD_QUERY_LIMITED_INFORMATION",
            "THREAD_ALL_ACCESS",
        ],
    )

    nt_tib = extract_struct(winnt, "_NT_TIB", "NT_TIB")
    client_id = extract_struct(winternl, "_CLIENT_ID", "CLIENT_ID")
    prototypes = extract_prototypes(winternl, NTPSAPI_FUNCTIONS)

    # M7: the info-class enums + basic-information shapes ntdll queries at
    # startup, the NtCreateUserProcess attribute machinery, and the user-APC
    # / thread-entry function-pointer types.
    info_enums = "\n\n".join(
        extract_enum(winternl, tag, typedef)
        for tag, typedef in [
            ("_PROCESSINFOCLASS", "PROCESSINFOCLASS"),
            ("_THREADINFOCLASS", "THREADINFOCLASS"),
            ("_SYSTEM_INFORMATION_CLASS", "SYSTEM_INFORMATION_CLASS"),
            ("_PS_CREATE_STATE", "PS_CREATE_STATE"),
            ("_PS_ATTRIBUTE_NUM", "PS_ATTRIBUTE_NUM"),
        ]
    )
    # PROCESS_BASIC_INFORMATION carries an #ifdef __WINESRC__ with the real
    # NT field names; resolve it keeping that branch (same layout, named).
    pbi = resolve_ifdef(
        extract_struct(winternl, "_PROCESS_BASIC_INFORMATION", "PROCESS_BASIC_INFORMATION"),
        "__WINESRC__",
        True,
    )
    info_structs = "\n\n".join(
        [
            extract_struct(winternl, "_THREAD_BASIC_INFORMATION", "THREAD_BASIC_INFORMATION"),
            pbi,
            resolve_ifdef(
                extract_struct(winternl, "_SYSTEM_BASIC_INFORMATION", "SYSTEM_BASIC_INFORMATION"),
                "__WINESRC__",
                True,
            ),
            resolve_ifdef(
                extract_struct(winternl, "_SYSTEM_CPU_INFORMATION", "SYSTEM_CPU_INFORMATION"),
                "__WINESRC__",
                True,
            ),
            resolve_ifdef(
                extract_struct(
                    winternl, "_SYSTEM_TIMEOFDAY_INFORMATION", "SYSTEM_TIMEOFDAY_INFORMATION"
                ),
                "__WINESRC__",
                True,
            ),
            extract_struct(
                winternl, "_SYSTEM_PERFORMANCE_INFORMATION", "SYSTEM_PERFORMANCE_INFORMATION"
            ),
            extract_struct(winternl, "_RTL_SYSTEM_TIME", "RTL_SYSTEM_TIME"),
            extract_struct(winternl, "_RTL_TIME_ZONE_INFORMATION", "RTL_TIME_ZONE_INFORMATION"),
            extract_struct(
                winternl, "_RTL_TIME_DYNAMIC_ZONE_INFORMATION", "RTL_DYNAMIC_TIME_ZONE_INFORMATION"
            ),
            extract_struct(winternl, "_VM_COUNTERS", "VM_COUNTERS"),
            extract_struct(winternl, "_VM_COUNTERS_EX", "VM_COUNTERS_EX"),
            extract_struct(winternl, "_PS_ATTRIBUTE", "PS_ATTRIBUTE"),
            extract_struct(winternl, "_PS_ATTRIBUTE_LIST", "PS_ATTRIBUTE_LIST"),
            extract_struct(winternl, "_PS_CREATE_INFO", "PS_CREATE_INFO"),
        ]
    )
    ps_attribute_defines = extract_defines(
        winternl,
        "winternl.h",
        [
            "PS_ATTRIBUTE_THREAD",
            "PS_ATTRIBUTE_INPUT",
            "PS_ATTRIBUTE_ADDITIVE",
            "PS_ATTRIBUTE_PARENT_PROCESS",
            "PS_ATTRIBUTE_DEBUG_PORT",
            "PS_ATTRIBUTE_TOKEN",
            "PS_ATTRIBUTE_CLIENT_ID",
            "PS_ATTRIBUTE_TEB_ADDRESS",
            "PS_ATTRIBUTE_IMAGE_NAME",
            "PS_ATTRIBUTE_IMAGE_INFO",
            "PS_ATTRIBUTE_MEMORY_RESERVE",
            "PS_ATTRIBUTE_PRIORITY_CLASS",
            "PS_ATTRIBUTE_ERROR_MODE",
            "PS_ATTRIBUTE_STD_HANDLE_INFO",
            "PS_ATTRIBUTE_HANDLE_LIST",
            "PS_ATTRIBUTE_MACHINE_TYPE",
            # NtCreateThreadEx flags
            "THREAD_CREATE_FLAGS_CREATE_SUSPENDED",
            "THREAD_CREATE_FLAGS_SKIP_THREAD_ATTACH",
            "THREAD_CREATE_FLAGS_HIDE_FROM_DEBUGGER",
            # NtCreateUserProcess process flags (M10)
            "PROCESS_CREATE_FLAGS_BREAKAWAY",
            "PROCESS_CREATE_FLAGS_NO_DEBUG_INHERIT",
            "PROCESS_CREATE_FLAGS_INHERIT_HANDLES",
            "PROCESS_CREATE_FLAGS_SUSPENDED",
            # RTL_USER_PROCESS_PARAMETERS.Flags
            "PROCESS_PARAMS_FLAG_NORMALIZED",
            "PROCESS_PARAMS_IMAGE_KEY_MISSING",
        ],
    )
    function_pointers = "\n".join(
        [
            extract_typedef_line(winternl, "winternl.h", "PNTAPCFUNC"),
            extract_typedef_line(winternl, "winternl.h", "PRTL_THREAD_START_ROUTINE"),
        ]
    )
    kcontinue = (
        extract_enum(winternl, "_KCONTINUE_TYPE", "KCONTINUE_TYPE")
        + "\n\n"
        + extract_struct(winternl, "_KCONTINUE_ARGUMENT", "KCONTINUE_ARGUMENT")
        + "\n"
        + extract_defines(winternl, "winternl.h",
                          ["KCONTINUE_FLAG_TEST_ALERT", "KCONTINUE_FLAG_DELIVER_APC"])
    )

    # M7 Wine bring-up: the NLS section types ntdll's locale_init passes to
    # NtGetNlsSectionPtr. Wine keeps them in dlls/ntdll/locale_private.h (a
    # plain enum, both sides of the boundary include it); extracted verbatim.
    locale_private = (wine / "dlls/ntdll/locale_private.h").read_text()
    match = re.search(r"enum nls_section_type\s*\{(.*?)\}\s*;", locale_private, re.S)
    if not match:
        sys.exit("gen_abi: enum nls_section_type not found in locale_private.h")
    nls_sections = ("/* NtGetNlsSectionPtr types, extracted verbatim from\n"
                    " * wine/dlls/ntdll/locale_private.h. */\n"
                    "typedef enum {" + match.group(1) + "} NLS_SECTION_TYPE;")

    # The normalization-form ids NtGetNlsSectionPtr's NLS_SECTION_NORMALIZE
    # takes (wine/dlls/ntdll/unix/env.c get_nls_file_path switches on them).
    winnls = (wine / "include/winnls.h").read_text()
    nls_sections += "\n\n" + extract_enum(winnls, "_NORM_FORM", "NORM_FORM")

    tib_asserts = """\
#include <stddef.h>
_Static_assert(sizeof(NT_TIB) == 56, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, StackBase) == 8, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, StackLimit) == 16, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, ArbitraryUserPointer) == 40, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, Self) == 48, "NT_TIB x64 layout");
"""

    return (
        BANNER.format(
            name="abi/ntpsapi.h", source="wine/include/{winnt.h,winternl.h}"
        )
        + "#ifndef PROSKRNL_ABI_NTPSAPI_H\n"
        + "#define PROSKRNL_ABI_NTPSAPI_H\n\n"
        + '#include "abi/ntdef.h"\n'
        + '#include "abi/ntcontext.h" /* CONTEXT/EXCEPTION_RECORD in prototypes */\n\n'
        + "/* Win32 alias scaffold used by extracted prototypes. */\n"
        + "typedef ULONG LCID, *PLCID;\n\n"
        + "/* The byte-exact bodies live in abi/ntpebteb.h (same tags); these\n"
        + " * forward typedefs let the structs/prototypes below reference them. */\n"
        + "typedef struct _PEB PEB, *PPEB;\n"
        + "typedef struct _TEB TEB, *PTEB;\n"
        + "typedef struct _RTL_USER_PROCESS_PARAMETERS RTL_USER_PROCESS_PARAMETERS,\n"
        + "    *PRTL_USER_PROCESS_PARAMETERS;\n\n"
        + "/* Process/thread access rights, extracted from wine/include/winnt.h. */\n"
        + process_rights
        + "\n\n/* The TEB begins with an NT_TIB. Extracted verbatim from\n"
        + " * wine/include/winnt.h; asserts pin the x64 layout. */\n"
        + "struct _EXCEPTION_REGISTRATION_RECORD;\n"
        + nt_tib
        + "\n\n"
        + tib_asserts
        + "\n/* Extracted verbatim from wine/include/winternl.h. */\n"
        + client_id
        + "\n\n/* M7: user-APC / thread-entry function-pointer types, extracted from\n"
        + " * wine/include/winternl.h. */\n"
        + function_pointers
        + "\n\n/* M7: info classes + creation attributes, extracted verbatim from\n"
        + " * wine/include/winternl.h. */\n"
        + kcontinue
        + "\n\n"
        + nls_sections
        + "\n\n"
        + info_enums
        + "\n\n"
        + ps_attribute_defines
        + "\n\n"
        + info_structs
        + "\n\n/* The M4+M7 Ps Nt* surface; signatures extracted verbatim from\n"
        + " * wine/include/winternl.h (linkage macros dropped). */\n"
        + prototypes
        + "\n\n#endif /* PROSKRNL_ABI_NTPSAPI_H */\n"
    )


# The Cm registry surface (M8; NtOpenKey/NtQueryValueKey were pinned in M7
# while the kernel side failed gracefully). The key/value info classes and
# struct shapes are what Wine's ntdll and the sem_reg suite exchange with the
# kernel.
NTREGAPI_FUNCTIONS = [
    "NtCreateKey",
    "NtOpenKey",
    "NtOpenKeyEx",
    "NtDeleteKey",
    "NtDeleteValueKey",
    "NtSetValueKey",
    "NtQueryValueKey",
    "NtEnumerateKey",
    "NtEnumerateValueKey",
    "NtQueryKey",
    "NtFlushKey",
]


def gen_ntregapi(wine: Path) -> str:
    winnt = (wine / "include/winnt.h").read_text()
    winternl = (wine / "include/winternl.h").read_text()

    key_rights = extract_defines(
        winnt,
        "winnt.h",
        [
            "KEY_QUERY_VALUE",
            "KEY_SET_VALUE",
            "KEY_CREATE_SUB_KEY",
            "KEY_ENUMERATE_SUB_KEYS",
            "KEY_NOTIFY",
            "KEY_CREATE_LINK",
            "KEY_WOW64_64KEY",
            "KEY_WOW64_32KEY",
            "KEY_WOW64_RES",
            "KEY_READ",
            "KEY_WRITE",
            "KEY_EXECUTE",
            "KEY_ALL_ACCESS",
            "REG_NONE",
            "REG_SZ",
            "REG_EXPAND_SZ",
            "REG_BINARY",
            "REG_DWORD",
            "REG_DWORD_LITTLE_ENDIAN",
            "REG_DWORD_BIG_ENDIAN",
            "REG_LINK",
            "REG_MULTI_SZ",
            "REG_QWORD",
            "REG_OPTION_NON_VOLATILE",
            "REG_OPTION_VOLATILE",
            "REG_OPTION_CREATE_LINK",
            "REG_CREATED_NEW_KEY",
            "REG_OPENED_EXISTING_KEY",
        ],
    )
    info_class = (
        extract_enum(winternl, "_KEY_INFORMATION_CLASS", "KEY_INFORMATION_CLASS")
        + "\n\n"
        + extract_enum(
            winternl, "_KEY_VALUE_INFORMATION_CLASS", "KEY_VALUE_INFORMATION_CLASS"
        )
    )
    structs = "\n\n".join(
        extract_struct(winternl, tag, typedef)
        for tag, typedef in [
            ("_KEY_BASIC_INFORMATION", "KEY_BASIC_INFORMATION"),
            ("_KEY_NODE_INFORMATION", "KEY_NODE_INFORMATION"),
            ("_KEY_FULL_INFORMATION", "KEY_FULL_INFORMATION"),
            ("_KEY_VALUE_BASIC_INFORMATION", "KEY_VALUE_BASIC_INFORMATION"),
            ("_KEY_VALUE_FULL_INFORMATION", "KEY_VALUE_FULL_INFORMATION"),
            ("_KEY_VALUE_PARTIAL_INFORMATION", "KEY_VALUE_PARTIAL_INFORMATION"),
        ]
    )
    prototypes = extract_prototypes(winternl, NTREGAPI_FUNCTIONS)

    return (
        BANNER.format(
            name="abi/ntregapi.h", source="wine/include/{winnt.h,winternl.h}"
        )
        + "#ifndef PROSKRNL_ABI_NTREGAPI_H\n"
        + "#define PROSKRNL_ABI_NTREGAPI_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + "/* Key access rights + value types, extracted from wine/include/winnt.h. */\n"
        + key_rights
        + "\n\n/* Extracted verbatim from wine/include/winternl.h. */\n"
        + info_class
        + "\n\n"
        + structs
        + "\n\n/* The Cm registry surface (M8);\n"
        + " * signatures extracted verbatim from wine/include/winternl.h. */\n"
        + prototypes
        + """

/* Info-class layouts the kernel's CmpFill*Info arithmetic leans on (fixed
 * headers + trailing-array offsets), pinned x64/LLP64 so a drift in the
 * extraction fails at compile time (Art. 4). */
_Static_assert(offsetof(KEY_BASIC_INFORMATION, Name) == 16, "KEY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_NODE_INFORMATION, Name) == 24, "KEY_NODE_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_FULL_INFORMATION, Class) == 44, "KEY_FULL_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_VALUE_BASIC_INFORMATION, Name) == 12,
               "KEY_VALUE_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_VALUE_FULL_INFORMATION, Name) == 20,
               "KEY_VALUE_FULL_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_VALUE_PARTIAL_INFORMATION, Data) == 12,
               "KEY_VALUE_PARTIAL_INFORMATION x64 layout");

#endif /* PROSKRNL_ABI_NTREGAPI_H */
"""
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parent.parent
    parser.add_argument("--wine", type=Path, default=root / "third_party/wine")
    parser.add_argument("--out", type=Path, default=root / "abi")
    args = parser.parse_args()

    args.out.mkdir(exist_ok=True)
    for name, text in [
        ("ntdef.h", gen_ntdef(args.wine)),
        ("ntstatus.h", gen_ntstatus(args.wine)),
        ("ntobapi.h", gen_ntobapi(args.wine)),
        ("ntmmapi.h", gen_ntmmapi(args.wine)),
        ("ntimage.h", gen_ntimage(args.wine)),
        ("ntioapi.h", gen_ntioapi(args.wine)),
        ("ntcondrv.h", gen_ntcondrv(args.wine)),
        ("ntcontext.h", gen_ntcontext(args.wine)),
        ("ntpsapi.h", gen_ntpsapi(args.wine)),
        ("ntpebteb.h", gen_ntpebteb(args.wine)),
        ("ntkeapi.h", gen_ntkeapi(args.wine)),
        ("ntregapi.h", gen_ntregapi(args.wine)),
    ]:
        (args.out / name).write_text(text)
        print(f"gen_abi: wrote abi/{name}")


if __name__ == "__main__":
    main()
