#!/usr/bin/env python3
"""gen_win32u_def.py - the export list of proskrnl's win32u.dll, from Wine's spec.

GUI-2 replaces win32u.dll with a PE build of the same tree's *unix-side*
sources (user/wine/win32u, Makefile target win32u.dll): user32/gdi32/imm32
import ~434 NtUser*/NtGdi* entry points by name, and the replacement has to
export exactly those names for the loader to bind them.

The name list is not typed out - it is read from the pinned tree's
dlls/win32u/win32u.spec, the same file winebuild reads (Art. 4: generate the
contract, never recall it). Only real entries are exported; the spec's `stub`
lines have no implementation on Wine either, and win32u's sources define
nothing for them, so exporting them would be a promise this build cannot
keep. If a shipped DLL ever imports one, the check below fails the build
loudly rather than leaving the loader to refuse at boot with no explanation.

  usage: gen_win32u_def.py <win32u.spec> <out.def> [importer.dll ...]
"""
import re
import subprocess
import sys


def spec_exports(path):
    """The non-stub, x86_64-relevant export names, in spec order."""
    real, stub = [], set()
    for line in open(path):
        line = line.split("#", 1)[0].strip()
        if not line.startswith("@"):
            continue
        fields = line.split()
        kind = fields[1]
        flags = [f for f in fields[2:] if f.startswith("-")]
        rest = [f for f in fields[2:] if not f.startswith("-")]
        if not rest:
            continue
        # -arch=... restricts an entry to some targets; we only build x86_64.
        arch = next((f[len("-arch="):] for f in flags if f.startswith("-arch=")), None)
        if arch is not None and "x86_64" not in arch.split(","):
            continue
        name = rest[0].split("(")[0]
        if kind == "stub":
            stub.add(name)
        else:
            real.append(name)
    return real, stub


def imported_from_win32u(dll):
    """Names `dll` imports from win32u.dll, via objdump's import listing."""
    out = subprocess.run(["objdump", "-p", dll], capture_output=True, text=True).stdout
    names, current = set(), None
    for line in out.splitlines():
        match = re.search(r"DLL Name: (\S+)", line)
        if match:
            current = match.group(1).lower()
            continue
        if current != "win32u.dll":
            continue
        match = re.match(r"\s+[0-9a-f]+\s+\d+\s+([A-Za-z_]\w*)\s*$", line)
        if match:
            names.add(match.group(1))
    return names


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    spec, out = sys.argv[1], sys.argv[2]
    real, stub = spec_exports(spec)
    exported = set(real)

    missing = {}
    for dll in sys.argv[3:]:
        for name in sorted(imported_from_win32u(dll) - exported):
            missing.setdefault(name, []).append(dll)
    if missing:
        for name, dlls in sorted(missing.items()):
            why = "spec stub" if name in stub else "absent from the spec"
            print("error: %s imports win32u.%s (%s)" % (", ".join(dlls), name, why),
                  file=sys.stderr)
        sys.exit(1)

    with open(out, "w") as f:
        f.write("; generated by tools/gen_win32u_def.py from %s -- do not edit\n" % spec)
        f.write("LIBRARY win32u.dll\nEXPORTS\n")
        for name in real:
            f.write("  %s\n" % name)
        # Wine keeps this one internal to win32u.so, where winex11.drv links
        # against it directly. winefb.drv is a separate PE, so it has to come
        # out through the export table.
        f.write("  __wine_set_user_driver\n")


if __name__ == "__main__":
    main()
