#!/usr/bin/env python3
"""gen_abi.py - generate abi/ headers from Wine's headers (Constitution Art. 4).

Every numeric value in abi/ (NTSTATUS codes, contract enums, boundary limits)
is extracted from third_party/wine/include/*.h - never typed by hand and never
recalled from model memory. Re-run after bumping the Wine submodule:

    python3 tools/gen_abi.py            # writes abi/ntstatus.h, abi/ntdef.h

The non-numeric scaffold (base typedefs, LIST_ENTRY/LARGE_INTEGER shapes) is
fixed text below; it carries static_asserts so a drift fails at compile time.
"""

import argparse
import re
import sys
from pathlib import Path

BANNER = """\
/* {name} - GENERATED by tools/gen_abi.py from {source}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
"""


def gen_ntstatus(wine: Path) -> str:
    """Extract every `#define STATUS_* ((NTSTATUS) 0x...)` from Wine's ntstatus.h."""
    src = (wine / "include/ntstatus.h").read_text()
    pattern = re.compile(
        r"^#define\s+(STATUS_\w+)\s+\(\(NTSTATUS\)\s*(0x[0-9A-Fa-f]+)\)", re.M
    )
    lines = [
        f"#define {name} ((NTSTATUS) {value})" for name, value in pattern.findall(src)
    ]
    if len(lines) < 2000:
        sys.exit(f"gen_abi: ntstatus extraction looks wrong ({len(lines)} values)")
    body = "\n".join(lines)
    return (
        BANNER.format(name="abi/ntstatus.h", source="wine/include/ntstatus.h")
        + "#ifndef PROSKRNL_ABI_NTSTATUS_H\n"
        + "#define PROSKRNL_ABI_NTSTATUS_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + body
        + "\n\n#endif /* PROSKRNL_ABI_NTSTATUS_H */\n"
    )


def extract_defines(src: str, source_name: str, names: list[str]) -> str:
    """Pull `#define NAME value` lines verbatim, in the order given (so a
    definition may reference an earlier one). Backslash-continued definitions
    (e.g. winnt.h's FILE_GENERIC_READ) are joined. Values are never retyped."""
    lines = []
    for name in names:
        match = re.search(
            r"^#define\s+" + re.escape(name) + r"\s+((?:[^\n]*\\\n)*[^\n]*?)\s*$",
            src,
            re.M,
        )
        if not match:
            sys.exit(f"gen_abi: #define {name} not found in {source_name}")
        value = re.sub(r"\s*\\\n\s*", " ", match.group(1))
        lines.append(f"#define {name} {value}")
    return "\n".join(lines)


def extract_struct(src: str, tag: str, typedef: str) -> str:
    """Pull one `typedef struct _TAG { ... } NAME, *PNAME...;` body verbatim.
    The reserved `_TAG` tag is dropped; members are kept byte-for-byte."""
    match = re.search(
        r"typedef struct " + tag + r"\s*\{(.*?)\}\s*([^;{}]*" + typedef + r"[^;{}]*)\s*;",
        src,
        re.S,
    )
    if not match:
        sys.exit(f"gen_abi: struct {typedef} not found")
    return "typedef struct {" + match.group(1) + "} " + match.group(2).strip() + ";"


def extract_prototypes(src: str, names: list[str]) -> str:
    """Pull `NTSYSAPI <ret> WINAPI Nt*(...)` prototypes verbatim from Wine's
    winternl.h, dropping the Windows linkage macros (signatures are contract;
    calling convention on x86_64 kernel builds is the platform default)."""
    lines = []
    for name in names:
        match = re.search(
            r"^NTSYSAPI\s+([\w* ]+?)\s+(?:WINAPI|NTAPI)\s+" + name + r"\s*\((.*)\);\s*$",
            src,
            re.M,
        )
        if not match:
            sys.exit(f"gen_abi: prototype {name} not found in winternl.h")
        ret, args = match.group(1).strip(), match.group(2).strip()
        lines.append(f"{ret} {name}({args});")
    return "\n".join(lines)


def extract_enum(src: str, tag: str, typedef: str) -> str:
    """Pull one `typedef enum _TAG { ... } NAME;` block verbatim (values are
    positional, so the body must come from the Wine header, not from memory).
    The reserved `_TAG` struct tag is dropped; the body is kept byte-for-byte."""
    match = re.search(
        r"typedef enum " + tag + r"\s*\{(.*?)\}\s*([^;{}]*" + typedef + r"[^;{}]*)\s*;",
        src,
        re.S,
    )
    if not match:
        sys.exit(f"gen_abi: enum {typedef} not found")
    return "typedef enum {" + match.group(1) + "} " + match.group(2).strip() + ";"


def gen_ntdef(wine: Path) -> str:
    ntdef = (wine / "include/ntdef.h").read_text()
    winnt = (wine / "include/winnt.h").read_text()
    winternl = (wine / "include/winternl.h").read_text()
    wdm = (wine / "include/ddk/wdm.h").read_text()

    enums = "\n\n".join(
        extract_enum(ntdef, tag, typedef)
        for tag, typedef in [
            ("_EVENT_TYPE", "EVENT_TYPE"),
            ("_TIMER_TYPE", "TIMER_TYPE"),
            ("_WAIT_TYPE", "WAIT_TYPE"),
        ]
    )

    match = re.search(r"^#define MAXIMUM_WAIT_OBJECTS\s+(\d+)", winnt, re.M)
    if not match:
        sys.exit("gen_abi: MAXIMUM_WAIT_OBJECTS not found")
    max_wait = match.group(1)

    # M3 (Ob): name/handle structs verbatim from Wine, values never retyped.
    ob_structs = "\n\n".join(
        [
            extract_struct(winternl, "_UNICODE_STRING", "UNICODE_STRING"),
            extract_struct(winternl, "_OBJECT_ATTRIBUTES", "OBJECT_ATTRIBUTES"),
        ]
    )
    obj_flags = extract_defines(
        winternl,
        "winternl.h",
        [
            "OBJ_INHERIT",
            "OBJ_PERMANENT",
            "OBJ_EXCLUSIVE",
            "OBJ_CASE_INSENSITIVE",
            "OBJ_OPENIF",
            "OBJ_OPENLINK",
            "OBJ_KERNEL_HANDLE",
        ],
    ) + "\n" + extract_defines(winternl, "winternl.h", ["NtCurrentProcess()"])
    access_rights = extract_defines(
        winnt,
        "winnt.h",
        [
            "DELETE",
            "READ_CONTROL",
            "WRITE_DAC",
            "WRITE_OWNER",
            "SYNCHRONIZE",
            "STANDARD_RIGHTS_REQUIRED",
            "STANDARD_RIGHTS_READ",
            "STANDARD_RIGHTS_WRITE",
            "STANDARD_RIGHTS_EXECUTE",
            "STANDARD_RIGHTS_ALL",
            "SPECIFIC_RIGHTS_ALL",
            "GENERIC_READ",
            "GENERIC_WRITE",
            "GENERIC_EXECUTE",
            "GENERIC_ALL",
            "MAXIMUM_ALLOWED",
            "EVENT_QUERY_STATE",
            "EVENT_MODIFY_STATE",
            "EVENT_ALL_ACCESS",
            "SEMAPHORE_QUERY_STATE",
            "SEMAPHORE_MODIFY_STATE",
            "SEMAPHORE_ALL_ACCESS",
            "MUTANT_QUERY_STATE",
            "MUTANT_ALL_ACCESS",
            "DUPLICATE_CLOSE_SOURCE",
            "DUPLICATE_SAME_ACCESS",
            "DUPLICATE_SAME_ATTRIBUTES",
        ],
    )
    directory_rights = extract_defines(
        wdm,
        "ddk/wdm.h",
        [
            "DIRECTORY_QUERY",
            "DIRECTORY_TRAVERSE",
            "DIRECTORY_CREATE_OBJECT",
            "DIRECTORY_CREATE_SUBDIRECTORY",
            "DIRECTORY_ALL_ACCESS",
            "SYMBOLIC_LINK_QUERY",
            "SYMBOLIC_LINK_ALL_ACCESS",
        ],
    )

    scaffold = """\
/* Base NT types (LLP64). The typedef shapes are fixed scaffold; the sizes are
 * pinned by the static_asserts below, so this cannot drift silently. */
typedef char CHAR;
typedef signed char CCHAR;
typedef unsigned char UCHAR;
typedef unsigned char BOOLEAN;
typedef short CSHORT;
typedef unsigned short USHORT;
typedef int LONG;
typedef unsigned int ULONG;
typedef long long LONGLONG;
typedef unsigned long long ULONGLONG;
typedef void *PVOID;
typedef ULONGLONG ULONG_PTR;

typedef LONG *PLONG;
typedef ULONG *PULONG;
typedef unsigned short WCHAR, *PWCHAR, *PWSTR;
typedef const WCHAR *PCWSTR;
typedef void *HANDLE;
typedef HANDLE *PHANDLE;
typedef ULONG ACCESS_MASK;

/* Win32-flavoured aliases some contract structs/prototypes are written in
 * (Wine's winnt.h MEMORY_BASIC_INFORMATION, winternl.h Nt* prototypes). */
typedef ULONG DWORD;
typedef PVOID LPVOID;
typedef const void *LPCVOID;
typedef ULONG_PTR SIZE_T, *PSIZE_T;

/* Win32 base names used verbatim inside extracted structs (winnt.h). */
typedef unsigned short WORD;
typedef unsigned char BYTE;

/* Anonymous-union/-struct spellings used verbatim inside extracted structs. */
#define DUMMYUNIONNAME
#define DUMMYSTRUCTNAME

typedef LONG NTSTATUS;
typedef LONG KPRIORITY;
typedef CCHAR KPROCESSOR_MODE;

#ifndef TRUE
#define TRUE 1
#define FALSE 0
#endif

#define NT_SUCCESS(status) (((NTSTATUS)(status)) >= 0)

typedef union {
    struct
    {
        ULONG LowPart;
        LONG HighPart;
    } u;
    LONGLONG QuadPart;
} LARGE_INTEGER, *PLARGE_INTEGER;

typedef union {
    struct
    {
        ULONG LowPart;
        ULONG HighPart;
    } u;
    ULONGLONG QuadPart;
} ULARGE_INTEGER, *PULARGE_INTEGER;

typedef struct LIST_ENTRY {
    struct LIST_ENTRY *Flink;
    struct LIST_ENTRY *Blink;
} LIST_ENTRY, *PLIST_ENTRY;

_Static_assert(sizeof(LONG) == 4, "LLP64: LONG is 4 bytes");
_Static_assert(sizeof(ULONGLONG) == 8, "LLP64: ULONGLONG is 8 bytes");
_Static_assert(sizeof(PVOID) == 8, "x86_64: pointers are 8 bytes");
_Static_assert(sizeof(LARGE_INTEGER) == 8, "LARGE_INTEGER is 8 bytes");
_Static_assert(sizeof(LIST_ENTRY) == 16, "LIST_ENTRY is two pointers");
_Static_assert(sizeof(BOOLEAN) == 1, "BOOLEAN is 1 byte");
_Static_assert(sizeof(WCHAR) == 2, "WCHAR is UTF-16");
_Static_assert(sizeof(HANDLE) == 8, "x86_64: HANDLE is pointer-sized");
_Static_assert(sizeof(DWORD) == 4, "LLP64: DWORD is 4 bytes");
_Static_assert(sizeof(SIZE_T) == 8, "x86_64: SIZE_T is 8 bytes");
_Static_assert(sizeof(WORD) == 2, "Win32: WORD is 2 bytes");
_Static_assert(sizeof(BYTE) == 1, "Win32: BYTE is 1 byte");
"""

    ob_asserts = """\
#include <stddef.h>
_Static_assert(sizeof(UNICODE_STRING) == 16, "UNICODE_STRING x64 layout");
_Static_assert(offsetof(UNICODE_STRING, MaximumLength) == 2, "UNICODE_STRING x64 layout");
_Static_assert(offsetof(UNICODE_STRING, Buffer) == 8, "UNICODE_STRING x64 layout");
_Static_assert(sizeof(OBJECT_ATTRIBUTES) == 48, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, RootDirectory) == 8, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, ObjectName) == 16, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, Attributes) == 24, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, SecurityDescriptor) == 32, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, SecurityQualityOfService) == 40, "OBJECT_ATTRIBUTES x64 layout");
"""

    return (
        BANNER.format(
            name="abi/ntdef.h",
            source="wine/include/{ntdef.h,winnt.h,winternl.h,ddk/wdm.h}",
        )
        + "#ifndef PROSKRNL_ABI_NTDEF_H\n"
        + "#define PROSKRNL_ABI_NTDEF_H\n\n"
        + scaffold
        + "\n/* Contract enums, extracted verbatim from wine/include/ntdef.h. */\n"
        + enums
        + "\n\n/* Extracted from wine/include/winnt.h. */\n"
        + f"#define MAXIMUM_WAIT_OBJECTS {max_wait}\n"
        + "\n/* Ob name/handle structs, extracted verbatim from wine/include/winternl.h;\n"
        + " * the static_asserts below pin the x64 layout the boundary depends on. */\n"
        + ob_structs
        + "\n\n"
        + ob_asserts
        + "\n/* Object-attribute flags, extracted from wine/include/winternl.h. */\n"
        + obj_flags
        + "\n\n/* Access rights, extracted from wine/include/winnt.h. */\n"
        + access_rights
        + "\n\n/* Directory/symlink access rights, extracted from wine/include/ddk/wdm.h. */\n"
        + directory_rights
        + "\n\n#endif /* PROSKRNL_ABI_NTDEF_H */\n"
    )


# The M3 Nt* surface (docs/02): Ob lifetime (close/duplicate), the dispatcher
# objects moved under Ob (event/mutant/semaphore), handle-based waits, and the
# namespace (directory/symbolic link). Prototypes are extracted verbatim from
# Wine's winternl.h so no signature is ever recalled from memory (Art. 4).
NTOBAPI_FUNCTIONS = [
    "NtClose",
    "NtDuplicateObject",
    "NtMakeTemporaryObject",
    "NtCreateEvent",
    "NtOpenEvent",
    "NtSetEvent",
    "NtResetEvent",
    "NtClearEvent",
    "NtPulseEvent",
    "NtQueryEvent",
    "NtCreateMutant",
    "NtOpenMutant",
    "NtReleaseMutant",
    "NtQueryMutant",
    "NtCreateSemaphore",
    "NtOpenSemaphore",
    "NtReleaseSemaphore",
    "NtQuerySemaphore",
    "NtWaitForSingleObject",
    "NtWaitForMultipleObjects",
    "NtCreateDirectoryObject",
    "NtOpenDirectoryObject",
    "NtCreateSymbolicLinkObject",
    "NtOpenSymbolicLinkObject",
    "NtQuerySymbolicLinkObject",
]


def gen_ntobapi(wine: Path) -> str:
    winternl = (wine / "include/winternl.h").read_text()

    enums = "\n\n".join(
        extract_enum(winternl, tag, typedef)
        for tag, typedef in [
            ("_EVENT_INFORMATION_CLASS", "EVENT_INFORMATION_CLASS"),
            ("_MUTANT_INFORMATION_CLASS", "MUTANT_INFORMATION_CLASS"),
            ("_SEMAPHORE_INFORMATION_CLASS", "SEMAPHORE_INFORMATION_CLASS"),
        ]
    )
    structs = "\n\n".join(
        extract_struct(winternl, tag, typedef)
        for tag, typedef in [
            ("_EVENT_BASIC_INFORMATION", "EVENT_BASIC_INFORMATION"),
            ("_MUTANT_BASIC_INFORMATION", "MUTANT_BASIC_INFORMATION"),
            ("_SEMAPHORE_BASIC_INFORMATION", "SEMAPHORE_BASIC_INFORMATION"),
        ]
    )
    prototypes = extract_prototypes(winternl, NTOBAPI_FUNCTIONS)

    return (
        BANNER.format(name="abi/ntobapi.h", source="wine/include/winternl.h")
        + "#ifndef PROSKRNL_ABI_NTOBAPI_H\n"
        + "#define PROSKRNL_ABI_NTOBAPI_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + "/* Information classes, extracted verbatim from wine/include/winternl.h. */\n"
        + enums
        + "\n\n"
        + structs
        + "\n\n/* The M3 Nt* surface; signatures extracted verbatim from\n"
        + " * wine/include/winternl.h (linkage macros dropped). */\n"
        + prototypes
        + "\n\n#endif /* PROSKRNL_ABI_NTOBAPI_H */\n"
    )


# The M4 Mm surface (docs/02): the reserve/commit two-step and its query.
# M5 adds the section surface: create/open/map/unmap/query (docs/02).
NTMMAPI_FUNCTIONS = [
    "NtAllocateVirtualMemory",
    "NtFreeVirtualMemory",
    "NtQueryVirtualMemory",
    "NtCreateSection",
    "NtOpenSection",
    "NtMapViewOfSection",
    "NtUnmapViewOfSection",
    "NtQuerySection",
]


def gen_ntmmapi(wine: Path) -> str:
    winnt = (wine / "include/winnt.h").read_text()
    winternl = (wine / "include/winternl.h").read_text()

    mem_flags = extract_defines(
        winnt,
        "winnt.h",
        [
            "PAGE_NOACCESS",
            "PAGE_READONLY",
            "PAGE_READWRITE",
            "PAGE_WRITECOPY",
            "PAGE_EXECUTE",
            "PAGE_EXECUTE_READ",
            "PAGE_EXECUTE_READWRITE",
            "PAGE_EXECUTE_WRITECOPY",
            "PAGE_GUARD",
            "PAGE_NOCACHE",
            "MEM_COMMIT",
            "MEM_RESERVE",
            "MEM_RESET",
            "MEM_TOP_DOWN",
            "MEM_DECOMMIT",
            "MEM_RELEASE",
            "MEM_FREE",
            "MEM_PRIVATE",
            "MEM_MAPPED",
            "MEM_WRITE_WATCH",
        ],
    )

    # M5 (sections): allocation attributes + section access rights (winnt.h).
    sec_flags = extract_defines(
        winnt,
        "winnt.h",
        [
            "SEC_FILE",
            "SEC_IMAGE",
            "SEC_RESERVE",
            "SEC_COMMIT",
            "SEC_NOCACHE",
            "SEC_WRITECOMBINE",
            "SEC_LARGE_PAGES",
            "MEM_IMAGE",
            "SECTION_QUERY",
            "SECTION_MAP_WRITE",
            "SECTION_MAP_READ",
            "SECTION_MAP_EXECUTE",
            "SECTION_EXTEND_SIZE",
            "SECTION_MAP_EXECUTE_EXPLICIT",
            "SECTION_ALL_ACCESS",
            "AT_ROUND_TO_PAGE",
        ],
    )

    mbi = extract_struct(winnt, "_MEMORY_BASIC_INFORMATION", "MEMORY_BASIC_INFORMATION")
    info_class = extract_enum(
        winternl, "_MEMORY_INFORMATION_CLASS", "MEMORY_INFORMATION_CLASS"
    )
    section_enums = "\n\n".join(
        extract_enum(winternl, tag, typedef)
        for tag, typedef in [
            ("_SECTION_INHERIT", "SECTION_INHERIT"),
            ("_SECTION_INFORMATION_CLASS", "SECTION_INFORMATION_CLASS"),
        ]
    )
    section_structs = "\n\n".join(
        extract_struct(winternl, tag, typedef)
        for tag, typedef in [
            ("_SECTION_BASIC_INFORMATION", "SECTION_BASIC_INFORMATION"),
            ("_SECTION_IMAGE_INFORMATION", "SECTION_IMAGE_INFORMATION"),
        ]
    )
    prototypes = extract_prototypes(winternl, NTMMAPI_FUNCTIONS)

    mbi_asserts = """\
#include <stddef.h>
_Static_assert(sizeof(MEMORY_BASIC_INFORMATION) == 48, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, AllocationBase) == 8, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, AllocationProtect) == 16, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, RegionSize) == 24, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, State) == 32, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, Protect) == 36, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, Type) == 40, "MEMORY_BASIC_INFORMATION x64 layout");
"""

    section_asserts = """\
_Static_assert(sizeof(SECTION_BASIC_INFORMATION) == 24, "SECTION_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_BASIC_INFORMATION, Attributes) == 8, "SECTION_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_BASIC_INFORMATION, Size) == 16, "SECTION_BASIC_INFORMATION x64 layout");
_Static_assert(sizeof(SECTION_IMAGE_INFORMATION) == 64, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, MaximumStackSize) == 16, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, SubSystemType) == 32, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, Machine) == 48, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, LoaderFlags) == 52, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, CheckSum) == 60, "SECTION_IMAGE_INFORMATION x64 layout");
"""

    return (
        BANNER.format(
            name="abi/ntmmapi.h", source="wine/include/{winnt.h,winternl.h}"
        )
        + "#ifndef PROSKRNL_ABI_NTMMAPI_H\n"
        + "#define PROSKRNL_ABI_NTMMAPI_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + "/* Allocation/protection flags, extracted from wine/include/winnt.h. */\n"
        + mem_flags
        + "\n\n/* Section allocation attributes + access rights (M5), extracted from\n"
        + " * wine/include/winnt.h. */\n"
        + sec_flags
        + "\n\n/* Extracted verbatim from wine/include/winnt.h; the static_asserts pin\n"
        + " * the x64 layout the boundary depends on. */\n"
        + mbi
        + "\n\n"
        + mbi_asserts
        + "\n/* Extracted verbatim from wine/include/winternl.h. */\n"
        + info_class
        + "\n\n/* Section enums/structs (M5), extracted verbatim from\n"
        + " * wine/include/winternl.h; static_asserts pin the x64 layout. */\n"
        + section_enums
        + "\n\n"
        + section_structs
        + "\n\n"
        + section_asserts
        + "\n/* The M4+M5 Mm Nt* surface; signatures extracted verbatim from\n"
        + " * wine/include/winternl.h (linkage macros dropped). */\n"
        + prototypes
        + "\n\n#endif /* PROSKRNL_ABI_NTMMAPI_H */\n"
    )


# The PE/COFF on-disk format (M5 image sections): structures and constants
# extracted verbatim from wine/include/winnt.h (the same layout Microsoft
# documents in the PE/COFF specification). x86_64 only (ADR 0006), so only
# the 64-bit optional header is carried.
def gen_ntimage(wine: Path) -> str:
    winnt = (wine / "include/winnt.h").read_text()

    signatures = extract_defines(
        winnt,
        "winnt.h",
        [
            "IMAGE_DOS_SIGNATURE",
            "IMAGE_NT_SIGNATURE",
            "IMAGE_NT_OPTIONAL_HDR64_MAGIC",
            "IMAGE_FILE_MACHINE_AMD64",
            "IMAGE_FILE_RELOCS_STRIPPED",
            "IMAGE_FILE_EXECUTABLE_IMAGE",
            "IMAGE_FILE_DLL",
            "IMAGE_NUMBEROF_DIRECTORY_ENTRIES",
            "IMAGE_SIZEOF_SHORT_NAME",
            "IMAGE_SIZEOF_SECTION_HEADER",
            "IMAGE_DIRECTORY_ENTRY_BASERELOC",
            "IMAGE_SCN_CNT_CODE",
            "IMAGE_SCN_CNT_INITIALIZED_DATA",
            "IMAGE_SCN_CNT_UNINITIALIZED_DATA",
            "IMAGE_SCN_MEM_SHARED",
            "IMAGE_SCN_MEM_EXECUTE",
            "IMAGE_SCN_MEM_READ",
            "IMAGE_SCN_MEM_WRITE",
            "IMAGE_REL_BASED_ABSOLUTE",
            "IMAGE_REL_BASED_HIGHLOW",
            "IMAGE_REL_BASED_DIR64",
            "IMAGE_SUBSYSTEM_NATIVE",
            "IMAGE_SUBSYSTEM_WINDOWS_GUI",
            "IMAGE_SUBSYSTEM_WINDOWS_CUI",
            "IMAGE_FIRST_SECTION(ntheader)",
        ],
    )

    structs = "\n\n".join(
        extract_struct(winnt, tag, typedef)
        for tag, typedef in [
            ("_IMAGE_DOS_HEADER", "IMAGE_DOS_HEADER"),
            ("_IMAGE_FILE_HEADER", "IMAGE_FILE_HEADER"),
            ("_IMAGE_DATA_DIRECTORY", "IMAGE_DATA_DIRECTORY"),
            ("_IMAGE_OPTIONAL_HEADER64", "IMAGE_OPTIONAL_HEADER64"),
            ("_IMAGE_NT_HEADERS64", "IMAGE_NT_HEADERS64"),
            ("_IMAGE_SECTION_HEADER", "IMAGE_SECTION_HEADER"),
            ("_IMAGE_BASE_RELOCATION", "IMAGE_BASE_RELOCATION"),
        ]
    )

    asserts = """\
#include <stddef.h>
_Static_assert(sizeof(IMAGE_DOS_HEADER) == 64, "IMAGE_DOS_HEADER layout");
_Static_assert(offsetof(IMAGE_DOS_HEADER, e_lfanew) == 0x3c, "IMAGE_DOS_HEADER layout");
_Static_assert(sizeof(IMAGE_FILE_HEADER) == 20, "IMAGE_FILE_HEADER layout");
_Static_assert(sizeof(IMAGE_OPTIONAL_HEADER64) == 240, "IMAGE_OPTIONAL_HEADER64 layout");
_Static_assert(offsetof(IMAGE_OPTIONAL_HEADER64, ImageBase) == 24, "IMAGE_OPTIONAL_HEADER64 layout");
_Static_assert(offsetof(IMAGE_OPTIONAL_HEADER64, SizeOfStackReserve) == 72, "IMAGE_OPTIONAL_HEADER64 layout");
_Static_assert(offsetof(IMAGE_NT_HEADERS64, OptionalHeader) == 24, "IMAGE_NT_HEADERS64 layout");
_Static_assert(sizeof(IMAGE_SECTION_HEADER) == IMAGE_SIZEOF_SECTION_HEADER, "IMAGE_SECTION_HEADER layout");
_Static_assert(sizeof(IMAGE_BASE_RELOCATION) == 8, "IMAGE_BASE_RELOCATION layout");
"""

    return (
        BANNER.format(name="abi/ntimage.h", source="wine/include/winnt.h")
        + "#ifndef PROSKRNL_ABI_NTIMAGE_H\n"
        + "#define PROSKRNL_ABI_NTIMAGE_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + "/* PE/COFF signatures and flags, extracted from wine/include/winnt.h. */\n"
        + signatures
        + "\n\n/* PE/COFF structures, extracted verbatim from wine/include/winnt.h;\n"
        + " * the static_asserts pin the on-disk layout. */\n"
        + structs
        + "\n\n"
        + asserts
        + "\n#endif /* PROSKRNL_ABI_NTIMAGE_H */\n"
    )


# The M6 Io surface (docs/02): NtCreateFile/NtOpenFile, read/write with the
# async-completion protocol shapes (IOSB, APC routine), the main info
# classes, directory enumeration, flush, and byte-range locks.
NTIOAPI_FUNCTIONS = [
    "NtCreateFile",
    "NtOpenFile",
    "NtReadFile",
    "NtWriteFile",
    "NtQueryInformationFile",
    "NtSetInformationFile",
    "NtQueryDirectoryFile",
    "NtQueryAttributesFile",
    "NtFlushBuffersFile",
    "NtLockFile",
    "NtUnlockFile",
]


def extract_typedef_line(src: str, source_name: str, name: str) -> str:
    """Pull a one-line `typedef ... NAME ...;` verbatim (used for the
    PIO_APC_ROUTINE function-pointer type), dropping the WINAPI macro."""
    match = re.search(r"^typedef[^\n;]*\b" + re.escape(name) + r"\b[^\n;]*;\s*$", src, re.M)
    if not match:
        sys.exit(f"gen_abi: typedef {name} not found in {source_name}")
    return match.group(0).strip().replace("WINAPI ", "").replace("CALLBACK ", "")


def gen_ntioapi(wine: Path) -> str:
    winnt = (wine / "include/winnt.h").read_text()
    winternl = (wine / "include/winternl.h").read_text()

    access_rights = extract_defines(
        winnt,
        "winnt.h",
        [
            "ANYSIZE_ARRAY",
            "FILE_READ_DATA",
            "FILE_LIST_DIRECTORY",
            "FILE_WRITE_DATA",
            "FILE_ADD_FILE",
            "FILE_APPEND_DATA",
            "FILE_ADD_SUBDIRECTORY",
            "FILE_READ_EA",
            "FILE_WRITE_EA",
            "FILE_EXECUTE",
            "FILE_TRAVERSE",
            "FILE_DELETE_CHILD",
            "FILE_READ_ATTRIBUTES",
            "FILE_WRITE_ATTRIBUTES",
            "FILE_ALL_ACCESS",
            "FILE_GENERIC_READ",
            "FILE_GENERIC_WRITE",
            "FILE_GENERIC_EXECUTE",
            "FILE_SHARE_READ",
            "FILE_SHARE_WRITE",
            "FILE_SHARE_DELETE",
            "FILE_ATTRIBUTE_READONLY",
            "FILE_ATTRIBUTE_HIDDEN",
            "FILE_ATTRIBUTE_SYSTEM",
            "FILE_ATTRIBUTE_DIRECTORY",
            "FILE_ATTRIBUTE_ARCHIVE",
            "FILE_ATTRIBUTE_NORMAL",
        ],
    )

    create_flags = extract_defines(
        winternl,
        "winternl.h",
        [
            # NtCreateFile options
            "FILE_DIRECTORY_FILE",
            "FILE_WRITE_THROUGH",
            "FILE_SEQUENTIAL_ONLY",
            "FILE_SYNCHRONOUS_IO_ALERT",
            "FILE_SYNCHRONOUS_IO_NONALERT",
            "FILE_NON_DIRECTORY_FILE",
            "FILE_RANDOM_ACCESS",
            "FILE_DELETE_ON_CLOSE",
            "FILE_OPEN_REPARSE_POINT",
            # IO_STATUS_BLOCK.Information values for create/open
            "FILE_SUPERSEDED",
            "FILE_OPENED",
            "FILE_CREATED",
            "FILE_OVERWRITTEN",
            "FILE_EXISTS",
            "FILE_DOES_NOT_EXIST",
            # create dispositions
            "FILE_SUPERSEDE",
            "FILE_OPEN",
            "FILE_CREATE",
            "FILE_OPEN_IF",
            "FILE_OVERWRITE",
            "FILE_OVERWRITE_IF",
            "FILE_MAXIMUM_DISPOSITION",
        ],
    )

    iosb = extract_struct(winternl, "_IO_STATUS_BLOCK", "IO_STATUS_BLOCK")
    apc_routine = extract_typedef_line(winternl, "winternl.h", "PIO_APC_ROUTINE")
    info_class = extract_enum(
        winternl, "_FILE_INFORMATION_CLASS", "FILE_INFORMATION_CLASS"
    )
    structs = "\n\n".join(
        extract_struct(winternl, tag, typedef)
        for tag, typedef in [
            ("_FILE_DIRECTORY_INFORMATION", "FILE_DIRECTORY_INFORMATION"),
            ("_FILE_FULL_DIRECTORY_INFORMATION", "FILE_FULL_DIRECTORY_INFORMATION"),
            ("_FILE_BOTH_DIRECTORY_INFORMATION", "FILE_BOTH_DIRECTORY_INFORMATION"),
            ("_FILE_BASIC_INFORMATION", "FILE_BASIC_INFORMATION"),
            ("_FILE_STANDARD_INFORMATION", "FILE_STANDARD_INFORMATION"),
            ("_FILE_INTERNAL_INFORMATION", "FILE_INTERNAL_INFORMATION"),
            ("_FILE_EA_INFORMATION", "FILE_EA_INFORMATION"),
            ("_FILE_ACCESS_INFORMATION", "FILE_ACCESS_INFORMATION"),
            ("_FILE_NAME_INFORMATION", "FILE_NAME_INFORMATION"),
            ("_FILE_NAMES_INFORMATION", "FILE_NAMES_INFORMATION"),
            ("_FILE_DISPOSITION_INFORMATION", "FILE_DISPOSITION_INFORMATION"),
            ("_FILE_POSITION_INFORMATION", "FILE_POSITION_INFORMATION"),
            ("_FILE_MODE_INFORMATION", "FILE_MODE_INFORMATION"),
            ("_FILE_ALIGNMENT_INFORMATION", "FILE_ALIGNMENT_INFORMATION"),
            ("_FILE_ALLOCATION_INFORMATION", "FILE_ALLOCATION_INFORMATION"),
            ("_FILE_END_OF_FILE_INFORMATION", "FILE_END_OF_FILE_INFORMATION"),
            ("_FILE_NETWORK_OPEN_INFORMATION", "FILE_NETWORK_OPEN_INFORMATION"),
            ("_FILE_ATTRIBUTE_TAG_INFORMATION", "FILE_ATTRIBUTE_TAG_INFORMATION"),
            ("_FILE_ALL_INFORMATION", "FILE_ALL_INFORMATION"),
        ]
    )
    prototypes = extract_prototypes(winternl, NTIOAPI_FUNCTIONS)

    asserts = """\
#include <stddef.h>
_Static_assert(sizeof(IO_STATUS_BLOCK) == 16, "IO_STATUS_BLOCK x64 layout");
_Static_assert(offsetof(IO_STATUS_BLOCK, Information) == 8, "IO_STATUS_BLOCK x64 layout");
_Static_assert(sizeof(FILE_BASIC_INFORMATION) == 40, "FILE_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_BASIC_INFORMATION, FileAttributes) == 32, "FILE_BASIC_INFORMATION x64 layout");
_Static_assert(sizeof(FILE_STANDARD_INFORMATION) == 24, "FILE_STANDARD_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_STANDARD_INFORMATION, DeletePending) == 20, "FILE_STANDARD_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_DIRECTORY_INFORMATION, FileName) == 64, "FILE_DIRECTORY_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_FULL_DIRECTORY_INFORMATION, FileName) == 68, "FILE_FULL_DIRECTORY_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_BOTH_DIRECTORY_INFORMATION, ShortName) == 70, "FILE_BOTH_DIRECTORY_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_BOTH_DIRECTORY_INFORMATION, FileName) == 94, "FILE_BOTH_DIRECTORY_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_NAMES_INFORMATION, FileName) == 12, "FILE_NAMES_INFORMATION x64 layout");
_Static_assert(offsetof(FILE_ALL_INFORMATION, NameInformation) == 96, "FILE_ALL_INFORMATION x64 layout");
"""

    return (
        BANNER.format(
            name="abi/ntioapi.h", source="wine/include/{winnt.h,winternl.h}"
        )
        + "#ifndef PROSKRNL_ABI_NTIOAPI_H\n"
        + "#define PROSKRNL_ABI_NTIOAPI_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + "/* File access rights, share modes, and attributes, extracted from\n"
        + " * wine/include/winnt.h. */\n"
        + access_rights
        + "\n\n/* Create options/dispositions and IOSB Information values, extracted\n"
        + " * from wine/include/winternl.h. */\n"
        + create_flags
        + "\n\n/* The async-completion protocol shapes (docs/03: IOSB timing is a kept\n"
        + " * contract), extracted verbatim from wine/include/winternl.h. */\n"
        + iosb
        + "\n\n"
        + apc_routine
        + "\n\n/* Extracted verbatim from wine/include/winternl.h. */\n"
        + info_class
        + "\n\n"
        + structs
        + "\n\n"
        + asserts
        + "\n/* The M6 Io Nt* surface; signatures extracted verbatim from\n"
        + " * wine/include/winternl.h (linkage macros dropped). */\n"
        + prototypes
        + "\n\n#endif /* PROSKRNL_ABI_NTIOAPI_H */\n"
    )


# The M4 Ps surface: process termination (the flat-binary exit path) plus
# NtDisplayString (the flat-binary test-output path, docs/14).
NTPSAPI_FUNCTIONS = [
    "NtTerminateProcess",
    "NtDisplayString",
]


def gen_ntpsapi(wine: Path) -> str:
    winnt = (wine / "include/winnt.h").read_text()
    winternl = (wine / "include/winternl.h").read_text()

    process_rights = extract_defines(
        winnt,
        "winnt.h",
        [
            "PROCESS_TERMINATE",
            "PROCESS_CREATE_THREAD",
            "PROCESS_VM_OPERATION",
            "PROCESS_VM_READ",
            "PROCESS_VM_WRITE",
            "PROCESS_QUERY_INFORMATION",
            "PROCESS_SET_INFORMATION",
            "PROCESS_SUSPEND_RESUME",
            "PROCESS_QUERY_LIMITED_INFORMATION",
            "PROCESS_ALL_ACCESS",
        ],
    )

    nt_tib = extract_struct(winnt, "_NT_TIB", "NT_TIB")
    client_id = extract_struct(winternl, "_CLIENT_ID", "CLIENT_ID")
    prototypes = extract_prototypes(winternl, NTPSAPI_FUNCTIONS)

    tib_asserts = """\
#include <stddef.h>
_Static_assert(sizeof(NT_TIB) == 56, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, StackBase) == 8, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, StackLimit) == 16, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, ArbitraryUserPointer) == 40, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, Self) == 48, "NT_TIB x64 layout");
"""

    return (
        BANNER.format(
            name="abi/ntpsapi.h", source="wine/include/{winnt.h,winternl.h}"
        )
        + "#ifndef PROSKRNL_ABI_NTPSAPI_H\n"
        + "#define PROSKRNL_ABI_NTPSAPI_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + "/* Process access rights, extracted from wine/include/winnt.h. */\n"
        + process_rights
        + "\n\n/* The TEB begins with an NT_TIB (the one TEB slice the M4 boundary\n"
        + " * carries; the full byte-exact TEB/PEB arrive with M7). Extracted\n"
        + " * verbatim from wine/include/winnt.h; asserts pin the x64 layout. */\n"
        + "struct _EXCEPTION_REGISTRATION_RECORD;\n"
        + nt_tib
        + "\n\n"
        + tib_asserts
        + "\n/* Extracted verbatim from wine/include/winternl.h. */\n"
        + client_id
        + "\n\n/* The M4 Ps Nt* surface; signatures extracted verbatim from\n"
        + " * wine/include/winternl.h (linkage macros dropped). */\n"
        + prototypes
        + "\n\n#endif /* PROSKRNL_ABI_NTPSAPI_H */\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parent.parent
    parser.add_argument("--wine", type=Path, default=root / "third_party/wine")
    parser.add_argument("--out", type=Path, default=root / "abi")
    args = parser.parse_args()

    args.out.mkdir(exist_ok=True)
    for name, text in [
        ("ntdef.h", gen_ntdef(args.wine)),
        ("ntstatus.h", gen_ntstatus(args.wine)),
        ("ntobapi.h", gen_ntobapi(args.wine)),
        ("ntmmapi.h", gen_ntmmapi(args.wine)),
        ("ntimage.h", gen_ntimage(args.wine)),
        ("ntioapi.h", gen_ntioapi(args.wine)),
        ("ntpsapi.h", gen_ntpsapi(args.wine)),
    ]:
        (args.out / name).write_text(text)
        print(f"gen_abi: wrote abi/{name}")


if __name__ == "__main__":
    main()
