#!/usr/bin/env python3
"""Generate kernel/lib/upcase.h — the NLS upcase table, from the pinned tree.

Case-insensitive NT name equality is decided by ONE table, and it is data
rather than a rule: `third_party/wine/nls/l_intl.nls`, the same file the
oracle reads on both sides of the boundary. Wine's PE ntdll maps it in
`init_environment` (`dlls/ntdll/unix/env.c`: `uctable = case_table + 2`) and
wineserver reads its lowercase half for `memicmp_strW`
(`server/unicode.c`), so a proskrnl that folds names by a hand-written rule
is measuring its own rule against the oracle's table (docs/03 "Name case
folding" recorded exactly that, twice).

So the table is GENERATED, never transcribed — the same reason `abi/` is
(Art. 4/G4: no hand-typed constants, and 1433 of them is the strongest
possible case for it). The output is checked in because `make format` runs
clang-tidy over `kernel/` on a bare checkout, where `third_party/wine` is
not present.

FILE LAYOUT, per the two readers above (this is the whole format):

    w[0]      1, the word offset of the uppercase table's size
    w[1]      N, the number of words in the uppercase table
    w[2..]    the uppercase table, N words
    w[2+N..]  the lowercase table, headed by its own size word

The table is the standard NLS three-level trie, indexed by the 16-bit code
unit and yielding a DELTA to add:

    upcase(ch) = ch + t[ t[ t[ch >> 8] + ((ch >> 4) & 0xf) ] + (ch & 0xf) ]

Two properties worth knowing, both checked by --check rather than assumed:

  * no index the lookup can produce reaches the last word of the slice, so
    the size word wineserver reads there (`server/unicode.c` reads the
    lowercase size at `2 + N - 1`) is never mistaken for table data;
  * the uppercase and lowercase tables induce the SAME partition of the BMP,
    so "which half does the oracle fold through" cannot be observed through
    name EQUALITY — only through ordering, where the upcase table is what
    ntdll's own RtlCompareUnicodeString uses.

Usage:
    gen_upcase.py                 # rewrite kernel/lib/upcase.h
    gen_upcase.py --check         # fail if the checked-in file is stale
"""

import argparse
import pathlib
import struct
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
NLS = ROOT / "third_party" / "wine" / "nls" / "l_intl.nls"
OUT = ROOT / "kernel" / "lib" / "upcase.h"

# clang-format (ColumnLimit 100, IndentWidth 4) packs `0x0000, ` at 8 columns
# each, so 12 per line is the widest that fits: 4 + 12*8 - 1 = 99. Emitting
# that shape makes `make format` a no-op on this file instead of a rewrite.
PER_LINE = 12


def read_tables(path):
    """Return (upper, lower) as tuples of USHORT deltas."""
    raw = path.read_bytes()
    if len(raw) % 2:
        sys.exit(f"{path}: odd byte count {len(raw)} — not an NLS casemap file")
    words = struct.unpack("<%dH" % (len(raw) // 2), raw)
    if len(words) < 3 or words[0] != 1:
        sys.exit(f"{path}: unexpected header {words[:2]} — expected an offset of 1")
    upperWords = words[1]
    upper = words[2 : 2 + upperWords]
    lower = words[2 + upperWords :]
    if len(upper) != upperWords or not lower:
        sys.exit(f"{path}: truncated casemap tables")
    return upper, lower


def casemap(table, ch):
    return (ch + table[table[table[ch >> 8] + ((ch >> 4) & 0x0F)] + (ch & 0x0F)]) & 0xFFFF


def audit(upper, lower):
    """The two properties the header's comment claims. Never assumed."""
    highest = 0
    for ch in range(0x10000):
        first = ch >> 8
        second = upper[first] + ((ch >> 4) & 0x0F)
        third = upper[second] + (ch & 0x0F)
        highest = max(highest, first, second, third)
    if highest >= len(upper) - 1:
        sys.exit(f"upcase lookup reaches index {highest} of {len(upper)} — the size word is data")

    byUpper, byLower = {}, {}
    for ch in range(0x10000):
        byUpper.setdefault(casemap(upper, ch), []).append(ch)
        byLower.setdefault(casemap(lower, ch), []).append(ch)
    if {frozenset(v) for v in byUpper.values()} != {frozenset(v) for v in byLower.values()}:
        sys.exit("the upper and lower casemap tables disagree about name equality")
    return highest


def render(upper, highest):
    lines = [
        "/* kernel/lib/upcase.h - GENERATED by tools/gen_upcase.py from",
        " * third_party/wine/nls/l_intl.nls (the pinned tree's NLS casemap file, the",
        " * SAME bytes the oracle folds through: Wine's PE ntdll maps it in",
        " * dlls/ntdll/unix/env.c init_environment, wineserver in server/unicode.c).",
        " * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:",
        " *     python3 tools/gen_upcase.py",
        " *",
        " * The standard NLS three-level trie of DELTAS, indexed by the 16-bit code",
        " * unit — see RtlUpcaseUnicodeChar in kernel/lib/rtl.c for the lookup and for",
        " * what it means that the fold is per-code-unit rather than per-code-point.",
        f" * The lookup reaches index {highest} at most, so the last word of the slice",
        " * (which is the lowercase table's size, not table data) is never read.",
        " *",
        " * kernel/lib/rtl.c is the ONE includer, which is what makes `static const`",
        " * right here: a second includer would get its own 2.8 KiB copy with no",
        " * diagnostic, so a new consumer calls RtlUpcaseUnicodeChar instead (Art. 11",
        " * says that anyway — there is one fold, not one table plus a caller).",
        " */",
        "#ifndef PROSKRNL_KERNEL_LIB_UPCASE_H",
        "#define PROSKRNL_KERNEL_LIB_UPCASE_H",
        "",
        '#include "abi/ntdef.h"',
        "",
        f"#define RTLP_UPCASE_TABLE_WORDS {len(upper)}",
        "",
        f"static const USHORT RtlpUpcaseTable[RTLP_UPCASE_TABLE_WORDS] = {{",
    ]
    for i in range(0, len(upper), PER_LINE):
        chunk = upper[i : i + PER_LINE]
        lines.append("    " + " ".join("0x%04X," % v for v in chunk))
    lines += [
        "};",
        "",
        "#endif /* PROSKRNL_KERNEL_LIB_UPCASE_H */",
    ]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = parser.parse_args()

    if not NLS.exists():
        sys.exit(f"{NLS} missing — build the pinned Wine tree first (tools/setup_linux.sh)")
    upper, lower = read_tables(NLS)
    highest = audit(upper, lower)
    text = render(upper, highest)

    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit(f"{OUT} is stale — run: python3 tools/gen_upcase.py")
        print(f"{OUT}: up to date ({len(upper)} words)")
        return
    OUT.write_text(text)
    print(f"{OUT}: {len(upper)} words from {NLS}")


if __name__ == "__main__":
    main()
