#!/usr/bin/env python3
r"""Generate drivers/usb/usbkeymap.h — USB HID keyboard usage -> evdev keycode.

\Device\Input0's contract is the virtio-input wire format: EV_KEY codes are
Linux evdev KEY_* numbers (drivers/hidproto.h, virtio 1.2 cs01 §5.8.6), and
the one consumer (user/wine/wineserver-lite/server/rawinput.c) turns exactly
those into scancodes. A USB HID keyboard in boot protocol reports Keyboard/
Keypad page usages instead (HID 1.11 Appendix B.1; HID Usage Tables §10), so
the USB driver needs the usage -> KEY_* renumbering. It is a renumbering of
the same physical key, not a layout: KEY_A and usage 0x04 both mean "the key
in the A position", whatever the cap says.

The table is GENERATED rather than typed (Art. 4 / G4 applied outside abi/:
a number recalled from memory is indistinguishable from a wrong one), from
third_party/keycodemapdb data/keymaps.csv — the key-code database the
pinned QEMU builds its own usb-to-qcode table from
(third_party/qemu/subprojects/keycodemapdb.wrap names the same revision this
submodule is pinned at), so the numbers the driver renumbers by are the
numbers QEMU's usb-kbd encodes by. The two columns read are "USB Keycodes"
(the HID usage, decimal) and "Linux Keycode" (KEY_*, decimal); nothing else
in the database is consulted. The database is dual-licensed BSD-3/GPL-2+
(its README); the BSD grant covers this use (docs/11, docs/provenance.md).

Usage:
    gen_usb_keymap.py              # rewrite drivers/usb/usbkeymap.h
    gen_usb_keymap.py --check      # fail if the checked-in file is stale
"""

import argparse
import csv
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DB = ROOT / "third_party" / "keycodemapdb"
CSV = DB / "data" / "keymaps.csv"
OUT = ROOT / "drivers" / "usb" / "usbkeymap.h"

USB_COLUMN = "USB Keycodes"
LINUX_COLUMN = "Linux Keycode"
NAME_COLUMN = "Linux Name"

# The Keyboard/Keypad page is a one-byte usage in a boot report (HID 1.11
# Appendix B.1: six one-byte key slots), so the table is indexed by 0..255.
TABLE_SIZE = 256


def pinned_revision():
    """The submodule's checked-out commit, recorded in the header so a reader
    can tell which database the numbers came from."""
    result = subprocess.run(
        ["git", "-C", str(DB), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


def read_table():
    table = {}
    names = {}
    with open(CSV, newline="") as handle:
        for row in csv.DictReader(handle):
            usb = row[USB_COLUMN].strip()
            linux = row[LINUX_COLUMN].strip()
            if not usb or not linux:
                continue
            usage = int(usb, 0)
            keycode = int(linux, 0)
            if usage == 0 or usage >= TABLE_SIZE:
                sys.exit(f"gen_usb_keymap: usage {usage} for {row[NAME_COLUMN]} is out of range")
            if keycode == 0 or keycode > 0xFFFF:
                sys.exit(f"gen_usb_keymap: keycode {keycode} for {row[NAME_COLUMN]} is out of range")
            # The database repeats a key when it has several names on some
            # other platform; the same pair twice is fine, two different
            # keycodes for one usage is a database bug we refuse to encode.
            if usage in table and table[usage] != keycode:
                sys.exit(
                    f"gen_usb_keymap: usage {usage} maps to both {table[usage]} and {keycode}"
                )
            table[usage] = keycode
            names.setdefault(usage, row[NAME_COLUMN])
    if not table:
        sys.exit("gen_usb_keymap: no rows read; is third_party/keycodemapdb checked out?")
    return table, names


def render(table, names, revision):
    lines = [
        "/* drivers/usb/usbkeymap.h — GENERATED by tools/gen_usb_keymap.py; do not",
        " * edit. USB HID Keyboard/Keypad page usage (HID Usage Tables §10, the",
        " * boot report's key slots) -> Linux evdev KEY_* keycode (the",
        " * \\Device\\Input0 wire format, drivers/hidproto.h), from the pinned",
        " * third_party/keycodemapdb data/keymaps.csv at",
        f" * {revision} — the database and revision the pinned QEMU's usb-kbd",
        " * encodes by (third_party/qemu/subprojects/keycodemapdb.wrap). Zero",
        " * means the usage has no evdev key, and the driver drops it. */",
        "#ifndef PROSKRNL_DRIVERS_USB_USBKEYMAP_H",
        "#define PROSKRNL_DRIVERS_USB_USBKEYMAP_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define USB_KEYMAP_SIZE {TABLE_SIZE}",
        "",
        f"static const uint16_t UsbKeymapUsageToEvdev[USB_KEYMAP_SIZE] = {{",
    ]
    # Trailing comments are column-aligned the way clang-format lays them out
    # (AlignTrailingComments over one contiguous block), so `make format`
    # leaves the generated file byte-identical.
    entries = {usage: f"[0x{usage:02x}] = {table[usage]}," for usage in table}
    width = max(len(entry) for entry in entries.values())
    for usage in sorted(table):
        lines.append(f"    {entries[usage].ljust(width)} /* {names[usage]} */")
    lines += ["};", "", "#endif /* PROSKRNL_DRIVERS_USB_USBKEYMAP_H */", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify the checked-in header")
    args = parser.parse_args()

    table, names = read_table()
    text = render(table, names, pinned_revision())
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            sys.exit(f"{OUT.relative_to(ROOT)} is stale: run tools/gen_usb_keymap.py")
        print(f"gen_usb_keymap: {OUT.relative_to(ROOT)} matches the pin ({len(table)} usages)")
        return
    OUT.write_text(text)
    print(f"gen_usb_keymap: wrote {OUT.relative_to(ROOT)} ({len(table)} usages)")


if __name__ == "__main__":
    main()
