#!/usr/bin/env python3
"""gen_server_table.py - wineserver-lite's request dispatch table.

wineserver-lite.exe links the pinned wineserver's GUI object model
(user/wine/wineserver-lite/) and calls its handlers directly. Only the files
that hold desktop state are compiled - the process/thread model, the fd layer
and the security engine are not - so most of the 300-odd request handlers
have no implementation here.

Rather than curate a whitelist by hand (which would drift), the table is
generated: the ordered request list comes from the pinned tree's own
request_handlers.h, and whether a handler exists is decided by looking at the
compiled objects. Anything absent gets a NULL slot, which the dispatcher
turns into a named refusal on serial plus STATUS_NOT_IMPLEMENTED - never a
plausible empty success (Art. 12).

Two outputs, because the two links need different halves of the same
generated list. The HANDLER table is the server's, and pulls in every
compiled server object by reference. The NAMES are shared: win32u.dll wants
them only to name a request in a diagnostic, and must not drag the state
machine into the DLL to get them (that is the whole point of the split -- the
DLL no longer links the object model at all). Same generator, same order, so
they cannot disagree.

  usage: gen_server_table.py <request_handlers.h> <out_table.c> <out_names.c>
                             <server .o files...>
"""
import re
import subprocess
import sys

NM = "x86_64-w64-mingw32-nm"


def table_order(header):
    """Request names in `enum request` order, from the generated table."""
    text = open(header).read()
    body = text[text.index("req_handlers[REQ_NB_REQUESTS]"):]
    return re.findall(r"\(req_handler\)req_(\w+)", body)


def defined_handlers(objects):
    names = set()
    for obj in objects:
        out = subprocess.run([NM, "--defined-only", obj], capture_output=True, text=True).stdout
        for line in out.splitlines():
            fields = line.split()
            if len(fields) == 3 and fields[1] in "TtDdBbRr" and fields[2].startswith("req_"):
                names.add(fields[2][len("req_"):])
    return names


def main():
    if len(sys.argv) < 5:
        sys.exit(__doc__)
    header, out, out_names, objects = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4:]
    order = table_order(header)
    built = defined_handlers(objects)

    with open(out, "w") as f:
        f.write('/* generated by tools/gen_server_table.py -- do not edit */\n')
        f.write('#include "prsk_request_table.h"\n\n')
        for name in order:
            if name in built:
                f.write("extern void req_%s( const void *req, void *reply );\n" % name)
        f.write("\nconst prsk_req_handler prsk_req_handlers[] =\n{\n")
        for name in order:
            f.write("    %s,\n" % (("req_" + name) if name in built else "NULL"))
        f.write("};\n")

    with open(out_names, "w") as f:
        f.write('/* generated by tools/gen_server_table.py -- do not edit */\n')
        f.write('#include "prsk_request_table.h"\n\n')
        f.write("const char * const prsk_req_names[] =\n{\n")
        for name in order:
            f.write('    "%s",\n' % name)
        f.write("};\n\n")
        f.write("const unsigned int prsk_req_count = %d;\n" % len(order))

    missing = [n for n in order if n not in built]
    print("gen_server_table: %d handlers linked, %d refuse (unbuilt)"
          % (len(order) - len(missing), len(missing)), file=sys.stderr)


if __name__ == "__main__":
    main()
