#!/usr/bin/env python3
"""gen_abi.py - generate abi/ headers from Wine's headers (Constitution Art. 4).

Every numeric value in abi/ (NTSTATUS codes, contract enums, boundary limits)
is extracted from third_party/wine/include/*.h - never typed by hand and never
recalled from model memory. Re-run after bumping the Wine submodule:

    python3 tools/gen_abi.py            # writes abi/ntstatus.h, abi/ntdef.h

The non-numeric scaffold (base typedefs, LIST_ENTRY/LARGE_INTEGER shapes) is
fixed text below; it carries static_asserts so a drift fails at compile time.
"""

import argparse
import re
import sys
from pathlib import Path

BANNER = """\
/* {name} - GENERATED by tools/gen_abi.py from {source}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
"""


def gen_ntstatus(wine: Path) -> str:
    """Extract every `#define STATUS_* ((NTSTATUS) 0x...)` from Wine's ntstatus.h."""
    src = (wine / "include/ntstatus.h").read_text()
    pattern = re.compile(
        r"^#define\s+(STATUS_\w+)\s+\(\(NTSTATUS\)\s*(0x[0-9A-Fa-f]+)\)", re.M
    )
    lines = [
        f"#define {name} ((NTSTATUS) {value})" for name, value in pattern.findall(src)
    ]
    if len(lines) < 2000:
        sys.exit(f"gen_abi: ntstatus extraction looks wrong ({len(lines)} values)")
    body = "\n".join(lines)
    return (
        BANNER.format(name="abi/ntstatus.h", source="wine/include/ntstatus.h")
        + "#ifndef PROSKRNL_ABI_NTSTATUS_H\n"
        + "#define PROSKRNL_ABI_NTSTATUS_H\n\n"
        + '#include "abi/ntdef.h"\n\n'
        + body
        + "\n\n#endif /* PROSKRNL_ABI_NTSTATUS_H */\n"
    )


def extract_enum(src: str, tag: str, typedef: str) -> str:
    """Pull one `typedef enum _TAG { ... } NAME;` block verbatim (values are
    positional, so the body must come from the Wine header, not from memory).
    The reserved `_TAG` struct tag is dropped; the body is kept byte-for-byte."""
    match = re.search(
        r"typedef enum " + tag + r"\s*\{(.*?)\}\s*" + typedef + r"\s*;", src, re.S
    )
    if not match:
        sys.exit(f"gen_abi: enum {typedef} not found")
    return "typedef enum {" + match.group(1) + "} " + typedef + ";"


def gen_ntdef(wine: Path) -> str:
    ntdef = (wine / "include/ntdef.h").read_text()
    winnt = (wine / "include/winnt.h").read_text()

    enums = "\n\n".join(
        extract_enum(ntdef, tag, typedef)
        for tag, typedef in [
            ("_EVENT_TYPE", "EVENT_TYPE"),
            ("_TIMER_TYPE", "TIMER_TYPE"),
            ("_WAIT_TYPE", "WAIT_TYPE"),
        ]
    )

    match = re.search(r"^#define MAXIMUM_WAIT_OBJECTS\s+(\d+)", winnt, re.M)
    if not match:
        sys.exit("gen_abi: MAXIMUM_WAIT_OBJECTS not found")
    max_wait = match.group(1)

    scaffold = """\
/* Base NT types (LLP64). The typedef shapes are fixed scaffold; the sizes are
 * pinned by the static_asserts below, so this cannot drift silently. */
typedef signed char CCHAR;
typedef unsigned char UCHAR;
typedef unsigned char BOOLEAN;
typedef short CSHORT;
typedef unsigned short USHORT;
typedef int LONG;
typedef unsigned int ULONG;
typedef long long LONGLONG;
typedef unsigned long long ULONGLONG;
typedef void *PVOID;
typedef ULONGLONG ULONG_PTR;

typedef LONG NTSTATUS;
typedef LONG KPRIORITY;
typedef CCHAR KPROCESSOR_MODE;

#ifndef TRUE
#define TRUE 1
#define FALSE 0
#endif

#define NT_SUCCESS(status) (((NTSTATUS)(status)) >= 0)

typedef union {
    struct
    {
        ULONG LowPart;
        LONG HighPart;
    } u;
    LONGLONG QuadPart;
} LARGE_INTEGER, *PLARGE_INTEGER;

typedef union {
    struct
    {
        ULONG LowPart;
        ULONG HighPart;
    } u;
    ULONGLONG QuadPart;
} ULARGE_INTEGER, *PULARGE_INTEGER;

typedef struct LIST_ENTRY {
    struct LIST_ENTRY *Flink;
    struct LIST_ENTRY *Blink;
} LIST_ENTRY, *PLIST_ENTRY;

_Static_assert(sizeof(LONG) == 4, "LLP64: LONG is 4 bytes");
_Static_assert(sizeof(ULONGLONG) == 8, "LLP64: ULONGLONG is 8 bytes");
_Static_assert(sizeof(PVOID) == 8, "x86_64: pointers are 8 bytes");
_Static_assert(sizeof(LARGE_INTEGER) == 8, "LARGE_INTEGER is 8 bytes");
_Static_assert(sizeof(LIST_ENTRY) == 16, "LIST_ENTRY is two pointers");
_Static_assert(sizeof(BOOLEAN) == 1, "BOOLEAN is 1 byte");
"""

    return (
        BANNER.format(
            name="abi/ntdef.h", source="wine/include/{ntdef.h,winnt.h}"
        )
        + "#ifndef PROSKRNL_ABI_NTDEF_H\n"
        + "#define PROSKRNL_ABI_NTDEF_H\n\n"
        + scaffold
        + "\n/* Contract enums, extracted verbatim from wine/include/ntdef.h. */\n"
        + enums
        + "\n\n/* Extracted from wine/include/winnt.h. */\n"
        + f"#define MAXIMUM_WAIT_OBJECTS {max_wait}\n"
        + "\n#endif /* PROSKRNL_ABI_NTDEF_H */\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parent.parent
    parser.add_argument("--wine", type=Path, default=root / "third_party/wine")
    parser.add_argument("--out", type=Path, default=root / "abi")
    args = parser.parse_args()

    args.out.mkdir(exist_ok=True)
    for name, text in [
        ("ntdef.h", gen_ntdef(args.wine)),
        ("ntstatus.h", gen_ntstatus(args.wine)),
    ]:
        (args.out / name).write_text(text)
        print(f"gen_abi: wrote abi/{name}")


if __name__ == "__main__":
    main()
