#!/usr/bin/env python3
"""gen_freetype_syms.py — the FreeType symbol table win32u's font backend looks up.

dlls/win32u/freetype.c reaches FreeType through dlopen/dlsym: one
MAKE_FUNCPTR per entry point, then a LOAD_FUNCPTR that resolves it by name.
On proskrnl there is no dynamic loader, and FreeType is linked statically
into win32u.dll, so the lookup is answered from a table
(user/wine/win32u/freetype_link.c).

The table is generated from the MAKE_FUNCPTR list in freetype.c rather than
typed out, so that a Wine pin which starts calling a new FreeType entry
point fails the BUILD (unresolved symbol at link time) instead of failing at
run time with a NULL function pointer and no glyphs (Art. 4: generate the
contract; Art. 12: refuse loudly, do not degrade quietly).

Only FT_* names are taken. freetype.c also MAKE_FUNCPTRs the fontconfig API,
which this build does not link -- without SONAME_LIBFONTCONFIG defined, that
half of the file is not compiled at all, and font discovery falls back to
scanning C:\\windows\\fonts, which is where the image bakes them.

  usage: gen_freetype_syms.py <freetype.c> <out.h>
"""
import re
import sys

MAKE_FUNCPTR = re.compile(r"^MAKE_FUNCPTR\((FT_\w+)\)", re.M)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    source, out = sys.argv[1], sys.argv[2]
    names = sorted(set(MAKE_FUNCPTR.findall(open(source).read())))
    if not names:
        sys.exit("gen_freetype_syms: no MAKE_FUNCPTR(FT_*) lines in %s" % source)

    with open(out, "w") as f:
        f.write("/* generated by tools/gen_freetype_syms.py from %s -- do not edit */\n" % source)
        f.write("#ifndef PRSK_FREETYPE_SYMS_H\n#define PRSK_FREETYPE_SYMS_H\n\n")
        f.write("struct prsk_freetype_sym { const char *name; void *address; };\n\n")
        f.write("static const struct prsk_freetype_sym prsk_freetype_syms[] =\n{\n")
        for name in names:
            f.write('    { "%s", (void *)%s },\n' % (name, name))
        f.write("};\n\n")
        f.write("static const unsigned int prsk_freetype_sym_count =\n"
                "    sizeof(prsk_freetype_syms) / sizeof(prsk_freetype_syms[0]);\n\n")
        f.write("#endif /* PRSK_FREETYPE_SYMS_H */\n")
    print("gen_freetype_syms: %d FreeType entry points" % len(names), file=sys.stderr)


if __name__ == "__main__":
    main()
