#!/usr/bin/env python3
"""gen_syscalls.py - generate the syscall number space and its two consumers.

The syscall NUMBERS are the one part of the contract we are free to invent
(docs/04: abi/syscall_numbers.h "our own numbers"): Windows renumbers its
SSDT every release, so nothing above ntdll may depend on the values, and our
own ntdll-stub layer (tests/ntapi/syscall/ now, user/ntdll-stubs at M7) is
the only caller. What must NOT drift is the agreement between the user-mode
stubs and the kernel table — so all three files come from the single list
below and are never edited by hand:

    abi/syscall_numbers.h            NTSYS_* number macros (kernel + user)
    kernel/syscall/table.inc         X-macro feeding kernel/syscall/table.c
    tests/ntapi/syscall/syscall_stubs.S  user-mode Nt* stubs (SysV in, syscall out)

Regenerate (also run by `make gen-abi`):

    python3 tools/gen_syscalls.py

Argument counts are those of the Wine winternl.h prototypes the abi/ headers
carry; tools/gen_abi.py is the authority for the signatures themselves.
"""

from pathlib import Path

# (name, argument count). Order defines the numbers - append only within a
# milestone; renumbering is free until the M7 stub generator ships, then
# append-only forever.
SYSCALLS = [
    # M3 Ob surface, reachable from user mode as of M4
    ("NtClose", 1),
    ("NtDuplicateObject", 7),
    ("NtMakeTemporaryObject", 1),
    ("NtCreateEvent", 5),
    ("NtOpenEvent", 3),
    ("NtSetEvent", 2),
    ("NtResetEvent", 2),
    ("NtClearEvent", 1),
    ("NtPulseEvent", 2),
    ("NtQueryEvent", 5),
    ("NtCreateMutant", 4),
    ("NtOpenMutant", 3),
    ("NtReleaseMutant", 2),
    ("NtQueryMutant", 5),
    ("NtCreateSemaphore", 5),
    ("NtOpenSemaphore", 3),
    ("NtReleaseSemaphore", 3),
    ("NtQuerySemaphore", 5),
    ("NtWaitForSingleObject", 3),
    ("NtWaitForMultipleObjects", 5),
    ("NtCreateDirectoryObject", 3),
    ("NtOpenDirectoryObject", 3),
    ("NtCreateSymbolicLinkObject", 4),
    ("NtOpenSymbolicLinkObject", 3),
    ("NtQuerySymbolicLinkObject", 3),
    # M4 Mm + Ps surface
    ("NtAllocateVirtualMemory", 6),
    ("NtFreeVirtualMemory", 4),
    ("NtQueryVirtualMemory", 6),
    ("NtTerminateProcess", 2),
    ("NtDisplayString", 1),
]

BANNER = """\
/* {name} - GENERATED by tools/gen_syscalls.py.
 * DO NOT EDIT BY HAND. The syscall list lives in tools/gen_syscalls.py;
 * regenerate with:
 *     python3 tools/gen_syscalls.py
 */
"""


def gen_numbers() -> str:
    lines = [f"#define NTSYS_{name} {number}" for number, (name, _) in enumerate(SYSCALLS)]
    return (
        BANNER.format(name="abi/syscall_numbers.h")
        + "#ifndef PROSKRNL_ABI_SYSCALL_NUMBERS_H\n"
        + "#define PROSKRNL_ABI_SYSCALL_NUMBERS_H\n\n"
        + "\n".join(lines)
        + f"\n\n#define NTSYS_SYSCALL_COUNT {len(SYSCALLS)}\n"
        + "\n#endif /* PROSKRNL_ABI_SYSCALL_NUMBERS_H */\n"
    )


def gen_table_inc() -> str:
    lines = [f"KI_SYSCALL({name}, {argc})" for name, argc in SYSCALLS]
    return (
        BANNER.format(name="kernel/syscall/table.inc")
        + "/* X-macro: KI_SYSCALL(name, argumentCount), in syscall-number order.\n"
        + " * kernel/syscall/table.c defines KI_SYSCALL and includes this file. */\n"
        + "\n".join(lines)
        + "\n"
    )


def gen_stubs() -> str:
    stubs = []
    for number, (name, _) in enumerate(SYSCALLS):
        stubs.append(
            f"    .global {name}\n"
            f"{name}:\n"
            f"    mov %rcx, %r10\n"
            f"    mov ${number}, %eax\n"
            f"    syscall\n"
            f"    ret\n"
        )
    return (
        BANNER.format(name="tests/ntapi/syscall/syscall_stubs.S")
        + "/* User-mode Nt* stubs for the proskrnl ntapi target and the M4 flat-\n"
        + " * binary clients (docs/14). Calling convention: the stub is an\n"
        + " * ordinary SysV C function; the kernel reads arguments 1-6 from\n"
        + " * rdi/rsi/rdx/r10/r8/r9 (rcx is clobbered by the syscall instruction,\n"
        + " * so it moves to r10 - the same dance the NT x64 convention does) and\n"
        + " * argument 7 from the caller's stack at [rsp+8]. Number in eax;\n"
        + " * NTSTATUS back in eax. */\n"
        + "    .section .text\n"
        + "\n".join(stubs)
        + '\n    .section .note.GNU-stack, "", @progbits\n'
    )


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    for path, text in [
        (root / "abi/syscall_numbers.h", gen_numbers()),
        (root / "kernel/syscall/table.inc", gen_table_inc()),
        (root / "tests/ntapi/syscall/syscall_stubs.S", gen_stubs()),
    ]:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"gen_syscalls: wrote {path.relative_to(root)}")


if __name__ == "__main__":
    main()
