/*
 * sem_file/short_names.c — the 8.3 SHORT NAME a directory enumeration
 * reports, and the second matching leg it gives the mask.
 *
 * Convicted by the winetest gate three ways: ntdll:directory asserts
 * ShortName is non-empty (directory.c:654) and then masks by the value it
 * got back (:661-675); its mask truth table has nine cells — {`<`, `<"`,
 * `<""`} x {`.a`, `..a`, `.aa`} — that no long-name matcher can satisfy;
 * and kernel32:path's eleven failures are all GetShortPathName, which is
 * kernelbase reading exactly this field (dlls/kernelbase/file.c
 * GetShortPathNameW -> wfd.cAlternateFileName).
 *
 * NO VALUE HERE IS PINNABLE, AND THAT IS THE POINT OF THE SHAPE BELOW.
 * The oracle runs on a unix filesystem and SYNTHESIZES a short name by
 * hashing the long one; proskrnl runs on FAT32 and reports the name the
 * volume actually stored. `longfilename.tmp` is `LONG~TIZ.TMP` on one and
 * `LONGFI~1.TMP` on the other. Every assertion here is therefore about a
 * PROPERTY — is it empty, is it 8.3-shaped, does it match the same entry —
 * and never about a string.
 *
 * ONE PROPERTY OF THE VALUE IS SHARED, AND SECTIONS 7-8 PIN IT. This file
 * used to say the value-dependent truth-table cells "can only ever be
 * checked by the winetest pair itself". That is too strong: the two runners
 * generate completely different STRINGS but agree exactly on whether the
 * generated name carries an EXTENSION, and that one bit is what decides
 * every DOS_STAR cell — a short name with a dot can never be matched by a
 * trailing `<`. Asserting the bit, and the mask answer it produces, is
 * runner-independent; only the characters are not.
 *
 * The one exact rule that IS shared: a short name is reported only when the
 * long name is not already a legal 8.3 name. Both runners suppress it on
 * the same predicate, so the empty/non-empty split can be asserted per
 * name. It is also the assertion that kills the tempting wrong
 * implementation "report whatever the volume stored": see kLegal83 below,
 * where a lower-case name has a stored short entry on FAT and must still
 * report nothing.
 *
 * Fixture note: every file is created by this test. The boot volume's own
 * entries were generated by the image builder, not by the FAT driver, so
 * their short names follow no rule this test may assume.
 *
 * Oracle-first (G5).
 */
#include "util.h"

static UCHAR dirBuffer[8192];

/* Names whose long form is ALREADY a legal 8.3 name: ShortName must be
 * empty. <= 8 base units, <= 3 extension units, at most one dot.
 *
 * `lower.txt` is in this list, and it is the most valuable entry in the
 * test. MEASURED on the oracle: it reports NO short name for it, so the
 * legality predicate is CASE-INSENSITIVE — lower case does not make a name
 * illegal. That is the opposite of what the FAT driver's storage rule says,
 * and rightly so: FAT rejects lower case because it cannot store it in a
 * bare 8.3 entry, which is a question about the disk, not about the name.
 * `lower.txt` therefore HAS a stored short entry on proskrnl and must still
 * report an empty ShortName. An implementation that reports whatever the
 * volume stored passes every other assertion here and fails this one. */
static const WCHAR *const kLegal83[] = {W("ABC.TXT"), W("EA"), W("N.TMP"), W("lower.txt")};

/* Names that are not: ShortName must be non-empty. */
static const WCHAR *const kNeedsShort[] = {
    W("longfilename.tmp"), /* too long */
    W("two.dots.here"),    /* more than one dot */
    W("has space.txt"),    /* a space in the base */
};

/* Find one entry by long name; returns its ShortName length in bytes, or
 * 0xFFFF when the entry was not listed at all. */
static USHORT short_name_of(HANDLE dir, const WCHAR *want, WCHAR shortOut[13])
{
    IO_STATUS_BLOCK iosb;
    NTSTATUS status;
    unsigned wantUnits = 0;

    while (want[wantUnits])
        wantUnits++;

    status = NtQueryDirectoryFile(dir, NULL, NULL, NULL, &iosb, dirBuffer, sizeof(dirBuffer),
                                  FileBothDirectoryInformation, FALSE, NULL, TRUE);
    while (NT_SUCCESS(status))
    {
        ULONG offset = 0;
        for (;;)
        {
            FILE_BOTH_DIRECTORY_INFORMATION *entry =
                (FILE_BOTH_DIRECTORY_INFORMATION *)(dirBuffer + offset);
            if (entry->FileNameLength == wantUnits * sizeof(WCHAR))
            {
                unsigned i = 0;
                while (i < wantUnits)
                {
                    WCHAR a = entry->FileName[i], b = want[i];
                    if (a >= 'a' && a <= 'z')
                        a = (WCHAR)(a - 'a' + 'A');
                    if (b >= 'a' && b <= 'z')
                        b = (WCHAR)(b - 'a' + 'A');
                    if (a != b)
                        break;
                    i++;
                }
                if (i == wantUnits)
                {
                    USHORT bytes = entry->ShortNameLength;
                    for (unsigned j = 0; j < 12 && j * sizeof(WCHAR) < bytes; j++)
                        shortOut[j] = entry->ShortName[j];
                    shortOut[bytes / sizeof(WCHAR)] = 0;
                    return bytes;
                }
            }
            if (entry->NextEntryOffset == 0)
                break;
            offset += entry->NextEntryOffset;
        }
        status = NtQueryDirectoryFile(dir, NULL, NULL, NULL, &iosb, dirBuffer, sizeof(dirBuffer),
                                      FileBothDirectoryInformation, FALSE, NULL, FALSE);
    }
    return 0xFFFF;
}

/* Enumerate under `mask` and report how many entries came back, plus the
 * long name of the last one. */
static unsigned count_under_mask(HANDLE dir, const WCHAR *maskText, unsigned maskUnits,
                                 WCHAR longOut[64])
{
    IO_STATUS_BLOCK iosb;
    UNICODE_STRING mask;
    unsigned count = 0;
    NTSTATUS status;

    mask.Buffer = (PWSTR)maskText;
    mask.Length = (USHORT)(maskUnits * sizeof(WCHAR));
    mask.MaximumLength = mask.Length;
    longOut[0] = 0;

    status = NtQueryDirectoryFile(dir, NULL, NULL, NULL, &iosb, dirBuffer, sizeof(dirBuffer),
                                  FileBothDirectoryInformation, TRUE, &mask, TRUE);
    while (NT_SUCCESS(status))
    {
        FILE_BOTH_DIRECTORY_INFORMATION *entry = (FILE_BOTH_DIRECTORY_INFORMATION *)dirBuffer;
        unsigned units = entry->FileNameLength / sizeof(WCHAR);
        count++;
        if (units < 63)
        {
            for (unsigned i = 0; i < units; i++)
                longOut[i] = entry->FileName[i];
            longOut[units] = 0;
        }
        status = NtQueryDirectoryFile(dir, NULL, NULL, NULL, &iosb, dirBuffer, sizeof(dirBuffer),
                                      FileBothDirectoryInformation, TRUE, NULL, FALSE);
    }
    return count;
}

/* Enumerate under `mask` and report whether `want` was among the entries. */
static int mask_finds(HANDLE dir, const WCHAR *maskText, const WCHAR *want)
{
    IO_STATUS_BLOCK iosb;
    UNICODE_STRING mask;
    unsigned maskUnits = 0, wantUnits = 0;
    NTSTATUS status;

    while (maskText[maskUnits])
        maskUnits++;
    while (want[wantUnits])
        wantUnits++;
    mask.Buffer = (PWSTR)maskText;
    mask.Length = (USHORT)(maskUnits * sizeof(WCHAR));
    mask.MaximumLength = mask.Length;

    status = NtQueryDirectoryFile(dir, NULL, NULL, NULL, &iosb, dirBuffer, sizeof(dirBuffer),
                                  FileBothDirectoryInformation, TRUE, &mask, TRUE);
    while (NT_SUCCESS(status))
    {
        FILE_BOTH_DIRECTORY_INFORMATION *entry = (FILE_BOTH_DIRECTORY_INFORMATION *)dirBuffer;
        if (entry->FileNameLength == wantUnits * sizeof(WCHAR) &&
            memcmp(entry->FileName, want, wantUnits * sizeof(WCHAR)) == 0)
            return 1;
        status = NtQueryDirectoryFile(dir, NULL, NULL, NULL, &iosb, dirBuffer, sizeof(dirBuffer),
                                      FileBothDirectoryInformation, TRUE, NULL, FALSE);
    }
    return 0;
}

/* Does the reported short name carry an extension? The two ways there is no
 * answer are kept apart, because they are different defects: -1 is "the entry
 * reported no alias", -2 is "the entry was not listed at all". */
static int short_name_has_dot(HANDLE dir, const WCHAR *want)
{
    WCHAR shortName[13];
    USHORT bytes = short_name_of(dir, want, shortName);

    if (bytes == 0xFFFF)
        return -2;
    if (bytes == 0)
        return -1;
    for (unsigned i = 0; i < bytes / sizeof(WCHAR); i++)
        if (shortName[i] == '.')
            return 1;
    return 0;
}

static int same_name(const WCHAR *a, const WCHAR *b)
{
    for (unsigned i = 0;; i++)
    {
        WCHAR x = a[i], y = b[i];
        if (x >= 'a' && x <= 'z')
            x = (WCHAR)(x - 'a' + 'A');
        if (y >= 'a' && y <= 'z')
            y = (WCHAR)(y - 'a' + 'A');
        if (x != y)
            return 0;
        if (x == 0)
            return 1;
    }
}

START_TEST(short_names)
{
    IO_STATUS_BLOCK iosb;
    NTSTATUS status;
    HANDLE dir, scratch;
    WCHAR shortName[13], other[13], longName[64];

    dir = open_test_dir(W("\\??\\C:\\prstest\\shortnm"));
    ok(dir != NULL, "test dir");
    if (dir == NULL)
        return;

    for (unsigned i = 0; i < 4; i++)
        scrub_file(dir, kLegal83[i]);
    for (unsigned i = 0; i < 3; i++)
        scrub_file(dir, kNeedsShort[i]);
    for (unsigned i = 0; i < 4; i++)
    {
        status = open_file(&scratch, dir, kLegal83[i], FILE_GENERIC_WRITE | SYNCHRONIZE,
                           FILE_SHARE_READ | FILE_SHARE_WRITE, FILE_CREATE, 0, &iosb);
        ok(status == STATUS_SUCCESS, "create an 8.3-legal file -> %08lx", (unsigned long)status);
        if (NT_SUCCESS(status))
            NtClose(scratch);
    }
    for (unsigned i = 0; i < 3; i++)
    {
        status = open_file(&scratch, dir, kNeedsShort[i], FILE_GENERIC_WRITE | SYNCHRONIZE,
                           FILE_SHARE_READ | FILE_SHARE_WRITE, FILE_CREATE, 0, &iosb);
        ok(status == STATUS_SUCCESS, "create a long-named file -> %08lx", (unsigned long)status);
        if (NT_SUCCESS(status))
            NtClose(scratch);
    }

    /* --- 1. the empty/non-empty split, per name --------------------------- */
    for (unsigned i = 0; i < 4; i++)
    {
        USHORT bytes = short_name_of(dir, kLegal83[i], shortName);
        ok(bytes == 0, "8.3-legal name #%u reported a %u-byte ShortName", i, (unsigned)bytes);
    }
    for (unsigned i = 0; i < 3; i++)
    {
        USHORT bytes = short_name_of(dir, kNeedsShort[i], shortName);
        ok(bytes != 0 && bytes != 0xFFFF, "non-8.3 name #%u reported a %u-byte ShortName", i,
           (unsigned)bytes);
    }

    /* --- 2. the shape of a reported short name ----------------------------
     * At most 12 units, one dot at most, base 1-8 and extension 1-3, and
     * never lower case. Holds on both runners: the oracle upper-cases its
     * hashed name, FAT stores 8.3 upper-case by construction. */
    {
        USHORT bytes = short_name_of(dir, kNeedsShort[0], shortName);
        unsigned units = bytes / sizeof(WCHAR), dots = 0, base = 0, ext = 0;
        ok(units >= 1 && units <= 12, "ShortName is %u units", units);
        /* A minimum WIDTH, and the number is the widest both runners can
         * agree on. MEASURED: the oracle's names are >= 8 units (it hashes
         * the long name into a full 8-character base); proskrnl's FAT names
         * are numeric-tail names and reach only 4. Four is what
         * ntdll:directory's table actually requires — a mask of three
         * DOS_QMs must not match any short name — so it is what is pinned. */
        ok(units >= 4, "ShortName is only %u units wide", units);
        for (unsigned i = 0; i < units; i++)
        {
            WCHAR c = shortName[i];
            ok(!(c >= 'a' && c <= 'z'), "ShortName unit %u is lower case", i);
            if (c == '.')
                dots++;
            else if (dots == 0)
                base++;
            else
                ext++;
        }
        ok(dots <= 1, "ShortName has %u dots", dots);
        ok(base >= 1 && base <= 8, "ShortName base is %u units", base);
        ok(dots == 0 || (ext >= 1 && ext <= 3), "ShortName extension is %u units", ext);
    }

    /* --- 3. the mask matches the short name, and the LONG name comes back --
     * This is the leg the nine truth-table cells need, and the one
     * GetShortPathName depends on. Value-independent: whatever the short
     * name is on this runner, masking by it must find that entry, and the
     * entry must still be identified by its long name. */
    {
        USHORT bytes = short_name_of(dir, kNeedsShort[0], shortName);
        unsigned units = bytes / sizeof(WCHAR);
        unsigned found = count_under_mask(dir, shortName, units, longName);
        ok(found == 1, "masking by the short name found %u entries", found);
        ok(same_name(longName, kNeedsShort[0]), "the entry came back under its short name");
    }

    /* --- 4. a WILDCARD over the short name, so an exact-string
     * implementation does not pass by accident. Replace the last unit with
     * '?': that mask still cannot match the long name, whose tail is
     * `e.tmp`, but must match the short one. */
    {
        USHORT bytes = short_name_of(dir, kNeedsShort[0], shortName);
        unsigned units = bytes / sizeof(WCHAR);
        unsigned found;
        shortName[units - 1] = '?';
        found = count_under_mask(dir, shortName, units, longName);
        ok(found == 1, "a wildcarded short name found %u entries", found);
        ok(same_name(longName, kNeedsShort[0]), "and it was still the same entry");
    }

    /* --- 5. two different long names get two different short names -------- */
    {
        USHORT a = short_name_of(dir, kNeedsShort[0], shortName);
        USHORT b = short_name_of(dir, kNeedsShort[1], other);
        ok(a != 0 && b != 0, "both names have short names");
        ok(!same_name(shortName, other), "two entries share one short name");
    }

    /* --- 6. FileIdBothDirectoryInformation agrees with FileBoth ------------
     * Both classes carry the field; filling one and forgetting the other is
     * the classic miss. Checked by length, which is value-independent. */
    {
        USHORT bothBytes = short_name_of(dir, kNeedsShort[0], shortName);
        IO_STATUS_BLOCK io;
        NTSTATUS s = NtQueryDirectoryFile(dir, NULL, NULL, NULL, &io, dirBuffer, sizeof(dirBuffer),
                                          FileIdBothDirectoryInformation, FALSE, NULL, TRUE);
        ok(NT_SUCCESS(s), "IdBoth enumeration -> %08lx", (unsigned long)s);
        if (NT_SUCCESS(s))
        {
            ULONG offset = 0;
            int seen = 0;
            for (;;)
            {
                FILE_ID_BOTH_DIRECTORY_INFORMATION *e =
                    (FILE_ID_BOTH_DIRECTORY_INFORMATION *)(dirBuffer + offset);
                if (e->FileNameLength == 16 * sizeof(WCHAR) &&
                    (e->FileName[0] == 'l' || e->FileName[0] == 'L'))
                {
                    ok(e->ShortNameLength == bothBytes, "IdBoth ShortNameLength %u != Both's %u",
                       (unsigned)e->ShortNameLength, (unsigned)bothBytes);
                    seen = 1;
                }
                if (e->NextEntryOffset == 0)
                    break;
                offset += e->NextEntryOffset;
            }
            ok(seen, "the long-named entry appeared in the IdBoth enumeration");
        }
    }

    for (unsigned i = 0; i < 4; i++)
        scrub_file(dir, kLegal83[i]);
    for (unsigned i = 0; i < 3; i++)
        scrub_file(dir, kNeedsShort[i]);
    NtClose(dir);

    /* --- 7-8. WHICH LEADING RUN IS STRIPPED before the extension is picked -
     * Its own directory, because the assertions below are about the whole
     * result set under a mask and the fixture above would drown them.
     *
     * The subject: a name that is not 8.3-legal gets a generated alias, and
     * the generator has to decide where the alias's extension separator is.
     * Both runners strip a leading run of DOTS before looking for the last
     * dot, so `.a`, `..a` and `.aaa` alias to a base with NO extension —
     * which is the ONLY reason a trailing DOS_STAR can reach them, since
     * their long names all still carry a dot. A leading SPACE is not part of
     * that run: ` .a` keeps its `.a`, aliases WITH an extension, and is
     * therefore invisible to the same mask.
     *
     * ` .a` versus `.a` is the entire content of the item. An implementation
     * that strips leading dots AND spaces answers every other cell of
     * kernel32:file's wildcard table correctly and gets ` .a` wrong in
     * sixteen of them (file.c:3208, "found incorrectly ' .a'", missed none). */
    {
        static const WCHAR *const kDotted[] = {
            W(".a"),   /* leading dots only: alias has no extension */
            W("..a"),  /* a longer leading run, same answer */
            W(".aaa"), /* and with a wider base */
            W(".a.a"), /* an EMBEDDED dot survives the strip: alias has one */
            W(" .a"),  /* the discriminator: a space is not a leading dot */
        };
        HANDLE dotDir = open_test_dir(W("\\??\\C:\\prstest\\shortdot"));

        ok(dotDir != NULL, "dotted-name test dir");
        if (dotDir == NULL)
            return;
        for (unsigned i = 0; i < 5; i++)
            scrub_file(dotDir, kDotted[i]);
        for (unsigned i = 0; i < 5; i++)
        {
            status = open_file(&scratch, dotDir, kDotted[i], FILE_GENERIC_WRITE | SYNCHRONIZE,
                               FILE_SHARE_READ | FILE_SHARE_WRITE, FILE_CREATE, 0, &iosb);
            ok(status == STATUS_SUCCESS, "create dotted fixture #%u -> %08lx", i,
               (unsigned long)status);
            if (NT_SUCCESS(status))
                NtClose(scratch);
        }

        /* 7. the mechanism: does the alias carry an extension at all. The
         * message prints the raw answer because "no alias reported" (-1) and
         * "entry not listed" (-2) are different defects from the wrong
         * split, and asserting `== 0` cannot tell them apart on its own.
         *
         * This section must stay AHEAD of section 8: the mask a query binds
         * lives on the HANDLE (docs/03, "NtQueryDirectoryFile mask
         * binding"), so once section 8 has masked `dotDir` a NULL-mask
         * enumeration here would silently reuse `a<` instead of listing
         * everything. */
        {
            static const int kWantsDot[] = {0, 0, 0, 1, 1};
            for (unsigned i = 0; i < 5; i++)
            {
                int has = short_name_has_dot(dotDir, kDotted[i]);
                ok(has == kWantsDot[i], "dotted fixture #%u: alias-has-extension %d, wanted %d", i,
                   has, kWantsDot[i]);
            }
        }

        /* 8. the observable it decides. `<` alone is what kernelbase's
         * fixup_mask emits for the DOS glob `*.` (dlls/kernelbase/file.c:
         * strip the trailing dot, then rewrite the trailing `*`), so this is
         * the shape every "list the extensionless files" call arrives as. */
        ok(mask_finds(dotDir, W("<"), kDotted[0]), "`<` missed `.a`");
        ok(mask_finds(dotDir, W("<"), kDotted[1]), "`<` missed `..a`");
        ok(mask_finds(dotDir, W("<"), kDotted[2]), "`<` missed `.aaa`");
        ok(!mask_finds(dotDir, W("<"), kDotted[3]), "`<` found `.a.a`");
        ok(!mask_finds(dotDir, W("<"), kDotted[4]), "`<` found ` .a`");

        /* The same split one character in, which is what `a*.` becomes. It
         * is not redundant: it can only be answered through the alias, since
         * no long name here begins with `a`. */
        ok(mask_finds(dotDir, W("a<"), kDotted[0]), "`a<` missed `.a`");
        ok(mask_finds(dotDir, W("a<"), kDotted[2]), "`a<` missed `.aaa`");
        ok(!mask_finds(dotDir, W("a<"), kDotted[4]), "`a<` found ` .a`");

        for (unsigned i = 0; i < 5; i++)
            scrub_file(dotDir, kDotted[i]);
        NtClose(dotDir);
    }
}
