/* abi/nsi.h - GENERATED by tools/gen_abi.py from wine/include/{wine/nsi.h,netiodef.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NSI_H
#define PROSKRNL_ABI_NSI_H

#include "abi/ntdef.h"
#include "abi/ntioapi.h" /* CTL_CODE, FILE_DEVICE_NETWORK */
#include "abi/ntpebteb.h" /* GUID */
#include "abi/ntseapi.h" /* LUID */

/* Win32 alias scaffold for the extracted structs; sizes pinned. */
typedef unsigned int UINT;
_Static_assert(sizeof(UINT) == 4, "Win32: UINT is 4 bytes");

/* Extracted verbatim from wine/include/netiodef.h. */
typedef enum {
    MIT_GUID = 1,
    MIT_IF_LUID
} NPI_MODULEID_TYPE;

typedef struct {
    USHORT Length;
    NPI_MODULEID_TYPE Type;
    union
    {
        GUID Guid;
        LUID IfLuid;
    };
} NPI_MODULEID;

/* The Nsi ioctl surface, extracted from wine/include/wine/nsi.h. */
#define IOCTL_NSIPROXY_WINE_ENUMERATE_ALL CTL_CODE(FILE_DEVICE_NETWORK, 0x400, METHOD_BUFFERED, 0)
#define IOCTL_NSIPROXY_WINE_GET_ALL_PARAMETERS CTL_CODE(FILE_DEVICE_NETWORK, 0x401, METHOD_BUFFERED, 0)
#define IOCTL_NSIPROXY_WINE_GET_PARAMETER CTL_CODE(FILE_DEVICE_NETWORK, 0x402, METHOD_BUFFERED, 0)
#define IOCTL_NSIPROXY_WINE_ICMP_ECHO CTL_CODE(FILE_DEVICE_NETWORK, 0x403, METHOD_BUFFERED, 0)
#define IOCTL_NSIPROXY_WINE_CHANGE_NOTIFICATION CTL_CODE(FILE_DEVICE_NETWORK, 0x404, METHOD_BUFFERED, 0)

#define NSI_PARAM_TYPE_RW 0
#define NSI_PARAM_TYPE_DYNAMIC 1
#define NSI_PARAM_TYPE_STATIC 2

/* The NSI table ids the consumers name, extracted from
 * wine/include/wine/nsi.h. */
#define NSI_NDIS_IFINFO_TABLE 0
#define NSI_NDIS_INDEX_LUID_TABLE 2
#define NSI_IP_COMPARTMENT_TABLE 2
#define NSI_IP_ICMPSTATS_TABLE 3
#define NSI_IP_IPSTATS_TABLE 6
#define NSI_IP_INTERFACE_TABLE 7
#define NSI_IP_UNICAST_TABLE 10
#define NSI_IP_NEIGHBOUR_TABLE 11
#define NSI_IP_FORWARD_TABLE 16

/* The request shapes, extracted verbatim from wine/include/wine/nsi.h. */
struct nsiproxy_enumerate_all
{
    NPI_MODULEID module;
    UINT first_arg;
    UINT second_arg;
    UINT table;
    UINT key_size;
    UINT rw_size;
    UINT dynamic_size;
    UINT static_size;
    UINT count;
};

struct nsiproxy_get_all_parameters
{
    NPI_MODULEID module;
    UINT first_arg;
    UINT table;
    UINT key_size;
    UINT rw_size;
    UINT dynamic_size;
    UINT static_size;
    BYTE key[1]; /* key_size */
};

struct nsiproxy_get_parameter
{
    NPI_MODULEID module;
    UINT first_arg;
    UINT table;
    UINT key_size;
    UINT param_type;
    UINT data_offset;
    BYTE key[1]; /* key_size */
};

struct nsiproxy_request_notification
{
    NPI_MODULEID module;
    UINT table;
};

#endif /* PROSKRNL_ABI_NSI_H */
