/* abi/ntdef.h - GENERATED by tools/gen_abi.py from wine/include/{ntdef.h,winnt.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTDEF_H
#define PROSKRNL_ABI_NTDEF_H

/* Base NT types (LLP64). The typedef shapes are fixed scaffold; the sizes are
 * pinned by the static_asserts below, so this cannot drift silently. */
typedef signed char CCHAR;
typedef unsigned char UCHAR;
typedef unsigned char BOOLEAN;
typedef short CSHORT;
typedef unsigned short USHORT;
typedef int LONG;
typedef unsigned int ULONG;
typedef long long LONGLONG;
typedef unsigned long long ULONGLONG;
typedef void *PVOID;
typedef ULONGLONG ULONG_PTR;

typedef LONG NTSTATUS;
typedef LONG KPRIORITY;
typedef CCHAR KPROCESSOR_MODE;

#ifndef TRUE
#define TRUE 1
#define FALSE 0
#endif

#define NT_SUCCESS(status) (((NTSTATUS)(status)) >= 0)

typedef union {
    struct
    {
        ULONG LowPart;
        LONG HighPart;
    } u;
    LONGLONG QuadPart;
} LARGE_INTEGER, *PLARGE_INTEGER;

typedef union {
    struct
    {
        ULONG LowPart;
        ULONG HighPart;
    } u;
    ULONGLONG QuadPart;
} ULARGE_INTEGER, *PULARGE_INTEGER;

typedef struct LIST_ENTRY {
    struct LIST_ENTRY *Flink;
    struct LIST_ENTRY *Blink;
} LIST_ENTRY, *PLIST_ENTRY;

_Static_assert(sizeof(LONG) == 4, "LLP64: LONG is 4 bytes");
_Static_assert(sizeof(ULONGLONG) == 8, "LLP64: ULONGLONG is 8 bytes");
_Static_assert(sizeof(PVOID) == 8, "x86_64: pointers are 8 bytes");
_Static_assert(sizeof(LARGE_INTEGER) == 8, "LARGE_INTEGER is 8 bytes");
_Static_assert(sizeof(LIST_ENTRY) == 16, "LIST_ENTRY is two pointers");
_Static_assert(sizeof(BOOLEAN) == 1, "BOOLEAN is 1 byte");

/* Contract enums, extracted verbatim from wine/include/ntdef.h. */
typedef enum {
    NotificationEvent,
    SynchronizationEvent
} EVENT_TYPE;

typedef enum {
    NotificationTimer,
    SynchronizationTimer
} TIMER_TYPE;

typedef enum {
    WaitAll,
    WaitAny,
    WaitNotification
} WAIT_TYPE;

/* Extracted from wine/include/winnt.h. */
#define MAXIMUM_WAIT_OBJECTS 64

#endif /* PROSKRNL_ABI_NTDEF_H */
