/* abi/ntdef.h - GENERATED by tools/gen_abi.py from wine/include/{ntdef.h,winnt.h,winternl.h,ddk/wdm.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTDEF_H
#define PROSKRNL_ABI_NTDEF_H

/* Base NT types (LLP64). The typedef shapes are fixed scaffold; the sizes are
 * pinned by the static_asserts below, so this cannot drift silently. */
typedef char CHAR;
typedef char *PCHAR;
typedef signed char CCHAR;
typedef unsigned char UCHAR;
typedef unsigned char BOOLEAN;
typedef BOOLEAN *PBOOLEAN;
typedef short CSHORT;
typedef unsigned short USHORT;
typedef int LONG;
typedef unsigned int ULONG;
typedef long long LONGLONG;
typedef unsigned long long ULONGLONG;
typedef void *PVOID;
typedef void *PVOID64; /* x86_64: identical to PVOID (winnt.h `typedef VOID *PVOID64`) */
typedef ULONGLONG ULONG_PTR;
typedef ULONG_PTR *PULONG_PTR;

typedef LONG *PLONG;
typedef ULONG *PULONG;
typedef unsigned short WCHAR, *PWCHAR, *PWSTR;
typedef const WCHAR *PCWSTR;
typedef void *HANDLE;
typedef HANDLE *PHANDLE;
typedef ULONG ACCESS_MASK;

/* Win32-flavoured aliases some contract structs/prototypes are written in
 * (Wine's winnt.h MEMORY_BASIC_INFORMATION, winternl.h Nt* prototypes). */
typedef ULONG DWORD;
typedef PVOID LPVOID;
typedef const void *LPCVOID;
typedef ULONG_PTR SIZE_T, *PSIZE_T;
/* KAFFINITY lives here rather than in the ntpebteb scaffold because BOTH
 * ntpebteb.h (TEB/PEB affinity fields) and ntpsapi.h (GROUP_AFFINITY, for
 * NtQueryInformationThread's ThreadGroupInformation) need it, and
 * ntpebteb.h already includes ntpsapi.h — so the reverse include would
 * cycle. ntdef.h is the header both of them already include. */
typedef ULONG_PTR KAFFINITY;

/* Win32 base names used verbatim inside extracted structs (winnt.h). */
typedef unsigned short WORD;
typedef unsigned char BYTE;

/* Anonymous-union/-struct spellings used verbatim inside extracted structs. */
#define DUMMYUNIONNAME
#define DUMMYUNIONNAME2
#define DUMMYUNIONNAME3
#define DUMMYSTRUCTNAME
#define DUMMYSTRUCTNAME2

/* winnt.h: `#define VOID void`, used verbatim in extracted prototypes. */
#define VOID void

typedef LONG NTSTATUS;
typedef LONG KPRIORITY;
typedef CCHAR KPROCESSOR_MODE;

#ifndef TRUE
#define TRUE 1
#define FALSE 0
#endif

#define NT_SUCCESS(status) (((NTSTATUS)(status)) >= 0)

typedef union {
    struct
    {
        ULONG LowPart;
        LONG HighPart;
    } u;
    LONGLONG QuadPart;
} LARGE_INTEGER, *PLARGE_INTEGER;

typedef union {
    struct
    {
        ULONG LowPart;
        ULONG HighPart;
    } u;
    ULONGLONG QuadPart;
} ULARGE_INTEGER, *PULARGE_INTEGER;

typedef struct LIST_ENTRY {
    struct LIST_ENTRY *Flink;
    struct LIST_ENTRY *Blink;
} LIST_ENTRY, *PLIST_ENTRY;

_Static_assert(sizeof(LONG) == 4, "LLP64: LONG is 4 bytes");
_Static_assert(sizeof(ULONGLONG) == 8, "LLP64: ULONGLONG is 8 bytes");
_Static_assert(sizeof(PVOID) == 8, "x86_64: pointers are 8 bytes");
_Static_assert(sizeof(PVOID64) == 8, "x86_64: PVOID64 is 8 bytes");
_Static_assert(sizeof(LARGE_INTEGER) == 8, "LARGE_INTEGER is 8 bytes");
_Static_assert(sizeof(LIST_ENTRY) == 16, "LIST_ENTRY is two pointers");
_Static_assert(sizeof(BOOLEAN) == 1, "BOOLEAN is 1 byte");
_Static_assert(sizeof(WCHAR) == 2, "WCHAR is UTF-16");
_Static_assert(sizeof(HANDLE) == 8, "x86_64: HANDLE is pointer-sized");
_Static_assert(sizeof(DWORD) == 4, "LLP64: DWORD is 4 bytes");
_Static_assert(sizeof(SIZE_T) == 8, "x86_64: SIZE_T is 8 bytes");
_Static_assert(sizeof(WORD) == 2, "Win32: WORD is 2 bytes");
_Static_assert(sizeof(BYTE) == 1, "Win32: BYTE is 1 byte");

/* Contract enums, extracted verbatim from wine/include/ntdef.h. */
typedef enum {
    NotificationEvent,
    SynchronizationEvent
} EVENT_TYPE;

typedef enum {
    NotificationTimer,
    SynchronizationTimer
} TIMER_TYPE;

typedef enum {
    WaitAll,
    WaitAny,
    WaitNotification
} WAIT_TYPE;

/* Extracted from wine/include/winnt.h. */
#define MAXIMUM_WAIT_OBJECTS 64

/* Ob name/handle structs, extracted verbatim from wine/include/winternl.h;
 * the static_asserts below pin the x64 layout the boundary depends on. */
typedef struct {
  USHORT Length;        /* bytes */
  USHORT MaximumLength; /* bytes */
  PWSTR  Buffer;
} UNICODE_STRING, *PUNICODE_STRING;

typedef struct {
  USHORT Length;
  USHORT MaximumLength;
  PCHAR Buffer;
} STRING, *PSTRING;

/* winternl.h's own aliases for the same struct. */
typedef STRING OEM_STRING;
typedef PSTRING POEM_STRING;

typedef struct {
  ULONG Length;
  HANDLE RootDirectory;
  PUNICODE_STRING ObjectName;
  ULONG Attributes;
  PVOID SecurityDescriptor;       /* type SECURITY_DESCRIPTOR */
  PVOID SecurityQualityOfService; /* type SECURITY_QUALITY_OF_SERVICE */
} OBJECT_ATTRIBUTES, *POBJECT_ATTRIBUTES;

#include <stddef.h>
_Static_assert(sizeof(UNICODE_STRING) == 16, "UNICODE_STRING x64 layout");
_Static_assert(offsetof(UNICODE_STRING, MaximumLength) == 2, "UNICODE_STRING x64 layout");
_Static_assert(offsetof(UNICODE_STRING, Buffer) == 8, "UNICODE_STRING x64 layout");
_Static_assert(sizeof(OBJECT_ATTRIBUTES) == 48, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, RootDirectory) == 8, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, ObjectName) == 16, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, Attributes) == 24, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, SecurityDescriptor) == 32, "OBJECT_ATTRIBUTES x64 layout");
_Static_assert(offsetof(OBJECT_ATTRIBUTES, SecurityQualityOfService) == 40, "OBJECT_ATTRIBUTES x64 layout");

/* Object-attribute flags, extracted from wine/include/winternl.h. */
#define OBJ_PROTECT_CLOSE 0x00000001
#define OBJ_INHERIT 0x00000002
#define OBJ_PERMANENT 0x00000010
#define OBJ_EXCLUSIVE 0x00000020
#define OBJ_CASE_INSENSITIVE 0x00000040
#define OBJ_OPENIF 0x00000080
#define OBJ_OPENLINK 0x00000100
#define OBJ_KERNEL_HANDLE 0x00000200
#define NtCurrentProcess() ((HANDLE)~(ULONG_PTR)0)
#define NtCurrentThread() ((HANDLE)~(ULONG_PTR)1)

/* Access rights, extracted from wine/include/winnt.h. */
#define DELETE 0x00010000
#define READ_CONTROL 0x00020000
#define WRITE_DAC 0x00040000
#define WRITE_OWNER 0x00080000
#define SYNCHRONIZE 0x00100000
#define STANDARD_RIGHTS_REQUIRED 0x000f0000
#define STANDARD_RIGHTS_READ READ_CONTROL
#define STANDARD_RIGHTS_WRITE READ_CONTROL
#define STANDARD_RIGHTS_EXECUTE READ_CONTROL
#define STANDARD_RIGHTS_ALL 0x001f0000
#define SPECIFIC_RIGHTS_ALL 0x0000ffff
#define GENERIC_READ 0x80000000
#define GENERIC_WRITE 0x40000000
#define GENERIC_EXECUTE 0x20000000
#define GENERIC_ALL 0x10000000
#define MAXIMUM_ALLOWED 0x02000000
#define EVENT_QUERY_STATE 0x0001
#define EVENT_MODIFY_STATE 0x0002
#define EVENT_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
#define SEMAPHORE_QUERY_STATE 0x0001
#define SEMAPHORE_MODIFY_STATE 0x0002
#define SEMAPHORE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
#define MUTANT_QUERY_STATE 0x0001
#define MUTANT_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|MUTANT_QUERY_STATE)
#define TIMER_QUERY_STATE 0x0001
#define TIMER_MODIFY_STATE 0x0002
#define TIMER_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
#define DUPLICATE_CLOSE_SOURCE 0x00000001
#define DUPLICATE_SAME_ACCESS 0x00000002
#define DUPLICATE_SAME_ATTRIBUTES 0x00000004

/* Directory/symlink access rights, extracted from wine/include/ddk/wdm.h. */
#define DIRECTORY_QUERY 0x0001
#define DIRECTORY_TRAVERSE 0x0002
#define DIRECTORY_CREATE_OBJECT 0x0004
#define DIRECTORY_CREATE_SUBDIRECTORY 0x0008
#define DIRECTORY_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | 0xF)
#define SYMBOLIC_LINK_QUERY 0x0001
#define SYMBOLIC_LINK_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | 0x1)

#endif /* PROSKRNL_ABI_NTDEF_H */
