/* abi/ntkeapi.h - GENERATED by tools/gen_abi.py from wine/include/{ddk/wdm.h,winnt.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTKEAPI_H
#define PROSKRNL_ABI_NTKEAPI_H

#include "abi/ntdef.h"

typedef ULONGLONG ULONG64;
typedef ULONGLONG DWORD64;

/* Extracted from wine/include/ddk/wdm.h. */
#define PROCESSOR_FEATURE_MAX 64
#define MAXIMUM_XSTATE_FEATURES 64
#define PF_COMPARE_EXCHANGE_DOUBLE 2
#define PF_MMX_INSTRUCTIONS_AVAILABLE 3
#define PF_XMMI_INSTRUCTIONS_AVAILABLE 6
#define PF_3DNOW_INSTRUCTIONS_AVAILABLE 7
#define PF_RDTSC_INSTRUCTION_AVAILABLE 8
#define PF_PAE_ENABLED 9
#define PF_XMMI64_INSTRUCTIONS_AVAILABLE 10
#define PF_SSE_DAZ_MODE_AVAILABLE 11
#define PF_NX_ENABLED 12
#define PF_SSE3_INSTRUCTIONS_AVAILABLE 13
#define PF_COMPARE_EXCHANGE128 14
#define PF_XSAVE_ENABLED 17
#define PF_VIRT_FIRMWARE_ENABLED 21
#define PF_RDWRFSGSBASE_AVAILABLE 22
#define PF_FASTFAIL_AVAILABLE 23
#define PF_RDRAND_INSTRUCTION_AVAILABLE 28
#define PF_RDTSCP_INSTRUCTION_AVAILABLE 32
#define PF_RDPID_INSTRUCTION_AVAILABLE 33
#define PF_MONITORX_INSTRUCTION_AVAILABLE 35
#define PF_SSSE3_INSTRUCTIONS_AVAILABLE 36
#define PF_SSE4_1_INSTRUCTIONS_AVAILABLE 37
#define PF_SSE4_2_INSTRUCTIONS_AVAILABLE 38
#define PF_AVX_INSTRUCTIONS_AVAILABLE 39
#define PF_AVX2_INSTRUCTIONS_AVAILABLE 40
#define PF_AVX512F_INSTRUCTIONS_AVAILABLE 41
#define PF_ERMS_AVAILABLE 42
#define PF_BMI2_INSTRUCTIONS_AVAILABLE 60
#define PF_MOVDIR64B_INSTRUCTION_AVAILABLE 61

typedef enum {
    NtProductWinNt = 1,
    NtProductLanManNt,
    NtProductServer
} NT_PRODUCT_TYPE, *PNT_PRODUCT_TYPE;

typedef enum {
   StandardDesign,
   NEC98x86,
   EndAlternatives
} ALTERNATIVE_ARCHITECTURE_TYPE;

typedef struct {
    ULONG LowPart;
    LONG High1Time;
    LONG High2Time;
} KSYSTEM_TIME, *PKSYSTEM_TIME;

/* Extracted verbatim from wine/include/winnt.h (embedded in
 * KUSER_SHARED_DATA.XState). */
typedef struct {
    ULONG Offset;
    ULONG Size;
} XSTATE_FEATURE, *PXSTATE_FEATURE;

typedef struct {
    ULONG64 EnabledFeatures;
    ULONG64 EnabledVolatileFeatures;
    ULONG Size;
    union
    {
        ULONG ControlFlags;
        struct
        {
            ULONG OptimizedSave : 1;
            ULONG CompactionEnabled : 1;
            ULONG ExtendedFeatureDisable : 1;
        };
    };
    XSTATE_FEATURE Features[MAXIMUM_XSTATE_FEATURES];
    ULONG64 EnabledSupervisorFeatures;
    ULONG64 AlignedFeatures;
    ULONG AllFeatureSize;
    ULONG AllFeatures[MAXIMUM_XSTATE_FEATURES];
    ULONG64 EnabledUserVisibleSupervisorFeatures;
    ULONG64 ExtendedFeatureDisableFeatures;
    ULONG AllNonLargeFeatureSize;
    ULONG Spare;
} XSTATE_CONFIGURATION, *PXSTATE_CONFIGURATION;

typedef struct {
    ULONG TickCountLowDeprecated;                          /* 0x000 */
    ULONG TickCountMultiplier;                             /* 0x004 */
    volatile KSYSTEM_TIME InterruptTime;                   /* 0x008 */
    volatile KSYSTEM_TIME SystemTime;                      /* 0x014 */
    volatile KSYSTEM_TIME TimeZoneBias;                    /* 0x020 */
    USHORT ImageNumberLow;                                 /* 0x02c */
    USHORT ImageNumberHigh;                                /* 0x02e */
    WCHAR NtSystemRoot[260];                               /* 0x030 */
    ULONG MaxStackTraceDepth;                              /* 0x238 */
    ULONG CryptoExponent;                                  /* 0x23c */
    ULONG TimeZoneId;                                      /* 0x240 */
    ULONG LargePageMinimum;                                /* 0x244 */
    ULONG AitSamplingValue;                                /* 0x248 */
    ULONG AppCompatFlag;                                   /* 0x24c */
    ULONGLONG RNGSeedVersion;                              /* 0x250 */
    ULONG GlobalValidationRunLevel;                        /* 0x258 */
    volatile ULONG TimeZoneBiasStamp;                      /* 0x25c */
    ULONG NtBuildNumber;                                   /* 0x260 */
    NT_PRODUCT_TYPE NtProductType;                         /* 0x264 */
    BOOLEAN ProductTypeIsValid;                            /* 0x268 */
    USHORT NativeProcessorArchitecture;                    /* 0x26a */
    ULONG NtMajorVersion;                                  /* 0x26c */
    ULONG NtMinorVersion;                                  /* 0x270 */
    BOOLEAN ProcessorFeatures[PROCESSOR_FEATURE_MAX];      /* 0x274 */
    ULONG Reserved1;                                       /* 0x2b4 */
    ULONG Reserved3;                                       /* 0x2b8 */
    volatile ULONG TimeSlip;                               /* 0x2bc */
    ALTERNATIVE_ARCHITECTURE_TYPE AlternativeArchitecture; /* 0x2c0 */
    ULONG BootId;                                          /* 0x2c4 */
    LARGE_INTEGER SystemExpirationDate;                    /* 0x2c8 */
    ULONG SuiteMask;                                       /* 0x2d0 */
    BOOLEAN KdDebuggerEnabled;                             /* 0x2d4 */
    UCHAR NXSupportPolicy;                                 /* 0x2d5 */
    USHORT CyclesPerYield;                                 /* 0x2d6 */
    volatile ULONG ActiveConsoleId;                        /* 0x2d8 */
    volatile ULONG DismountCount;                          /* 0x2dc */
    ULONG ComPlusPackage;                                  /* 0x2e0 */
    ULONG LastSystemRITEventTickCount;                     /* 0x2e4 */
    ULONG NumberOfPhysicalPages;                           /* 0x2e8 */
    BOOLEAN SafeBootMode;                                  /* 0x2ec */
    UCHAR VirtualizationFlags;                             /* 0x2ed */
    union {
        ULONG SharedDataFlags;                             /* 0x2f0 */
        struct {
            ULONG DbgErrorPortPresent       : 1;
            ULONG DbgElevationEnabed        : 1;
            ULONG DbgVirtEnabled            : 1;
            ULONG DbgInstallerDetectEnabled : 1;
            ULONG DbgLkgEnabled             : 1;
            ULONG DbgDynProcessorEnabled    : 1;
            ULONG DbgConsoleBrokerEnabled   : 1;
            ULONG DbgSecureBootEnabled      : 1;
            ULONG DbgMultiSessionSku        : 1;
            ULONG DbgMultiUsersInSessionSku : 1;
            ULONG DbgStateSeparationEnabled : 1;
            ULONG SpareBits                 : 21;
        } DUMMYSTRUCTNAME2;
    } DUMMYUNIONNAME2;
    ULONG DataFlagsPad[1];                                 /* 0x2f4 */
    ULONGLONG TestRetInstruction;                          /* 0x2f8 */
    LONGLONG QpcFrequency;                                 /* 0x300 */
    ULONG SystemCall;                                      /* 0x308 */
    union {
        ULONG AllFlags;                                    /* 0x30c */
        struct {
            ULONG Win32Process            : 1;
            ULONG Sgx2Enclave             : 1;
            ULONG VbsBasicEnclave         : 1;
            ULONG SpareBits               : 29;
        } DUMMYSTRUCTNAME;
    } UserCetAvailableEnvironments;
    ULONGLONG SystemCallPad[2];                            /* 0x310 */
    union {
        volatile KSYSTEM_TIME TickCount;                   /* 0x320 */
        volatile ULONG64 TickCountQuad;
    } DUMMYUNIONNAME;
    ULONG Cookie;                                          /* 0x330 */
    ULONG CookiePad[1];                                    /* 0x334 */
    LONGLONG ConsoleSessionForegroundProcessId;            /* 0x338 */
    ULONGLONG TimeUpdateLock;                              /* 0x340 */
    ULONGLONG BaselineSystemTimeQpc;                       /* 0x348 */
    ULONGLONG BaselineInterruptTimeQpc;                    /* 0x350 */
    ULONGLONG QpcSystemTimeIncrement;                      /* 0x358 */
    ULONGLONG QpcInterruptTimeIncrement;                   /* 0x360 */
    UCHAR QpcSystemTimeIncrementShift;                     /* 0x368 */
    UCHAR QpcInterruptTimeIncrementShift;                  /* 0x369 */
    USHORT UnparkedProcessorCount;                         /* 0x36a */
    ULONG EnclaveFeatureMask[4];                           /* 0x36c */
    ULONG TelemetryCoverageRound;                          /* 0x37c */
    USHORT UserModeGlobalLogger[16];                       /* 0x380 */
    ULONG ImageFileExecutionOptions;                       /* 0x3a0 */
    ULONG LangGenerationCount;                             /* 0x3a4 */
    ULONG ActiveProcessorAffinity;                         /* 0x3a8 */
    volatile ULONGLONG InterruptTimeBias;                  /* 0x3b0 */
    volatile ULONGLONG QpcBias;                            /* 0x3b8 */
    ULONG ActiveProcessorCount;                            /* 0x3c0 */
    volatile UCHAR ActiveGroupCount;                       /* 0x3c4 */
    union {
        USHORT QpcData;                                    /* 0x3c6 */
        struct {
            UCHAR volatile QpcBypassEnabled;
            UCHAR QpcShift;
        } DUMMYSTRUCTNAME;
    } DUMMYUNIONNAME3;
    LARGE_INTEGER TimeZoneBiasEffectiveStart;              /* 0x3c8 */
    LARGE_INTEGER TimeZoneBiasEffectiveEnd;                /* 0x3d0 */
    XSTATE_CONFIGURATION XState;                           /* 0x3d8 */
    KSYSTEM_TIME FeatureConfigurationChangeStamp;          /* 0x720 */
    ULONG Spare;
    ULONG64 UserPointerAuthMask;                           /* 0x730 */
} KUSER_SHARED_DATA, *PKUSER_SHARED_DATA;

#include <stddef.h>
_Static_assert(sizeof(KUSER_SHARED_DATA) == 0x738, "KUSER_SHARED_DATA size (C_ASSERT in wine/include/ddk/wdm.h)");

/* Layout pins, generated from the offset comments in the SAME Wine
 * header the struct was extracted from (Art. 4). */
_Static_assert(offsetof(KUSER_SHARED_DATA, TickCountLowDeprecated) == 0x000, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, TickCountMultiplier) == 0x004, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, InterruptTime) == 0x008, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, SystemTime) == 0x014, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, TimeZoneBias) == 0x020, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ImageNumberLow) == 0x02c, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ImageNumberHigh) == 0x02e, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, NtSystemRoot) == 0x030, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, MaxStackTraceDepth) == 0x238, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, CryptoExponent) == 0x23c, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, TimeZoneId) == 0x240, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, LargePageMinimum) == 0x244, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, AitSamplingValue) == 0x248, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, AppCompatFlag) == 0x24c, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, RNGSeedVersion) == 0x250, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, GlobalValidationRunLevel) == 0x258, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, TimeZoneBiasStamp) == 0x25c, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, NtBuildNumber) == 0x260, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, NtProductType) == 0x264, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ProductTypeIsValid) == 0x268, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, NativeProcessorArchitecture) == 0x26a, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, NtMajorVersion) == 0x26c, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, NtMinorVersion) == 0x270, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ProcessorFeatures) == 0x274, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, Reserved1) == 0x2b4, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, Reserved3) == 0x2b8, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, TimeSlip) == 0x2bc, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, AlternativeArchitecture) == 0x2c0, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, BootId) == 0x2c4, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, SystemExpirationDate) == 0x2c8, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, SuiteMask) == 0x2d0, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, KdDebuggerEnabled) == 0x2d4, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, NXSupportPolicy) == 0x2d5, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, CyclesPerYield) == 0x2d6, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ActiveConsoleId) == 0x2d8, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, DismountCount) == 0x2dc, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ComPlusPackage) == 0x2e0, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, LastSystemRITEventTickCount) == 0x2e4, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, NumberOfPhysicalPages) == 0x2e8, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, SafeBootMode) == 0x2ec, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, VirtualizationFlags) == 0x2ed, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, DataFlagsPad) == 0x2f4, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, TestRetInstruction) == 0x2f8, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, QpcFrequency) == 0x300, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, SystemCall) == 0x308, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, SystemCallPad) == 0x310, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, Cookie) == 0x330, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, CookiePad) == 0x334, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ConsoleSessionForegroundProcessId) == 0x338, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, TimeUpdateLock) == 0x340, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, BaselineSystemTimeQpc) == 0x348, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, BaselineInterruptTimeQpc) == 0x350, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, QpcSystemTimeIncrement) == 0x358, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, QpcInterruptTimeIncrement) == 0x360, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, QpcSystemTimeIncrementShift) == 0x368, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, QpcInterruptTimeIncrementShift) == 0x369, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, UnparkedProcessorCount) == 0x36a, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, EnclaveFeatureMask) == 0x36c, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, TelemetryCoverageRound) == 0x37c, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, UserModeGlobalLogger) == 0x380, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ImageFileExecutionOptions) == 0x3a0, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, LangGenerationCount) == 0x3a4, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ActiveProcessorAffinity) == 0x3a8, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, InterruptTimeBias) == 0x3b0, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, QpcBias) == 0x3b8, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ActiveProcessorCount) == 0x3c0, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, ActiveGroupCount) == 0x3c4, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, TimeZoneBiasEffectiveStart) == 0x3c8, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, TimeZoneBiasEffectiveEnd) == 0x3d0, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, XState) == 0x3d8, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, FeatureConfigurationChangeStamp) == 0x720, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(KUSER_SHARED_DATA, UserPointerAuthMask) == 0x730, "KUSER_SHARED_DATA x64 layout (offset comment in the Wine header)");

#endif /* PROSKRNL_ABI_NTKEAPI_H */
