/* abi/ntmmapi.h - GENERATED by tools/gen_abi.py from wine/include/{winnt.h,winternl.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTMMAPI_H
#define PROSKRNL_ABI_NTMMAPI_H

#include "abi/ntdef.h"
#include "abi/ntioapi.h" /* IO_STATUS_BLOCK in NtFlushVirtualMemory (CUI-7) */

/* Allocation/protection flags, extracted from wine/include/winnt.h. */
#define PAGE_NOACCESS 0x00000001
#define PAGE_READONLY 0x00000002
#define PAGE_READWRITE 0x00000004
#define PAGE_WRITECOPY 0x00000008
#define PAGE_EXECUTE 0x00000010
#define PAGE_EXECUTE_READ 0x00000020
#define PAGE_EXECUTE_READWRITE 0x00000040
#define PAGE_EXECUTE_WRITECOPY 0x00000080
#define PAGE_GUARD 0x00000100
#define PAGE_NOCACHE 0x00000200
#define MEM_COMMIT 0x00001000
#define MEM_RESERVE 0x00002000
#define MEM_RESET 0x00080000
#define MEM_TOP_DOWN 0x00100000
#define MEM_DECOMMIT 0x00004000
#define MEM_RELEASE 0x00008000
#define MEM_FREE 0x00010000
#define MEM_PRIVATE 0x00020000
#define MEM_MAPPED 0x00040000
#define MEM_WRITE_WATCH 0x00200000
#define MEM_REPLACE_PLACEHOLDER 0x00004000
#define MEM_RESERVE_PLACEHOLDER 0x00040000
#define MEM_COALESCE_PLACEHOLDERS 0x00000001
#define MEM_PRESERVE_PLACEHOLDER 0x00000002
#define MEM_UNMAP_WITH_TRANSIENT_BOOST 0x00000001
#define WRITE_WATCH_FLAG_RESET 0x00000001
#define MEM_EXTENDED_PARAMETER_TYPE_BITS 8
#define MEM_EXTENDED_PARAMETER_EC_CODE 0x00000040

/* Section allocation attributes + access rights (M5), extracted from
 * wine/include/winnt.h. */
#define SEC_FILE 0x00800000
#define SEC_IMAGE 0x01000000
#define SEC_RESERVE 0x04000000
#define SEC_COMMIT 0x08000000
#define SEC_NOCACHE 0x10000000
#define SEC_WRITECOMBINE 0x40000000
#define SEC_LARGE_PAGES 0x80000000
#define MEM_IMAGE SEC_IMAGE
#define SECTION_QUERY 0x0001
#define SECTION_MAP_WRITE 0x0002
#define SECTION_MAP_READ 0x0004
#define SECTION_MAP_EXECUTE 0x0008
#define SECTION_EXTEND_SIZE 0x0010
#define SECTION_MAP_EXECUTE_EXPLICIT 0x0020
#define SECTION_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|0x01f)
#define AT_ROUND_TO_PAGE 0x40000000

/* Extracted verbatim from wine/include/winnt.h; the static_asserts pin
 * the x64 layout the boundary depends on. */
typedef struct {
    LPVOID   BaseAddress;
    LPVOID   AllocationBase;
    DWORD    AllocationProtect;
    SIZE_T   RegionSize;
    DWORD    State;
    DWORD    Protect;
    DWORD    Type;
} MEMORY_BASIC_INFORMATION, *PMEMORY_BASIC_INFORMATION;

#include <stddef.h>
_Static_assert(sizeof(MEMORY_BASIC_INFORMATION) == 48, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, AllocationBase) == 8, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, AllocationProtect) == 16, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, RegionSize) == 24, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, State) == 32, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, Protect) == 36, "MEMORY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_BASIC_INFORMATION, Type) == 40, "MEMORY_BASIC_INFORMATION x64 layout");

/* Extracted verbatim from wine/include/winternl.h. */
typedef enum {
    MemoryBasicInformation = 0,
    MemoryWorkingSetInformation = 1,
    MemoryMappedFilenameInformation = 2,
    MemoryRegionInformation = 3,
    MemoryWorkingSetExInformation = 4,
    MemorySharedCommitInformation = 5,
    MemoryImageInformation = 6,
    MemoryRegionInformationEx = 7,
    MemoryPrivilegedBasicInformation = 8,
    MemoryEnclaveImageInformation = 9,
    MemoryBasicInformationCapped = 10,
    MemoryPhysicalContiguityInformation = 11,
    MemoryBadInformation = 12,
    MemoryBadInformationAllProcesses = 13,
    MemoryImageExtensionInformation = 14,
#ifdef __WINESRC__
    MemoryWineLoadUnixLib = 1000,
    MemoryWineLoadUnixLibWow64,
    MemoryWineLoadUnixLibByName,
    MemoryWineLoadUnixLibByNameWow64,
    MemoryWineUnloadUnixLib,
#endif
} MEMORY_INFORMATION_CLASS;

/* M10 (docs/21 W5 tail): NtQueryVirtualMemory's
 * MemoryRegionInformation, extracted verbatim from
 * wine/include/winternl.h. */
typedef struct {
    PVOID AllocationBase;
    ULONG AllocationProtect;
    union
    {
        ULONG RegionType;
        struct
        {
            ULONG Private : 1;
            ULONG MappedDataFile : 1;
            ULONG MappedImage : 1;
            ULONG MappedPageFile : 1;
            ULONG MappedPhysical : 1;
            ULONG DirectMapped : 1;
            ULONG Reserved : 26;
        } DUMMYSTRUCTNAME;
    } DUMMYUNIONNAME;
    SIZE_T RegionSize;
    SIZE_T CommitSize;
    ULONG_PTR PartitionId;
    ULONG_PTR NodePreference;
} MEMORY_REGION_INFORMATION, *PMEMORY_REGION_INFORMATION;

_Static_assert(sizeof(MEMORY_REGION_INFORMATION) == 48, "MEMORY_REGION_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_REGION_INFORMATION, AllocationProtect) == 8,
               "MEMORY_REGION_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_REGION_INFORMATION, RegionType) == 12,
               "MEMORY_REGION_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_REGION_INFORMATION, RegionSize) == 16,
               "MEMORY_REGION_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_REGION_INFORMATION, CommitSize) == 24,
               "MEMORY_REGION_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_REGION_INFORMATION, PartitionId) == 32,
               "MEMORY_REGION_INFORMATION x64 layout");

/* M10 (docs/21 W5 tail): NtQueryVirtualMemory's
 * MemoryImageInformation, extracted verbatim from
 * wine/include/winternl.h. */
typedef struct {
    PVOID ImageBase;
    SIZE_T SizeOfImage;
    union
    {
        ULONG ImageFlags;
        struct
        {
            ULONG ImagePartialMap : 1;
            ULONG ImageNotExecutable : 1;
            ULONG ImageSigningLevel : 4;
            ULONG Reserved : 26;
        };
    };
} MEMORY_IMAGE_INFORMATION, *PMEMORY_IMAGE_INFORMATION;

_Static_assert(sizeof(MEMORY_IMAGE_INFORMATION) == 24, "MEMORY_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_IMAGE_INFORMATION, SizeOfImage) == 8,
               "MEMORY_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(MEMORY_IMAGE_INFORMATION, ImageFlags) == 16,
               "MEMORY_IMAGE_INFORMATION x64 layout");


/* CUI-7: the *Ex extended-parameter contract, extracted verbatim from
 * wine/include/{winnt.h,winternl.h}. DWORD64 is a Win32 alias scaffold
 * (wine/include/basetsd.h: unsigned 64-bit). */
typedef ULONGLONG DWORD64;

typedef struct {
  void      *LowestStartingAddress;
  void      *HighestEndingAddress;
  SIZE_T     Alignment;
} MEM_ADDRESS_REQUIREMENTS, *PMEM_ADDRESS_REQUIREMENTS;

typedef enum {
    MemExtendedParameterInvalidType = 0,
    MemExtendedParameterAddressRequirements,
    MemExtendedParameterNumaNode,
    MemExtendedParameterPartitionHandle,
    MemExtendedParameterUserPhysicalHandle,
    MemExtendedParameterAttributeFlags,
    MemExtendedParameterImageMachine,
    MemExtendedParameterMax
} MEM_EXTENDED_PARAMETER_TYPE, *PMEM_EXTENDED_PARAMETER_TYPE;

typedef struct {
    struct
    {
        DWORD64 Type : MEM_EXTENDED_PARAMETER_TYPE_BITS;
        DWORD64 Reserved : 64 - MEM_EXTENDED_PARAMETER_TYPE_BITS;
    } DUMMYSTRUCTNAME;

    union
    {
        DWORD64 ULong64;
        PVOID Pointer;
        SIZE_T Size;
        HANDLE Handle;
        DWORD ULong;
    } DUMMYUNIONNAME;
} MEM_EXTENDED_PARAMETER, *PMEM_EXTENDED_PARAMETER;

typedef struct {
    PVOID  VirtualAddress;
    SIZE_T NumberOfBytes;
} MEMORY_RANGE_ENTRY, *PMEMORY_RANGE_ENTRY;

typedef enum
{
    VmPrefetchInformation,
    VmPagePriorityInformation,
    VmCfgCallTargetInformation,
    VmPageDirtyStateInformation,
    VmImageHotPatchInformation,
    VmPhysicalContiguityInformation,
    VmVirtualMachinePrepopulateInformation,
    VmRemoveFromWorkingSetInformation,
} VIRTUAL_MEMORY_INFORMATION_CLASS, *PVIRTUAL_MEMORY_INFORMATION_CLASS;

_Static_assert(sizeof(MEM_ADDRESS_REQUIREMENTS) == 24, "MEM_ADDRESS_REQUIREMENTS x64 layout");
_Static_assert(offsetof(MEM_ADDRESS_REQUIREMENTS, Alignment) == 16,
               "MEM_ADDRESS_REQUIREMENTS x64 layout");
_Static_assert(sizeof(MEM_EXTENDED_PARAMETER) == 16, "MEM_EXTENDED_PARAMETER x64 layout");
_Static_assert(_Alignof(MEM_EXTENDED_PARAMETER) == 8,
               "MEM_EXTENDED_PARAMETER x64 layout (DECLSPEC_ALIGN(8) in the Wine header)");
_Static_assert(sizeof(MEMORY_RANGE_ENTRY) == 16, "MEMORY_RANGE_ENTRY x64 layout");

/* Section enums/structs (M5), extracted verbatim from
 * wine/include/winternl.h; static_asserts pin the x64 layout. */
typedef enum {
    ViewShare = 1,
    ViewUnmap = 2
} SECTION_INHERIT;

typedef enum {
  SectionBasicInformation,
  SectionImageInformation,
  SectionRelocationInformation,
  SectionOriginalBaseInformation,
  SectionInternalImageInformation
} SECTION_INFORMATION_CLASS;

typedef struct {
  PVOID BaseAddress;
  ULONG Attributes;
  LARGE_INTEGER Size;
} SECTION_BASIC_INFORMATION, *PSECTION_BASIC_INFORMATION;

typedef struct {
  PVOID TransferAddress;
  ULONG ZeroBits;
  SIZE_T MaximumStackSize;
  SIZE_T CommittedStackSize;
  ULONG SubSystemType;
  USHORT MinorSubsystemVersion;
  USHORT MajorSubsystemVersion;
  USHORT MajorOperatingSystemVersion;
  USHORT MinorOperatingSystemVersion;
  USHORT ImageCharacteristics;
  USHORT DllCharacteristics;
  USHORT Machine;
  BOOLEAN ImageContainsCode;
  union
  {
      UCHAR ImageFlags;
      struct
      {
          UCHAR ComPlusNativeReady        : 1;
          UCHAR ComPlusILOnly             : 1;
          UCHAR ImageDynamicallyRelocated : 1;
          UCHAR ImageMappedFlat           : 1;
          UCHAR BaseBelow4gb              : 1;
          UCHAR ComPlusPrefer32bit        : 1;
          UCHAR Reserved                  : 2;
      } DUMMYSTRUCTNAME;
  } DUMMYUNIONNAME;
  ULONG LoaderFlags;
  ULONG ImageFileSize;
  ULONG CheckSum;
} SECTION_IMAGE_INFORMATION, *PSECTION_IMAGE_INFORMATION;

_Static_assert(sizeof(SECTION_BASIC_INFORMATION) == 24, "SECTION_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_BASIC_INFORMATION, Attributes) == 8, "SECTION_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_BASIC_INFORMATION, Size) == 16, "SECTION_BASIC_INFORMATION x64 layout");
_Static_assert(sizeof(SECTION_IMAGE_INFORMATION) == 64, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, MaximumStackSize) == 16, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, SubSystemType) == 32, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, Machine) == 48, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, LoaderFlags) == 52, "SECTION_IMAGE_INFORMATION x64 layout");
_Static_assert(offsetof(SECTION_IMAGE_INFORMATION, CheckSum) == 60, "SECTION_IMAGE_INFORMATION x64 layout");

/* The M4+M5 Mm Nt* surface; signatures extracted verbatim from
 * wine/include/winternl.h (linkage macros dropped). */
NTSTATUS NtAllocateVirtualMemory(HANDLE,PVOID*,ULONG_PTR,SIZE_T*,ULONG,ULONG);
NTSTATUS NtFreeVirtualMemory(HANDLE,PVOID*,SIZE_T*,ULONG);
NTSTATUS NtQueryVirtualMemory(HANDLE,LPCVOID,MEMORY_INFORMATION_CLASS,PVOID,SIZE_T,SIZE_T*);
NTSTATUS NtCreateSection(HANDLE*,ACCESS_MASK,const OBJECT_ATTRIBUTES*,const LARGE_INTEGER*,ULONG,ULONG,HANDLE);
NTSTATUS NtOpenSection(HANDLE*,ACCESS_MASK,const OBJECT_ATTRIBUTES*);
NTSTATUS NtMapViewOfSection(HANDLE,HANDLE,PVOID*,ULONG_PTR,SIZE_T,const LARGE_INTEGER*,SIZE_T*,SECTION_INHERIT,ULONG,ULONG);
NTSTATUS NtUnmapViewOfSection(HANDLE,PVOID);
NTSTATUS NtQuerySection(HANDLE,SECTION_INFORMATION_CLASS,PVOID,SIZE_T,SIZE_T*);
NTSTATUS NtProtectVirtualMemory(HANDLE,PVOID*,SIZE_T*,ULONG,ULONG*);
NTSTATUS NtFlushInstructionCache(HANDLE,LPCVOID,SIZE_T);
NTSTATUS NtAreMappedFilesTheSame(PVOID,PVOID);
NTSTATUS NtReadVirtualMemory(HANDLE,const void*,void*,SIZE_T,SIZE_T*);
NTSTATUS NtWriteVirtualMemory(HANDLE,void*,const void*,SIZE_T,SIZE_T*);
NTSTATUS NtAllocateVirtualMemoryEx(HANDLE,PVOID*,SIZE_T*,ULONG,ULONG,MEM_EXTENDED_PARAMETER*,ULONG);
NTSTATUS NtCreateSectionEx(HANDLE*,ACCESS_MASK,const OBJECT_ATTRIBUTES*,const LARGE_INTEGER*,ULONG,ULONG,HANDLE,MEM_EXTENDED_PARAMETER*,ULONG);
NTSTATUS NtMapViewOfSectionEx(HANDLE,HANDLE,PVOID*,const LARGE_INTEGER*,SIZE_T*,ULONG,ULONG,MEM_EXTENDED_PARAMETER*,ULONG);
NTSTATUS NtUnmapViewOfSectionEx(HANDLE,PVOID,ULONG);
NTSTATUS NtFlushVirtualMemory(HANDLE,LPCVOID*,SIZE_T*,IO_STATUS_BLOCK*);
NTSTATUS NtLockVirtualMemory(HANDLE,PVOID*,SIZE_T*,ULONG);
NTSTATUS NtUnlockVirtualMemory(HANDLE,PVOID*,SIZE_T*,ULONG);
NTSTATUS NtGetWriteWatch(HANDLE,ULONG,PVOID,SIZE_T,PVOID*,ULONG_PTR*,ULONG*);
NTSTATUS NtResetWriteWatch(HANDLE,PVOID,SIZE_T);
NTSTATUS NtSetInformationVirtualMemory(HANDLE,VIRTUAL_MEMORY_INFORMATION_CLASS,ULONG_PTR,PMEMORY_RANGE_ENTRY,PVOID,ULONG);

#endif /* PROSKRNL_ABI_NTMMAPI_H */
