/* abi/ntmountmgr.h - GENERATED by tools/gen_abi.py from wine/include/ddk/mountmgr.h.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTMOUNTMGR_H
#define PROSKRNL_ABI_NTMOUNTMGR_H

#include "abi/ntdef.h"
#include "abi/ntioapi.h" /* CTL_CODE, METHOD_BUFFERED, FILE_*_ACCESS */

/* The mount-manager ioctl codes, extracted from
 * wine/include/ddk/mountmgr.h. */
#define MOUNTMGRCONTROLTYPE ((ULONG)'m')
#define IOCTL_MOUNTMGR_CREATE_POINT CTL_CODE(MOUNTMGRCONTROLTYPE, 0, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_MOUNTMGR_DELETE_POINTS CTL_CODE(MOUNTMGRCONTROLTYPE, 1, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_MOUNTMGR_QUERY_POINTS CTL_CODE(MOUNTMGRCONTROLTYPE, 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MOUNTMGR_DELETE_POINTS_DBONLY CTL_CODE(MOUNTMGRCONTROLTYPE, 3, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_MOUNTMGR_NEXT_DRIVE_LETTER CTL_CODE(MOUNTMGRCONTROLTYPE, 4, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_MOUNTMGR_AUTO_DL_ASSIGNMENTS CTL_CODE(MOUNTMGRCONTROLTYPE, 5, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_MOUNTMGR_VOLUME_MOUNT_POINT_CREATED CTL_CODE(MOUNTMGRCONTROLTYPE, 6, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_MOUNTMGR_VOLUME_MOUNT_POINT_DELETED CTL_CODE(MOUNTMGRCONTROLTYPE, 7, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_MOUNTMGR_CHANGE_NOTIFY CTL_CODE(MOUNTMGRCONTROLTYPE, 8, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_MOUNTMGR_KEEP_LINKS_WHEN_OFFLINE CTL_CODE(MOUNTMGRCONTROLTYPE, 9, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_MOUNTMGR_CHECK_UNPROCESSED_VOLUMES CTL_CODE(MOUNTMGRCONTROLTYPE, 10, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_MOUNTMGR_VOLUME_ARRIVAL_NOTIFICATION CTL_CODE(MOUNTMGRCONTROLTYPE, 11, METHOD_BUFFERED, FILE_READ_ACCESS)

/* The QUERY_POINTS request and reply shapes. Both are
 * variable-length: every name is an (offset, length) pair into the
 * SAME buffer the fixed part sits at the head of, and the lengths
 * are in BYTES and the strings are NOT NUL-terminated -- which
 * dlls/kernelbase/volume.c relies on, copying SymbolicLinkNameLength
 * bytes and terminating the result itself. */
typedef struct {
    ULONG  SymbolicLinkNameOffset;
    USHORT SymbolicLinkNameLength;
    ULONG  UniqueIdOffset;
    USHORT UniqueIdLength;
    ULONG  DeviceNameOffset;
    USHORT DeviceNameLength;
} MOUNTMGR_MOUNT_POINT, *PMOUNTMGR_MOUNT_POINT;

typedef struct {
    ULONG                Size;
    ULONG                NumberOfMountPoints;
    MOUNTMGR_MOUNT_POINT MountPoints[1];
} MOUNTMGR_MOUNT_POINTS, *PMOUNTMGR_MOUNT_POINTS;

#include <stddef.h>
/* 24, not 20: each USHORT is followed by two bytes of padding, because the
 * header carries no #pragma pack and every ULONG must stay 4-aligned. The
 * offsets a caller reads out of this struct index the SAME buffer the
 * struct sits in, so getting its size wrong shifts every name in the
 * reply. */
_Static_assert(sizeof(MOUNTMGR_MOUNT_POINT) == 24, "MOUNTMGR_MOUNT_POINT layout");
_Static_assert(offsetof(MOUNTMGR_MOUNT_POINT, UniqueIdOffset) == 8,
               "MOUNTMGR_MOUNT_POINT layout");
_Static_assert(offsetof(MOUNTMGR_MOUNT_POINT, DeviceNameOffset) == 16,
               "MOUNTMGR_MOUNT_POINT layout");
_Static_assert(offsetof(MOUNTMGR_MOUNT_POINTS, MountPoints) == 8,
               "MOUNTMGR_MOUNT_POINTS layout");

#endif /* PROSKRNL_ABI_NTMOUNTMGR_H */
