/* abi/ntpebteb.h - GENERATED by tools/gen_abi.py from wine/include/{winternl.h,guiddef.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTPEBTEB_H
#define PROSKRNL_ABI_NTPEBTEB_H

#include "abi/ntdef.h"
#include "abi/ntpsapi.h" /* NT_TIB, CLIENT_ID */

/* x86_64 only (ADR 0006): the extracted PEB/TEB carry #ifdef _WIN64 blocks
 * verbatim; this build is always the 64-bit layout. */
#ifndef _WIN64
#define _WIN64 1
#endif

/* Win32 alias/opaque scaffold for extracted-struct member types. Only the
 * pointer identity matters for layout; the pointees are not part of the M7
 * boundary (nothing dereferences them across it). */
typedef PVOID HMODULE;
typedef struct _RTL_CRITICAL_SECTION *PRTL_CRITICAL_SECTION;
typedef struct _ACTIVATION_CONTEXT ACTIVATION_CONTEXT;
typedef struct _TEB_ACTIVE_FRAME TEB_ACTIVE_FRAME;
typedef struct _TEB_FLS_DATA TEB_FLS_DATA;
typedef struct _CHPEV2_PROCESS_INFO CHPEV2_PROCESS_INFO;
typedef struct _CHPE_V2_CPU_AREA_INFO CHPE_V2_CPU_AREA_INFO;

/* Extracted verbatim from wine/include/guiddef.h. */
typedef struct {
#if !defined(__LP64__) && !defined(WINE_UNIX_LIB)
    unsigned long  Data1;
#else
    unsigned int   Data1;
#endif
    unsigned short Data2;
    unsigned short Data3;
    unsigned char  Data4[ 8 ];
} GUID;

/* Extracted verbatim from wine/include/winternl.h. */
typedef NTSTATUS (*KERNEL_CALLBACK_PROC)(void *, ULONG);

typedef struct {
    UNICODE_STRING DosPath;
    PVOID Handle;
} CURDIR, *PCURDIR;

typedef struct {
    USHORT              Flags;
    USHORT              Length;
    ULONG               TimeStamp;
    UNICODE_STRING      DosPath;
} RTL_DRIVE_LETTER_CURDIR, *PRTL_DRIVE_LETTER_CURDIR;

typedef struct {
    ULONG  SizeOfBitMap; /* Number of bits in the bitmap */
    PULONG Buffer; /* Bitmap data, assumed sized to a DWORD boundary */
} RTL_BITMAP, *PRTL_BITMAP;

typedef struct {
    ULONG               Length;
    BOOLEAN             Initialized;
    PVOID               SsHandle;
    LIST_ENTRY          InLoadOrderModuleList;
    LIST_ENTRY          InMemoryOrderModuleList;
    LIST_ENTRY          InInitializationOrderModuleList;
    PVOID               EntryInProgress;
    BOOLEAN             ShutdownInProgress;
    HANDLE              ShutdownThreadId;
} PEB_LDR_DATA, *PPEB_LDR_DATA;

typedef struct {
    ULONG  Offset;
    HANDLE HDC;
    ULONG  Buffer[0x136];
} GDI_TEB_BATCH;

typedef struct {
    struct _RTL_ACTIVATION_CONTEXT_STACK_FRAME *Previous;
    struct _ACTIVATION_CONTEXT                 *ActivationContext;
    ULONG                                       Flags;
} RTL_ACTIVATION_CONTEXT_STACK_FRAME, *PRTL_ACTIVATION_CONTEXT_STACK_FRAME;

typedef struct {
    RTL_ACTIVATION_CONTEXT_STACK_FRAME *ActiveFrame;
    LIST_ENTRY                          FrameListCache;
    ULONG                               Flags;
    ULONG                               NextCookieSequenceNumber;
    ULONG_PTR                           StackId;
} ACTIVATION_CONTEXT_STACK, *PACTIVATION_CONTEXT_STACK;

typedef struct _RTL_USER_PROCESS_PARAMETERS {
    ULONG               AllocationSize;
    ULONG               Size;
    ULONG               Flags;
    ULONG               DebugFlags;
    HANDLE              ConsoleHandle;
    ULONG               ConsoleFlags;
    HANDLE              hStdInput;
    HANDLE              hStdOutput;
    HANDLE              hStdError;
    CURDIR              CurrentDirectory;
    UNICODE_STRING      DllPath;
    UNICODE_STRING      ImagePathName;
    UNICODE_STRING      CommandLine;
    PWSTR               Environment;
    ULONG               dwX;
    ULONG               dwY;
    ULONG               dwXSize;
    ULONG               dwYSize;
    ULONG               dwXCountChars;
    ULONG               dwYCountChars;
    ULONG               dwFillAttribute;
    ULONG               dwFlags;
    ULONG               wShowWindow;
    UNICODE_STRING      WindowTitle;
    UNICODE_STRING      Desktop;
    UNICODE_STRING      ShellInfo;
    UNICODE_STRING      RuntimeInfo;
    RTL_DRIVE_LETTER_CURDIR DLCurrentDirectory[0x20];
    ULONG_PTR           EnvironmentSize;
    ULONG_PTR           EnvironmentVersion;
    PVOID               PackageDependencyData;
    ULONG               ProcessGroupId;
    ULONG               LoaderThreads;
} RTL_USER_PROCESS_PARAMETERS, *PRTL_USER_PROCESS_PARAMETERS;

typedef struct _PEB {                                                                 /* win32/win64 */
    BOOLEAN                      InheritedAddressSpace;             /* 000/000 */
    BOOLEAN                      ReadImageFileExecOptions;          /* 001/001 */
    BOOLEAN                      BeingDebugged;                     /* 002/002 */
    UCHAR                        ImageUsedLargePages : 1;           /* 003/003 */
    UCHAR                        IsProtectedProcess : 1;
    UCHAR                        IsImageDynamicallyRelocated : 1;
    UCHAR                        SkipPatchingUser32Forwarders : 1;
    UCHAR                        IsPackagedProcess : 1;
    UCHAR                        IsAppContainer: 1;
    UCHAR                        IsProtectedProcessLight : 1;
    UCHAR                        IsLongPathAwareProcess : 1;
    HANDLE                       Mutant;                            /* 004/008 */
    HMODULE                      ImageBaseAddress;                  /* 008/010 */
    PPEB_LDR_DATA                LdrData;                           /* 00c/018 */
    RTL_USER_PROCESS_PARAMETERS *ProcessParameters;                 /* 010/020 */
    PVOID                        SubSystemData;                     /* 014/028 */
    HANDLE                       ProcessHeap;                       /* 018/030 */
    PRTL_CRITICAL_SECTION        FastPebLock;                       /* 01c/038 */
    PVOID                        AtlThunkSListPtr;                  /* 020/040 */
    PVOID                        IFEOKey;                           /* 024/048 */
    ULONG                        ProcessInJob : 1;                  /* 028/050 */
    ULONG                        ProcessInitializing : 1;
    ULONG                        ProcessUsingVEH : 1;
    ULONG                        ProcessUsingVCH : 1;
    ULONG                        ProcessUsingFTH : 1;
    ULONG                        ProcessPreviouslyThrottled : 1;
    ULONG                        ProcessCurrentlyThrottled : 1;
    ULONG                        ProcessImagesHotPatched : 1;
    ULONG                        ReservedBits0 : 24;
    KERNEL_CALLBACK_PROC        *KernelCallbackTable;               /* 02c/058 */
    ULONG                        Reserved;                          /* 030/060 */
    ULONG                        AtlThunkSListPtr32;                /* 034/064 */
    PVOID                        ApiSetMap;                         /* 038/068 */
    ULONG                        TlsExpansionCounter;               /* 03c/070 */
    PRTL_BITMAP                  TlsBitmap;                         /* 040/078 */
    ULONG                        TlsBitmapBits[2];                  /* 044/080 */
    PVOID                        ReadOnlySharedMemoryBase;          /* 04c/088 */
    PVOID                        SharedData;                        /* 050/090 */
    PVOID                       *ReadOnlyStaticServerData;          /* 054/098 */
    PVOID                        AnsiCodePageData;                  /* 058/0a0 */
    PVOID                        OemCodePageData;                   /* 05c/0a8 */
    PVOID                        UnicodeCaseTableData;              /* 060/0b0 */
    ULONG                        NumberOfProcessors;                /* 064/0b8 */
    ULONG                        NtGlobalFlag;                      /* 068/0bc */
    LARGE_INTEGER                CriticalSectionTimeout;            /* 070/0c0 */
    SIZE_T                       HeapSegmentReserve;                /* 078/0c8 */
    SIZE_T                       HeapSegmentCommit;                 /* 07c/0d0 */
    SIZE_T                       HeapDeCommitTotalFreeThreshold;    /* 080/0d8 */
    SIZE_T                       HeapDeCommitFreeBlockThreshold;    /* 084/0e0 */
    ULONG                        NumberOfHeaps;                     /* 088/0e8 */
    ULONG                        MaximumNumberOfHeaps;              /* 08c/0ec */
    PVOID                       *ProcessHeaps;                      /* 090/0f0 */
    PVOID                        GdiSharedHandleTable;              /* 094/0f8 */
    PVOID                        ProcessStarterHelper;              /* 098/100 */
    PVOID                        GdiDCAttributeList;                /* 09c/108 */
    PVOID                        LoaderLock;                        /* 0a0/110 */
    ULONG                        OSMajorVersion;                    /* 0a4/118 */
    ULONG                        OSMinorVersion;                    /* 0a8/11c */
    ULONG                        OSBuildNumber;                     /* 0ac/120 */
    ULONG                        OSPlatformId;                      /* 0b0/124 */
    ULONG                        ImageSubSystem;                    /* 0b4/128 */
    ULONG                        ImageSubSystemMajorVersion;        /* 0b8/12c */
    ULONG                        ImageSubSystemMinorVersion;        /* 0bc/130 */
    KAFFINITY                    ActiveProcessAffinityMask;         /* 0c0/138 */
#ifdef _WIN64
    ULONG                        GdiHandleBuffer[60];               /*    /140 */
#else
    ULONG                        GdiHandleBuffer[34];               /* 0c4/    */
#endif
    PVOID                        PostProcessInitRoutine;            /* 14c/230 */
    PRTL_BITMAP                  TlsExpansionBitmap;                /* 150/238 */
    ULONG                        TlsExpansionBitmapBits[32];        /* 154/240 */
    ULONG                        SessionId;                         /* 1d4/2c0 */
    ULARGE_INTEGER               AppCompatFlags;                    /* 1d8/2c8 */
    ULARGE_INTEGER               AppCompatFlagsUser;                /* 1e0/2d0 */
    PVOID                        ShimData;                          /* 1e8/2d8 */
    PVOID                        AppCompatInfo;                     /* 1ec/2e0 */
    UNICODE_STRING               CSDVersion;                        /* 1f0/2e8 */
    PVOID                        ActivationContextData;             /* 1f8/2f8 */
    PVOID                        ProcessAssemblyStorageMap;         /* 1fc/300 */
    PVOID                        SystemDefaultActivationData;       /* 200/308 */
    PVOID                        SystemAssemblyStorageMap;          /* 204/310 */
    SIZE_T                       MinimumStackCommit;                /* 208/318 */
    PVOID                        SparePointers[2];                  /* 20c/320 */
    PVOID                        PatchLoaderData;                   /* 214/330 */
    CHPEV2_PROCESS_INFO         *ChpeV2ProcessInfo;                 /* 218/338 */
    ULONG                        AppModelFeatureState;              /* 21c/340 */
    ULONG                        SpareUlongs[2];                    /* 220/344 */
    USHORT                       ActiveCodePage;                    /* 228/34c */
    USHORT                       OemCodePage;                       /* 22a/34e */
    USHORT                       UseCaseMapping;                    /* 22c/350 */
    USHORT                       UnusedNlsField;                    /* 22e/352 */
    PVOID                        WerRegistrationData;               /* 230/358 */
    PVOID                        WerShipAssertPtr;                  /* 234/360 */
    PVOID                        EcCodeBitMap;                      /* 238/368 */
    PVOID                        pImageHeaderHash;                  /* 23c/370 */
    ULONG                        HeapTracingEnabled : 1;            /* 240/378 */
    ULONG                        CritSecTracingEnabled : 1;
    ULONG                        LibLoaderTracingEnabled : 1;
    ULONG                        SpareTracingBits : 29;
    ULONGLONG                    CsrServerReadOnlySharedMemoryBase; /* 248/380 */
    ULONG                        TppWorkerpListLock;                /* 250/388 */
    LIST_ENTRY                   TppWorkerpList;                    /* 254/390 */
    PVOID                        WaitOnAddressHashTable [0x80];     /* 25c/3a0 */
    PVOID                        TelemetryCoverageHeader;           /* 45c/7a0 */
    ULONG                        CloudFileFlags;                    /* 460/7a8 */
    ULONG                        CloudFileDiagFlags;                /* 464/7ac */
    CHAR                         PlaceholderCompatibilityMode;      /* 468/7b0 */
    CHAR                         PlaceholderCompatibilityModeReserved[7]; /* 469/7b1 */
    PVOID                        LeapSecondData;                    /* 470/7b8 */
    ULONG                        LeapSecondFlags;                   /* 474/7c0 */
    ULONG                        NtGlobalFlag2;                     /* 478/7c4 */
} PEB, *PPEB;

typedef struct _TEB {                                                                 /* win32/win64 */
    NT_TIB                       Tib;                               /* 000/0000 */
    PVOID                        EnvironmentPointer;                /* 01c/0038 */
    CLIENT_ID                    ClientId;                          /* 020/0040 */
    PVOID                        ActiveRpcHandle;                   /* 028/0050 */
    PVOID                        ThreadLocalStoragePointer;         /* 02c/0058 */
    PPEB                         Peb;                               /* 030/0060 */
    ULONG                        LastErrorValue;                    /* 034/0068 */
    ULONG                        CountOfOwnedCriticalSections;      /* 038/006c */
    PVOID                        CsrClientThread;                   /* 03c/0070 */
    PVOID                        Win32ThreadInfo;                   /* 040/0078 */
    ULONG                        User32Reserved[26];                /* 044/0080 */
    ULONG                        UserReserved[5];                   /* 0ac/00e8 */
    PVOID                        WOW32Reserved;                     /* 0c0/0100 */
    ULONG                        CurrentLocale;                     /* 0c4/0108 */
    ULONG                        FpSoftwareStatusRegister;          /* 0c8/010c */
    PVOID                        ReservedForDebuggerInstrumentation[16]; /* 0cc/0110 */
#ifdef _WIN64
    PVOID                        SystemReserved1[30];               /*    /0190 */
#else
    PVOID                        SystemReserved1[26];               /* 10c/     used for krnl386 private data in Wine */
#endif
    char                         PlaceholderCompatibilityMode;      /* 174/0280 */
    BOOLEAN                      PlaceholderHydrationAlwaysExplicit;/* 175/0281 */
    char                         PlaceholderReserved[10];           /* 176/0282 */
    DWORD                        ProxiedProcessId;                  /* 180/028c */
    ACTIVATION_CONTEXT_STACK     ActivationContextStack;            /* 184/0290 */
    UCHAR                        WorkingOnBehalfOfTicket[8];        /* 19c/02b8 */
    LONG                         ExceptionCode;                     /* 1a4/02c0 */
    ACTIVATION_CONTEXT_STACK    *ActivationContextStackPointer;     /* 1a8/02c8 */
    ULONG_PTR                    InstrumentationCallbackSp;         /* 1ac/02d0 */
    ULONG_PTR                    InstrumentationCallbackPreviousPc; /* 1b0/02d8 */
    ULONG_PTR                    InstrumentationCallbackPreviousSp; /* 1b4/02e0 */
#ifdef _WIN64
    ULONG                        TxFsContext;                       /*    /02e8 */
    BOOLEAN                      InstrumentationCallbackDisabled;   /*    /02ec */
    BOOLEAN                      UnalignedLoadStoreExceptions;      /*    /02ed */
#else
    BOOLEAN                      InstrumentationCallbackDisabled;   /* 1b8/     */
    BYTE                         SpareBytes1[23];                   /* 1b9/     */
    ULONG                        TxFsContext;                       /* 1d0/     */
#endif
    GDI_TEB_BATCH                GdiTebBatch;                       /* 1d4/02f0 used for ntdll private data in Wine */
    CLIENT_ID                    RealClientId;                      /* 6b4/07d8 */
    HANDLE                       GdiCachedProcessHandle;            /* 6bc/07e8 */
    ULONG                        GdiClientPID;                      /* 6c0/07f0 */
    ULONG                        GdiClientTID;                      /* 6c4/07f4 */
    PVOID                        GdiThreadLocaleInfo;               /* 6c8/07f8 */
    ULONG_PTR                    Win32ClientInfo[62];               /* 6cc/0800 used for user32 private data in Wine */
    PVOID                        glDispatchTable[233];              /* 7c4/09f0 */
    PVOID                        glReserved1[29];                   /* b68/1138 */
    PVOID                        glReserved2;                       /* bdc/1220 */
    PVOID                        glSectionInfo;                     /* be0/1228 */
    PVOID                        glSection;                         /* be4/1230 */
    PVOID                        glTable;                           /* be8/1238 */
    PVOID                        glCurrentRC;                       /* bec/1240 */
    PVOID                        glContext;                         /* bf0/1248 */
    ULONG                        LastStatusValue;                   /* bf4/1250 */
    UNICODE_STRING               StaticUnicodeString;               /* bf8/1258 */
    WCHAR                        StaticUnicodeBuffer[261];          /* c00/1268 */
    PVOID                        DeallocationStack;                 /* e0c/1478 */
    PVOID                        TlsSlots[64];                      /* e10/1480 */
    LIST_ENTRY                   TlsLinks;                          /* f10/1680 */
    PVOID                        Vdm;                               /* f18/1690 */
    PVOID                        ReservedForNtRpc;                  /* f1c/1698 */
    PVOID                        DbgSsReserved[2];                  /* f20/16a0 */
    ULONG                        HardErrorMode;                     /* f28/16b0 */
#ifdef _WIN64
    PVOID                        Instrumentation[11];               /*    /16b8 */
#else
    PVOID                        Instrumentation[9];                /* f2c/ */
#endif
    GUID                         ActivityId;                        /* f50/1710 */
    PVOID                        SubProcessTag;                     /* f60/1720 */
    PVOID                        PerflibData;                       /* f64/1728 */
    PVOID                        EtwTraceData;                      /* f68/1730 */
    PVOID                        WinSockData;                       /* f6c/1738 */
    ULONG                        GdiBatchCount;                     /* f70/1740 */
    ULONG                        IdealProcessorValue;               /* f74/1744 */
    ULONG                        GuaranteedStackBytes;              /* f78/1748 */
    PVOID                        ReservedForPerf;                   /* f7c/1750 */
    PVOID                        ReservedForOle;                    /* f80/1758 */
    ULONG                        WaitingOnLoaderLock;               /* f84/1760 */
    PVOID                        SavedPriorityState;                /* f88/1768 */
    ULONG_PTR                    ReservedForCodeCoverage;           /* f8c/1770 */
    PVOID                        ThreadPoolData;                    /* f90/1778 */
    PVOID                       *TlsExpansionSlots;                 /* f94/1780 */
#ifdef _WIN64
    union {
        PVOID                    DeallocationBStore;                /*    /1788 */
        CHPE_V2_CPU_AREA_INFO   *ChpeV2CpuAreaInfo;                 /*    /1788 */
    } DUMMYUNIONNAME;
    PVOID                        BStoreLimit;                       /*    /1790 */
#endif
    ULONG                        MuiGeneration;                     /* f98/1798 */
    ULONG                        IsImpersonating;                   /* f9c/179c */
    PVOID                        NlsCache;                          /* fa0/17a0 */
    PVOID                        ShimData;                          /* fa4/17a8 */
    ULONG                        HeapVirtualAffinity;               /* fa8/17b0 */
    PVOID                        CurrentTransactionHandle;          /* fac/17b8 */
    TEB_ACTIVE_FRAME            *ActiveFrame;                       /* fb0/17c0 */
    TEB_FLS_DATA                *FlsSlots;                          /* fb4/17c8 */
    PVOID                        PreferredLanguages;                /* fb8/17d0 */
    PVOID                        UserPrefLanguages;                 /* fbc/17d8 */
    PVOID                        MergedPrefLanguages;               /* fc0/17e0 */
    ULONG                        MuiImpersonation;                  /* fc4/17e8 */
    USHORT                       CrossTebFlags;                     /* fc8/17ec */
    union {
        USHORT SameTebFlags;                                        /* fca/17ee */
        struct {
            USHORT SafeThunkCall : 1;
            USHORT InDebugPrint : 1;
            USHORT HasFiberData : 1;
            USHORT SkipThreadAttach : 1;
            USHORT WerInShipAssertCode : 1;
            USHORT RanProcessInit : 1;
            USHORT ClonedThread : 1;
            USHORT SuppressDebugMsg : 1;
            USHORT DisableUserStackWalk : 1;
            USHORT RtlExceptionAttached : 1;
            USHORT InitialThread : 1;
            USHORT SessionAware : 1;
            USHORT LoadOwner : 1;
            USHORT LoaderWorker : 1;
            USHORT SkipLoaderInit : 1;
            USHORT SkipFileAPIBrokering : 1;
        };
    };
    PVOID                        TxnScopeEnterCallback;             /* fcc/17f0 */
    PVOID                        TxnScopeExitCallback;              /* fd0/17f8 */
    PVOID                        TxnScopeContext;                   /* fd4/1800 */
    ULONG                        LockCount;                         /* fd8/1808 */
    LONG                         WowTebOffset;                      /* fdc/180c */
    PVOID                        ResourceRetValue;                  /* fe0/1810 */
    PVOID                        ReservedForWdf;                    /* fe4/1818 */
    ULONGLONG                    ReservedForCrt;                    /* fe8/1820 */
    GUID                         EffectiveContainerId;              /* ff0/1828 */
} TEB, *PTEB;

#include <stddef.h>
/* Layout pins, generated from the offset comments in the SAME Wine
 * header the structs were extracted from (Art. 4). */
_Static_assert(offsetof(PEB, InheritedAddressSpace) == 0x000, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ReadImageFileExecOptions) == 0x001, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, BeingDebugged) == 0x002, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, Mutant) == 0x008, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ImageBaseAddress) == 0x010, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, LdrData) == 0x018, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ProcessParameters) == 0x020, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, SubSystemData) == 0x028, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ProcessHeap) == 0x030, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, FastPebLock) == 0x038, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, AtlThunkSListPtr) == 0x040, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, IFEOKey) == 0x048, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, KernelCallbackTable) == 0x058, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, Reserved) == 0x060, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, AtlThunkSListPtr32) == 0x064, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ApiSetMap) == 0x068, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, TlsExpansionCounter) == 0x070, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, TlsBitmap) == 0x078, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, TlsBitmapBits) == 0x080, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ReadOnlySharedMemoryBase) == 0x088, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, SharedData) == 0x090, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ReadOnlyStaticServerData) == 0x098, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, AnsiCodePageData) == 0x0a0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, OemCodePageData) == 0x0a8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, UnicodeCaseTableData) == 0x0b0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, NumberOfProcessors) == 0x0b8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, NtGlobalFlag) == 0x0bc, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, CriticalSectionTimeout) == 0x0c0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, HeapSegmentReserve) == 0x0c8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, HeapSegmentCommit) == 0x0d0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, HeapDeCommitTotalFreeThreshold) == 0x0d8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, HeapDeCommitFreeBlockThreshold) == 0x0e0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, NumberOfHeaps) == 0x0e8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, MaximumNumberOfHeaps) == 0x0ec, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ProcessHeaps) == 0x0f0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, GdiSharedHandleTable) == 0x0f8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ProcessStarterHelper) == 0x100, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, GdiDCAttributeList) == 0x108, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, LoaderLock) == 0x110, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, OSMajorVersion) == 0x118, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, OSMinorVersion) == 0x11c, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, OSBuildNumber) == 0x120, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, OSPlatformId) == 0x124, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ImageSubSystem) == 0x128, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ImageSubSystemMajorVersion) == 0x12c, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ImageSubSystemMinorVersion) == 0x130, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ActiveProcessAffinityMask) == 0x138, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, GdiHandleBuffer) == 0x140, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, PostProcessInitRoutine) == 0x230, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, TlsExpansionBitmap) == 0x238, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, TlsExpansionBitmapBits) == 0x240, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, SessionId) == 0x2c0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, AppCompatFlags) == 0x2c8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, AppCompatFlagsUser) == 0x2d0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ShimData) == 0x2d8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, AppCompatInfo) == 0x2e0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, CSDVersion) == 0x2e8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ActivationContextData) == 0x2f8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ProcessAssemblyStorageMap) == 0x300, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, SystemDefaultActivationData) == 0x308, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, SystemAssemblyStorageMap) == 0x310, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, MinimumStackCommit) == 0x318, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, SparePointers) == 0x320, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, PatchLoaderData) == 0x330, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ChpeV2ProcessInfo) == 0x338, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, AppModelFeatureState) == 0x340, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, SpareUlongs) == 0x344, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, ActiveCodePage) == 0x34c, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, OemCodePage) == 0x34e, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, UseCaseMapping) == 0x350, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, UnusedNlsField) == 0x352, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, WerRegistrationData) == 0x358, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, WerShipAssertPtr) == 0x360, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, EcCodeBitMap) == 0x368, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, pImageHeaderHash) == 0x370, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, CsrServerReadOnlySharedMemoryBase) == 0x380, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, TppWorkerpListLock) == 0x388, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, TppWorkerpList) == 0x390, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, WaitOnAddressHashTable) == 0x3a0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, TelemetryCoverageHeader) == 0x7a0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, CloudFileFlags) == 0x7a8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, CloudFileDiagFlags) == 0x7ac, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, PlaceholderCompatibilityMode) == 0x7b0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, PlaceholderCompatibilityModeReserved) == 0x7b1, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, LeapSecondData) == 0x7b8, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, LeapSecondFlags) == 0x7c0, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB, NtGlobalFlag2) == 0x7c4, "PEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, Tib) == 0x0000, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, EnvironmentPointer) == 0x0038, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ClientId) == 0x0040, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ActiveRpcHandle) == 0x0050, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ThreadLocalStoragePointer) == 0x0058, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, Peb) == 0x0060, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, LastErrorValue) == 0x0068, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, CountOfOwnedCriticalSections) == 0x006c, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, CsrClientThread) == 0x0070, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, Win32ThreadInfo) == 0x0078, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, User32Reserved) == 0x0080, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, UserReserved) == 0x00e8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, WOW32Reserved) == 0x0100, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, CurrentLocale) == 0x0108, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, FpSoftwareStatusRegister) == 0x010c, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ReservedForDebuggerInstrumentation) == 0x0110, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, SystemReserved1) == 0x0190, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, PlaceholderCompatibilityMode) == 0x0280, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, PlaceholderHydrationAlwaysExplicit) == 0x0281, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, PlaceholderReserved) == 0x0282, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ProxiedProcessId) == 0x028c, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ActivationContextStack) == 0x0290, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, WorkingOnBehalfOfTicket) == 0x02b8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ExceptionCode) == 0x02c0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ActivationContextStackPointer) == 0x02c8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, InstrumentationCallbackSp) == 0x02d0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, InstrumentationCallbackPreviousPc) == 0x02d8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, InstrumentationCallbackPreviousSp) == 0x02e0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, TxFsContext) == 0x02e8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, InstrumentationCallbackDisabled) == 0x02ec, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, UnalignedLoadStoreExceptions) == 0x02ed, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, GdiTebBatch) == 0x02f0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, RealClientId) == 0x07d8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, GdiCachedProcessHandle) == 0x07e8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, GdiClientPID) == 0x07f0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, GdiClientTID) == 0x07f4, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, GdiThreadLocaleInfo) == 0x07f8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, Win32ClientInfo) == 0x0800, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, glDispatchTable) == 0x09f0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, glReserved1) == 0x1138, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, glReserved2) == 0x1220, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, glSectionInfo) == 0x1228, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, glSection) == 0x1230, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, glTable) == 0x1238, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, glCurrentRC) == 0x1240, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, glContext) == 0x1248, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, LastStatusValue) == 0x1250, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, StaticUnicodeString) == 0x1258, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, StaticUnicodeBuffer) == 0x1268, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, DeallocationStack) == 0x1478, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, TlsSlots) == 0x1480, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, TlsLinks) == 0x1680, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, Vdm) == 0x1690, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ReservedForNtRpc) == 0x1698, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, DbgSsReserved) == 0x16a0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, HardErrorMode) == 0x16b0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, Instrumentation) == 0x16b8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ActivityId) == 0x1710, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, SubProcessTag) == 0x1720, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, PerflibData) == 0x1728, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, EtwTraceData) == 0x1730, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, WinSockData) == 0x1738, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, GdiBatchCount) == 0x1740, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, IdealProcessorValue) == 0x1744, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, GuaranteedStackBytes) == 0x1748, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ReservedForPerf) == 0x1750, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ReservedForOle) == 0x1758, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, WaitingOnLoaderLock) == 0x1760, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, SavedPriorityState) == 0x1768, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ReservedForCodeCoverage) == 0x1770, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ThreadPoolData) == 0x1778, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, TlsExpansionSlots) == 0x1780, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, BStoreLimit) == 0x1790, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, MuiGeneration) == 0x1798, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, IsImpersonating) == 0x179c, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, NlsCache) == 0x17a0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ShimData) == 0x17a8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, HeapVirtualAffinity) == 0x17b0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, CurrentTransactionHandle) == 0x17b8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ActiveFrame) == 0x17c0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, FlsSlots) == 0x17c8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, PreferredLanguages) == 0x17d0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, UserPrefLanguages) == 0x17d8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, MergedPrefLanguages) == 0x17e0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, MuiImpersonation) == 0x17e8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, CrossTebFlags) == 0x17ec, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, TxnScopeEnterCallback) == 0x17f0, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, TxnScopeExitCallback) == 0x17f8, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, TxnScopeContext) == 0x1800, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, LockCount) == 0x1808, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, WowTebOffset) == 0x180c, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ResourceRetValue) == 0x1810, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ReservedForWdf) == 0x1818, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, ReservedForCrt) == 0x1820, "TEB x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB, EffectiveContainerId) == 0x1828, "TEB x64 layout (offset comment in the Wine header)");

#endif /* PROSKRNL_ABI_NTPEBTEB_H */
