/* abi/ntpsapi.h - GENERATED by tools/gen_abi.py from wine/include/{winnt.h,winternl.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTPSAPI_H
#define PROSKRNL_ABI_NTPSAPI_H

#include "abi/ntdef.h"

/* Process access rights, extracted from wine/include/winnt.h. */
#define PROCESS_TERMINATE 0x0001
#define PROCESS_CREATE_THREAD 0x0002
#define PROCESS_VM_OPERATION 0x0008
#define PROCESS_VM_READ 0x0010
#define PROCESS_VM_WRITE 0x0020
#define PROCESS_QUERY_INFORMATION 0x0400
#define PROCESS_SET_INFORMATION 0x0200
#define PROCESS_SUSPEND_RESUME 0x0800
#define PROCESS_QUERY_LIMITED_INFORMATION 0x1000
#define PROCESS_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0xffff)

/* The TEB begins with an NT_TIB (the one TEB slice the M4 boundary
 * carries; the full byte-exact TEB/PEB arrive with M7). Extracted
 * verbatim from wine/include/winnt.h; asserts pin the x64 layout. */
struct _EXCEPTION_REGISTRATION_RECORD;
typedef struct {
	struct _EXCEPTION_REGISTRATION_RECORD *ExceptionList;
	PVOID StackBase;
	PVOID StackLimit;
	PVOID SubSystemTib;
	union {
          PVOID FiberData;
          DWORD Version;
	} DUMMYUNIONNAME;
	PVOID ArbitraryUserPointer;
	struct _NT_TIB *Self;
} NT_TIB, *PNT_TIB;

#include <stddef.h>
_Static_assert(sizeof(NT_TIB) == 56, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, StackBase) == 8, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, StackLimit) == 16, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, ArbitraryUserPointer) == 40, "NT_TIB x64 layout");
_Static_assert(offsetof(NT_TIB, Self) == 48, "NT_TIB x64 layout");

/* Extracted verbatim from wine/include/winternl.h. */
typedef struct {
   HANDLE UniqueProcess;
   HANDLE UniqueThread;
} CLIENT_ID, *PCLIENT_ID;

/* The M4 Ps Nt* surface; signatures extracted verbatim from
 * wine/include/winternl.h (linkage macros dropped). */
NTSTATUS NtTerminateProcess(HANDLE,LONG);
NTSTATUS NtDisplayString(PUNICODE_STRING);

#endif /* PROSKRNL_ABI_NTPSAPI_H */
