/* abi/ntregapi.h - GENERATED by tools/gen_abi.py from wine/include/{winnt.h,winternl.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTREGAPI_H
#define PROSKRNL_ABI_NTREGAPI_H

#include "abi/ntdef.h"

/* Key access rights + value types, extracted from wine/include/winnt.h. */
#define KEY_QUERY_VALUE 0x00000001
#define KEY_SET_VALUE 0x00000002
#define KEY_CREATE_SUB_KEY 0x00000004
#define KEY_ENUMERATE_SUB_KEYS 0x00000008
#define KEY_NOTIFY 0x00000010
#define KEY_CREATE_LINK 0x00000020
#define KEY_WOW64_64KEY 0x00000100
#define KEY_WOW64_32KEY 0x00000200
#define KEY_WOW64_RES 0x00000300
#define KEY_READ ((STANDARD_RIGHTS_READ| KEY_QUERY_VALUE| KEY_ENUMERATE_SUB_KEYS| KEY_NOTIFY) & (~SYNCHRONIZE) )
#define KEY_WRITE ((STANDARD_RIGHTS_WRITE| KEY_SET_VALUE| KEY_CREATE_SUB_KEY) & (~SYNCHRONIZE) )
#define KEY_EXECUTE ((KEY_READ) & (~SYNCHRONIZE))
#define KEY_ALL_ACCESS ((STANDARD_RIGHTS_ALL| KEY_QUERY_VALUE| KEY_SET_VALUE| KEY_CREATE_SUB_KEY| KEY_ENUMERATE_SUB_KEYS| KEY_NOTIFY| KEY_CREATE_LINK) & (~SYNCHRONIZE) )
#define REG_NONE 0	/* no type */
#define REG_SZ 1	/* string type (ASCII) */
#define REG_EXPAND_SZ 2	/* string, includes %ENVVAR% (expanded by caller) (ASCII) */
#define REG_BINARY 3	/* binary format, callerspecific */
#define REG_DWORD 4	/* DWORD in little endian format */
#define REG_DWORD_LITTLE_ENDIAN 4	/* DWORD in little endian format */
#define REG_DWORD_BIG_ENDIAN 5	/* DWORD in big endian format  */
#define REG_LINK 6	/* symbolic link (UNICODE) */
#define REG_MULTI_SZ 7	/* multiple strings, delimited by \0, terminated by \0\0 (ASCII) */
#define REG_QWORD 11	/* QWORD in little endian format */

/* Extracted verbatim from wine/include/winternl.h. */
typedef enum {
    KeyValueBasicInformation,
    KeyValueFullInformation,
    KeyValuePartialInformation,
    KeyValueFullInformationAlign64,
    KeyValuePartialInformationAlign64,
    KeyValueLayerInformation,
} KEY_VALUE_INFORMATION_CLASS;

typedef struct {
    ULONG TitleIndex;
    ULONG Type;
    ULONG DataOffset;
    ULONG DataLength;
    ULONG NameLength;
    WCHAR Name[1];
} KEY_VALUE_FULL_INFORMATION, *PKEY_VALUE_FULL_INFORMATION;

typedef struct {
    ULONG TitleIndex;
    ULONG Type;
    ULONG DataLength;
    UCHAR Data[1];
} KEY_VALUE_PARTIAL_INFORMATION, *PKEY_VALUE_PARTIAL_INFORMATION;

/* The M7 registry Nt* slice (graceful failure until Cm at M8);
 * signatures extracted verbatim from wine/include/winternl.h. */
NTSTATUS NtOpenKey(PHANDLE,ACCESS_MASK,const OBJECT_ATTRIBUTES *);
NTSTATUS NtQueryValueKey(HANDLE,const UNICODE_STRING *,KEY_VALUE_INFORMATION_CLASS,void *,DWORD,DWORD *);

#endif /* PROSKRNL_ABI_NTREGAPI_H */
