/* abi/ntregapi.h - GENERATED by tools/gen_abi.py from wine/include/{winnt.h,winternl.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTREGAPI_H
#define PROSKRNL_ABI_NTREGAPI_H

#include "abi/ntdef.h"

/* Key access rights + value types, extracted from wine/include/winnt.h. */
#define KEY_QUERY_VALUE 0x00000001
#define KEY_SET_VALUE 0x00000002
#define KEY_CREATE_SUB_KEY 0x00000004
#define KEY_ENUMERATE_SUB_KEYS 0x00000008
#define KEY_NOTIFY 0x00000010
#define KEY_CREATE_LINK 0x00000020
#define KEY_WOW64_64KEY 0x00000100
#define KEY_WOW64_32KEY 0x00000200
#define KEY_WOW64_RES 0x00000300
#define KEY_READ ((STANDARD_RIGHTS_READ| KEY_QUERY_VALUE| KEY_ENUMERATE_SUB_KEYS| KEY_NOTIFY) & (~SYNCHRONIZE) )
#define KEY_WRITE ((STANDARD_RIGHTS_WRITE| KEY_SET_VALUE| KEY_CREATE_SUB_KEY) & (~SYNCHRONIZE) )
#define KEY_EXECUTE ((KEY_READ) & (~SYNCHRONIZE))
#define KEY_ALL_ACCESS ((STANDARD_RIGHTS_ALL| KEY_QUERY_VALUE| KEY_SET_VALUE| KEY_CREATE_SUB_KEY| KEY_ENUMERATE_SUB_KEYS| KEY_NOTIFY| KEY_CREATE_LINK) & (~SYNCHRONIZE) )
#define REG_NONE 0	/* no type */
#define REG_SZ 1	/* string type (ASCII) */
#define REG_EXPAND_SZ 2	/* string, includes %ENVVAR% (expanded by caller) (ASCII) */
#define REG_BINARY 3	/* binary format, callerspecific */
#define REG_DWORD 4	/* DWORD in little endian format */
#define REG_DWORD_LITTLE_ENDIAN 4	/* DWORD in little endian format */
#define REG_DWORD_BIG_ENDIAN 5	/* DWORD in big endian format  */
#define REG_LINK 6	/* symbolic link (UNICODE) */
#define REG_MULTI_SZ 7	/* multiple strings, delimited by \0, terminated by \0\0 (ASCII) */
#define REG_QWORD 11	/* QWORD in little endian format */
#define REG_OPTION_NON_VOLATILE 0x00000000
#define REG_OPTION_VOLATILE 0x00000001
#define REG_OPTION_CREATE_LINK 0x00000002
#define REG_CREATED_NEW_KEY 0x00000001
#define REG_OPENED_EXISTING_KEY 0x00000002

/* Extracted verbatim from wine/include/winternl.h. */
typedef enum {
    KeyBasicInformation,
    KeyNodeInformation,
    KeyFullInformation,
    KeyNameInformation,
    KeyCachedInformation,
    KeyFlagsInformation,
    KeyVirtualizationInformation,
    KeyHandleTagsInformation,
    KeyTrustInformation,
    KeyLayerInformation,
    MaxKeyInfoClass
} KEY_INFORMATION_CLASS;

typedef enum {
    KeyValueBasicInformation,
    KeyValueFullInformation,
    KeyValuePartialInformation,
    KeyValueFullInformationAlign64,
    KeyValuePartialInformationAlign64,
    KeyValueLayerInformation,
} KEY_VALUE_INFORMATION_CLASS;

typedef struct {
    LARGE_INTEGER LastWriteTime;
    ULONG         TitleIndex;
    ULONG         NameLength;
    WCHAR         Name[1];
} KEY_BASIC_INFORMATION, *PKEY_BASIC_INFORMATION;

typedef struct {
    LARGE_INTEGER LastWriteTime;
    ULONG         TitleIndex;
    ULONG         ClassOffset;
    ULONG         ClassLength;
    ULONG         NameLength;
    WCHAR         Name[1];
   /* Class[1]; */
} KEY_NODE_INFORMATION, *PKEY_NODE_INFORMATION;

typedef struct {
    LARGE_INTEGER LastWriteTime;
    ULONG         TitleIndex;
    ULONG         ClassOffset;
    ULONG         ClassLength;
    ULONG         SubKeys;
    ULONG         MaxNameLen;
    ULONG         MaxClassLen;
    ULONG         Values;
    ULONG         MaxValueNameLen;
    ULONG         MaxValueDataLen;
    WCHAR         Class[1];
} KEY_FULL_INFORMATION, *PKEY_FULL_INFORMATION;

typedef struct {
    ULONG TitleIndex;
    ULONG Type;
    ULONG NameLength;
    WCHAR Name[1];
} KEY_VALUE_BASIC_INFORMATION, *PKEY_VALUE_BASIC_INFORMATION;

typedef struct {
    ULONG TitleIndex;
    ULONG Type;
    ULONG DataOffset;
    ULONG DataLength;
    ULONG NameLength;
    WCHAR Name[1];
} KEY_VALUE_FULL_INFORMATION, *PKEY_VALUE_FULL_INFORMATION;

typedef struct {
    ULONG TitleIndex;
    ULONG Type;
    ULONG DataLength;
    UCHAR Data[1];
} KEY_VALUE_PARTIAL_INFORMATION, *PKEY_VALUE_PARTIAL_INFORMATION;

typedef struct {
    ULONG         NameLength;
    WCHAR         Name[1];
} KEY_NAME_INFORMATION, *PKEY_NAME_INFORMATION;

typedef struct {
    LARGE_INTEGER LastWriteTime;
    ULONG         TitleIndex;
    ULONG         SubKeys;
    ULONG         MaxNameLen;
    ULONG         Values;
    ULONG         MaxValueNameLen;
    ULONG         MaxValueDataLen;
    ULONG         NameLength;
} KEY_CACHED_INFORMATION, *PKEY_CACHED_INFORMATION;

typedef struct {
    ULONG Type;
    ULONG DataLength;
    UCHAR Data[1];
} KEY_VALUE_PARTIAL_INFORMATION_ALIGN64, *PKEY_VALUE_PARTIAL_INFORMATION_ALIGN64;

/* The Cm registry surface (M8);
 * signatures extracted verbatim from wine/include/winternl.h. */
NTSTATUS NtCreateKey(PHANDLE,ACCESS_MASK,const OBJECT_ATTRIBUTES*,ULONG,const UNICODE_STRING*,ULONG,PULONG);
NTSTATUS NtOpenKey(PHANDLE,ACCESS_MASK,const OBJECT_ATTRIBUTES *);
NTSTATUS NtOpenKeyEx(PHANDLE,ACCESS_MASK,const OBJECT_ATTRIBUTES*,ULONG);
NTSTATUS NtDeleteKey(HANDLE);
NTSTATUS NtDeleteValueKey(HANDLE,const UNICODE_STRING *);
NTSTATUS NtSetValueKey(HANDLE,const UNICODE_STRING *,ULONG,ULONG,const void *,ULONG);
NTSTATUS NtQueryValueKey(HANDLE,const UNICODE_STRING *,KEY_VALUE_INFORMATION_CLASS,void *,DWORD,DWORD *);
NTSTATUS NtEnumerateKey(HANDLE,ULONG,KEY_INFORMATION_CLASS,void *,DWORD,DWORD *);
NTSTATUS NtEnumerateValueKey(HANDLE,ULONG,KEY_VALUE_INFORMATION_CLASS,PVOID,ULONG,PULONG);
NTSTATUS NtQueryKey(HANDLE,KEY_INFORMATION_CLASS,void *,DWORD,DWORD *);
NTSTATUS NtFlushKey(HANDLE);

/* Info-class layouts the kernel's CmpFill*Info arithmetic leans on (fixed
 * headers + trailing-array offsets), pinned x64/LLP64 so a drift in the
 * extraction fails at compile time (Art. 4). */
_Static_assert(offsetof(KEY_BASIC_INFORMATION, Name) == 16, "KEY_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_NODE_INFORMATION, Name) == 24, "KEY_NODE_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_FULL_INFORMATION, Class) == 44, "KEY_FULL_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_VALUE_BASIC_INFORMATION, Name) == 12,
               "KEY_VALUE_BASIC_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_VALUE_FULL_INFORMATION, Name) == 20,
               "KEY_VALUE_FULL_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_VALUE_PARTIAL_INFORMATION, Data) == 12,
               "KEY_VALUE_PARTIAL_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_NAME_INFORMATION, Name) == 4, "KEY_NAME_INFORMATION x64 layout");
_Static_assert(sizeof(KEY_CACHED_INFORMATION) == 40, "KEY_CACHED_INFORMATION x64 layout");
_Static_assert(offsetof(KEY_VALUE_PARTIAL_INFORMATION_ALIGN64, Data) == 8,
               "KEY_VALUE_PARTIAL_INFORMATION_ALIGN64 x64 layout");

#endif /* PROSKRNL_ABI_NTREGAPI_H */
