/* abi/ntseapi.h - GENERATED by tools/gen_abi.py from wine/include/{winnt.h,winternl.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTSEAPI_H
#define PROSKRNL_ABI_NTSEAPI_H

#include "abi/ntdef.h"
#include "abi/ntobapi.h" /* GENERIC_MAPPING */

/* Non-numeric scaffold (shapes, not values). __MSABI_LONG carries the LP64
 * 'l' suffix in Wine's headers; the kernel is char/short/int/long-long only,
 * so the suffix is dropped (values are 32-bit RIDs either way). */
#ifndef __MSABI_LONG
#define __MSABI_LONG(x) x
#endif
typedef BOOLEAN *PBOOLEAN;
typedef DWORD *PDWORD;
/* winnt.h: `typedef BOOLEAN SECURITY_CONTEXT_TRACKING_MODE` (wrapped over
 * two lines there, so re-typed as scaffold: a shape, not a value). */
typedef BOOLEAN SECURITY_CONTEXT_TRACKING_MODE;

/* Pointer/handle scaffold typedefs, extracted from wine/include/winnt.h. */
typedef PVOID PSECURITY_DESCRIPTOR;
typedef PVOID PSID;
typedef DWORD SECURITY_INFORMATION, *PSECURITY_INFORMATION;
typedef WORD SECURITY_DESCRIPTOR_CONTROL, *PSECURITY_DESCRIPTOR_CONTROL;

/* Token access rights, extracted from wine/include/winnt.h. */
#define TOKEN_ASSIGN_PRIMARY 0x0001
#define TOKEN_DUPLICATE 0x0002
#define TOKEN_IMPERSONATE 0x0004
#define TOKEN_QUERY 0x0008
#define TOKEN_QUERY_SOURCE 0x0010
#define TOKEN_ADJUST_PRIVILEGES 0x0020
#define TOKEN_ADJUST_GROUPS 0x0040
#define TOKEN_ADJUST_DEFAULT 0x0080
#define TOKEN_ADJUST_SESSIONID 0x0100
#define TOKEN_EXECUTE STANDARD_RIGHTS_EXECUTE
#define TOKEN_READ (STANDARD_RIGHTS_READ|TOKEN_QUERY)
#define TOKEN_WRITE (STANDARD_RIGHTS_WRITE     | TOKEN_ADJUST_PRIVILEGES | TOKEN_ADJUST_GROUPS | TOKEN_ADJUST_DEFAULT )
#define TOKEN_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | TOKEN_ASSIGN_PRIMARY | TOKEN_DUPLICATE | TOKEN_IMPERSONATE | TOKEN_QUERY | TOKEN_QUERY_SOURCE | TOKEN_ADJUST_PRIVILEGES | TOKEN_ADJUST_GROUPS | TOKEN_ADJUST_SESSIONID | TOKEN_ADJUST_DEFAULT )
#define ACCESS_SYSTEM_SECURITY 0x01000000

/* SID scaffolding limits, extracted from wine/include/winnt.h. */
#define ANYSIZE_ARRAY 1
#define SID_REVISION (1)	/* Current revision */
#define SID_MAX_SUB_AUTHORITIES (15)	/* current max subauths */
#define SID_RECOMMENDED_SUB_AUTHORITIES (1)	/* recommended subauths */
#define SECURITY_MAX_SID_SIZE (sizeof(SID) - sizeof(DWORD) + (SID_MAX_SUB_AUTHORITIES * sizeof(DWORD)))
#define TOKEN_SOURCE_LENGTH 8

/* SID identifier authorities + RIDs, extracted from wine/include/winnt.h. */
#define SECURITY_WORLD_SID_AUTHORITY {0,0,0,0,0,1}
#define SECURITY_LOCAL_SID_AUTHORITY {0,0,0,0,0,2}
#define SECURITY_NT_AUTHORITY {0,0,0,0,0,5}
#define SECURITY_MANDATORY_LABEL_AUTHORITY {0,0,0,0,0,16}
#define SECURITY_WORLD_RID __MSABI_LONG(0x00000000)
#define SECURITY_LOCAL_RID __MSABI_LONG(0X00000000)
#define SECURITY_INTERACTIVE_RID __MSABI_LONG(0x00000004)
#define SECURITY_LOGON_IDS_RID __MSABI_LONG(0x00000005)
#define SECURITY_AUTHENTICATED_USER_RID __MSABI_LONG(0x0000000B)
#define SECURITY_LOCAL_SYSTEM_RID __MSABI_LONG(0x00000012)
#define SECURITY_NT_NON_UNIQUE __MSABI_LONG(0x00000015)
#define SECURITY_BUILTIN_DOMAIN_RID __MSABI_LONG(0x00000020)
#define DOMAIN_GROUP_RID_ADMINS __MSABI_LONG(0x00000200)
#define DOMAIN_GROUP_RID_USERS __MSABI_LONG(0x00000201)
#define DOMAIN_ALIAS_RID_ADMINS __MSABI_LONG(0x00000220)
#define DOMAIN_ALIAS_RID_USERS __MSABI_LONG(0x00000221)
#define SECURITY_MANDATORY_HIGH_RID __MSABI_LONG(0x00003000)

/* Group/privilege attribute bits, extracted from wine/include/winnt.h. */
#define SE_GROUP_MANDATORY 0x00000001
#define SE_GROUP_ENABLED_BY_DEFAULT 0x00000002
#define SE_GROUP_ENABLED 0x00000004
#define SE_GROUP_OWNER 0x00000008
#define SE_GROUP_USE_FOR_DENY_ONLY 0x00000010
#define SE_GROUP_INTEGRITY 0x00000020
#define SE_GROUP_INTEGRITY_ENABLED 0x00000040
#define SE_GROUP_LOGON_ID 0xC0000000
#define SE_GROUP_RESOURCE 0x20000000
#define SE_GROUP_VALID_ATTRIBUTES 0xE000007F
#define SE_PRIVILEGE_ENABLED_BY_DEFAULT 0x00000001
#define SE_PRIVILEGE_ENABLED 0x00000002
#define SE_PRIVILEGE_REMOVED 0x00000004
#define SE_PRIVILEGE_USED_FOR_ACCESS 0x80000000
#define SE_PRIVILEGE_VALID_ATTRIBUTES 0x80000007
#define PRIVILEGE_SET_ALL_NECESSARY 1

/* ACL/ACE revisions, types and flags, extracted from wine/include/winnt.h. */
#define ACL_REVISION1 1
#define ACL_REVISION2 2
#define ACL_REVISION3 3
#define ACL_REVISION4 4
#define MIN_ACL_REVISION ACL_REVISION2
#define MAX_ACL_REVISION ACL_REVISION4
#define ACL_REVISION 2
#define ACCESS_ALLOWED_ACE_TYPE 0x0
#define ACCESS_DENIED_ACE_TYPE 0x1
#define SYSTEM_AUDIT_ACE_TYPE 0x2
#define SYSTEM_ALARM_ACE_TYPE 0x3
#define SYSTEM_MANDATORY_LABEL_ACE_TYPE 0x11
#define OBJECT_INHERIT_ACE 0x01
#define CONTAINER_INHERIT_ACE 0x02
#define NO_PROPAGATE_INHERIT_ACE 0x04
#define INHERIT_ONLY_ACE 0x08
#define INHERITED_ACE 0x10
#define VALID_INHERIT_FLAGS 0x1F

/* Security-descriptor control/info bits, extracted from wine/include/winnt.h. */
#define SECURITY_DESCRIPTOR_REVISION 1
#define SE_OWNER_DEFAULTED 0x00000001
#define SE_GROUP_DEFAULTED 0x00000002
#define SE_DACL_PRESENT 0x00000004
#define SE_DACL_DEFAULTED 0x00000008
#define SE_SACL_PRESENT 0x00000010
#define SE_SACL_DEFAULTED 0x00000020
#define SE_DACL_AUTO_INHERITED 0x00000400
#define SE_SACL_AUTO_INHERITED 0x00000800
#define SE_DACL_PROTECTED 0x00001000
#define SE_SACL_PROTECTED 0x00002000
#define SE_SELF_RELATIVE 0x00008000
#define OWNER_SECURITY_INFORMATION 0x00000001
#define GROUP_SECURITY_INFORMATION 0x00000002
#define DACL_SECURITY_INFORMATION 0x00000004
#define SACL_SECURITY_INFORMATION 0x00000008
#define LABEL_SECURITY_INFORMATION 0x00000010

/* Privilege LUID low parts, extracted from wine/include/winternl.h. */
#define SE_MIN_WELL_KNOWN_PRIVILEGE 2
#define SE_CREATE_TOKEN_PRIVILEGE 2
#define SE_ASSIGNPRIMARYTOKEN_PRIVILEGE 3
#define SE_LOCK_MEMORY_PRIVILEGE 4
#define SE_INCREASE_QUOTA_PRIVILEGE 5
#define SE_MACHINE_ACCOUNT_PRIVILEGE 6
#define SE_TCB_PRIVILEGE 7
#define SE_SECURITY_PRIVILEGE 8
#define SE_TAKE_OWNERSHIP_PRIVILEGE 9
#define SE_LOAD_DRIVER_PRIVILEGE 10
#define SE_SYSTEM_PROFILE_PRIVILEGE 11
#define SE_SYSTEMTIME_PRIVILEGE 12
#define SE_PROF_SINGLE_PROCESS_PRIVILEGE 13
#define SE_INC_BASE_PRIORITY_PRIVILEGE 14
#define SE_CREATE_PAGEFILE_PRIVILEGE 15
#define SE_CREATE_PERMANENT_PRIVILEGE 16
#define SE_BACKUP_PRIVILEGE 17
#define SE_RESTORE_PRIVILEGE 18
#define SE_SHUTDOWN_PRIVILEGE 19
#define SE_DEBUG_PRIVILEGE 20
#define SE_AUDIT_PRIVILEGE 21
#define SE_SYSTEM_ENVIRONMENT_PRIVILEGE 22
#define SE_CHANGE_NOTIFY_PRIVILEGE 23
#define SE_REMOTE_SHUTDOWN_PRIVILEGE 24
#define SE_UNDOCK_PRIVILEGE 25
#define SE_SYNC_AGENT_PRIVILEGE 26
#define SE_ENABLE_DELEGATION_PRIVILEGE 27
#define SE_MANAGE_VOLUME_PRIVILEGE 28
#define SE_IMPERSONATE_PRIVILEGE 29
#define SE_CREATE_GLOBAL_PRIVILEGE 30
#define SE_MAX_WELL_KNOWN_PRIVILEGE SE_CREATE_GLOBAL_PRIVILEGE

/* Enums, extracted verbatim from wine/include/winnt.h. */
typedef enum {
  TokenElevationTypeDefault = 1,
  TokenElevationTypeFull,
  TokenElevationTypeLimited
} TOKEN_ELEVATION_TYPE, *PTOKEN_ELEVATION_TYPE;

typedef enum {
    TokenUser = 1,
    TokenGroups = 2,
    TokenPrivileges = 3,
    TokenOwner = 4,
    TokenPrimaryGroup = 5,
    TokenDefaultDacl = 6,
    TokenSource = 7,
    TokenType = 8,
    TokenImpersonationLevel = 9,
    TokenStatistics = 10,
    TokenRestrictedSids = 11,
    TokenSessionId = 12,
    TokenGroupsAndPrivileges = 13,
    TokenSessionReference = 14,
    TokenSandBoxInert = 15,
    TokenAuditPolicy = 16,
    TokenOrigin = 17,
    TokenElevationType = 18,
    TokenLinkedToken = 19,
    TokenElevation = 20,
    TokenHasRestrictions = 21,
    TokenAccessInformation = 22,
    TokenVirtualizationAllowed = 23,
    TokenVirtualizationEnabled = 24,
    TokenIntegrityLevel = 25,
    TokenUIAccess = 26,
    TokenMandatoryPolicy = 27,
    TokenLogonSid = 28,
    TokenIsAppContainer = 29,
    TokenCapabilities = 30,
    TokenAppContainerSid = 31,
    TokenAppContainerNumber = 32,
    TokenUserClaimAttributes = 33,
    TokenDeviceClaimAttributes = 34,
    TokenRestrictedUserClaimAttributes = 35,
    TokenRestrictedDeviceClaimAttributes = 36,
    TokenDeviceGroups = 37,
    TokenRestrictedDeviceGroups = 38,
    TokenSecurityAttributes = 39,
    TokenIsRestricted = 40,
    TokenProcessTrustLevel = 41,
    TokenPrivateNameSpace = 42,
    TokenSingletonAttributes = 43,
    TokenBnoIsolation = 44,
    TokenChildProcessFlags = 45,
    TokenIsLessPrivilegedAppContainer = 46,
    TokenIsSandboxed = 47,
    TokenIsAppSilo = 48,
    TokenLoggingInformation = 49,
    TokenLearningMode = 50,
    MaxTokenInfoClass
} TOKEN_INFORMATION_CLASS;

typedef enum {
  TokenPrimary = 1,
  TokenImpersonation
} TOKEN_TYPE;

typedef enum {
  SecurityAnonymous,
  SecurityIdentification,
  SecurityImpersonation,
  SecurityDelegation
} SECURITY_IMPERSONATION_LEVEL, *PSECURITY_IMPERSONATION_LEVEL;

typedef struct
{
    BYTE Value[6];
} SID_IDENTIFIER_AUTHORITY, *PSID_IDENTIFIER_AUTHORITY;

typedef struct {
    BYTE Revision;
    BYTE SubAuthorityCount;
    SID_IDENTIFIER_AUTHORITY IdentifierAuthority;
    DWORD SubAuthority[1];
} SID,*PISID;

typedef struct {
  PSID  Sid;
  DWORD Attributes;
} SID_AND_ATTRIBUTES, *PSID_AND_ATTRIBUTES;

typedef struct {
    DWORD LowPart;
    LONG HighPart;
} LUID, *PLUID;

#pragma pack(push,4)
typedef struct {
  LUID   Luid;
  DWORD  Attributes;
} LUID_AND_ATTRIBUTES, *PLUID_AND_ATTRIBUTES;
#pragma pack(pop)

typedef struct {
    DWORD PrivilegeCount;
    DWORD Control;
    LUID_AND_ATTRIBUTES Privilege[ANYSIZE_ARRAY];
} PRIVILEGE_SET, *PPRIVILEGE_SET;

typedef struct {
    BYTE AclRevision;
    BYTE Sbz1;
    WORD AclSize;
    WORD AceCount;
    WORD Sbz2;
} ACL, *PACL;

typedef struct {
	BYTE	AceType;
	BYTE	AceFlags;
	WORD	AceSize;
} ACE_HEADER,*PACE_HEADER;

typedef struct {
	ACE_HEADER	Header;
	DWORD		Mask;
	DWORD		SidStart;
} ACCESS_ALLOWED_ACE,*PACCESS_ALLOWED_ACE;

typedef struct {
	ACE_HEADER	Header;
	DWORD		Mask;
	DWORD		SidStart;
} ACCESS_DENIED_ACE,*PACCESS_DENIED_ACE;

typedef struct {
    BYTE Revision;
    BYTE Sbz1;
    SECURITY_DESCRIPTOR_CONTROL Control;
    DWORD Owner;
    DWORD Group;
    DWORD Sacl;
    DWORD Dacl;
} SECURITY_DESCRIPTOR_RELATIVE, *PISECURITY_DESCRIPTOR_RELATIVE;

typedef struct {
    BYTE Revision;
    BYTE Sbz1;
    SECURITY_DESCRIPTOR_CONTROL Control;
    PSID Owner;
    PSID Group;
    PACL Sacl;
    PACL Dacl;
} SECURITY_DESCRIPTOR, *PISECURITY_DESCRIPTOR;

typedef struct {
    SID_AND_ATTRIBUTES User;
} TOKEN_USER, *PTOKEN_USER;

typedef struct {
    DWORD GroupCount;
    SID_AND_ATTRIBUTES Groups[ANYSIZE_ARRAY];
} TOKEN_GROUPS, *PTOKEN_GROUPS;

typedef struct {
  DWORD PrivilegeCount;
  LUID_AND_ATTRIBUTES Privileges[ANYSIZE_ARRAY];
} TOKEN_PRIVILEGES, *PTOKEN_PRIVILEGES;

typedef struct {
  PSID Owner;
} TOKEN_OWNER, *PTOKEN_OWNER;

typedef struct {
  PSID PrimaryGroup;
} TOKEN_PRIMARY_GROUP, *PTOKEN_PRIMARY_GROUP;

typedef struct {
  PACL DefaultDacl;
} TOKEN_DEFAULT_DACL, *PTOKEN_DEFAULT_DACL;

typedef struct {
  char SourceName[TOKEN_SOURCE_LENGTH];
  LUID SourceIdentifier;
} TOKEN_SOURCE, *PTOKEN_SOURCE;

typedef struct {
  DWORD				Length;
  SECURITY_IMPERSONATION_LEVEL	ImpersonationLevel;
  SECURITY_CONTEXT_TRACKING_MODE ContextTrackingMode;
  BOOLEAN			EffectiveOnly;
} SECURITY_QUALITY_OF_SERVICE, *PSECURITY_QUALITY_OF_SERVICE;

#pragma pack(push,4)
typedef struct {
  LUID  TokenId;
  LUID  AuthenticationId;
  LARGE_INTEGER ExpirationTime;
  TOKEN_TYPE    TokenType;
  SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
  DWORD DynamicCharged;
  DWORD DynamicAvailable;
  DWORD GroupCount;
  DWORD PrivilegeCount;
  LUID  ModifiedId;
} TOKEN_STATISTICS;
#pragma pack(pop)

typedef struct {
  DWORD TokenIsElevated;
} TOKEN_ELEVATION, * PTOKEN_ELEVATION;

typedef struct {
  SID_AND_ATTRIBUTES Label;
} TOKEN_MANDATORY_LABEL, * PTOKEN_MANDATORY_LABEL;

typedef struct {
  PSID TokenAppContainer;
} TOKEN_APPCONTAINER_INFORMATION, * PTOKEN_APPCONTAINER_INFORMATION;

/* The CUI-2 Se surface; signatures extracted verbatim from
 * wine/include/winternl.h (linkage macros dropped). */
NTSTATUS NtAccessCheck(PSECURITY_DESCRIPTOR,HANDLE,ACCESS_MASK,PGENERIC_MAPPING,PPRIVILEGE_SET,PULONG,PULONG,NTSTATUS*);
NTSTATUS NtAdjustPrivilegesToken(HANDLE,BOOLEAN,PTOKEN_PRIVILEGES,DWORD,PTOKEN_PRIVILEGES,PDWORD);
NTSTATUS NtAllocateLocallyUniqueId(PLUID lpLuid);
NTSTATUS NtDuplicateToken(HANDLE,ACCESS_MASK,POBJECT_ATTRIBUTES,BOOLEAN,TOKEN_TYPE,PHANDLE);
NTSTATUS NtOpenProcessToken(HANDLE,DWORD,HANDLE *);
NTSTATUS NtOpenProcessTokenEx(HANDLE,DWORD,DWORD,HANDLE *);
NTSTATUS NtOpenThreadToken(HANDLE,DWORD,BOOLEAN,HANDLE *);
NTSTATUS NtOpenThreadTokenEx(HANDLE,DWORD,BOOLEAN,DWORD,HANDLE *);
NTSTATUS NtPrivilegeCheck(HANDLE,PPRIVILEGE_SET,PBOOLEAN);
NTSTATUS NtQueryInformationToken(HANDLE,TOKEN_INFORMATION_CLASS,PVOID,ULONG,PULONG);
NTSTATUS NtQuerySecurityObject(HANDLE,SECURITY_INFORMATION,PSECURITY_DESCRIPTOR,ULONG,PULONG);
NTSTATUS NtSetSecurityObject(HANDLE,SECURITY_INFORMATION,PSECURITY_DESCRIPTOR);

/* x64/LLP64 layouts the kernel's Se marshalling arithmetic leans on, pinned
 * so a drift in the extraction fails at compile time (Art. 4). The same
 * shapes compile mingw-side in tests/ntapi/sem_se/, so oracle and kernel
 * agree by construction. */
_Static_assert(sizeof(SID) == 12, "SID with 1 subauthority");
_Static_assert(offsetof(SID, SubAuthority) == 8, "SID x64 layout");
_Static_assert(sizeof(LUID) == 8, "LUID is 2 DWORDs");
_Static_assert(sizeof(LUID_AND_ATTRIBUTES) == 12, "LUID_AND_ATTRIBUTES pack(4)");
_Static_assert(sizeof(TOKEN_USER) == 16, "TOKEN_USER x64 layout");
_Static_assert(offsetof(TOKEN_GROUPS, Groups) == 8, "TOKEN_GROUPS x64 layout");
_Static_assert(offsetof(TOKEN_PRIVILEGES, Privileges) == 4,
               "TOKEN_PRIVILEGES x64 layout");
_Static_assert(offsetof(PRIVILEGE_SET, Privilege) == 8, "PRIVILEGE_SET x64 layout");
_Static_assert(sizeof(ACL) == 8, "ACL header");
_Static_assert(sizeof(ACE_HEADER) == 4, "ACE_HEADER");
_Static_assert(sizeof(ACCESS_ALLOWED_ACE) == 12, "ACCESS_ALLOWED_ACE header+mask+SidStart");
_Static_assert(sizeof(SECURITY_DESCRIPTOR_RELATIVE) == 20,
               "self-relative SD header");
_Static_assert(sizeof(TOKEN_STATISTICS) == 56, "TOKEN_STATISTICS pack(4) x64 layout");
_Static_assert(sizeof(TOKEN_SOURCE) == 16, "TOKEN_SOURCE x64 layout");
_Static_assert(sizeof(SECURITY_QUALITY_OF_SERVICE) == 12,
               "SECURITY_QUALITY_OF_SERVICE x64 layout");

#endif /* PROSKRNL_ABI_NTSEAPI_H */
