/* abi/ntwow64.h - GENERATED by tools/gen_abi.py from wine/include/{winternl.h,winnt.h}.
 * DO NOT EDIT BY HAND (Constitution Art. 4 / gate G4). Regenerate with:
 *     python3 tools/gen_abi.py
 */
#ifndef PROSKRNL_ABI_NTWOW64_H
#define PROSKRNL_ABI_NTWOW64_H

#include "abi/ntdef.h"
#include "abi/ntcontext.h" /* ULONG64, DECLSPEC_ALIGN */
#include "abi/ntpebteb.h"  /* GUID */

/* Pointer-free 32-bit mirrors: every member is a ULONG/ULONG64, so the
 * structs are layout-correct in a 64-bit kernel build as-is. */
typedef ULONG ULONG32;

/* Extracted from wine/include/winnt.h. */
#define I386_SIZE_OF_80387_REGISTERS 80
#define I386_MAXIMUM_SUPPORTED_EXTENSION 512
#define CONTEXT_i386 0x00010000
#define CONTEXT_I386_CONTROL (CONTEXT_i386 | 0x0001) /* SS:SP, CS:IP, FLAGS, BP */
#define CONTEXT_I386_INTEGER (CONTEXT_i386 | 0x0002) /* AX, BX, CX, DX, SI, DI */
#define CONTEXT_I386_SEGMENTS (CONTEXT_i386 | 0x0004) /* DS, ES, FS, GS */
#define CONTEXT_I386_FLOATING_POINT (CONTEXT_i386 | 0x0008) /* 387 state */
#define CONTEXT_I386_DEBUG_REGISTERS (CONTEXT_i386 | 0x0010) /* DB 0-3,6,7 */
#define CONTEXT_I386_EXTENDED_REGISTERS (CONTEXT_i386 | 0x0020)
#define CONTEXT_I386_XSTATE (CONTEXT_i386 | 0x0040)
#define CONTEXT_I386_FULL (CONTEXT_I386_CONTROL | CONTEXT_I386_INTEGER | CONTEXT_I386_SEGMENTS)
#define CONTEXT_I386_ALL (CONTEXT_I386_FULL | CONTEXT_I386_FLOATING_POINT | CONTEXT_I386_DEBUG_REGISTERS | CONTEXT_I386_EXTENDED_REGISTERS)

typedef struct {
    ULONG ExceptionList;        /* 0000 */
    ULONG StackBase;            /* 0004 */
    ULONG StackLimit;           /* 0008 */
    ULONG SubSystemTib;         /* 000c */
    ULONG FiberData;            /* 0010 */
    ULONG ArbitraryUserPointer; /* 0014 */
    ULONG Self;                 /* 0018 */
} NT_TIB32;

typedef struct {
    DWORD   ControlWord;
    DWORD   StatusWord;
    DWORD   TagWord;
    DWORD   ErrorOffset;
    DWORD   ErrorSelector;
    DWORD   DataOffset;
    DWORD   DataSelector;
    BYTE    RegisterArea[I386_SIZE_OF_80387_REGISTERS];
    DWORD   Cr0NpxState;
} I386_FLOATING_SAVE_AREA, WOW64_FLOATING_SAVE_AREA, *PWOW64_FLOATING_SAVE_AREA;

typedef struct {
    DWORD   ContextFlags;  /* 000 */

    /* These are selected by CONTEXT_DEBUG_REGISTERS */
    DWORD   Dr0;           /* 004 */
    DWORD   Dr1;           /* 008 */
    DWORD   Dr2;           /* 00c */
    DWORD   Dr3;           /* 010 */
    DWORD   Dr6;           /* 014 */
    DWORD   Dr7;           /* 018 */

    /* These are selected by CONTEXT_FLOATING_POINT */
    I386_FLOATING_SAVE_AREA FloatSave; /* 01c */

    /* These are selected by CONTEXT_SEGMENTS */
    DWORD   SegGs;         /* 08c */
    DWORD   SegFs;         /* 090 */
    DWORD   SegEs;         /* 094 */
    DWORD   SegDs;         /* 098 */

    /* These are selected by CONTEXT_INTEGER */
    DWORD   Edi;           /* 09c */
    DWORD   Esi;           /* 0a0 */
    DWORD   Ebx;           /* 0a4 */
    DWORD   Edx;           /* 0a8 */
    DWORD   Ecx;           /* 0ac */
    DWORD   Eax;           /* 0b0 */

    /* These are selected by CONTEXT_CONTROL */
    DWORD   Ebp;           /* 0b4 */
    DWORD   Eip;           /* 0b8 */
    DWORD   SegCs;         /* 0bc */
    DWORD   EFlags;        /* 0c0 */
    DWORD   Esp;           /* 0c4 */
    DWORD   SegSs;         /* 0c8 */

    BYTE    ExtendedRegisters[I386_MAXIMUM_SUPPORTED_EXTENSION];  /* 0xcc */
} I386_CONTEXT, WOW64_CONTEXT, *PWOW64_CONTEXT;

/* Extracted from wine/include/winternl.h. */
#define WOW64_CPURESERVED_FLAG_RESET_STATE 1
#define WOW64_CPUFLAGS_MSFT64 0x01
#define WOW64_CPUFLAGS_SOFTWARE 0x02
#define WOW64_TLS_CPURESERVED 1
#define WOW64_TLS_WOW64INFO 10
#define WOW64_TLS_MAX_NUMBER 19

typedef struct {
    ULONG Flink;
    ULONG Blink;
} LIST_ENTRY32;

typedef struct {
    USHORT  Length;
    USHORT  MaximumLength;
    ULONG   Buffer;
} UNICODE_STRING32;

typedef struct {
   ULONG UniqueProcess;
   ULONG UniqueThread;
} CLIENT_ID32;

typedef struct {
    ULONG        ActiveFrame;
    LIST_ENTRY32 FrameListCache;
    ULONG        Flags;
    ULONG        NextCookieSequenceNumber;
    ULONG32      StackId;
} ACTIVATION_CONTEXT_STACK32;

typedef struct {
    UNICODE_STRING32 DosPath;
    ULONG Handle;
} CURDIR32;

typedef struct {
    USHORT              Flags;
    USHORT              Length;
    ULONG               TimeStamp;
    UNICODE_STRING32    DosPath;
} RTL_DRIVE_LETTER_CURDIR32;

typedef struct {
    ULONG               AllocationSize;
    ULONG               Size;
    ULONG               Flags;
    ULONG               DebugFlags;
    ULONG               ConsoleHandle;
    ULONG               ConsoleFlags;
    ULONG               hStdInput;
    ULONG               hStdOutput;
    ULONG               hStdError;
    CURDIR32            CurrentDirectory;
    UNICODE_STRING32    DllPath;
    UNICODE_STRING32    ImagePathName;
    UNICODE_STRING32    CommandLine;
    ULONG               Environment;
    ULONG               dwX;
    ULONG               dwY;
    ULONG               dwXSize;
    ULONG               dwYSize;
    ULONG               dwXCountChars;
    ULONG               dwYCountChars;
    ULONG               dwFillAttribute;
    ULONG               dwFlags;
    ULONG               wShowWindow;
    UNICODE_STRING32    WindowTitle;
    UNICODE_STRING32    Desktop;
    UNICODE_STRING32    ShellInfo;
    UNICODE_STRING32    RuntimeInfo;
    RTL_DRIVE_LETTER_CURDIR32 DLCurrentDirectory[0x20];
    ULONG               EnvironmentSize;
    ULONG               EnvironmentVersion;
    ULONG               PackageDependencyData;
    ULONG               ProcessGroupId;
    ULONG               LoaderThreads;
} RTL_USER_PROCESS_PARAMETERS32;

typedef struct {
    BOOLEAN                      InheritedAddressSpace;             /* 0000 */
    BOOLEAN                      ReadImageFileExecOptions;          /* 0001 */
    BOOLEAN                      BeingDebugged;                     /* 0002 */
    UCHAR                        ImageUsedLargePages : 1;           /* 0003 */
    UCHAR                        IsProtectedProcess : 1;
    UCHAR                        IsImageDynamicallyRelocated : 1;
    UCHAR                        SkipPatchingUser32Forwarders : 1;
    UCHAR                        IsPackagedProcess : 1;
    UCHAR                        IsAppContainer: 1;
    UCHAR                        IsProtectedProcessLight : 1;
    UCHAR                        IsLongPathAwareProcess : 1;
    ULONG                        Mutant;                            /* 0004 */
    ULONG                        ImageBaseAddress;                  /* 0008 */
    ULONG                        LdrData;                           /* 000c */
    ULONG                        ProcessParameters;                 /* 0010 */
    ULONG                        SubSystemData;                     /* 0014 */
    ULONG                        ProcessHeap;                       /* 0018 */
    ULONG                        FastPebLock;                       /* 001c */
    ULONG                        AtlThunkSListPtr;                  /* 0020 */
    ULONG                        IFEOKey;                           /* 0024 */
    ULONG                        ProcessInJob : 1;                  /* 0028 */
    ULONG                        ProcessInitializing : 1;
    ULONG                        ProcessUsingVEH : 1;
    ULONG                        ProcessUsingVCH : 1;
    ULONG                        ProcessUsingFTH : 1;
    ULONG                        ProcessPreviouslyThrottled : 1;
    ULONG                        ProcessCurrentlyThrottled : 1;
    ULONG                        ProcessImagesHotPatched : 1;
    ULONG                        ReservedBits0 : 24;
    ULONG                        KernelCallbackTable;               /* 002c */
    ULONG                        Reserved;                          /* 0030 */
    ULONG                        AtlThunkSListPtr32;                /* 0034 */
    ULONG                        ApiSetMap;                         /* 0038 */
    ULONG                        TlsExpansionCounter;               /* 003c */
    ULONG                        TlsBitmap;                         /* 0040 */
    ULONG                        TlsBitmapBits[2];                  /* 0044 */
    ULONG                        ReadOnlySharedMemoryBase;          /* 004c */
    ULONG                        SharedData;                        /* 0050 */
    ULONG                        ReadOnlyStaticServerData;          /* 0054 */
    ULONG                        AnsiCodePageData;                  /* 0058 */
    ULONG                        OemCodePageData;                   /* 005c */
    ULONG                        UnicodeCaseTableData;              /* 0060 */
    ULONG                        NumberOfProcessors;                /* 0064 */
    ULONG                        NtGlobalFlag;                      /* 0068 */
    LARGE_INTEGER                CriticalSectionTimeout;            /* 0070 */
    ULONG                        HeapSegmentReserve;                /* 0078 */
    ULONG                        HeapSegmentCommit;                 /* 007c */
    ULONG                        HeapDeCommitTotalFreeThreshold;    /* 0080 */
    ULONG                        HeapDeCommitFreeBlockThreshold;    /* 0084 */
    ULONG                        NumberOfHeaps;                     /* 0088 */
    ULONG                        MaximumNumberOfHeaps;              /* 008c */
    ULONG                        ProcessHeaps;                      /* 0090 */
    ULONG                        GdiSharedHandleTable;              /* 0094 */
    ULONG                        ProcessStarterHelper;              /* 0098 */
    ULONG                        GdiDCAttributeList;                /* 009c */
    ULONG                        LoaderLock;                        /* 00a0 */
    ULONG                        OSMajorVersion;                    /* 00a4 */
    ULONG                        OSMinorVersion;                    /* 00a8 */
    ULONG                        OSBuildNumber;                     /* 00ac */
    ULONG                        OSPlatformId;                      /* 00b0 */
    ULONG                        ImageSubSystem;                    /* 00b4 */
    ULONG                        ImageSubSystemMajorVersion;        /* 00b8 */
    ULONG                        ImageSubSystemMinorVersion;        /* 00bc */
    ULONG                        ActiveProcessAffinityMask;         /* 00c0 */
    ULONG                        GdiHandleBuffer[34];               /* 00c4 */
    ULONG                        PostProcessInitRoutine;            /* 014c */
    ULONG                        TlsExpansionBitmap;                /* 0150 */
    ULONG                        TlsExpansionBitmapBits[32];        /* 0154 */
    ULONG                        SessionId;                         /* 01d4 */
    ULARGE_INTEGER               AppCompatFlags;                    /* 01d8 */
    ULARGE_INTEGER               AppCompatFlagsUser;                /* 01e0 */
    ULONG                        ShimData;                          /* 01e8 */
    ULONG                        AppCompatInfo;                     /* 01ec */
    UNICODE_STRING32             CSDVersion;                        /* 01f0 */
    ULONG                        ActivationContextData;             /* 01f8 */
    ULONG                        ProcessAssemblyStorageMap;         /* 01fc */
    ULONG                        SystemDefaultActivationData;       /* 0200 */
    ULONG                        SystemAssemblyStorageMap;          /* 0204 */
    ULONG                        MinimumStackCommit;                /* 0208 */
    ULONG                        SparePointers[2];                  /* 020c */
    ULONG                        PatchLoaderData;                   /* 0214 */
    ULONG                        ChpeV2ProcessInfo;                 /* 0218 */
    ULONG                        AppModelFeatureState;              /* 021c */
    ULONG                        SpareUlongs[2];                    /* 0220 */
    USHORT                       ActiveCodePage;                    /* 0228 */
    USHORT                       OemCodePage;                       /* 022a */
    USHORT                       UseCaseMapping;                    /* 022c */
    USHORT                       UnusedNlsField;                    /* 022e */
    ULONG                        WerRegistrationData;               /* 0230 */
    ULONG                        WerShipAssertPtr;                  /* 0234 */
    ULONG                        pUnused;                           /* 0238 */
    ULONG                        pImageHeaderHash;                  /* 023c */
    ULONG                        HeapTracingEnabled : 1;            /* 0240 */
    ULONG                        CritSecTracingEnabled : 1;
    ULONG                        LibLoaderTracingEnabled : 1;
    ULONG                        SpareTracingBits : 29;
    ULONGLONG                    CsrServerReadOnlySharedMemoryBase; /* 0248 */
    ULONG                        TppWorkerpListLock;                /* 0250 */
    LIST_ENTRY32                 TppWorkerpList;                    /* 0254 */
    ULONG                        WaitOnAddressHashTable [0x80];     /* 025c */
    ULONG                        TelemetryCoverageHeader;           /* 045c */
    ULONG                        CloudFileFlags;                    /* 0460 */
    ULONG                        CloudFileDiagFlags;                /* 0464 */
    CHAR                         PlaceholderCompatibilityMode;      /* 0468 */
    CHAR                         PlaceholderCompatibilityModeReserved[7]; /* 0469 */
    ULONG                        LeapSecondData;                    /* 0470 */
    ULONG                        LeapSecondFlags;                   /* 0474 */
    ULONG                        NtGlobalFlag2;                     /* 0478 */
} PEB32;

typedef struct {
    NT_TIB32                     Tib;                               /* 0000 */
    ULONG                        EnvironmentPointer;                /* 001c */
    CLIENT_ID32                  ClientId;                          /* 0020 */
    ULONG                        ActiveRpcHandle;                   /* 0028 */
    ULONG                        ThreadLocalStoragePointer;         /* 002c */
    ULONG                        Peb;                               /* 0030 */
    ULONG                        LastErrorValue;                    /* 0034 */
    ULONG                        CountOfOwnedCriticalSections;      /* 0038 */
    ULONG                        CsrClientThread;                   /* 003c */
    ULONG                        Win32ThreadInfo;                   /* 0040 */
    ULONG                        User32Reserved[26];                /* 0044 */
    ULONG                        UserReserved[5];                   /* 00ac */
    ULONG                        WOW32Reserved;                     /* 00c0 */
    ULONG                        CurrentLocale;                     /* 00c4 */
    ULONG                        FpSoftwareStatusRegister;          /* 00c8 */
    ULONG                        ReservedForDebuggerInstrumentation[16]; /* 00cc */
    ULONG                        SystemReserved1[26];               /* 010c */
    char                         PlaceholderCompatibilityMode;      /* 0174 */
    BOOLEAN                      PlaceholderHydrationAlwaysExplicit;/* 0175 */
    char                         PlaceholderReserved[10];           /* 0176 */
    DWORD                        ProxiedProcessId;                  /* 0180 */
    ACTIVATION_CONTEXT_STACK32   ActivationContextStack;            /* 0184 */
    UCHAR                        WorkingOnBehalfOfTicket[8];        /* 019c */
    LONG                         ExceptionCode;                     /* 01a4 */
    ULONG                        ActivationContextStackPointer;     /* 01a8 */
    ULONG                        InstrumentationCallbackSp;         /* 01ac */
    ULONG                        InstrumentationCallbackPreviousPc; /* 01b0 */
    ULONG                        InstrumentationCallbackPreviousSp; /* 01b4 */
    BOOLEAN                      InstrumentationCallbackDisabled;   /* 01b8 */
    BYTE                         SpareBytes1[23];                   /* 01b9 */
    ULONG                        TxFsContext;                       /* 01d0 */
    ULONG                        GdiTebBatch[0x138];                /* 01d4 */
    CLIENT_ID32                  RealClientId;                      /* 06b4 */
    ULONG                        GdiCachedProcessHandle;            /* 06bc */
    ULONG                        GdiClientPID;                      /* 06c0 */
    ULONG                        GdiClientTID;                      /* 06c4 */
    ULONG                        GdiThreadLocaleInfo;               /* 06c8 */
    ULONG                        Win32ClientInfo[62];               /* 06cc */
    ULONG                        glDispatchTable[233];              /* 07c4 */
    ULONG                        glReserved1[29];                   /* 0b68 */
    ULONG                        glReserved2;                       /* 0bdc */
    ULONG                        glSectionInfo;                     /* 0be0 */
    ULONG                        glSection;                         /* 0be4 */
    ULONG                        glTable;                           /* 0be8 */
    ULONG                        glCurrentRC;                       /* 0bec */
    ULONG                        glContext;                         /* 0bf0 */
    ULONG                        LastStatusValue;                   /* 0bf4 */
    UNICODE_STRING32             StaticUnicodeString;               /* 0bf8 */
    WCHAR                        StaticUnicodeBuffer[261];          /* 0c00 */
    ULONG                        DeallocationStack;                 /* 0e0c */
    ULONG                        TlsSlots[64];                      /* 0e10 */
    LIST_ENTRY32                 TlsLinks;                          /* 0f10 */
    ULONG                        Vdm;                               /* 0f18 */
    ULONG                        ReservedForNtRpc;                  /* 0f1c */
    ULONG                        DbgSsReserved[2];                  /* 0f20 */
    ULONG                        HardErrorMode;                     /* 0f28 */
    ULONG                        Instrumentation[9];                /* 0f2c */
    GUID                         ActivityId;                        /* 0f50 */
    ULONG                        SubProcessTag;                     /* 0f60 */
    ULONG                        PerflibData;                       /* 0f64 */
    ULONG                        EtwTraceData;                      /* 0f68 */
    ULONG                        WinSockData;                       /* 0f6c */
    ULONG                        GdiBatchCount;                     /* 0f70 */
    ULONG                        IdealProcessorValue;               /* 0f74 */
    ULONG                        GuaranteedStackBytes;              /* 0f78 */
    ULONG                        ReservedForPerf;                   /* 0f7c */
    ULONG                        ReservedForOle;                    /* 0f80 */
    ULONG                        WaitingOnLoaderLock;               /* 0f84 */
    ULONG                        SavedPriorityState;                /* 0f88 */
    ULONG                        ReservedForCodeCoverage;           /* 0f8c */
    ULONG                        ThreadPoolData;                    /* 0f90 */
    ULONG                        TlsExpansionSlots;                 /* 0f94 */
    ULONG                        MuiGeneration;                     /* 0f98 */
    ULONG                        IsImpersonating;                   /* 0f9c */
    ULONG                        NlsCache;                          /* 0fa0 */
    ULONG                        ShimData;                          /* 0fa4 */
    ULONG                        HeapVirtualAffinity;               /* 0fa8 */
    ULONG                        CurrentTransactionHandle;          /* 0fac */
    ULONG                        ActiveFrame;                       /* 0fb0 */
    ULONG                        FlsSlots;                          /* 0fb4 */
    ULONG                        PreferredLanguages;                /* 0fb8 */
    ULONG                        UserPrefLanguages;                 /* 0fbc */
    ULONG                        MergedPrefLanguages;               /* 0fc0 */
    ULONG                        MuiImpersonation;                  /* 0fc4 */
    USHORT                       CrossTebFlags;                     /* 0fc8 */
    union {
        USHORT SameTebFlags;                                        /* 0fca */
        struct {
            USHORT SafeThunkCall : 1;
            USHORT InDebugPrint : 1;
            USHORT HasFiberData : 1;
            USHORT SkipThreadAttach : 1;
            USHORT WerInShipAssertCode : 1;
            USHORT RanProcessInit : 1;
            USHORT ClonedThread : 1;
            USHORT SuppressDebugMsg : 1;
            USHORT DisableUserStackWalk : 1;
            USHORT RtlExceptionAttached : 1;
            USHORT InitialThread : 1;
            USHORT SessionAware : 1;
            USHORT LoadOwner : 1;
            USHORT LoaderWorker : 1;
            USHORT SkipLoaderInit : 1;
            USHORT SkipFileAPIBrokering : 1;
        };
    };
    ULONG                        TxnScopeEnterCallback;             /* 0fcc */
    ULONG                        TxnScopeExitCallback;              /* 0fd0 */
    ULONG                        TxnScopeContext;                   /* 0fd4 */
    ULONG                        LockCount;                         /* 0fd8 */
    LONG                         WowTebOffset;                      /* 0fdc */
    ULONG                        ResourceRetValue;                  /* 0fe0 */
    ULONG                        ReservedForWdf;                    /* 0fe4 */
    ULONGLONG                    ReservedForCrt;                    /* 0fe8 */
    GUID                         EffectiveContainerId;              /* 0ff0 */
} TEB32;

typedef struct {
    USHORT          Flags;
    USHORT          Machine;
    /* CONTEXT context */
    /* CONTEXT_EX *context_ex */
} WOW64_CPURESERVED, *PWOW64_CPURESERVED;

typedef struct {
    void              *Context;
    void              *ContextEx;
    void              *ContextFlagsLocation;
    WOW64_CPURESERVED *CpuReserved;
    ULONG              ContextFlag;
    USHORT             Machine;
} WOW64_CPU_AREA_INFO, *PWOW64_CPU_AREA_INFO;

typedef struct {
    ULONG     NativeSystemPageSize;
    ULONG     CpuFlags;
    ULONG     Wow64ExecuteFlags;
    ULONG     unknown;
    ULONGLONG SectionHandle;
    ULONGLONG CrossProcessWorkList;
    USHORT    NativeMachineType;
    USHORT    EmulatedMachineType;
} WOW64INFO;

/* win10-2004 layout (wine winternl.h: "undocumented layout of
 * LdrSystemDllInitBlock"): the block the creator fills in both the
 * 64-bit and 32-bit ntdll before the first thread enters user mode. */
typedef struct
{
    ULONG   version;
    ULONG   unknown1[3];
    ULONG64 unknown2;
    ULONG64 pLdrInitializeThunk;
    ULONG64 pKiUserExceptionDispatcher;
    ULONG64 pKiUserApcDispatcher;
    ULONG64 pKiUserCallbackDispatcher;
    ULONG64 pRtlUserThreadStart;
    ULONG64 pRtlpQueryProcessDebugInformationRemote;
    ULONG64 ntdll_handle;
    ULONG64 pLdrSystemDllInitBlock;
    ULONG64 pRtlpFreezeTimeBias;
} SYSTEM_DLL_INIT_BLOCK;

#include <stddef.h>
_Static_assert(sizeof(WOW64INFO) == 40, "WOW64INFO size (C_ASSERT in the Wine header)");
/* Layout pins, generated from the offset comments in the SAME Wine
 * headers the structs were extracted from (Art. 4). */
_Static_assert(offsetof(PEB32, InheritedAddressSpace) == 0x0000, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ReadImageFileExecOptions) == 0x0001, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, BeingDebugged) == 0x0002, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, Mutant) == 0x0004, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ImageBaseAddress) == 0x0008, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, LdrData) == 0x000c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ProcessParameters) == 0x0010, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, SubSystemData) == 0x0014, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ProcessHeap) == 0x0018, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, FastPebLock) == 0x001c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, AtlThunkSListPtr) == 0x0020, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, IFEOKey) == 0x0024, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, KernelCallbackTable) == 0x002c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, Reserved) == 0x0030, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, AtlThunkSListPtr32) == 0x0034, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ApiSetMap) == 0x0038, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, TlsExpansionCounter) == 0x003c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, TlsBitmap) == 0x0040, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, TlsBitmapBits) == 0x0044, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ReadOnlySharedMemoryBase) == 0x004c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, SharedData) == 0x0050, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ReadOnlyStaticServerData) == 0x0054, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, AnsiCodePageData) == 0x0058, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, OemCodePageData) == 0x005c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, UnicodeCaseTableData) == 0x0060, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, NumberOfProcessors) == 0x0064, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, NtGlobalFlag) == 0x0068, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, CriticalSectionTimeout) == 0x0070, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, HeapSegmentReserve) == 0x0078, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, HeapSegmentCommit) == 0x007c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, HeapDeCommitTotalFreeThreshold) == 0x0080, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, HeapDeCommitFreeBlockThreshold) == 0x0084, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, NumberOfHeaps) == 0x0088, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, MaximumNumberOfHeaps) == 0x008c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ProcessHeaps) == 0x0090, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, GdiSharedHandleTable) == 0x0094, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ProcessStarterHelper) == 0x0098, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, GdiDCAttributeList) == 0x009c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, LoaderLock) == 0x00a0, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, OSMajorVersion) == 0x00a4, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, OSMinorVersion) == 0x00a8, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, OSBuildNumber) == 0x00ac, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, OSPlatformId) == 0x00b0, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ImageSubSystem) == 0x00b4, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ImageSubSystemMajorVersion) == 0x00b8, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ImageSubSystemMinorVersion) == 0x00bc, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ActiveProcessAffinityMask) == 0x00c0, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, GdiHandleBuffer) == 0x00c4, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, PostProcessInitRoutine) == 0x014c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, TlsExpansionBitmap) == 0x0150, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, TlsExpansionBitmapBits) == 0x0154, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, SessionId) == 0x01d4, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, AppCompatFlags) == 0x01d8, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, AppCompatFlagsUser) == 0x01e0, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ShimData) == 0x01e8, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, AppCompatInfo) == 0x01ec, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, CSDVersion) == 0x01f0, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ActivationContextData) == 0x01f8, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ProcessAssemblyStorageMap) == 0x01fc, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, SystemDefaultActivationData) == 0x0200, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, SystemAssemblyStorageMap) == 0x0204, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, MinimumStackCommit) == 0x0208, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, SparePointers) == 0x020c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, PatchLoaderData) == 0x0214, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ChpeV2ProcessInfo) == 0x0218, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, AppModelFeatureState) == 0x021c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, SpareUlongs) == 0x0220, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, ActiveCodePage) == 0x0228, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, OemCodePage) == 0x022a, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, UseCaseMapping) == 0x022c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, UnusedNlsField) == 0x022e, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, WerRegistrationData) == 0x0230, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, WerShipAssertPtr) == 0x0234, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, pUnused) == 0x0238, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, pImageHeaderHash) == 0x023c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, CsrServerReadOnlySharedMemoryBase) == 0x0248, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, TppWorkerpListLock) == 0x0250, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, TppWorkerpList) == 0x0254, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, WaitOnAddressHashTable) == 0x025c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, TelemetryCoverageHeader) == 0x045c, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, CloudFileFlags) == 0x0460, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, CloudFileDiagFlags) == 0x0464, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, PlaceholderCompatibilityMode) == 0x0468, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, PlaceholderCompatibilityModeReserved) == 0x0469, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, LeapSecondData) == 0x0470, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, LeapSecondFlags) == 0x0474, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(PEB32, NtGlobalFlag2) == 0x0478, "PEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, Tib) == 0x0000, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, EnvironmentPointer) == 0x001c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ClientId) == 0x0020, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ActiveRpcHandle) == 0x0028, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ThreadLocalStoragePointer) == 0x002c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, Peb) == 0x0030, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, LastErrorValue) == 0x0034, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, CountOfOwnedCriticalSections) == 0x0038, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, CsrClientThread) == 0x003c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, Win32ThreadInfo) == 0x0040, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, User32Reserved) == 0x0044, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, UserReserved) == 0x00ac, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, WOW32Reserved) == 0x00c0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, CurrentLocale) == 0x00c4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, FpSoftwareStatusRegister) == 0x00c8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ReservedForDebuggerInstrumentation) == 0x00cc, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, SystemReserved1) == 0x010c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, PlaceholderCompatibilityMode) == 0x0174, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, PlaceholderHydrationAlwaysExplicit) == 0x0175, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, PlaceholderReserved) == 0x0176, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ProxiedProcessId) == 0x0180, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ActivationContextStack) == 0x0184, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, WorkingOnBehalfOfTicket) == 0x019c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ExceptionCode) == 0x01a4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ActivationContextStackPointer) == 0x01a8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, InstrumentationCallbackSp) == 0x01ac, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, InstrumentationCallbackPreviousPc) == 0x01b0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, InstrumentationCallbackPreviousSp) == 0x01b4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, InstrumentationCallbackDisabled) == 0x01b8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, SpareBytes1) == 0x01b9, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, TxFsContext) == 0x01d0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, GdiTebBatch) == 0x01d4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, RealClientId) == 0x06b4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, GdiCachedProcessHandle) == 0x06bc, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, GdiClientPID) == 0x06c0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, GdiClientTID) == 0x06c4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, GdiThreadLocaleInfo) == 0x06c8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, Win32ClientInfo) == 0x06cc, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, glDispatchTable) == 0x07c4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, glReserved1) == 0x0b68, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, glReserved2) == 0x0bdc, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, glSectionInfo) == 0x0be0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, glSection) == 0x0be4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, glTable) == 0x0be8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, glCurrentRC) == 0x0bec, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, glContext) == 0x0bf0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, LastStatusValue) == 0x0bf4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, StaticUnicodeString) == 0x0bf8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, StaticUnicodeBuffer) == 0x0c00, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, DeallocationStack) == 0x0e0c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, TlsSlots) == 0x0e10, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, TlsLinks) == 0x0f10, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, Vdm) == 0x0f18, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ReservedForNtRpc) == 0x0f1c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, DbgSsReserved) == 0x0f20, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, HardErrorMode) == 0x0f28, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, Instrumentation) == 0x0f2c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ActivityId) == 0x0f50, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, SubProcessTag) == 0x0f60, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, PerflibData) == 0x0f64, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, EtwTraceData) == 0x0f68, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, WinSockData) == 0x0f6c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, GdiBatchCount) == 0x0f70, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, IdealProcessorValue) == 0x0f74, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, GuaranteedStackBytes) == 0x0f78, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ReservedForPerf) == 0x0f7c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ReservedForOle) == 0x0f80, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, WaitingOnLoaderLock) == 0x0f84, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, SavedPriorityState) == 0x0f88, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ReservedForCodeCoverage) == 0x0f8c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ThreadPoolData) == 0x0f90, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, TlsExpansionSlots) == 0x0f94, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, MuiGeneration) == 0x0f98, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, IsImpersonating) == 0x0f9c, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, NlsCache) == 0x0fa0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ShimData) == 0x0fa4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, HeapVirtualAffinity) == 0x0fa8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, CurrentTransactionHandle) == 0x0fac, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ActiveFrame) == 0x0fb0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, FlsSlots) == 0x0fb4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, PreferredLanguages) == 0x0fb8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, UserPrefLanguages) == 0x0fbc, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, MergedPrefLanguages) == 0x0fc0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, MuiImpersonation) == 0x0fc4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, CrossTebFlags) == 0x0fc8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, TxnScopeEnterCallback) == 0x0fcc, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, TxnScopeExitCallback) == 0x0fd0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, TxnScopeContext) == 0x0fd4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, LockCount) == 0x0fd8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, WowTebOffset) == 0x0fdc, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ResourceRetValue) == 0x0fe0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ReservedForWdf) == 0x0fe4, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, ReservedForCrt) == 0x0fe8, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(TEB32, EffectiveContainerId) == 0x0ff0, "TEB32 x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, ContextFlags) == 0x000, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Dr0) == 0x004, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Dr1) == 0x008, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Dr2) == 0x00c, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Dr3) == 0x010, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Dr6) == 0x014, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Dr7) == 0x018, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, FloatSave) == 0x01c, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, SegGs) == 0x08c, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, SegFs) == 0x090, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, SegEs) == 0x094, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, SegDs) == 0x098, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Edi) == 0x09c, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Esi) == 0x0a0, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Ebx) == 0x0a4, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Edx) == 0x0a8, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Ecx) == 0x0ac, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Eax) == 0x0b0, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Ebp) == 0x0b4, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Eip) == 0x0b8, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, SegCs) == 0x0bc, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, EFlags) == 0x0c0, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, Esp) == 0x0c4, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, SegSs) == 0x0c8, "I386_CONTEXT x64 layout (offset comment in the Wine header)");
_Static_assert(offsetof(I386_CONTEXT, ExtendedRegisters) == 0xcc, "I386_CONTEXT x64 layout (offset comment in the Wine header)");

#endif /* PROSKRNL_ABI_NTWOW64_H */
