/* abi/syscall_numbers.h - GENERATED by tools/gen_syscalls.py.
 * DO NOT EDIT BY HAND. The syscall list lives in tools/gen_syscalls.py;
 * regenerate with:
 *     python3 tools/gen_syscalls.py
 */
#ifndef PROSKRNL_ABI_SYSCALL_NUMBERS_H
#define PROSKRNL_ABI_SYSCALL_NUMBERS_H

/* Ids are the pinned Wine tree's 64-bit syscall numbers
 * (third_party/wine/dlls/ntdll/ntsyscalls.h) - the values its PE
 * ntdll's thunks place in eax. Only implemented services are listed;
 * the kernel table covers the full id space (unimplemented ids log
 * and fail with STATUS_NOT_IMPLEMENTED). */
#define NTSYS_NtClose 0x000f
#define NTSYS_NtDuplicateObject 0x003c
#define NTSYS_NtMakeTemporaryObject 0x00af
#define NTSYS_NtCreateEvent 0x0048
#define NTSYS_NtOpenEvent 0x0040
#define NTSYS_NtSetEvent 0x000e
#define NTSYS_NtResetEvent 0x00dd
#define NTSYS_NtClearEvent 0x003e
#define NTSYS_NtPulseEvent 0x00c1
#define NTSYS_NtQueryEvent 0x0056
#define NTSYS_NtCreateMutant 0x0084
#define NTSYS_NtOpenMutant 0x00ba
#define NTSYS_NtReleaseMutant 0x0020
#define NTSYS_NtQueryMutant 0x00cb
#define NTSYS_NtCreateSemaphore 0x0089
#define NTSYS_NtOpenSemaphore 0x00bc
#define NTSYS_NtReleaseSemaphore 0x000a
#define NTSYS_NtQuerySemaphore 0x00cd
#define NTSYS_NtWaitForSingleObject 0x0004
#define NTSYS_NtWaitForMultipleObjects 0x005b
#define NTSYS_NtCreateDirectoryObject 0x007d
#define NTSYS_NtOpenDirectoryObject 0x0058
#define NTSYS_NtCreateSymbolicLinkObject 0x008a
#define NTSYS_NtOpenSymbolicLinkObject 0x00bd
#define NTSYS_NtQuerySymbolicLinkObject 0x00ce
#define NTSYS_NtAllocateVirtualMemory 0x0018
#define NTSYS_NtFreeVirtualMemory 0x001e
#define NTSYS_NtQueryVirtualMemory 0x0023
#define NTSYS_NtTerminateProcess 0x002c
#define NTSYS_NtDisplayString 0x0096
#define NTSYS_NtCreateSection 0x004a
#define NTSYS_NtOpenSection 0x0037
#define NTSYS_NtMapViewOfSection 0x0028
#define NTSYS_NtUnmapViewOfSection 0x002a
#define NTSYS_NtQuerySection 0x0051
#define NTSYS_NtCreateFile 0x0055
#define NTSYS_NtOpenFile 0x0033
#define NTSYS_NtReadFile 0x0006
#define NTSYS_NtWriteFile 0x0008
#define NTSYS_NtQueryInformationFile 0x0011
#define NTSYS_NtSetInformationFile 0x0027
#define NTSYS_NtQueryDirectoryFile 0x0035
#define NTSYS_NtQueryAttributesFile 0x003d
#define NTSYS_NtFlushBuffersFile 0x004b
#define NTSYS_NtLockFile 0x00ac
#define NTSYS_NtUnlockFile 0x0102
#define NTSYS_NtCreateUserProcess 0x008f
#define NTSYS_NtCreateThreadEx 0x008b
#define NTSYS_NtOpenThread 0x00be
#define NTSYS_NtResumeThread 0x0052
#define NTSYS_NtSuspendThread 0x00fb
#define NTSYS_NtTerminateThread 0x0053
#define NTSYS_NtAlertThread 0x0066
#define NTSYS_NtTestAlert 0x00fe
#define NTSYS_NtYieldExecution 0x0046
#define NTSYS_NtDelayExecution 0x0034
#define NTSYS_NtQueueApcThread 0x0045
#define NTSYS_NtContinue 0x0043
#define NTSYS_NtRaiseException 0x00d5
#define NTSYS_NtQueryInformationProcess 0x0019
#define NTSYS_NtSetInformationProcess 0x001c
#define NTSYS_NtQueryInformationThread 0x0025
#define NTSYS_NtSetInformationThread 0x000d
#define NTSYS_NtQueryPerformanceCounter 0x0031
#define NTSYS_NtQuerySystemInformation 0x0036
#define NTSYS_NtQueryDefaultLocale 0x0015
#define NTSYS_NtGetContextThread 0x009d
#define NTSYS_NtSetContextThread 0x00e4
#define NTSYS_NtProtectVirtualMemory 0x0050
#define NTSYS_NtFlushInstructionCache 0x0099
#define NTSYS_NtContinueEx 0x007b
#define NTSYS_NtCallbackReturn 0x0005
#define NTSYS_NtWaitForAlertByThreadId 0x0105
#define NTSYS_NtAlertThreadByThreadId 0x0067
#define NTSYS_NtInitializeNlsFiles 0x00a4
#define NTSYS_NtGetNlsSectionPtr 0x00a1
#define NTSYS_NtOpenKey 0x0012
#define NTSYS_NtQueryValueKey 0x0017
#define NTSYS_NtQueryVolumeInformationFile 0x0049

/* One past the highest Wine 64-bit syscall id. */
#define NTSYS_SYSCALL_LIMIT 0x0108

#endif /* PROSKRNL_ABI_SYSCALL_NUMBERS_H */
