/* abi/syscall_numbers.h - GENERATED by tools/gen_syscalls.py.
 * DO NOT EDIT BY HAND. The syscall list lives in tools/gen_syscalls.py;
 * regenerate with:
 *     python3 tools/gen_syscalls.py
 */
#ifndef PROSKRNL_ABI_SYSCALL_NUMBERS_H
#define PROSKRNL_ABI_SYSCALL_NUMBERS_H

#define NTSYS_NtClose 0
#define NTSYS_NtDuplicateObject 1
#define NTSYS_NtMakeTemporaryObject 2
#define NTSYS_NtCreateEvent 3
#define NTSYS_NtOpenEvent 4
#define NTSYS_NtSetEvent 5
#define NTSYS_NtResetEvent 6
#define NTSYS_NtClearEvent 7
#define NTSYS_NtPulseEvent 8
#define NTSYS_NtQueryEvent 9
#define NTSYS_NtCreateMutant 10
#define NTSYS_NtOpenMutant 11
#define NTSYS_NtReleaseMutant 12
#define NTSYS_NtQueryMutant 13
#define NTSYS_NtCreateSemaphore 14
#define NTSYS_NtOpenSemaphore 15
#define NTSYS_NtReleaseSemaphore 16
#define NTSYS_NtQuerySemaphore 17
#define NTSYS_NtWaitForSingleObject 18
#define NTSYS_NtWaitForMultipleObjects 19
#define NTSYS_NtCreateDirectoryObject 20
#define NTSYS_NtOpenDirectoryObject 21
#define NTSYS_NtCreateSymbolicLinkObject 22
#define NTSYS_NtOpenSymbolicLinkObject 23
#define NTSYS_NtQuerySymbolicLinkObject 24
#define NTSYS_NtAllocateVirtualMemory 25
#define NTSYS_NtFreeVirtualMemory 26
#define NTSYS_NtQueryVirtualMemory 27
#define NTSYS_NtTerminateProcess 28
#define NTSYS_NtDisplayString 29
#define NTSYS_NtCreateSection 30
#define NTSYS_NtOpenSection 31
#define NTSYS_NtMapViewOfSection 32
#define NTSYS_NtUnmapViewOfSection 33
#define NTSYS_NtQuerySection 34

#define NTSYS_SYSCALL_COUNT 35

#endif /* PROSKRNL_ABI_SYSCALL_NUMBERS_H */
